from _typeshed import Incomplete
from collections import UserDict, UserList

__all__ = ['LazyDict', 'LazyList']

class LazyDict(UserDict):
    data: Incomplete
    def __init__(self, data) -> None: ...
    def __getitem__(self, k): ...

class LazyList(UserList):
    def __getitem__(self, k): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
