import ast

safeEval = ast.literal_eval

class Tag(str):
    @staticmethod
    def transcode(blob): ...
    def __new__(self, content): ...
    def __ne__(self, other): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def tobytes(self): ...

def readHex(content):
    """Convert a list of hex strings to binary data."""
def deHexStr(hexdata):
    """Convert a hex string to binary data."""
def hexStr(data):
    """Convert binary data to a hex string."""
def num2binary(l, bits: int = 32): ...
def binary2num(bin): ...
def caselessSort(alist):
    """Return a sorted copy of a list. If there are only strings
    in the list, it will not consider case.
    """
def pad(data, size):
    """Pad byte string 'data' with null bytes until its length is a
    multiple of 'size'.

    >>> len(pad(b'abcd', 4))
    4
    >>> len(pad(b'abcde', 2))
    6
    >>> len(pad(b'abcde', 4))
    8
    >>> pad(b'abcdef', 4) == b'abcdef\\x00\\x00'
    True
    """
def tostr(s, encoding: str = 'ascii', errors: str = 'strict'): ...
def tobytes(s, encoding: str = 'ascii', errors: str = 'strict'): ...
def bytechr(n): ...
def byteord(c): ...
def strjoin(iterable, joiner: str = ''): ...
def bytesjoin(iterable, joiner: bytes = b''): ...
