from _typeshed import Incomplete

np: Incomplete

class ModelType:
    NONE: int
    TF_SAVED_MODEL: int
    KERAS_MODEL: int
    TF_CONCRETE_FUNCTIONS: int
    TF_GRAPH_DEF: int
    TF_SESSION: int
    JAX: int

class ModelOptimizationMode:
    PTQ_FLOAT16: int
    PTQ_DYNAMIC_RANGE: int
    PTQ_FULL_INTEGER: int
    PTQ_INT16: int
    QUANTIZATION_AWARE_TRAINING: int
    RANDOM_SPARSITY: int
    BLOCK_SPARSITY: int
    STRUCTURED_SPARSITY: int

class Environment:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsEnvironment(cls, buf, offset: int = 0):
        """This method is deprecated. Please switch to GetRootAs."""
    def Init(self, buf, pos) -> None: ...
    def TensorflowVersion(self): ...
    def ApiVersion(self): ...
    def ModelType(self): ...

def EnvironmentStart(builder) -> None: ...
def EnvironmentAddTensorflowVersion(builder, tensorflowVersion) -> None: ...
def EnvironmentAddApiVersion(builder, apiVersion) -> None: ...
def EnvironmentAddModelType(builder, modelType) -> None: ...
def EnvironmentEnd(builder): ...

class EnvironmentT:
    tensorflowVersion: Incomplete
    apiVersion: int
    modelType: int
    def __init__(self) -> None: ...
    @classmethod
    def InitFromBuf(cls, buf, pos): ...
    @classmethod
    def InitFromPackedBuf(cls, buf, pos: int = 0): ...
    @classmethod
    def InitFromObj(cls, environment): ...
    def Pack(self, builder): ...

class SparsityBlockSize:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsSparsityBlockSize(cls, buf, offset: int = 0):
        """This method is deprecated. Please switch to GetRootAs."""
    def Init(self, buf, pos) -> None: ...
    def Values(self, j): ...
    def ValuesAsNumpy(self): ...
    def ValuesLength(self): ...
    def ValuesIsNone(self): ...

def SparsityBlockSizeStart(builder) -> None: ...
def SparsityBlockSizeAddValues(builder, values) -> None: ...
def SparsityBlockSizeStartValuesVector(builder, numElems): ...
def SparsityBlockSizeEnd(builder): ...

class SparsityBlockSizeT:
    values: Incomplete
    def __init__(self) -> None: ...
    @classmethod
    def InitFromBuf(cls, buf, pos): ...
    @classmethod
    def InitFromPackedBuf(cls, buf, pos: int = 0): ...
    @classmethod
    def InitFromObj(cls, sparsityBlockSize): ...
    def Pack(self, builder): ...

class ConversionOptions:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsConversionOptions(cls, buf, offset: int = 0):
        """This method is deprecated. Please switch to GetRootAs."""
    def Init(self, buf, pos) -> None: ...
    def ModelOptimizationModes(self, j): ...
    def ModelOptimizationModesAsNumpy(self): ...
    def ModelOptimizationModesLength(self): ...
    def ModelOptimizationModesIsNone(self): ...
    def AllowCustomOps(self): ...
    def EnableSelectTfOps(self): ...
    def ForceSelectTfOps(self): ...
    def SparsityBlockSizes(self, j): ...
    def SparsityBlockSizesLength(self): ...
    def SparsityBlockSizesIsNone(self): ...

def ConversionOptionsStart(builder) -> None: ...
def ConversionOptionsAddModelOptimizationModes(builder, modelOptimizationModes) -> None: ...
def ConversionOptionsStartModelOptimizationModesVector(builder, numElems): ...
def ConversionOptionsAddAllowCustomOps(builder, allowCustomOps) -> None: ...
def ConversionOptionsAddEnableSelectTfOps(builder, enableSelectTfOps) -> None: ...
def ConversionOptionsAddForceSelectTfOps(builder, forceSelectTfOps) -> None: ...
def ConversionOptionsAddSparsityBlockSizes(builder, sparsityBlockSizes) -> None: ...
def ConversionOptionsStartSparsityBlockSizesVector(builder, numElems): ...
def ConversionOptionsEnd(builder): ...

class ConversionOptionsT:
    modelOptimizationModes: Incomplete
    allowCustomOps: bool
    enableSelectTfOps: bool
    forceSelectTfOps: bool
    sparsityBlockSizes: Incomplete
    def __init__(self) -> None: ...
    @classmethod
    def InitFromBuf(cls, buf, pos): ...
    @classmethod
    def InitFromPackedBuf(cls, buf, pos: int = 0): ...
    @classmethod
    def InitFromObj(cls, conversionOptions): ...
    def Pack(self, builder): ...

class ConversionMetadata:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsConversionMetadata(cls, buf, offset: int = 0):
        """This method is deprecated. Please switch to GetRootAs."""
    def Init(self, buf, pos) -> None: ...
    def Environment(self): ...
    def Options(self): ...

def ConversionMetadataStart(builder) -> None: ...
def ConversionMetadataAddEnvironment(builder, environment) -> None: ...
def ConversionMetadataAddOptions(builder, options) -> None: ...
def ConversionMetadataEnd(builder): ...

class ConversionMetadataT:
    environment: Incomplete
    options: Incomplete
    def __init__(self) -> None: ...
    @classmethod
    def InitFromBuf(cls, buf, pos): ...
    @classmethod
    def InitFromPackedBuf(cls, buf, pos: int = 0): ...
    @classmethod
    def InitFromObj(cls, conversionMetadata): ...
    def Pack(self, builder): ...
