from _typeshed import Incomplete

def device_memset(dst, val, size, stream: int = 0) -> None: ...
def host_to_device(dst, src, size, stream: int = 0) -> None: ...
def device_to_host(dst, src, size, stream: int = 0) -> None: ...
def device_memory_size(obj): ...
def device_to_device(dst, src, size, stream: int = 0) -> None: ...

class FakeDriver:
    def get_device_count(self): ...

driver: Incomplete
Linker: Incomplete

class LinkerError(RuntimeError): ...
class NvrtcError(RuntimeError): ...
class CudaAPIError(RuntimeError): ...

def launch_kernel(*args, **kwargs) -> None: ...

USE_NV_BINDING: bool
