from _typeshed import Incomplete
from transformers import ChineseCLIPConfig as ChineseCLIPConfig, ChineseCLIPModel as ChineseCLIPModel

def copy_attn_layer(hf_attn_layer, pt_weights, prefix) -> None: ...
def copy_mlp(hf_mlp, pt_weights, prefix) -> None: ...
def copy_linear(hf_linear, pt_weights, prefix) -> None: ...
def copy_layer(hf_layer, pt_weights, prefix) -> None: ...
def copy_layers(hf_layers, pt_weights, prefix) -> None: ...
def copy_text_model_and_projection(hf_model, pt_weights) -> None: ...
def copy_vision_model_and_projection(hf_model, pt_weights) -> None: ...
def convert_chinese_clip_checkpoint(checkpoint_path, pytorch_dump_folder_path, config_path: Incomplete | None = None) -> None:
    """
    Copy/paste/tweak model's weights to transformers design.
    """
