from debugpy import launcher as launcher
from debugpy.common import json as json
from debugpy.launcher import debuggee as debuggee

def launch_request(request): ...
def terminate_request(request) -> None: ...
def disconnect() -> None: ...
