from _typeshed import Incomplete

class TlzLoader:
    """ Finds and loads ``tlz`` modules when added to sys.meta_path"""
    always_from_toolz: Incomplete
    def __init__(self) -> None: ...
    def find_module(self, fullname, path: Incomplete | None = None): ...
    def load_module(self, fullname): ...
    def find_spec(self, fullname, path, target: Incomplete | None = None): ...
    def create_module(self, spec): ...
    def exec_module(self, module) -> None: ...

tlz_loader: Incomplete
