from _typeshed import Incomplete

__all__ = ['format_flamegraph', 'segments', 'memory', 'compare']

def format_flamegraph(flamegraph_lines, flamegraph_script: Incomplete | None = None): ...
def segments(snapshot, format_flamegraph=...): ...
def memory(snapshot, format_flamegraph=...): ...
def compare(before, after, format_flamegraph=...): ...

class Bytes:
    value: Incomplete
    def __init__(self, value) -> None: ...
    def __add__(self, rhs): ...

class PlotWriter:
    add_element: Incomplete
    allocate: Incomplete
    free: Incomplete
    initially_allocated: Incomplete
    to_html: Incomplete
    def __init__(self) -> None: ...
