import torch
import torch.cuda
from _typeshed import Incomplete
from typing import Sequence

__all__ = ['all_reduce', 'reduce', 'broadcast', 'all_gather', 'reduce_scatter']

def all_reduce(inputs, outputs: Incomplete | None = None, op=..., streams: Incomplete | None = None, comms: Incomplete | None = None) -> None: ...
def reduce(inputs: Sequence[torch.Tensor], output: torch.Tensor | Sequence[torch.Tensor] | None = None, root: int = 0, op: int = ..., streams: Sequence[torch.cuda.Stream] | None = None, comms: Incomplete | None = None, *, outputs: Sequence[torch.Tensor] | None = None) -> None: ...
def broadcast(inputs: Sequence[torch.Tensor], root: int = 0, streams: Incomplete | None = None, comms: Incomplete | None = None) -> None: ...
def all_gather(inputs: Sequence[torch.Tensor], outputs: Sequence[torch.Tensor], streams: Incomplete | None = None, comms: Incomplete | None = None) -> None: ...
def reduce_scatter(inputs: Sequence[torch.Tensor], outputs: Sequence[torch.Tensor], op: int = ..., streams: Incomplete | None = None, comms: Incomplete | None = None) -> None: ...
