from _typeshed import Incomplete

def get_named_tuple(name, dict): ...

Align: Incomplete
Group: Incomplete
Padding: Incomplete
Prefix: Incomplete
Scheme: Incomplete
Sign: Incomplete
Symbol: Incomplete
Trim: Incomplete

class Format:
    def __init__(self, **kwargs) -> None: ...
    def align(self, value): ...
    def fill(self, value): ...
    def group(self, value): ...
    def padding(self, value): ...
    def padding_width(self, value): ...
    def precision(self, value): ...
    def scheme(self, value): ...
    def sign(self, value): ...
    def symbol(self, value): ...
    def trim(self, value): ...
    def symbol_prefix(self, value): ...
    def symbol_suffix(self, value): ...
    def decimal_delimiter(self, value): ...
    def group_delimiter(self, value): ...
    def groups(self, groups): ...
    def nully(self, value): ...
    def si_prefix(self, value): ...
    def to_plotly_json(self): ...
