import torch.nn as nn
from _typeshed import Incomplete

__all__ = ['AutoActivation']

class UnaryIdentity(nn.Module):
    def forward(self, x): ...

class UnaryNegative(nn.Module):
    def forward(self, x): ...

class UnaryAbs(nn.Module):
    def forward(self, x): ...

class UnarySquare(nn.Module):
    def forward(self, x): ...

class UnaryPow(nn.Module):
    def forward(self, x): ...

class UnarySqrt(nn.Module):
    def forward(self, x): ...

class UnaryMul(nn.Module):
    beta: Incomplete
    def __init__(self) -> None: ...
    def forward(self, x): ...

class UnaryAdd(nn.Module):
    beta: Incomplete
    def __init__(self) -> None: ...
    def forward(self, x): ...

class UnaryLogAbs(nn.Module):
    def forward(self, x): ...

class UnaryExp(nn.Module):
    def forward(self, x): ...

class UnarySin(nn.Module):
    def forward(self, x): ...

class UnaryCos(nn.Module):
    def forward(self, x): ...

class UnarySinh(nn.Module):
    def forward(self, x): ...

class UnaryCosh(nn.Module):
    def forward(self, x): ...

class UnaryTanh(nn.Module):
    def forward(self, x): ...

class UnaryAsinh(nn.Module):
    def forward(self, x): ...

class UnaryAtan(nn.Module):
    def forward(self, x): ...

class UnarySinc(nn.Module):
    def forward(self, x): ...

class UnaryMax(nn.Module):
    def forward(self, x): ...

class UnaryMin(nn.Module):
    def forward(self, x): ...

class UnarySigmoid(nn.Module):
    def forward(self, x): ...

class UnaryLogExp(nn.Module):
    def forward(self, x): ...

class UnaryExpSquare(nn.Module):
    def forward(self, x): ...

class UnaryErf(nn.Module):
    def forward(self, x): ...

class BinaryAdd(nn.Module):
    def forward(self, x): ...

class BinaryMul(nn.Module):
    def forward(self, x): ...

class BinaryMinus(nn.Module):
    def forward(self, x): ...

class BinaryDivide(nn.Module):
    def forward(self, x): ...

class BinaryMax(nn.Module):
    def forward(self, x): ...

class BinaryMin(nn.Module):
    def forward(self, x): ...

class BinarySigmoid(nn.Module):
    def forward(self, x): ...

class BinaryExpSquare(nn.Module):
    beta: Incomplete
    def __init__(self) -> None: ...
    def forward(self, x): ...

class BinaryExpAbs(nn.Module):
    beta: Incomplete
    def __init__(self) -> None: ...
    def forward(self, x): ...

class BinaryParamAdd(nn.Module):
    beta: Incomplete
    def __init__(self) -> None: ...
    def forward(self, x): ...

class AutoActivation(nn.Module):
    """
    This module is an implementation of the paper `Searching for Activation Functions <https://arxiv.org/abs/1710.05941>`__.

    Parameters
    ----------
    unit_num : int
        the number of core units

    Notes
    -----
    Current `beta` is not per-channel parameter.
    """
    unaries: Incomplete
    binaries: Incomplete
    first_unary: Incomplete
    def __init__(self, unit_num: int = 1, label: str | None = None) -> None: ...
    @property
    def label(self): ...
    def forward(self, x): ...
