import collections.abc

class ImmutableDict(collections.abc.Mapping):
    """Immutable `Mapping`."""
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, key): ...
    def __contains__(self, key) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    __supported_by_tf_nest__: bool
