from _typeshed import Incomplete
from dataclasses import dataclass
from enum import Enum
from fastapi.exceptions import RequestErrorModel as RequestErrorModel
from fastapi.types import IncEx as IncEx, ModelNameMap as ModelNameMap, UnionType as UnionType
from pydantic import BaseModel
from pydantic._internal._typing_extra import eval_type_lenient
from pydantic.fields import FieldInfo as FieldInfo, ModelField as ModelField
from pydantic.json_schema import GenerateJsonSchema as GenerateJsonSchema, JsonSchemaValue as JsonSchemaValue
from pydantic_core import PydanticUndefined, PydanticUndefinedType
from typing import Any, Dict, List, Sequence, Set, Tuple, Type
from typing_extensions import Literal

PYDANTIC_V2: Incomplete
sequence_annotation_to_type: Incomplete
sequence_types: Incomplete
Required = PydanticUndefined
Undefined = PydanticUndefined
UndefinedType = PydanticUndefinedType
evaluate_forwardref = eval_type_lenient
Validator = Any

class BaseConfig: ...
class ErrorWrapper(Exception): ...

@dataclass
class ModelField:
    field_info: FieldInfo
    name: str
    mode: Literal['validation', 'serialization'] = ...
    @property
    def alias(self) -> str: ...
    @property
    def required(self) -> bool: ...
    @property
    def default(self) -> Any: ...
    @property
    def type_(self) -> Any: ...
    def __post_init__(self) -> None: ...
    def get_default(self) -> Any: ...
    def validate(self, value: Any, values: Dict[str, Any] = {}, *, loc: Tuple[int | str, ...] = ()) -> Tuple[Any, List[Dict[str, Any]] | None]: ...
    def serialize(self, value: Any, *, mode: Literal['json', 'python'] = 'json', include: IncEx | None = None, exclude: IncEx | None = None, by_alias: bool = True, exclude_unset: bool = False, exclude_defaults: bool = False, exclude_none: bool = False) -> Any: ...
    def __hash__(self) -> int: ...
    def __init__(self, field_info, name, mode) -> None: ...

def get_annotation_from_field_info(annotation: Any, field_info: FieldInfo, field_name: str) -> Any: ...
def get_schema_from_model_field(*, field: ModelField, schema_generator: GenerateJsonSchema, model_name_map: ModelNameMap, field_mapping: Dict[Tuple[ModelField, Literal['validation', 'serialization']], JsonSchemaValue], separate_input_output_schemas: bool = True) -> Dict[str, Any]: ...
def get_compat_model_name_map(fields: List[ModelField]) -> ModelNameMap: ...
def get_definitions(*, fields: List[ModelField], schema_generator: GenerateJsonSchema, model_name_map: ModelNameMap, separate_input_output_schemas: bool = True) -> Tuple[Dict[Tuple[ModelField, Literal['validation', 'serialization']], JsonSchemaValue], Dict[str, Dict[str, Any]]]: ...
def is_scalar_field(field: ModelField) -> bool: ...
def is_sequence_field(field: ModelField) -> bool: ...
def is_scalar_sequence_field(field: ModelField) -> bool: ...
def is_bytes_field(field: ModelField) -> bool: ...
def is_bytes_sequence_field(field: ModelField) -> bool: ...
def copy_field_info(*, field_info: FieldInfo, annotation: Any) -> FieldInfo: ...
def serialize_sequence_value(*, field: ModelField, value: Any) -> Sequence[Any]: ...
def get_missing_field_error(loc: Tuple[str, ...]) -> Dict[str, Any]: ...
def create_body_model(*, fields: Sequence[ModelField], model_name: str) -> Type[BaseModel]: ...
GetJsonSchemaHandler = Any
JsonSchemaValue = Dict[str, Any]
CoreSchema = Any
sequence_shapes: Incomplete
sequence_shape_to_type: Incomplete

@dataclass
class GenerateJsonSchema:
    ref_template: str
    def __init__(self, ref_template) -> None: ...

class PydanticSchemaGenerationError(Exception): ...

def get_model_definitions(*, flat_models: Set[Type[BaseModel] | Type[Enum]], model_name_map: Dict[Type[BaseModel] | Type[Enum], str]) -> Dict[str, Any]: ...
def is_pv1_scalar_field(field: ModelField) -> bool: ...
def is_pv1_scalar_sequence_field(field: ModelField) -> bool: ...
def field_annotation_is_sequence(annotation: Type[Any] | None) -> bool: ...
def value_is_sequence(value: Any) -> bool: ...
def field_annotation_is_complex(annotation: Type[Any] | None) -> bool: ...
def field_annotation_is_scalar(annotation: Any) -> bool: ...
def field_annotation_is_scalar_sequence(annotation: Type[Any] | None) -> bool: ...
def is_bytes_or_nonable_bytes_annotation(annotation: Any) -> bool: ...
def is_uploadfile_or_nonable_uploadfile_annotation(annotation: Any) -> bool: ...
def is_bytes_sequence_annotation(annotation: Any) -> bool: ...
def is_uploadfile_sequence_annotation(annotation: Any) -> bool: ...
