from _typeshed import Incomplete
from enum import Enum
from fastapi import routing as routing
from fastapi.datastructures import Default as Default, DefaultPlaceholder as DefaultPlaceholder
from fastapi.exception_handlers import http_exception_handler as http_exception_handler, request_validation_exception_handler as request_validation_exception_handler, websocket_request_validation_exception_handler as websocket_request_validation_exception_handler
from fastapi.exceptions import RequestValidationError as RequestValidationError, WebSocketRequestValidationError as WebSocketRequestValidationError
from fastapi.logger import logger as logger
from fastapi.middleware.asyncexitstack import AsyncExitStackMiddleware as AsyncExitStackMiddleware
from fastapi.openapi.docs import get_redoc_html as get_redoc_html, get_swagger_ui_html as get_swagger_ui_html, get_swagger_ui_oauth2_redirect_html as get_swagger_ui_oauth2_redirect_html
from fastapi.openapi.utils import get_openapi as get_openapi
from fastapi.params import Depends as Depends
from fastapi.types import DecoratedCallable as DecoratedCallable, IncEx as IncEx
from fastapi.utils import generate_unique_id as generate_unique_id
from starlette.applications import Starlette
from starlette.middleware import Middleware
from starlette.requests import Request as Request
from starlette.responses import HTMLResponse as HTMLResponse, Response as Response
from starlette.routing import BaseRoute as BaseRoute
from starlette.types import ASGIApp as ASGIApp, Lifespan as Lifespan, Receive as Receive, Scope as Scope, Send as Send
from typing import Any, Callable, Coroutine, Dict, List, Sequence, Type, TypeVar

AppType = TypeVar('AppType', bound='FastAPI')

class FastAPI(Starlette):
    debug: Incomplete
    title: Incomplete
    summary: Incomplete
    description: Incomplete
    version: Incomplete
    terms_of_service: Incomplete
    contact: Incomplete
    license_info: Incomplete
    openapi_url: Incomplete
    openapi_tags: Incomplete
    root_path_in_servers: Incomplete
    docs_url: Incomplete
    redoc_url: Incomplete
    swagger_ui_oauth2_redirect_url: Incomplete
    swagger_ui_init_oauth: Incomplete
    swagger_ui_parameters: Incomplete
    servers: Incomplete
    separate_input_output_schemas: Incomplete
    extra: Incomplete
    openapi_version: str
    openapi_schema: Incomplete
    webhooks: Incomplete
    root_path: Incomplete
    state: Incomplete
    dependency_overrides: Incomplete
    router: Incomplete
    exception_handlers: Incomplete
    user_middleware: Incomplete
    middleware_stack: Incomplete
    def __init__(self, *, debug: bool = False, routes: List[BaseRoute] | None = None, title: str = 'FastAPI', summary: str | None = None, description: str = '', version: str = '0.1.0', openapi_url: str | None = '/openapi.json', openapi_tags: List[Dict[str, Any]] | None = None, servers: List[Dict[str, str | Any]] | None = None, dependencies: Sequence[Depends] | None = None, default_response_class: Type[Response] = ..., redirect_slashes: bool = True, docs_url: str | None = '/docs', redoc_url: str | None = '/redoc', swagger_ui_oauth2_redirect_url: str | None = '/docs/oauth2-redirect', swagger_ui_init_oauth: Dict[str, Any] | None = None, middleware: Sequence[Middleware] | None = None, exception_handlers: Dict[int | Type[Exception], Callable[[Request, Any], Coroutine[Any, Any, Response]]] | None = None, on_startup: Sequence[Callable[[], Any]] | None = None, on_shutdown: Sequence[Callable[[], Any]] | None = None, lifespan: Lifespan[AppType] | None = None, terms_of_service: str | None = None, contact: Dict[str, str | Any] | None = None, license_info: Dict[str, str | Any] | None = None, openapi_prefix: str = '', root_path: str = '', root_path_in_servers: bool = True, responses: Dict[int | str, Dict[str, Any]] | None = None, callbacks: List[BaseRoute] | None = None, webhooks: routing.APIRouter | None = None, deprecated: bool | None = None, include_in_schema: bool = True, swagger_ui_parameters: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ..., separate_input_output_schemas: bool = True, **extra: Any) -> None: ...
    def build_middleware_stack(self) -> ASGIApp: ...
    def openapi(self) -> Dict[str, Any]: ...
    def setup(self) -> None: ...
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None: ...
    def add_api_route(self, path: str, endpoint: Callable[..., Coroutine[Any, Any, Response]], *, response_model: Any = ..., status_code: int | None = None, tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, summary: str | None = None, description: str | None = None, response_description: str = 'Successful Response', responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, methods: List[str] | None = None, operation_id: str | None = None, response_model_include: IncEx | None = None, response_model_exclude: IncEx | None = None, response_model_by_alias: bool = True, response_model_exclude_unset: bool = False, response_model_exclude_defaults: bool = False, response_model_exclude_none: bool = False, include_in_schema: bool = True, response_class: Type[Response] | DefaultPlaceholder = ..., name: str | None = None, openapi_extra: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> None: ...
    def api_route(self, path: str, *, response_model: Any = ..., status_code: int | None = None, tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, summary: str | None = None, description: str | None = None, response_description: str = 'Successful Response', responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, methods: List[str] | None = None, operation_id: str | None = None, response_model_include: IncEx | None = None, response_model_exclude: IncEx | None = None, response_model_by_alias: bool = True, response_model_exclude_unset: bool = False, response_model_exclude_defaults: bool = False, response_model_exclude_none: bool = False, include_in_schema: bool = True, response_class: Type[Response] = ..., name: str | None = None, openapi_extra: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def add_api_websocket_route(self, path: str, endpoint: Callable[..., Any], name: str | None = None, *, dependencies: Sequence[Depends] | None = None) -> None: ...
    def websocket(self, path: str, name: str | None = None, *, dependencies: Sequence[Depends] | None = None) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def include_router(self, router: routing.APIRouter, *, prefix: str = '', tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, include_in_schema: bool = True, default_response_class: Type[Response] = ..., callbacks: List[BaseRoute] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> None: ...
    def get(self, path: str, *, response_model: Any = ..., status_code: int | None = None, tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, summary: str | None = None, description: str | None = None, response_description: str = 'Successful Response', responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, operation_id: str | None = None, response_model_include: IncEx | None = None, response_model_exclude: IncEx | None = None, response_model_by_alias: bool = True, response_model_exclude_unset: bool = False, response_model_exclude_defaults: bool = False, response_model_exclude_none: bool = False, include_in_schema: bool = True, response_class: Type[Response] = ..., name: str | None = None, callbacks: List[BaseRoute] | None = None, openapi_extra: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def put(self, path: str, *, response_model: Any = ..., status_code: int | None = None, tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, summary: str | None = None, description: str | None = None, response_description: str = 'Successful Response', responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, operation_id: str | None = None, response_model_include: IncEx | None = None, response_model_exclude: IncEx | None = None, response_model_by_alias: bool = True, response_model_exclude_unset: bool = False, response_model_exclude_defaults: bool = False, response_model_exclude_none: bool = False, include_in_schema: bool = True, response_class: Type[Response] = ..., name: str | None = None, callbacks: List[BaseRoute] | None = None, openapi_extra: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def post(self, path: str, *, response_model: Any = ..., status_code: int | None = None, tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, summary: str | None = None, description: str | None = None, response_description: str = 'Successful Response', responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, operation_id: str | None = None, response_model_include: IncEx | None = None, response_model_exclude: IncEx | None = None, response_model_by_alias: bool = True, response_model_exclude_unset: bool = False, response_model_exclude_defaults: bool = False, response_model_exclude_none: bool = False, include_in_schema: bool = True, response_class: Type[Response] = ..., name: str | None = None, callbacks: List[BaseRoute] | None = None, openapi_extra: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def delete(self, path: str, *, response_model: Any = ..., status_code: int | None = None, tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, summary: str | None = None, description: str | None = None, response_description: str = 'Successful Response', responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, operation_id: str | None = None, response_model_include: IncEx | None = None, response_model_exclude: IncEx | None = None, response_model_by_alias: bool = True, response_model_exclude_unset: bool = False, response_model_exclude_defaults: bool = False, response_model_exclude_none: bool = False, include_in_schema: bool = True, response_class: Type[Response] = ..., name: str | None = None, callbacks: List[BaseRoute] | None = None, openapi_extra: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def options(self, path: str, *, response_model: Any = ..., status_code: int | None = None, tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, summary: str | None = None, description: str | None = None, response_description: str = 'Successful Response', responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, operation_id: str | None = None, response_model_include: IncEx | None = None, response_model_exclude: IncEx | None = None, response_model_by_alias: bool = True, response_model_exclude_unset: bool = False, response_model_exclude_defaults: bool = False, response_model_exclude_none: bool = False, include_in_schema: bool = True, response_class: Type[Response] = ..., name: str | None = None, callbacks: List[BaseRoute] | None = None, openapi_extra: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def head(self, path: str, *, response_model: Any = ..., status_code: int | None = None, tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, summary: str | None = None, description: str | None = None, response_description: str = 'Successful Response', responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, operation_id: str | None = None, response_model_include: IncEx | None = None, response_model_exclude: IncEx | None = None, response_model_by_alias: bool = True, response_model_exclude_unset: bool = False, response_model_exclude_defaults: bool = False, response_model_exclude_none: bool = False, include_in_schema: bool = True, response_class: Type[Response] = ..., name: str | None = None, callbacks: List[BaseRoute] | None = None, openapi_extra: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def patch(self, path: str, *, response_model: Any = ..., status_code: int | None = None, tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, summary: str | None = None, description: str | None = None, response_description: str = 'Successful Response', responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, operation_id: str | None = None, response_model_include: IncEx | None = None, response_model_exclude: IncEx | None = None, response_model_by_alias: bool = True, response_model_exclude_unset: bool = False, response_model_exclude_defaults: bool = False, response_model_exclude_none: bool = False, include_in_schema: bool = True, response_class: Type[Response] = ..., name: str | None = None, callbacks: List[BaseRoute] | None = None, openapi_extra: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def trace(self, path: str, *, response_model: Any = ..., status_code: int | None = None, tags: List[str | Enum] | None = None, dependencies: Sequence[Depends] | None = None, summary: str | None = None, description: str | None = None, response_description: str = 'Successful Response', responses: Dict[int | str, Dict[str, Any]] | None = None, deprecated: bool | None = None, operation_id: str | None = None, response_model_include: IncEx | None = None, response_model_exclude: IncEx | None = None, response_model_by_alias: bool = True, response_model_exclude_unset: bool = False, response_model_exclude_defaults: bool = False, response_model_exclude_none: bool = False, include_in_schema: bool = True, response_class: Type[Response] = ..., name: str | None = None, callbacks: List[BaseRoute] | None = None, openapi_extra: Dict[str, Any] | None = None, generate_unique_id_function: Callable[[routing.APIRoute], str] = ...) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def websocket_route(self, path: str, name: str | None = None) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def on_event(self, event_type: str) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def middleware(self, middleware_type: str) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
    def exception_handler(self, exc_class_or_status_code: int | Type[Exception]) -> Callable[[DecoratedCallable], DecoratedCallable]: ...
