from pasta.augment import errors as errors
from pasta.base import ast_utils as ast_utils, test_utils as test_utils

class UtilsTest(test_utils.TestCase):
    def test_sanitize_source(self) -> None: ...

class AlterChildTest(test_utils.TestCase):
    def testRemoveChildMethod(self) -> None: ...
    def testRemoveAlias(self) -> None: ...
    def testRemoveFromBlock(self) -> None: ...
    def testReplaceChildInBody(self) -> None: ...
    def testReplaceChildInvalid(self) -> None: ...
