from _typeshed import Incomplete

TFMODELS: Incomplete

def download_compressed_file(tf_ckpt_url, ckpt_dir): ...
def get_ckpt_prefix_path(ckpt_dir): ...
def download_tf_checkpoint(model_name, tf_models_dir: str = 'tf_models'): ...
def init_pytorch_model(model_name, tf_checkpoint_path): ...
def convert_tf_checkpoint_to_pytorch(model_name, config, init_model, tf_checkpoint_path, is_tf2): ...
def tf2pt_pipeline(model_name, is_tf2: bool = False): ...
def tf2pt_pipeline_test() -> None: ...
