from _typeshed import Incomplete
from onnx_model_bert import BertOnnxModel

logger: Incomplete

class BertOnnxModelTF(BertOnnxModel):
    def __init__(self, model, num_heads, hidden_size) -> None: ...
    def remove_identity(self) -> None: ...
    def match_mask_path(self, add_or_sub_before_softmax): ...
    def get_2d_initializers_from_parent_subgraphs(self, current_node):
        """
        Find initializers that is 2D. Returns a dictionary with name as key and shape as value.
        """
    def find_segment_ids(self, segment_embedding, input_ids): ...
    def find_input_ids(self, word_embedding): ...
    def find_mask_input(self, excluded_graph_inputs): ...
    bert_inputs: Incomplete
    def create_embedding_subgraph(self, normalize_node, word_embedding, segment_embedding, position_embedding): ...
    def process_embedding(self) -> None:
        """
        Automatically detect word, segment and position embeddings.
        """
    def check_attention_input(self, matmul_q, matmul_k, matmul_v, parent, output_name_to_node): ...
    def fuse_attention(self) -> None: ...
    def preprocess(self) -> None: ...
    def skip_reshape(self) -> None: ...
    def remove_reshape_before_first_attention(self) -> None: ...
    def postprocess(self) -> None: ...
