from _typeshed import Incomplete
from onnx_model_bert_tf import BertOnnxModelTF

logger: Incomplete

class BertOnnxModelKeras(BertOnnxModelTF):
    def __init__(self, model, num_heads, hidden_size) -> None: ...
    def match_mask_path(self, add_or_sub_before_softmax): ...
    def check_attention_input(self, matmul_q, matmul_k, matmul_v, parent, output_name_to_node): ...
    def fuse_attention(self) -> None: ...
    def preprocess(self) -> None: ...
    def skip_reshape(self) -> None: ...
    def fuse_embedding(self, node, output_name_to_node): ...
    def process_embedding(self) -> None:
        """
        Automatically detect word, segment and position embeddings.
        """
    def fuse_mask(self) -> None: ...
    def remove_extra_reshape(self): ...
    def remove_extra_reshape_2(self): ...
    def postprocess(self) -> None: ...
