from Cython.Compiler.TreeFragment import *
from Cython.Compiler.Nodes import *
from Cython.Compiler.UtilNodes import *
from Cython.TestUtils import CythonTest as CythonTest

class TestTreeFragments(CythonTest):
    def test_basic(self) -> None: ...
    def test_copy_is_taken(self) -> None: ...
    def test_substitutions_are_copied(self) -> None: ...
    def test_substitution(self) -> None: ...
    def test_exprstat(self) -> None: ...
    def test_pos_is_transferred(self) -> None: ...
    def test_temps(self) -> None: ...
