from Cython.Compiler.Nodes import *
from Cython.Compiler.ParseTreeTransforms import *
from Cython.Compiler.Buffer import *
from Cython.TestUtils import CythonTest as CythonTest

class TestMemviewParsing(CythonTest):
    def parse(self, s): ...
    def not_parseable(self, expected_error, s): ...
    def test_default_1dim(self) -> None: ...
    def test_default_ndim(self) -> None: ...
    def test_zero_offset(self) -> None: ...
    def test_zero_offset_ndim(self) -> None: ...
    def test_def_arg(self) -> None: ...
    def test_cdef_arg(self) -> None: ...
    def test_general_slice(self) -> None: ...
    def test_non_slice_memview(self) -> None: ...
    def test_basic(self) -> None: ...
    def disable_test_no_buf_arg(self) -> None: ...
    def disable_test_parse_sizeof(self) -> None: ...
