import unittest
from Cython.Compiler.ExprNodes import NameNode as NameNode
from Cython.Compiler.PyrexTypes import CFuncTypeArg as CFuncTypeArg

def cfunctype(*arg_types): ...
def cppclasstype(name, base_classes): ...

class SignatureMatcherTest(unittest.TestCase):
    """
    Test the signature matching algorithm for overloaded signatures.
    """
    def assertMatches(self, expected_type, arg_types, functions) -> None: ...
    def test_cpp_reference_single_arg(self) -> None: ...
    def test_cpp_reference_two_args(self) -> None: ...
    def test_cpp_reference_cpp_class(self) -> None: ...
    def test_cpp_reference_cpp_class_and_int(self) -> None: ...
