from Cython.Compiler.Nodes import *
from Cython.Compiler.ParseTreeTransforms import *
from Cython.Compiler.Buffer import *
from Cython.TestUtils import CythonTest as CythonTest
from _typeshed import Incomplete

class TestBufferParsing(CythonTest):
    def parse(self, s): ...
    def not_parseable(self, expected_error, s): ...
    def test_basic(self) -> None: ...
    def test_type_pos(self) -> None: ...
    def test_type_keyword(self) -> None: ...
    def test_pos_after_key(self) -> None: ...

class TestBufferOptions(CythonTest):
    error: Incomplete
    def nonfatal_error(self, error) -> None: ...
    expect_error: Incomplete
    def parse_opts(self, opts, expect_error: bool = False): ...
    def non_parse(self, expected_err, opts) -> None: ...
