from Cython.Compiler.ParseTreeTransforms import *
from Cython.Compiler.Nodes import *
import unittest
from Cython.Compiler import Main as Main, Options as Options, Symtab as Symtab
from Cython.Debugger import DebugWriter as DebugWriter
from Cython.Debugger.Tests.TestLibCython import DebuggerTestCase as DebuggerTestCase
from Cython.TestUtils import TransformTest as TransformTest
from _typeshed import Incomplete

class TestNormalizeTree(TransformTest):
    def test_parserbehaviour_is_what_we_coded_for(self) -> None: ...
    def test_wrap_singlestat(self) -> None: ...
    def test_wrap_multistat(self) -> None: ...
    def test_statinexpr(self) -> None: ...
    def test_wrap_offagain(self) -> None: ...
    def test_pass_eliminated(self) -> None: ...

class TestWithTransform:
    def test_simplified(self) -> None: ...
    def test_basic(self) -> None: ...

class TestInterpretCompilerDirectives(TransformTest):
    """
    This class tests the parallel directives AST-rewriting and importing.
    """
    import_code: str
    expected_directives_dict: Incomplete
    pipeline: Incomplete
    debug_exception_on_error: Incomplete
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_parallel_directives_cimports(self) -> None: ...
    def test_parallel_directives_imports(self) -> None: ...
DebuggerTestCase = object

class TestDebugTransform(DebuggerTestCase):
    def elem_hasattrs(self, elem, attrs): ...
    def test_debug_info(self): ...

class TestAnalyseDeclarationsTransform(unittest.TestCase):
    def test_calculate_pickle_checksums(self) -> None: ...
