from mlflow.exceptions import MlflowException as MlflowException
from mlflow.store.model_registry.rest_store import RestStore as RestStore

class DatabricksWorkspaceModelRegistryRestStore(RestStore):
    def set_registered_model_alias(self, name, alias, version) -> None: ...
    def delete_registered_model_alias(self, name, alias) -> None: ...
    def get_model_version_by_alias(self, name, alias) -> None: ...
