from wandb.sklearn import utils as utils

def class_proportions(y_train, y_test, labels): ...
def make_table(class_column, dataset_column, count_column): ...
def make_columns(class_ids, counts_train, counts_test): ...
def get_named_labels(labels, numeric_labels): ...
