from ._generated.models import ArrowConfiguration as ArrowConfiguration, BlobTag as BlobTag, BlobTags as BlobTags, ContainerCpkScopeInfo as ContainerCpkScopeInfo, CpkScopeInfo as CpkScopeInfo, DelimitedTextConfiguration as DelimitedTextConfiguration, JsonTextConfiguration as JsonTextConfiguration, LeaseAccessConditions as LeaseAccessConditions, ModifiedAccessConditions as ModifiedAccessConditions, QueryFormat as QueryFormat, QueryFormatType as QueryFormatType, QuerySerialization as QuerySerialization, SourceModifiedAccessConditions as SourceModifiedAccessConditions
from ._lease import BlobLeaseClient as BlobLeaseClient
from ._models import ContainerEncryptionScope as ContainerEncryptionScope, DelimitedJsonDialect as DelimitedJsonDialect
from typing import Any, Dict

def get_access_conditions(lease: BlobLeaseClient | str | None) -> LeaseAccessConditions | None: ...
def get_modify_conditions(kwargs: Dict[str, Any]) -> ModifiedAccessConditions: ...
def get_source_conditions(kwargs: Dict[str, Any]) -> SourceModifiedAccessConditions: ...
def get_cpk_scope_info(kwargs: Dict[str, Any]) -> CpkScopeInfo: ...
def get_container_cpk_scope_info(kwargs: Dict[str, Any]) -> ContainerCpkScopeInfo: ...
def get_api_version(kwargs: Dict[str, Any]) -> str: ...
def get_version_id(self_vid: str | None, kwargs: Dict[str, Any]) -> str | None: ...
def serialize_blob_tags_header(tags: Dict[str, str] | None = None) -> str: ...
def serialize_blob_tags(tags: Dict[str, str] | None = None) -> BlobTags | None: ...
def serialize_query_format(formater): ...
