from _typeshed import Incomplete
from patsy.util import no_pickling as no_pickling

class _ExpandedFactor:
    """A factor, with an additional annotation for whether it is coded
    full-rank (includes_intercept=True) or not.

    These objects are treated as immutable."""
    includes_intercept: Incomplete
    factor: Incomplete
    def __init__(self, includes_intercept, factor) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class _Subterm:
    """Also immutable."""
    efactors: Incomplete
    def __init__(self, efactors) -> None: ...
    def can_absorb(self, other): ...
    def absorb(self, other): ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

def test__Subterm() -> None: ...
def test__subsets_sorted() -> None: ...
def test__simplify_subterms() -> None: ...
def pick_contrasts_for_term(term, numeric_factors, used_subterms): ...
def test_pick_contrasts_for_term() -> None: ...
