from _typeshed import Incomplete
from collections.abc import Generator

__all__ = ['python_tokenize', 'pretty_untokenize', 'normalize_token_spacing']

def python_tokenize(code) -> Generator[Incomplete, None, None]: ...
def pretty_untokenize(typed_tokens): ...
def normalize_token_spacing(code): ...
