from _typeshed import Incomplete

__all__ = ['atleast_2d_column_default', 'uniqueify_list', 'widest_float', 'widest_complex', 'wide_dtype_for', 'widen', 'repr_pretty_delegate', 'repr_pretty_impl', 'SortAnythingKey', 'safe_scalar_isnan', 'safe_isnan', 'iterable', 'have_pandas', 'have_pandas_categorical', 'have_pandas_categorical_dtype', 'pandas_Categorical_from_codes', 'pandas_Categorical_categories', 'pandas_Categorical_codes', 'safe_is_pandas_categorical_dtype', 'safe_is_pandas_categorical', 'safe_issubdtype', 'no_pickling', 'assert_no_pickling', 'safe_string_eq']

have_pandas: bool
have_pandas_categorical: Incomplete
have_pandas_categorical_dtype: bool

def atleast_2d_column_default(a, preserve_pandas: bool = False): ...
def uniqueify_list(seq): ...

widest_float: Incomplete
widest_complex: Incomplete

def wide_dtype_for(arr): ...
def widen(arr): ...

class PushbackAdapter:
    def __init__(self, it) -> None: ...
    def __iter__(self): ...
    def push_back(self, obj) -> None: ...
    def next(self): ...
    __next__ = next
    def peek(self): ...
    def has_more(self): ...

class _MiniPPrinter:
    indentation: int
    def __init__(self) -> None: ...
    def text(self, text) -> None: ...
    def breakable(self, sep: str = ' ') -> None: ...
    def begin_group(self, _, text) -> None: ...
    def end_group(self, _, text) -> None: ...
    def pretty(self, obj) -> None: ...
    def getvalue(self): ...

def repr_pretty_delegate(obj): ...
def repr_pretty_impl(p, obj, args, kwargs=[]) -> None: ...

class SortAnythingKey:
    obj: Incomplete
    def __init__(self, obj) -> None: ...
    def __lt__(self, other): ...

def safe_scalar_isnan(x): ...

safe_isnan: Incomplete

def iterable(obj): ...
def pandas_Categorical_from_codes(codes, categories): ...
def pandas_Categorical_categories(cat): ...
def pandas_Categorical_codes(cat): ...
def safe_is_pandas_categorical_dtype(dt): ...
def safe_is_pandas_categorical(data): ...
def safe_issubdtype(dt1, dt2): ...
def no_pickling(*args, **kwargs) -> None: ...
def assert_no_pickling(obj) -> None: ...
def safe_string_eq(obj, value): ...
