from llvmlite.binding import ffi as ffi

def create_context(): ...
def get_global_context(): ...

class ContextRef(ffi.ObjectRef):
    def __init__(self, context_ptr) -> None: ...

class GlobalContextRef(ContextRef): ...
