import jax
import jax.numpy as jnp
from _typeshed import Incomplete
from jax import lax as lax
from typing import Any

DEFAULT_MASK_VALUE: Incomplete

def mha_forward_kernel(q_ref, k_ref, v_ref, segment_ids_ref: jax.Array | None, o_ref: Any, *residual_refs: Any, sm_scale: float, causal: bool, block_q: int, block_d: int, block_k: int): ...
def segment_mask(q_segment_ids: jax.Array, kv_segment_ids: jax.Array): ...
def mha(q, k, v, segment_ids: jnp.ndarray | None, sm_scale: float = 1.0, causal: bool = False, block_q: int = 128, block_k: int = 128, backward_pass_impl: str = 'triton', num_warps: int | None = None, num_stages: int = 2, grid: Incomplete | None = None, interpret: bool = False, debug: bool = False): ...
def mha_backward_kernel(q_ref, k_ref, v_ref, segment_ids_ref: jax.Array | None, out_ref, do_scaled_ref, l_ref, m_ref, delta_ref, _, dq_ref, dk_ref, dv_ref, *, sm_scale: float, causal: bool, block_q: int, block_d: int, block_k: int): ...
def mha_reference(q, k, v, segment_ids: jnp.ndarray | None, sm_scale: float = 1.0, causal: bool = False): ...
