from tensorflow.python.training.experimental.mixed_precision_global_state import is_mixed_precision_graph_rewrite_enabled as is_mixed_precision_graph_rewrite_enabled, set_using_mixed_precision_policy as set_using_mixed_precision_policy
from tensorflow.python.training.moving_averages import assign_moving_average as assign_moving_average
