from jedi import debug as debug
from jedi.inference.base_value import NO_VALUES as NO_VALUES, ValueSet as ValueSet, ValueWrapper as ValueWrapper
from jedi.inference.gradual.base import BaseTypingValue as BaseTypingValue

class TypeVarClass(ValueWrapper):
    def py__call__(self, arguments): ...

class TypeVar(BaseTypingValue):
    def __init__(self, parent_context, tree_name, var_name, unpacked_args) -> None: ...
    def py__name__(self): ...
    def get_filters(self, *args, **kwargs): ...
    def is_same_class(self, other): ...
    @property
    def constraints(self): ...
    def define_generics(self, type_var_dict): ...
    def execute_annotation(self): ...
    def infer_type_vars(self, value_set): ...

class TypeWrapper(ValueWrapper):
    def __init__(self, wrapped_value, original_value) -> None: ...
    def execute_annotation(self): ...
