import abc
import dataclasses
from _typeshed import Incomplete

IS_COLAB_ENABLED: Incomplete

class DOMElement(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def render(self): ...
Element = DOMElement | str

class DynamicDOMElement(DOMElement, metaclass=abc.ABCMeta):
    """A DOM element that can be mutated."""
    @abc.abstractmethod
    def render(self): ...
    @abc.abstractmethod
    def append(self, child: DOMElement): ...
    @abc.abstractmethod
    def update(self, elem: DOMElement): ...
    @abc.abstractmethod
    def clear(self): ...

@dataclasses.dataclass
class DynamicDiv(DynamicDOMElement):
    """A `div` that can be edited."""
    elem: DOMElement | str
    def __post_init__(self) -> None: ...
    @property
    def tag(self): ...
    def render(self) -> None: ...
    def append(self, child: DOMElement): ...
    def update(self, elem: DOMElement): ...
    def clear(self) -> None: ...
    def __init__(self, elem) -> None: ...

@dataclasses.dataclass
class StaticDOMElement(DOMElement):
    """An immutable DOM element."""
    name: str
    children: list[str | DOMElement]
    attrs: dict[str, str]
    def html(self): ...
    def render(self) -> None: ...
    def attr(self, key: str) -> str: ...
    def append(self, child: DOMElement) -> DOMElement: ...
    def replace(self, **kwargs) -> DOMElement: ...
    def __init__(self, name, children, attrs) -> None: ...

def dynamic(elem: StaticDOMElement) -> DynamicDiv: ...

code: Incomplete
div: Incomplete
li: Incomplete
ol: Incomplete
pre: Incomplete
progress: Incomplete
span: Incomplete

def css(text: str) -> StaticDOMElement: ...
def style(*args, **kwargs): ...
