from _typeshed import Incomplete
from tensorflow_estimator.python.estimator import estimator as estimator
from tensorflow_estimator.python.estimator.canned import linear as linear, metric_keys as metric_keys
from tensorflow_estimator.python.estimator.export import export as export
from tensorflow_estimator.python.estimator.inputs import numpy_io as numpy_io, pandas_io as pandas_io

HAS_PANDAS: bool
AGE_WEIGHT_NAME: str
HEIGHT_WEIGHT_NAME: str
OCCUPATION_WEIGHT_NAME: str
BIAS_NAME: str
LANGUAGE_WEIGHT_NAME: str

def assert_close(expected, actual, rtol: float = 0.0001, name: str = 'assert_close'): ...
def save_variables_to_ckpt(model_dir) -> None: ...
def queue_parsed_features(feature_map): ...
def sorted_key_dict(unsorted_dict): ...
def sigmoid(x): ...
def mock_optimizer(testcase, expected_loss: Incomplete | None = None): ...

class BaseLinearRegressorEvaluationTest:
    def __init__(self, linear_regressor_fn, fc_lib=...) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_evaluation_for_simple_data(self): ...
    def test_evaluation_batch(self):
        """Tests evaluation for batch_size==2."""
    def test_evaluation_weights(self):
        """Tests evaluation with weights."""
    def test_evaluation_for_multi_dimensions(self) -> None: ...
    def test_evaluation_for_multiple_feature_columns(self) -> None: ...
    def test_evaluation_for_multiple_feature_columns_mix(self): ...

class BaseLinearRegressorPredictTest:
    def __init__(self, linear_regressor_fn, fc_lib=...) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_1d(self) -> None:
        """Tests predict when all variables are one-dimensional."""
    def testMultiDim(self) -> None:
        """Tests predict when all variables are multi-dimenstional."""
    def testTwoFeatureColumns(self) -> None:
        """Tests predict with two feature columns."""
    def testTwoFeatureColumnsMix(self):
        """Tests predict with two feature columns."""
    def testSparseCombiner(self): ...

class BaseLinearRegressorIntegrationTest:
    def __init__(self, linear_regressor_fn, fc_lib=...) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_numpy_input_fn(self) -> None:
        """Tests complete flow with numpy_input_fn."""
    def test_pandas_input_fn(self) -> None:
        """Tests complete flow with pandas_input_fn."""
    def test_input_fn_from_parse_example(self):
        """Tests complete flow with input_fn constructed from parse_example."""

class BaseLinearRegressorTrainingTest:
    def __init__(self, linear_regressor_fn, fc_lib=...) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def testFromScratchWithDefaultOptimizer(self): ...
    def testTrainWithOneDimLabel(self) -> None: ...
    def testTrainWithOneDimWeight(self) -> None: ...
    def testFromScratch(self): ...
    def testFromCheckpoint(self): ...
    def testFromCheckpointMultiBatch(self): ...

class BaseLinearClassifierTrainingTest:
    def __init__(self, linear_classifier_fn, fc_lib=...) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def testBinaryClassesFromScratchWithDefaultOptimizer(self) -> None: ...
    def testMultiClassesFromScratchWithDefaultOptimizer(self) -> None: ...
    def testBinaryClassesTrainWithTwoDimsLabel(self) -> None: ...
    def testMultiClassesTrainWithTwoDimsLabel(self) -> None: ...
    def testBinaryClassesTrainWithOneDimLabel(self) -> None: ...
    def testMultiClassesTrainWithOneDimLabel(self) -> None: ...
    def testBinaryClassesTrainWithTwoDimsWeight(self) -> None: ...
    def testMultiClassesTrainWithTwoDimsWeight(self) -> None: ...
    def testBinaryClassesTrainWithOneDimWeight(self) -> None: ...
    def testMultiClassesTrainWithOneDimWeight(self) -> None: ...
    def testBinaryClassesFromScratch(self) -> None: ...
    def testMultiClassesFromScratch(self) -> None: ...
    def testBinaryClassesFromCheckpoint(self) -> None: ...
    def testMultiClassesFromCheckpoint(self) -> None: ...
    def testBinaryClassesFromCheckpointFloatLabels(self) -> None: ...
    def testMultiClassesFromCheckpointFloatLabels(self) -> None: ...
    def testBinaryClassesFromCheckpointMultiBatch(self) -> None: ...
    def testMultiClassesFromCheckpointMultiBatch(self) -> None: ...

class BaseLinearClassifierEvaluationTest:
    def __init__(self, linear_classifier_fn, fc_lib=...) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_binary_classes_evaluation_for_simple_data(self) -> None: ...
    def test_multi_classes_evaluation_for_simple_data(self) -> None: ...
    def test_binary_classes_evaluation_batch(self) -> None: ...
    def test_multi_classes_evaluation_batch(self) -> None: ...
    def test_binary_classes_evaluation_weights(self) -> None: ...
    def test_multi_classes_evaluation_weights(self) -> None: ...

class BaseLinearClassifierPredictTest:
    def __init__(self, linear_classifier_fn, fc_lib=...) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def testBinaryClassesWithoutLabelVocabulary(self): ...
    def testBinaryClassesWithLabelVocabulary(self): ...
    def testMultiClassesWithoutLabelVocabulary(self): ...
    def testMultiClassesWithLabelVocabulary(self): ...
    def testSparseCombiner(self): ...

class BaseLinearClassifierIntegrationTest:
    def __init__(self, linear_classifier_fn, fc_lib=...) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_binary_classes_numpy_input_fn(self) -> None: ...
    def test_multi_classes_numpy_input_fn(self) -> None: ...
    def test_binary_classes_pandas_input_fn(self) -> None: ...
    def test_multi_classes_pandas_input_fn(self) -> None: ...
    def test_binary_classes_input_fn_from_parse_example(self) -> None: ...
    def test_multi_classes_input_fn_from_parse_example(self) -> None: ...

class BaseLinearLogitFnTest:
    def __init__(self, fc_lib=...) -> None: ...
    def test_basic_logit_correctness(self) -> None:
        """linear_logit_fn simply wraps feature_column_lib.linear_model."""
    def test_compute_fraction_of_zero_v2(self) -> None:
        """Tests the calculation of sparsity."""

class BaseLinearWarmStartingTest:
    def __init__(self, _linear_classifier_fn, _linear_regressor_fn, fc_lib=...) -> None: ...
    def setUp(self): ...
    def tearDown(self) -> None: ...
    def test_classifier_basic_warm_starting(self) -> None:
        """Tests correctness of LinearClassifier default warm-start."""
    def test_regressor_basic_warm_starting(self) -> None:
        """Tests correctness of LinearRegressor default warm-start."""
    def test_warm_starting_selective_variables(self) -> None:
        """Tests selecting variables to warm-start."""
    def test_warm_starting_with_vocab_remapping_and_partitioning(self) -> None:
        """Tests warm-starting with vocab remapping and partitioning."""
    def test_warm_starting_with_naming_change(self) -> None:
        """Tests warm-starting with a Tensor name remapping."""
