from _typeshed import Incomplete
from mypy.nodes import AssertTypeExpr as AssertTypeExpr, AssignmentExpr as AssignmentExpr, AwaitExpr as AwaitExpr, CallExpr as CallExpr, CastExpr as CastExpr, ComparisonExpr as ComparisonExpr, ConditionalExpr as ConditionalExpr, DictExpr as DictExpr, DictionaryComprehension as DictionaryComprehension, Expression as Expression, GeneratorExpr as GeneratorExpr, IndexExpr as IndexExpr, LambdaExpr as LambdaExpr, ListComprehension as ListComprehension, ListExpr as ListExpr, MemberExpr as MemberExpr, Node as Node, OpExpr as OpExpr, RevealExpr as RevealExpr, SetComprehension as SetComprehension, SetExpr as SetExpr, SliceExpr as SliceExpr, StarExpr as StarExpr, TupleExpr as TupleExpr, TypeApplication as TypeApplication, UnaryExpr as UnaryExpr, YieldExpr as YieldExpr, YieldFromExpr as YieldFromExpr
from mypy.traverser import TraverserVisitor as TraverserVisitor

def get_subexpressions(node: Node) -> list[Expression]: ...

class SubexpressionFinder(TraverserVisitor):
    expressions: Incomplete
    def __init__(self) -> None: ...
    def visit_int_expr(self, o: Expression) -> None: ...
    def visit_name_expr(self, o: Expression) -> None: ...
    def visit_float_expr(self, o: Expression) -> None: ...
    def visit_str_expr(self, o: Expression) -> None: ...
    def visit_bytes_expr(self, o: Expression) -> None: ...
    def visit_unicode_expr(self, o: Expression) -> None: ...
    def visit_complex_expr(self, o: Expression) -> None: ...
    def visit_ellipsis(self, o: Expression) -> None: ...
    def visit_super_expr(self, o: Expression) -> None: ...
    def visit_type_var_expr(self, o: Expression) -> None: ...
    def visit_type_alias_expr(self, o: Expression) -> None: ...
    def visit_namedtuple_expr(self, o: Expression) -> None: ...
    def visit_typeddict_expr(self, o: Expression) -> None: ...
    def visit__promote_expr(self, o: Expression) -> None: ...
    def visit_newtype_expr(self, o: Expression) -> None: ...
    def visit_member_expr(self, e: MemberExpr) -> None: ...
    def visit_yield_from_expr(self, e: YieldFromExpr) -> None: ...
    def visit_yield_expr(self, e: YieldExpr) -> None: ...
    def visit_call_expr(self, e: CallExpr) -> None: ...
    def visit_op_expr(self, e: OpExpr) -> None: ...
    def visit_comparison_expr(self, e: ComparisonExpr) -> None: ...
    def visit_slice_expr(self, e: SliceExpr) -> None: ...
    def visit_cast_expr(self, e: CastExpr) -> None: ...
    def visit_assert_type_expr(self, e: AssertTypeExpr) -> None: ...
    def visit_reveal_expr(self, e: RevealExpr) -> None: ...
    def visit_assignment_expr(self, e: AssignmentExpr) -> None: ...
    def visit_unary_expr(self, e: UnaryExpr) -> None: ...
    def visit_list_expr(self, e: ListExpr) -> None: ...
    def visit_tuple_expr(self, e: TupleExpr) -> None: ...
    def visit_dict_expr(self, e: DictExpr) -> None: ...
    def visit_set_expr(self, e: SetExpr) -> None: ...
    def visit_index_expr(self, e: IndexExpr) -> None: ...
    def visit_generator_expr(self, e: GeneratorExpr) -> None: ...
    def visit_dictionary_comprehension(self, e: DictionaryComprehension) -> None: ...
    def visit_list_comprehension(self, e: ListComprehension) -> None: ...
    def visit_set_comprehension(self, e: SetComprehension) -> None: ...
    def visit_conditional_expr(self, e: ConditionalExpr) -> None: ...
    def visit_type_application(self, e: TypeApplication) -> None: ...
    def visit_lambda_expr(self, e: LambdaExpr) -> None: ...
    def visit_star_expr(self, e: StarExpr) -> None: ...
    def visit_await_expr(self, e: AwaitExpr) -> None: ...
    def add(self, e: Expression) -> None: ...
