from .encoding import DEFAULT_ENCODING as DEFAULT_ENCODING
from _typeshed import Incomplete

def decode(s, encoding: Incomplete | None = None): ...
def encode(u, encoding: Incomplete | None = None): ...
def cast_unicode(s, encoding: Incomplete | None = None): ...
def safe_unicode(e):
    """unicode(e) with various fallbacks. Used for exceptions, which may not be
    safe to call unicode() on.
    """
def input(prompt: str = ''): ...
def execfile(fname, glob, loc: Incomplete | None = None, compiler: Incomplete | None = None) -> None: ...

PYPY: Incomplete

def no_code(x, encoding: Incomplete | None = None): ...
unicode_to_str = no_code
cast_bytes_py2 = no_code
