from torchgen.api import cpp as cpp
from torchgen.api.types import ArgName as ArgName, ArrayRefCType as ArrayRefCType, BaseCType as BaseCType, Binding as Binding, ConstRefCType as ConstRefCType, NamedCType as NamedCType, OptionalCType as OptionalCType, dimnameListT as dimnameListT, iOptTensorListRefT as iOptTensorListRefT, iTensorListRefT as iTensorListRefT, intArrayRefT as intArrayRefT, optionalIntArrayRefT as optionalIntArrayRefT, optionalScalarRefT as optionalScalarRefT, optionalTensorRefT as optionalTensorRefT, scalarT as scalarT, tensorT as tensorT
from torchgen.model import Argument as Argument, BaseTy as BaseTy, BaseType as BaseType, ListType as ListType, NativeFunctionsGroup as NativeFunctionsGroup, OptionalType as OptionalType, SelfArgument as SelfArgument, TensorOptionsArguments as TensorOptionsArguments, Type as Type
from torchgen.utils import assert_never as assert_never
from typing import List

def argumenttype_type(t: Type, *, mutable: bool, binds: ArgName) -> NamedCType: ...
def argument_type(a: Argument, *, binds: ArgName) -> NamedCType: ...
def argument(a: Argument | SelfArgument | TensorOptionsArguments) -> List[Binding]: ...
def impl_arguments(g: NativeFunctionsGroup) -> List[Binding]: ...
def meta_arguments(g: NativeFunctionsGroup) -> List[Binding]: ...
def out_arguments(g: NativeFunctionsGroup) -> List[Binding]: ...
