from ... import testing as testing
from ...testing import TestBase as TestBase, config as config, eq_ as eq_, is_true as is_true
from ._autogen_fixtures import AutogenFixtureTest as AutogenFixtureTest
from _typeshed import Incomplete

class AutogenerateIdentityTest(AutogenFixtureTest, TestBase):
    __requires__: Incomplete
    __backend__: bool
    def test_add_identity_column(self) -> None: ...
    def test_remove_identity_column(self) -> None: ...
    def test_no_change_identity_column(self) -> None: ...
    def test_change_identity(self, before, after) -> None: ...
    def test_add_identity_to_column(self) -> None: ...
    def test_remove_identity_from_column(self) -> None: ...
    def test_identity_on_null(self) -> None: ...
