from ...testing import TestBase as TestBase, eq_ as eq_, mock as mock
from ._autogen_fixtures import AutogenFixtureTest as AutogenFixtureTest
from _typeshed import Incomplete

class AutogenerateCommentsTest(AutogenFixtureTest, TestBase):
    __backend__: bool
    __requires__: Incomplete
    def test_existing_table_comment_no_change(self) -> None: ...
    def test_add_table_comment(self) -> None: ...
    def test_remove_table_comment(self) -> None: ...
    def test_alter_table_comment(self) -> None: ...
    def test_existing_column_comment_no_change(self) -> None: ...
    def test_add_column_comment(self) -> None: ...
    def test_remove_column_comment(self) -> None: ...
    def test_alter_column_comment(self) -> None: ...
