from ... import testing as testing
from ...testing import TestBase as TestBase, config as config, eq_ as eq_, is_ as is_
from ._autogen_fixtures import AutogenFixtureTest as AutogenFixtureTest
from _typeshed import Incomplete

class AlterColumnTest(AutogenFixtureTest, TestBase):
    __backend__: bool
    def test_all_existings_filled(self, pk) -> None: ...
    def test_all_existings_filled_in_notnull(self, pk) -> None: ...
    def test_all_existings_filled_in_comment(self, pk) -> None: ...
    def test_all_existings_filled_in_server_default(self, pk) -> None: ...

class AutoincrementTest(AutogenFixtureTest, TestBase):
    __backend__: bool
    __requires__: Incomplete
    def test_alter_column_autoincrement_none(self) -> None: ...
    def test_alter_column_autoincrement_pk_false(self) -> None: ...
    def test_alter_column_autoincrement_pk_implicit_true(self) -> None: ...
    def test_alter_column_autoincrement_pk_explicit_true(self) -> None: ...
    def test_alter_column_autoincrement_nonpk_false(self) -> None: ...
    def test_alter_column_autoincrement_nonpk_implicit_false(self) -> None: ...
    def test_alter_column_autoincrement_nonpk_explicit_true(self) -> None: ...
    def test_alter_column_autoincrement_compositepk_false(self) -> None: ...
    def test_alter_column_autoincrement_compositepk_implicit_false(self) -> None: ...
    def test_alter_column_autoincrement_compositepk_explicit_true(self) -> None: ...
