from ...testing import TestBase as TestBase, combinations as combinations, config as config, eq_ as eq_, mock as mock
from ._autogen_fixtures import AutogenFixtureTest as AutogenFixtureTest
from _typeshed import Incomplete

class AutogenerateForeignKeysTest(AutogenFixtureTest, TestBase):
    __backend__: bool
    __requires__: Incomplete
    def test_remove_fk(self) -> None: ...
    def test_add_fk(self) -> None: ...
    def test_no_change(self) -> None: ...
    def test_no_change_composite_fk(self) -> None: ...
    def test_casing_convention_changed_so_put_drops_first(self) -> None: ...
    def test_add_composite_fk_with_name(self) -> None: ...
    def test_remove_composite_fk(self) -> None: ...
    def test_add_fk_colkeys(self) -> None: ...
    def test_no_change_colkeys(self) -> None: ...

class IncludeHooksTest(AutogenFixtureTest, TestBase):
    __backend__: bool
    __requires__: Incomplete
    def test_remove_connection_fk(self, hook_type): ...
    def test_add_metadata_fk(self): ...
    def test_change_fk(self, hook_type): ...

class AutogenerateFKOptionsTest(AutogenFixtureTest, TestBase):
    __backend__: bool
    def test_add_ondelete(self) -> None: ...
    def test_remove_ondelete(self) -> None: ...
    def test_nochange_ondelete(self) -> None:
        """test case sensitivity"""
    def test_add_onupdate(self) -> None: ...
    def test_remove_onupdate(self) -> None: ...
    def test_nochange_onupdate(self) -> None:
        """test case sensitivity"""
    def test_nochange_ondelete_restrict(self) -> None:
        """test the RESTRICT option which MySQL doesn't report on"""
    def test_nochange_onupdate_restrict(self) -> None:
        """test the RESTRICT option which MySQL doesn't report on"""
    def test_nochange_ondelete_noaction(self) -> None:
        """test the NO ACTION option which generally comes back as None"""
    def test_nochange_onupdate_noaction(self) -> None:
        """test the NO ACTION option which generally comes back as None"""
    def test_change_ondelete_from_restrict(self) -> None:
        """test the RESTRICT option which MySQL doesn't report on"""
    def test_change_onupdate_from_restrict(self) -> None:
        """test the RESTRICT option which MySQL doesn't report on"""
    def test_ondelete_onupdate_combo(self) -> None: ...
    def test_add_initially_deferred(self) -> None: ...
    def test_remove_initially_deferred(self) -> None: ...
    def test_add_initially_immediate_plus_deferrable(self) -> None: ...
    def test_remove_initially_immediate_plus_deferrable(self) -> None: ...
    def test_add_initially_deferrable_nochange_one(self) -> None: ...
    def test_add_initially_deferrable_nochange_two(self) -> None: ...
    def test_add_initially_deferrable_nochange_three(self) -> None: ...
    def test_add_deferrable(self) -> None: ...
    def test_remove_deferrable(self) -> None: ...
