class _TzSingleton(type):
    def __init__(cls, *args, **kwargs) -> None: ...
    def __call__(cls): ...

class _TzFactory(type):
    def instance(cls, *args, **kwargs):
        """Alternate constructor that returns a fresh instance"""

class _TzOffsetFactory(_TzFactory):
    def __init__(cls, *args, **kwargs) -> None: ...
    def __call__(cls, name, offset): ...

class _TzStrFactory(_TzFactory):
    def __init__(cls, *args, **kwargs) -> None: ...
    def __call__(cls, s, posix_offset: bool = False): ...
