from ._base import DirectivePlugin

__all__ = ['Image', 'Figure']

class Image(DirectivePlugin):
    NAME: str
    def parse(self, block, m, state): ...
    def __call__(self, directive, md) -> None: ...

class Figure(DirectivePlugin):
    NAME: str
    def parse_directive_content(self, block, m, state): ...
    def parse(self, block, m, state): ...
    def __call__(self, directive, md) -> None: ...
