from ..toc import normalize_toc_item as normalize_toc_item, render_toc_ul as render_toc_ul
from ._base import DirectivePlugin as DirectivePlugin
from _typeshed import Incomplete

class TableOfContents(DirectivePlugin):
    min_level: Incomplete
    max_level: Incomplete
    def __init__(self, min_level: int = 1, max_level: int = 3) -> None: ...
    def generate_heading_id(self, token, index): ...
    def parse(self, block, m, state): ...
    def toc_hook(self, md, state) -> None: ...
    def __call__(self, directive, md) -> None: ...

def render_html_toc(renderer, title, collapse: bool = False, **attrs): ...
