PLATFORM_SYNAPSE_INTERNAL: str
PLATFORM_SYNAPSE: str
PLATFORM_BINDER: str
PLATFORM_DATABRICKS: str
PLATFORM_UNKNOWN: str
SECRET_STORE: str
SYNAPSE_PROJECT_NAME: str

def current_platform(): ...
def running_on_synapse_internal(): ...
def running_on_synapse(): ...
def running_on_binder(): ...
def running_on_databricks(): ...
def find_secret(secret_name, keyvault): ...
def materializing_display(data) -> None: ...
