from jedi.inference.base_value import ValueSet as ValueSet, ValueWrapper as ValueWrapper

class Decoratee(ValueWrapper):
    def __init__(self, wrapped_value, original_value) -> None: ...
    def py__doc__(self): ...
    def py__get__(self, instance, class_value): ...
    def get_signatures(self): ...
