from _typeshed import Incomplete
from tensorboard import errors as errors
from tensorboard.compat.proto import summary_pb2 as summary_pb2
from tensorboard.data import provider as provider
from tensorboard.util import tb_logging as tb_logging, tensor_util as tensor_util

logger: Incomplete

class MultiplexerDataProvider(provider.DataProvider):
    def __init__(self, multiplexer, logdir) -> None:
        """Trivial initializer.

        Args:
          multiplexer: A `plugin_event_multiplexer.EventMultiplexer` (note:
            not a boring old `event_multiplexer.EventMultiplexer`).
          logdir: The log directory from which data is being read. Only used
            cosmetically. Should be a `str`.
        """
    def experiment_metadata(self, ctx: Incomplete | None = None, *, experiment_id): ...
    def list_plugins(self, ctx: Incomplete | None = None, *, experiment_id): ...
    def list_runs(self, ctx: Incomplete | None = None, *, experiment_id): ...
    def list_scalars(self, ctx: Incomplete | None = None, *, experiment_id, plugin_name, run_tag_filter: Incomplete | None = None): ...
    def read_scalars(self, ctx: Incomplete | None = None, *, experiment_id, plugin_name, downsample: Incomplete | None = None, run_tag_filter: Incomplete | None = None): ...
    def list_tensors(self, ctx: Incomplete | None = None, *, experiment_id, plugin_name, run_tag_filter: Incomplete | None = None): ...
    def read_tensors(self, ctx: Incomplete | None = None, *, experiment_id, plugin_name, downsample: Incomplete | None = None, run_tag_filter: Incomplete | None = None): ...
    def list_blob_sequences(self, ctx: Incomplete | None = None, *, experiment_id, plugin_name, run_tag_filter: Incomplete | None = None): ...
    def read_blob_sequences(self, ctx: Incomplete | None = None, *, experiment_id, plugin_name, downsample: Incomplete | None = None, run_tag_filter: Incomplete | None = None): ...
    def read_blob(self, ctx: Incomplete | None = None, *, blob_key): ...
