from ..quant_utils import QuantizedValue as QuantizedValue, QuantizedValueType as QuantizedValueType, TENSOR_NAME_QUANT_SUFFIX as TENSOR_NAME_QUANT_SUFFIX
from .base_operator import QuantOperatorBase as QuantOperatorBase
from .qdq_base_operator import QDQOperatorBase as QDQOperatorBase

class Direct8BitOp(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def quantize(self): ...

class QDQDirect8BitOp(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def quantize(self) -> None: ...
