from ..quant_utils import QuantizedValue as QuantizedValue, QuantizedValueType as QuantizedValueType, TENSOR_NAME_QUANT_SUFFIX as TENSOR_NAME_QUANT_SUFFIX, attribute_to_kwarg as attribute_to_kwarg, find_by_name as find_by_name, get_mul_node as get_mul_node, ms_domain as ms_domain
from .base_operator import QuantOperatorBase as QuantOperatorBase
from .matmul import QOpMatMul as QOpMatMul
from .qdq_base_operator import QDQOperatorBase as QDQOperatorBase

def is_B_transposed(gemm_node): ...
def get_beta(gemm_node): ...
def set_default_beta(gemm_node): ...

class QLinearGemm(QOpMatMul):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def quantize(self): ...

class QDQGemm(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def quantize(self) -> None: ...
