from _typeshed import Incomplete

DESCRIPTOR: Incomplete
ArtifactCredentialType: Incomplete
AZURE_SAS_URI: int
AWS_PRESIGNED_URL: int
GCP_SIGNED_URL: int
AZURE_ADLS_GEN2_SAS_URI: int
ArtifactCredentialInfo: Incomplete
GetCredentialsForRead: Incomplete
GetCredentialsForWrite: Incomplete
CreateMultipartUpload: Incomplete
PartEtag: Incomplete
CompleteMultipartUpload: Incomplete
GetPresignedUploadPartUrl: Incomplete
DatabricksMlflowArtifactsService: Incomplete
DatabricksMlflowArtifactsService_Stub: Incomplete
