from _typeshed import Incomplete
from mypy.nodes import ARG_STAR as ARG_STAR, ARG_STAR2 as ARG_STAR2
from mypy.types import AnyType as AnyType, CallableType as CallableType, DeletedType as DeletedType, ErasedType as ErasedType, Instance as Instance, LiteralType as LiteralType, NoneType as NoneType, Overloaded as Overloaded, ParamSpecType as ParamSpecType, Parameters as Parameters, PartialType as PartialType, ProperType as ProperType, TupleType as TupleType, Type as Type, TypeAliasType as TypeAliasType, TypeOfAny as TypeOfAny, TypeTranslator as TypeTranslator, TypeType as TypeType, TypeVarId as TypeVarId, TypeVarTupleType as TypeVarTupleType, TypeVarType as TypeVarType, TypeVisitor as TypeVisitor, TypedDictType as TypedDictType, UnboundType as UnboundType, UninhabitedType as UninhabitedType, UnionType as UnionType, UnpackType as UnpackType, get_proper_type as get_proper_type, get_proper_types as get_proper_types
from typing import Callable, Container

def erase_type(typ: Type) -> ProperType:
    """Erase any type variables from a type.

    Also replace tuple types with the corresponding concrete types.

    Examples:
      A -> A
      B[X] -> B[Any]
      Tuple[A, B] -> tuple
      Callable[[A1, A2, ...], R] -> Callable[..., Any]
      Type[X] -> Type[Any]
    """

class EraseTypeVisitor(TypeVisitor[ProperType]):
    def visit_unbound_type(self, t: UnboundType) -> ProperType: ...
    def visit_any(self, t: AnyType) -> ProperType: ...
    def visit_none_type(self, t: None) -> ProperType: ...
    def visit_uninhabited_type(self, t: UninhabitedType) -> ProperType: ...
    def visit_erased_type(self, t: ErasedType) -> ProperType: ...
    def visit_partial_type(self, t: PartialType) -> ProperType: ...
    def visit_deleted_type(self, t: DeletedType) -> ProperType: ...
    def visit_instance(self, t: Instance) -> ProperType: ...
    def visit_type_var(self, t: TypeVarType) -> ProperType: ...
    def visit_param_spec(self, t: ParamSpecType) -> ProperType: ...
    def visit_parameters(self, t: Parameters) -> ProperType: ...
    def visit_type_var_tuple(self, t: TypeVarTupleType) -> ProperType: ...
    def visit_unpack_type(self, t: UnpackType) -> ProperType: ...
    def visit_callable_type(self, t: CallableType) -> ProperType: ...
    def visit_overloaded(self, t: Overloaded) -> ProperType: ...
    def visit_tuple_type(self, t: TupleType) -> ProperType: ...
    def visit_typeddict_type(self, t: TypedDictType) -> ProperType: ...
    def visit_literal_type(self, t: LiteralType) -> ProperType: ...
    def visit_union_type(self, t: UnionType) -> ProperType: ...
    def visit_type_type(self, t: TypeType) -> ProperType: ...
    def visit_type_alias_type(self, t: TypeAliasType) -> ProperType: ...

def erase_typevars(t: Type, ids_to_erase: Container[TypeVarId] | None = None) -> Type:
    """Replace all type variables in a type with any,
    or just the ones in the provided collection.
    """
def replace_meta_vars(t: Type, target_type: Type) -> Type:
    """Replace unification variables in a type with the target type."""

class TypeVarEraser(TypeTranslator):
    """Implementation of type erasure"""
    erase_id: Incomplete
    replacement: Incomplete
    def __init__(self, erase_id: Callable[[TypeVarId], bool], replacement: Type) -> None: ...
    def visit_type_var(self, t: TypeVarType) -> Type: ...
    def visit_type_var_tuple(self, t: TypeVarTupleType) -> Type: ...
    def visit_param_spec(self, t: ParamSpecType) -> Type: ...
    def visit_type_alias_type(self, t: TypeAliasType) -> Type: ...

def remove_instance_last_known_values(t: Type) -> Type: ...

class LastKnownValueEraser(TypeTranslator):
    """Removes the Literal[...] type that may be associated with any
    Instance types."""
    def visit_instance(self, t: Instance) -> Type: ...
    def visit_type_alias_type(self, t: TypeAliasType) -> Type: ...
    def visit_union_type(self, t: UnionType) -> Type: ...
