import mypy.nodes
from _typeshed import Incomplete
from mypy.visitor import ExpressionVisitor as ExpressionVisitor

UNKNOWN: Incomplete

class _NodeEvaluator(ExpressionVisitor[object]):
    def visit_int_expr(self, o: mypy.nodes.IntExpr) -> int: ...
    def visit_str_expr(self, o: mypy.nodes.StrExpr) -> str: ...
    def visit_bytes_expr(self, o: mypy.nodes.BytesExpr) -> object: ...
    def visit_float_expr(self, o: mypy.nodes.FloatExpr) -> float: ...
    def visit_complex_expr(self, o: mypy.nodes.ComplexExpr) -> object: ...
    def visit_ellipsis(self, o: mypy.nodes.EllipsisExpr) -> object: ...
    def visit_star_expr(self, o: mypy.nodes.StarExpr) -> object: ...
    def visit_name_expr(self, o: mypy.nodes.NameExpr) -> object: ...
    def visit_member_expr(self, o: mypy.nodes.MemberExpr) -> object: ...
    def visit_yield_from_expr(self, o: mypy.nodes.YieldFromExpr) -> object: ...
    def visit_yield_expr(self, o: mypy.nodes.YieldExpr) -> object: ...
    def visit_call_expr(self, o: mypy.nodes.CallExpr) -> object: ...
    def visit_op_expr(self, o: mypy.nodes.OpExpr) -> object: ...
    def visit_comparison_expr(self, o: mypy.nodes.ComparisonExpr) -> object: ...
    def visit_cast_expr(self, o: mypy.nodes.CastExpr) -> object: ...
    def visit_assert_type_expr(self, o: mypy.nodes.AssertTypeExpr) -> object: ...
    def visit_reveal_expr(self, o: mypy.nodes.RevealExpr) -> object: ...
    def visit_super_expr(self, o: mypy.nodes.SuperExpr) -> object: ...
    def visit_unary_expr(self, o: mypy.nodes.UnaryExpr) -> object: ...
    def visit_assignment_expr(self, o: mypy.nodes.AssignmentExpr) -> object: ...
    def visit_list_expr(self, o: mypy.nodes.ListExpr) -> object: ...
    def visit_dict_expr(self, o: mypy.nodes.DictExpr) -> object: ...
    def visit_tuple_expr(self, o: mypy.nodes.TupleExpr) -> object: ...
    def visit_set_expr(self, o: mypy.nodes.SetExpr) -> object: ...
    def visit_index_expr(self, o: mypy.nodes.IndexExpr) -> object: ...
    def visit_type_application(self, o: mypy.nodes.TypeApplication) -> object: ...
    def visit_lambda_expr(self, o: mypy.nodes.LambdaExpr) -> object: ...
    def visit_list_comprehension(self, o: mypy.nodes.ListComprehension) -> object: ...
    def visit_set_comprehension(self, o: mypy.nodes.SetComprehension) -> object: ...
    def visit_dictionary_comprehension(self, o: mypy.nodes.DictionaryComprehension) -> object: ...
    def visit_generator_expr(self, o: mypy.nodes.GeneratorExpr) -> object: ...
    def visit_slice_expr(self, o: mypy.nodes.SliceExpr) -> object: ...
    def visit_conditional_expr(self, o: mypy.nodes.ConditionalExpr) -> object: ...
    def visit_type_var_expr(self, o: mypy.nodes.TypeVarExpr) -> object: ...
    def visit_paramspec_expr(self, o: mypy.nodes.ParamSpecExpr) -> object: ...
    def visit_type_var_tuple_expr(self, o: mypy.nodes.TypeVarTupleExpr) -> object: ...
    def visit_type_alias_expr(self, o: mypy.nodes.TypeAliasExpr) -> object: ...
    def visit_namedtuple_expr(self, o: mypy.nodes.NamedTupleExpr) -> object: ...
    def visit_enum_call_expr(self, o: mypy.nodes.EnumCallExpr) -> object: ...
    def visit_typeddict_expr(self, o: mypy.nodes.TypedDictExpr) -> object: ...
    def visit_newtype_expr(self, o: mypy.nodes.NewTypeExpr) -> object: ...
    def visit__promote_expr(self, o: mypy.nodes.PromoteExpr) -> object: ...
    def visit_await_expr(self, o: mypy.nodes.AwaitExpr) -> object: ...
    def visit_temp_node(self, o: mypy.nodes.TempNode) -> object: ...

def evaluate_expression(expr: mypy.nodes.Expression) -> object:
    """Evaluate an expression at runtime.

    Return the result of the expression, or UNKNOWN if the expression cannot be
    evaluated.
    """
