from _typeshed import Incomplete
from mypy.lookup import lookup_fully_qualified as lookup_fully_qualified
from mypy.nodes import Block as Block, ClassDef as ClassDef, Decorator as Decorator, FuncDef as FuncDef, MypyFile as MypyFile, OverloadedFuncDef as OverloadedFuncDef, ParamSpecExpr as ParamSpecExpr, SymbolTable as SymbolTable, TypeAlias as TypeAlias, TypeInfo as TypeInfo, TypeVarExpr as TypeVarExpr, TypeVarTupleExpr as TypeVarTupleExpr, Var as Var
from mypy.types import AnyType as AnyType, CallableType as CallableType, Instance as Instance, LiteralType as LiteralType, NOT_READY as NOT_READY, Overloaded as Overloaded, ParamSpecType as ParamSpecType, Parameters as Parameters, TupleType as TupleType, TypeAliasType as TypeAliasType, TypeOfAny as TypeOfAny, TypeType as TypeType, TypeVarTupleType as TypeVarTupleType, TypeVarType as TypeVarType, TypeVisitor as TypeVisitor, TypedDictType as TypedDictType, UnboundType as UnboundType, UnionType as UnionType, UnpackType as UnpackType
from mypy.visitor import NodeVisitor as NodeVisitor
from typing import Any

def fixup_module(tree: MypyFile, modules: dict[str, MypyFile], allow_missing: bool) -> None: ...

class NodeFixer(NodeVisitor[None]):
    current_info: TypeInfo | None
    modules: Incomplete
    allow_missing: Incomplete
    type_fixer: Incomplete
    def __init__(self, modules: dict[str, MypyFile], allow_missing: bool) -> None: ...
    def visit_type_info(self, info: TypeInfo) -> None: ...
    def visit_symbol_table(self, symtab: SymbolTable, table_fullname: str) -> None: ...
    def visit_func_def(self, func: FuncDef) -> None: ...
    def visit_overloaded_func_def(self, o: OverloadedFuncDef) -> None: ...
    def visit_decorator(self, d: Decorator) -> None: ...
    def visit_class_def(self, c: ClassDef) -> None: ...
    def visit_type_var_expr(self, tv: TypeVarExpr) -> None: ...
    def visit_paramspec_expr(self, p: ParamSpecExpr) -> None: ...
    def visit_type_var_tuple_expr(self, tv: TypeVarTupleExpr) -> None: ...
    def visit_var(self, v: Var) -> None: ...
    def visit_type_alias(self, a: TypeAlias) -> None: ...

class TypeFixer(TypeVisitor[None]):
    modules: Incomplete
    allow_missing: Incomplete
    def __init__(self, modules: dict[str, MypyFile], allow_missing: bool) -> None: ...
    def visit_instance(self, inst: Instance) -> None: ...
    def visit_type_alias_type(self, t: TypeAliasType) -> None: ...
    def visit_any(self, o: Any) -> None: ...
    def visit_callable_type(self, ct: CallableType) -> None: ...
    def visit_overloaded(self, t: Overloaded) -> None: ...
    def visit_erased_type(self, o: Any) -> None: ...
    def visit_deleted_type(self, o: Any) -> None: ...
    def visit_none_type(self, o: Any) -> None: ...
    def visit_uninhabited_type(self, o: Any) -> None: ...
    def visit_partial_type(self, o: Any) -> None: ...
    def visit_tuple_type(self, tt: TupleType) -> None: ...
    def visit_typeddict_type(self, tdt: TypedDictType) -> None: ...
    def visit_literal_type(self, lt: LiteralType) -> None: ...
    def visit_type_var(self, tvt: TypeVarType) -> None: ...
    def visit_param_spec(self, p: ParamSpecType) -> None: ...
    def visit_type_var_tuple(self, t: TypeVarTupleType) -> None: ...
    def visit_unpack_type(self, u: UnpackType) -> None: ...
    def visit_parameters(self, p: Parameters) -> None: ...
    def visit_unbound_type(self, o: UnboundType) -> None: ...
    def visit_union_type(self, ut: UnionType) -> None: ...
    def visit_void(self, o: Any) -> None: ...
    def visit_type_type(self, t: TypeType) -> None: ...

def lookup_fully_qualified_typeinfo(modules: dict[str, MypyFile], name: str, *, allow_missing: bool) -> TypeInfo: ...
def lookup_fully_qualified_alias(modules: dict[str, MypyFile], name: str, *, allow_missing: bool) -> TypeAlias: ...
def missing_info(modules: dict[str, MypyFile]) -> TypeInfo: ...
def missing_alias() -> TypeAlias: ...
