import mypy.types as types
from _typeshed import Incomplete
from mypy.types import TypeVisitor as TypeVisitor
from mypy.util import split_module_names as split_module_names
from typing import Iterable, Set

def extract_module_names(type_name: str | None) -> list[str]:
    """Returns the module names of a fully qualified type name."""

class TypeIndirectionVisitor(TypeVisitor[Set[str]]):
    """Returns all module references within a particular type."""
    cache: Incomplete
    seen_aliases: Incomplete
    def __init__(self) -> None: ...
    def find_modules(self, typs: Iterable[types.Type]) -> set[str]: ...
    def visit_unbound_type(self, t: types.UnboundType) -> set[str]: ...
    def visit_any(self, t: types.AnyType) -> set[str]: ...
    def visit_none_type(self, t: types.NoneType) -> set[str]: ...
    def visit_uninhabited_type(self, t: types.UninhabitedType) -> set[str]: ...
    def visit_erased_type(self, t: types.ErasedType) -> set[str]: ...
    def visit_deleted_type(self, t: types.DeletedType) -> set[str]: ...
    def visit_type_var(self, t: types.TypeVarType) -> set[str]: ...
    def visit_param_spec(self, t: types.ParamSpecType) -> set[str]: ...
    def visit_type_var_tuple(self, t: types.TypeVarTupleType) -> set[str]: ...
    def visit_unpack_type(self, t: types.UnpackType) -> set[str]: ...
    def visit_parameters(self, t: types.Parameters) -> set[str]: ...
    def visit_instance(self, t: types.Instance) -> set[str]: ...
    def visit_callable_type(self, t: types.CallableType) -> set[str]: ...
    def visit_overloaded(self, t: types.Overloaded) -> set[str]: ...
    def visit_tuple_type(self, t: types.TupleType) -> set[str]: ...
    def visit_typeddict_type(self, t: types.TypedDictType) -> set[str]: ...
    def visit_literal_type(self, t: types.LiteralType) -> set[str]: ...
    def visit_union_type(self, t: types.UnionType) -> set[str]: ...
    def visit_partial_type(self, t: types.PartialType) -> set[str]: ...
    def visit_type_type(self, t: types.TypeType) -> set[str]: ...
    def visit_type_alias_type(self, t: types.TypeAliasType) -> set[str]: ...
