from mypy.nodes import AssertTypeExpr as AssertTypeExpr, AssignmentStmt as AssignmentStmt, CastExpr as CastExpr, ClassDef as ClassDef, ForStmt as ForStmt, FuncItem as FuncItem, NamedTupleExpr as NamedTupleExpr, NewTypeExpr as NewTypeExpr, PromoteExpr as PromoteExpr, TypeAliasExpr as TypeAliasExpr, TypeApplication as TypeApplication, TypeVarExpr as TypeVarExpr, TypedDictExpr as TypedDictExpr, Var as Var, WithStmt as WithStmt
from mypy.traverser import TraverserVisitor as TraverserVisitor
from mypy.types import Type as Type
from mypy.typetraverser import TypeTraverserVisitor as TypeTraverserVisitor

class MixedTraverserVisitor(TraverserVisitor, TypeTraverserVisitor):
    """Recursive traversal of both Node and Type objects."""
    in_type_alias_expr: bool
    def __init__(self) -> None: ...
    def visit_var(self, var: Var) -> None: ...
    def visit_func(self, o: FuncItem) -> None: ...
    def visit_class_def(self, o: ClassDef) -> None: ...
    def visit_type_alias_expr(self, o: TypeAliasExpr) -> None: ...
    def visit_type_var_expr(self, o: TypeVarExpr) -> None: ...
    def visit_typeddict_expr(self, o: TypedDictExpr) -> None: ...
    def visit_namedtuple_expr(self, o: NamedTupleExpr) -> None: ...
    def visit__promote_expr(self, o: PromoteExpr) -> None: ...
    def visit_newtype_expr(self, o: NewTypeExpr) -> None: ...
    def visit_assignment_stmt(self, o: AssignmentStmt) -> None: ...
    def visit_for_stmt(self, o: ForStmt) -> None: ...
    def visit_with_stmt(self, o: WithStmt) -> None: ...
    def visit_cast_expr(self, o: CastExpr) -> None: ...
    def visit_assert_type_expr(self, o: AssertTypeExpr) -> None: ...
    def visit_type_application(self, o: TypeApplication) -> None: ...
    def visit_optional_type(self, t: Type | None) -> None: ...
