from _typeshed import Incomplete
from mypy.nodes import Argument as Argument, AssertStmt as AssertStmt, AssertTypeExpr as AssertTypeExpr, AssignmentExpr as AssignmentExpr, AssignmentStmt as AssignmentStmt, AwaitExpr as AwaitExpr, Block as Block, BreakStmt as BreakStmt, BytesExpr as BytesExpr, CallExpr as CallExpr, CastExpr as CastExpr, ClassDef as ClassDef, ComparisonExpr as ComparisonExpr, ComplexExpr as ComplexExpr, ConditionalExpr as ConditionalExpr, ContinueStmt as ContinueStmt, Decorator as Decorator, DelStmt as DelStmt, DictExpr as DictExpr, DictionaryComprehension as DictionaryComprehension, EllipsisExpr as EllipsisExpr, EnumCallExpr as EnumCallExpr, Expression as Expression, ExpressionStmt as ExpressionStmt, FloatExpr as FloatExpr, ForStmt as ForStmt, FuncDef as FuncDef, FuncItem as FuncItem, GDEF as GDEF, GeneratorExpr as GeneratorExpr, GlobalDecl as GlobalDecl, IfStmt as IfStmt, Import as Import, ImportAll as ImportAll, ImportFrom as ImportFrom, IndexExpr as IndexExpr, IntExpr as IntExpr, LambdaExpr as LambdaExpr, ListComprehension as ListComprehension, ListExpr as ListExpr, MatchStmt as MatchStmt, MemberExpr as MemberExpr, MypyFile as MypyFile, NameExpr as NameExpr, NamedTupleExpr as NamedTupleExpr, NewTypeExpr as NewTypeExpr, Node as Node, NonlocalDecl as NonlocalDecl, OpExpr as OpExpr, OperatorAssignmentStmt as OperatorAssignmentStmt, OverloadPart as OverloadPart, OverloadedFuncDef as OverloadedFuncDef, ParamSpecExpr as ParamSpecExpr, PassStmt as PassStmt, PromoteExpr as PromoteExpr, REVEAL_TYPE as REVEAL_TYPE, RaiseStmt as RaiseStmt, RefExpr as RefExpr, ReturnStmt as ReturnStmt, RevealExpr as RevealExpr, SetComprehension as SetComprehension, SetExpr as SetExpr, SliceExpr as SliceExpr, StarExpr as StarExpr, Statement as Statement, StrExpr as StrExpr, SuperExpr as SuperExpr, SymbolTable as SymbolTable, TempNode as TempNode, TryStmt as TryStmt, TupleExpr as TupleExpr, TypeAliasExpr as TypeAliasExpr, TypeApplication as TypeApplication, TypeVarExpr as TypeVarExpr, TypeVarTupleExpr as TypeVarTupleExpr, TypedDictExpr as TypedDictExpr, UnaryExpr as UnaryExpr, Var as Var, WhileStmt as WhileStmt, WithStmt as WithStmt, YieldExpr as YieldExpr, YieldFromExpr as YieldFromExpr
from mypy.patterns import AsPattern as AsPattern, ClassPattern as ClassPattern, MappingPattern as MappingPattern, OrPattern as OrPattern, Pattern as Pattern, SequencePattern as SequencePattern, SingletonPattern as SingletonPattern, StarredPattern as StarredPattern, ValuePattern as ValuePattern
from mypy.traverser import TraverserVisitor as TraverserVisitor
from mypy.types import FunctionLike as FunctionLike, ProperType as ProperType, Type as Type
from mypy.util import replace_object_state as replace_object_state
from mypy.visitor import NodeVisitor as NodeVisitor
from typing import Iterable

class TransformVisitor(NodeVisitor[Node]):
    """Transform a semantically analyzed AST (or subtree) to an identical copy.

    Use the node() method to transform an AST node.

    Subclass to perform a non-identity transform.

    Notes:

     * This can only be used to transform functions or classes, not top-level
       statements, and/or modules as a whole.
     * Do not duplicate TypeInfo nodes. This would generally not be desirable.
     * Only update some name binding cross-references, but only those that
       refer to Var, Decorator or FuncDef nodes, not those targeting ClassDef or
       TypeInfo nodes.
     * Types are not transformed, but you can override type() to also perform
       type transformation.

    TODO nested classes and functions have not been tested well enough
    """
    test_only: bool
    var_map: Incomplete
    func_placeholder_map: Incomplete
    def __init__(self) -> None: ...
    def visit_mypy_file(self, node: MypyFile) -> MypyFile: ...
    def visit_import(self, node: Import) -> Import: ...
    def visit_import_from(self, node: ImportFrom) -> ImportFrom: ...
    def visit_import_all(self, node: ImportAll) -> ImportAll: ...
    def copy_argument(self, argument: Argument) -> Argument: ...
    def visit_func_def(self, node: FuncDef) -> FuncDef: ...
    def visit_lambda_expr(self, node: LambdaExpr) -> LambdaExpr: ...
    def copy_function_attributes(self, new: FuncItem, original: FuncItem) -> None: ...
    def visit_overloaded_func_def(self, node: OverloadedFuncDef) -> OverloadedFuncDef: ...
    def visit_class_def(self, node: ClassDef) -> ClassDef: ...
    def visit_global_decl(self, node: GlobalDecl) -> GlobalDecl: ...
    def visit_nonlocal_decl(self, node: NonlocalDecl) -> NonlocalDecl: ...
    def visit_block(self, node: Block) -> Block: ...
    def visit_decorator(self, node: Decorator) -> Decorator: ...
    def visit_var(self, node: Var) -> Var: ...
    def visit_expression_stmt(self, node: ExpressionStmt) -> ExpressionStmt: ...
    def visit_assignment_stmt(self, node: AssignmentStmt) -> AssignmentStmt: ...
    def duplicate_assignment(self, node: AssignmentStmt) -> AssignmentStmt: ...
    def visit_operator_assignment_stmt(self, node: OperatorAssignmentStmt) -> OperatorAssignmentStmt: ...
    def visit_while_stmt(self, node: WhileStmt) -> WhileStmt: ...
    def visit_for_stmt(self, node: ForStmt) -> ForStmt: ...
    def visit_return_stmt(self, node: ReturnStmt) -> ReturnStmt: ...
    def visit_assert_stmt(self, node: AssertStmt) -> AssertStmt: ...
    def visit_del_stmt(self, node: DelStmt) -> DelStmt: ...
    def visit_if_stmt(self, node: IfStmt) -> IfStmt: ...
    def visit_break_stmt(self, node: BreakStmt) -> BreakStmt: ...
    def visit_continue_stmt(self, node: ContinueStmt) -> ContinueStmt: ...
    def visit_pass_stmt(self, node: PassStmt) -> PassStmt: ...
    def visit_raise_stmt(self, node: RaiseStmt) -> RaiseStmt: ...
    def visit_try_stmt(self, node: TryStmt) -> TryStmt: ...
    def visit_with_stmt(self, node: WithStmt) -> WithStmt: ...
    def visit_as_pattern(self, p: AsPattern) -> AsPattern: ...
    def visit_or_pattern(self, p: OrPattern) -> OrPattern: ...
    def visit_value_pattern(self, p: ValuePattern) -> ValuePattern: ...
    def visit_singleton_pattern(self, p: SingletonPattern) -> SingletonPattern: ...
    def visit_sequence_pattern(self, p: SequencePattern) -> SequencePattern: ...
    def visit_starred_pattern(self, p: StarredPattern) -> StarredPattern: ...
    def visit_mapping_pattern(self, p: MappingPattern) -> MappingPattern: ...
    def visit_class_pattern(self, p: ClassPattern) -> ClassPattern: ...
    def visit_match_stmt(self, o: MatchStmt) -> MatchStmt: ...
    def visit_star_expr(self, node: StarExpr) -> StarExpr: ...
    def visit_int_expr(self, node: IntExpr) -> IntExpr: ...
    def visit_str_expr(self, node: StrExpr) -> StrExpr: ...
    def visit_bytes_expr(self, node: BytesExpr) -> BytesExpr: ...
    def visit_float_expr(self, node: FloatExpr) -> FloatExpr: ...
    def visit_complex_expr(self, node: ComplexExpr) -> ComplexExpr: ...
    def visit_ellipsis(self, node: EllipsisExpr) -> EllipsisExpr: ...
    def visit_name_expr(self, node: NameExpr) -> NameExpr: ...
    def duplicate_name(self, node: NameExpr) -> NameExpr: ...
    def visit_member_expr(self, node: MemberExpr) -> MemberExpr: ...
    def copy_ref(self, new: RefExpr, original: RefExpr) -> None: ...
    def visit_yield_from_expr(self, node: YieldFromExpr) -> YieldFromExpr: ...
    def visit_yield_expr(self, node: YieldExpr) -> YieldExpr: ...
    def visit_await_expr(self, node: AwaitExpr) -> AwaitExpr: ...
    def visit_call_expr(self, node: CallExpr) -> CallExpr: ...
    def visit_op_expr(self, node: OpExpr) -> OpExpr: ...
    def visit_comparison_expr(self, node: ComparisonExpr) -> ComparisonExpr: ...
    def visit_cast_expr(self, node: CastExpr) -> CastExpr: ...
    def visit_assert_type_expr(self, node: AssertTypeExpr) -> AssertTypeExpr: ...
    def visit_reveal_expr(self, node: RevealExpr) -> RevealExpr: ...
    def visit_super_expr(self, node: SuperExpr) -> SuperExpr: ...
    def visit_assignment_expr(self, node: AssignmentExpr) -> AssignmentExpr: ...
    def visit_unary_expr(self, node: UnaryExpr) -> UnaryExpr: ...
    def visit_list_expr(self, node: ListExpr) -> ListExpr: ...
    def visit_dict_expr(self, node: DictExpr) -> DictExpr: ...
    def visit_tuple_expr(self, node: TupleExpr) -> TupleExpr: ...
    def visit_set_expr(self, node: SetExpr) -> SetExpr: ...
    def visit_index_expr(self, node: IndexExpr) -> IndexExpr: ...
    def visit_type_application(self, node: TypeApplication) -> TypeApplication: ...
    def visit_list_comprehension(self, node: ListComprehension) -> ListComprehension: ...
    def visit_set_comprehension(self, node: SetComprehension) -> SetComprehension: ...
    def visit_dictionary_comprehension(self, node: DictionaryComprehension) -> DictionaryComprehension: ...
    def visit_generator_expr(self, node: GeneratorExpr) -> GeneratorExpr: ...
    def duplicate_generator(self, node: GeneratorExpr) -> GeneratorExpr: ...
    def visit_slice_expr(self, node: SliceExpr) -> SliceExpr: ...
    def visit_conditional_expr(self, node: ConditionalExpr) -> ConditionalExpr: ...
    def visit_type_var_expr(self, node: TypeVarExpr) -> TypeVarExpr: ...
    def visit_paramspec_expr(self, node: ParamSpecExpr) -> ParamSpecExpr: ...
    def visit_type_var_tuple_expr(self, node: TypeVarTupleExpr) -> TypeVarTupleExpr: ...
    def visit_type_alias_expr(self, node: TypeAliasExpr) -> TypeAliasExpr: ...
    def visit_newtype_expr(self, node: NewTypeExpr) -> NewTypeExpr: ...
    def visit_namedtuple_expr(self, node: NamedTupleExpr) -> NamedTupleExpr: ...
    def visit_enum_call_expr(self, node: EnumCallExpr) -> EnumCallExpr: ...
    def visit_typeddict_expr(self, node: TypedDictExpr) -> Node: ...
    def visit__promote_expr(self, node: PromoteExpr) -> PromoteExpr: ...
    def visit_temp_node(self, node: TempNode) -> TempNode: ...
    def node(self, node: Node) -> Node: ...
    def mypyfile(self, node: MypyFile) -> MypyFile: ...
    def expr(self, expr: Expression) -> Expression: ...
    def stmt(self, stmt: Statement) -> Statement: ...
    def pattern(self, pattern: Pattern) -> Pattern: ...
    def optional_expr(self, expr: Expression | None) -> Expression | None: ...
    def block(self, block: Block) -> Block: ...
    def optional_block(self, block: Block | None) -> Block | None: ...
    def statements(self, statements: list[Statement]) -> list[Statement]: ...
    def expressions(self, expressions: list[Expression]) -> list[Expression]: ...
    def optional_expressions(self, expressions: Iterable[Expression | None]) -> list[Expression | None]: ...
    def blocks(self, blocks: list[Block]) -> list[Block]: ...
    def names(self, names: list[NameExpr]) -> list[NameExpr]: ...
    def optional_names(self, names: Iterable[NameExpr | None]) -> list[NameExpr | None]: ...
    def type(self, type: Type) -> Type: ...
    def optional_type(self, type: Type | None) -> Type | None: ...
    def types(self, types: list[Type]) -> list[Type]: ...

class FuncMapInitializer(TraverserVisitor):
    """This traverser creates mappings from nested FuncDefs to placeholder FuncDefs.

    The placeholders will later be replaced with transformed nodes.
    """
    transformer: Incomplete
    def __init__(self, transformer: TransformVisitor) -> None: ...
    def visit_func_def(self, node: FuncDef) -> None: ...
