from mypy.types import AnyType as AnyType, CallableArgument as CallableArgument, CallableType as CallableType, DeletedType as DeletedType, EllipsisType as EllipsisType, ErasedType as ErasedType, Instance as Instance, LiteralType as LiteralType, NoneType as NoneType, Overloaded as Overloaded, ParamSpecType as ParamSpecType, Parameters as Parameters, PartialType as PartialType, PlaceholderType as PlaceholderType, RawExpressionType as RawExpressionType, SyntheticTypeVisitor as SyntheticTypeVisitor, TupleType as TupleType, Type as Type, TypeAliasType as TypeAliasType, TypeList as TypeList, TypeType as TypeType, TypeVarTupleType as TypeVarTupleType, TypeVarType as TypeVarType, TypedDictType as TypedDictType, UnboundType as UnboundType, UninhabitedType as UninhabitedType, UnionType as UnionType, UnpackType as UnpackType
from typing import Iterable

class TypeTraverserVisitor(SyntheticTypeVisitor[None]):
    """Visitor that traverses all components of a type"""
    def visit_any(self, t: AnyType) -> None: ...
    def visit_uninhabited_type(self, t: UninhabitedType) -> None: ...
    def visit_none_type(self, t: None) -> None: ...
    def visit_erased_type(self, t: ErasedType) -> None: ...
    def visit_deleted_type(self, t: DeletedType) -> None: ...
    def visit_type_var(self, t: TypeVarType) -> None: ...
    def visit_param_spec(self, t: ParamSpecType) -> None: ...
    def visit_parameters(self, t: Parameters) -> None: ...
    def visit_type_var_tuple(self, t: TypeVarTupleType) -> None: ...
    def visit_literal_type(self, t: LiteralType) -> None: ...
    def visit_instance(self, t: Instance) -> None: ...
    def visit_callable_type(self, t: CallableType) -> None: ...
    def visit_tuple_type(self, t: TupleType) -> None: ...
    def visit_typeddict_type(self, t: TypedDictType) -> None: ...
    def visit_union_type(self, t: UnionType) -> None: ...
    def visit_overloaded(self, t: Overloaded) -> None: ...
    def visit_type_type(self, t: TypeType) -> None: ...
    def visit_callable_argument(self, t: CallableArgument) -> None: ...
    def visit_unbound_type(self, t: UnboundType) -> None: ...
    def visit_type_list(self, t: TypeList) -> None: ...
    def visit_ellipsis_type(self, t: EllipsisType) -> None: ...
    def visit_placeholder_type(self, t: PlaceholderType) -> None: ...
    def visit_partial_type(self, t: PartialType) -> None: ...
    def visit_raw_expression_type(self, t: RawExpressionType) -> None: ...
    def visit_type_alias_type(self, t: TypeAliasType) -> None: ...
    def visit_unpack_type(self, t: UnpackType) -> None: ...
    def traverse_types(self, types: Iterable[Type]) -> None: ...
