from _typeshed import Incomplete
from sympy.plotting.pygletplot.util import get_basis_vectors as get_basis_vectors, get_direction_vectors as get_direction_vectors

class PlotController:
    normal_mouse_sensitivity: float
    modified_mouse_sensitivity: float
    normal_key_sensitivity: float
    modified_key_sensitivity: float
    keymap: Incomplete
    invert_mouse_zoom: Incomplete
    window: Incomplete
    camera: Incomplete
    action: Incomplete
    def __init__(self, window, *, invert_mouse_zoom: bool = False, **kwargs) -> None: ...
    def update(self, dt): ...
    def get_mouse_sensitivity(self): ...
    def get_key_sensitivity(self): ...
    def on_key_press(self, symbol, modifiers) -> None: ...
    def on_key_release(self, symbol, modifiers) -> None: ...
    def on_mouse_drag(self, x, y, dx, dy, buttons, modifiers) -> None: ...
    def on_mouse_scroll(self, x, y, dx, dy) -> None: ...
    def is_2D(self): ...
