from _typeshed import Incomplete

def logInfoPy(msg: str): ...
def logWarningPy(msg: str): ...
def logErrorPy(msg: str): ...
def logInfoSys(msg: str): ...
def logWarningSys(msg: str): ...
def logErrorSys(msg: str): ...

info: Incomplete

warning: Incomplete

error: Incomplete

def init() -> None: ...
