from _typeshed import Incomplete

__all__ = ['TemplateError', 'Template', 'sub', 'bunch']

class TemplateError(Exception):
    """Exception raised while parsing a template
    """
    position: Incomplete
    name: Incomplete
    def __init__(self, message, position, name: Incomplete | None = None) -> None: ...

class _TemplateContinue(Exception): ...
class _TemplateBreak(Exception): ...

class Template:
    default_namespace: Incomplete
    default_encoding: str
    default_inherit: Incomplete
    content: Incomplete
    delimiters: Incomplete
    name: Incomplete
    namespace: Incomplete
    get_template: Incomplete
    def __init__(self, content, name: Incomplete | None = None, namespace: Incomplete | None = None, stacklevel: Incomplete | None = None, get_template: Incomplete | None = None, default_inherit: Incomplete | None = None, line_offset: int = 0, delimiters: Incomplete | None = None, delimeters: Incomplete | None = None) -> None: ...
    def from_filename(cls, filename, namespace: Incomplete | None = None, encoding: Incomplete | None = None, default_inherit: Incomplete | None = None, get_template=...): ...
    from_filename: Incomplete
    def substitute(self, *args, **kw): ...

def sub(content, delimiters: Incomplete | None = None, **kw): ...

class bunch(dict):
    def __init__(self, **kw) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def __getattr__(self, name): ...
    def __getitem__(self, key): ...

class TemplateDef:
    def __init__(self, template, func_name, func_signature, body, ns, pos, bound_self: Incomplete | None = None) -> None: ...
    def __call__(self, *args, **kw): ...
    def __get__(self, obj, type: Incomplete | None = None): ...

class TemplateObject:
    get: Incomplete
    def __init__(self, name) -> None: ...

class TemplateObjectGetter:
    def __init__(self, template_obj) -> None: ...
    def __getattr__(self, attr): ...

class _Empty:
    def __call__(self, *args, **kw): ...
    def __unicode__(self): ...
    def __iter__(self): ...
    def __bool__(self) -> bool: ...
    __nonzero__ = __bool__
