from _typeshed import Incomplete
from collections.abc import Generator

LOGGER: Incomplete

def enum_keys(key) -> Generator[Incomplete, None, None]: ...
def get_value(key, value_name): ...
def discover_pythons() -> Generator[Incomplete, Incomplete, None]: ...
def process_set(hive, hive_name, key, flags, default_arch) -> Generator[Incomplete, Incomplete, None]: ...
def process_company(hive_name, company, root_key, default_arch) -> Generator[Incomplete, None, None]: ...
def process_tag(hive_name, company, company_key, tag, default_arch): ...
def load_exe(hive_name, company, company_key, tag): ...
def load_arch_data(hive_name, company, tag, tag_key, default_arch): ...
def parse_arch(arch_str): ...
def load_version_data(hive_name, company, tag, tag_key): ...
def parse_version(version_str): ...
def msg(path, what) -> None: ...
