from .objcreator import QObjectCreator as QObjectCreator
from .properties import Properties as Properties
from _typeshed import Incomplete

logger: Incomplete
DEBUG: Incomplete
QtCore: Incomplete
QtWidgets: Incomplete

class WidgetStack(list):
    topwidget: Incomplete
    def push(self, item) -> None: ...
    def popLayout(self): ...
    def popWidget(self): ...
    def peek(self): ...
    def topIsLayout(self): ...
    def topIsLayoutWidget(self): ...

class ButtonGroup:
    """ Encapsulate the configuration of a button group and its implementation.
    """
    exclusive: bool
    object: Incomplete
    def __init__(self) -> None:
        """ Initialise the button group. """

class UIParser:
    factory: Incomplete
    wprops: Incomplete
    def __init__(self, qtcore_module, qtgui_module, qtwidgets_module, creatorPolicy) -> None: ...
    def uniqueName(self, name):
        '''UIParser.uniqueName(string) -> string

        Create a unique name from a string.
        >>> p = UIParser(QtCore, QtGui, QtWidgets)
        >>> p.uniqueName("foo")
        \'foo\'
        >>> p.uniqueName("foo")
        \'foo1\'
        '''
    toplevelWidget: Incomplete
    stack: Incomplete
    name_suffixes: Incomplete
    defaults: Incomplete
    actions: Incomplete
    currentActionGroup: Incomplete
    resources: Incomplete
    button_groups: Incomplete
    def reset(self) -> None: ...
    def setupObject(self, clsname, parent, branch, is_attribute: bool = True): ...
    def getProperty(self, elem, name): ...
    column_counter: int
    row_counter: int
    item_nr: int
    itemstack: Incomplete
    sorting_enabled: Incomplete
    def createWidget(self, elem) -> None: ...
    def handleHeaderView(self, elem, name, header) -> None: ...
    def createSpacer(self, elem) -> None: ...
    def createLayout(self, elem) -> None: ...
    def configureLayout(self, elem, layout) -> None: ...
    def setArray(self, elem, name, setter) -> None: ...
    def disableSorting(self, w) -> None: ...
    def handleItem(self, elem) -> None: ...
    def addAction(self, elem) -> None: ...
    @staticmethod
    def any_i18n(*args):
        """ Return True if any argument appears to be an i18n string. """
    def createWidgetItem(self, item_type, elem, getter, *getter_args):
        """ Create a specific type of widget item. """
    def addHeader(self, elem) -> None: ...
    def setZOrder(self, elem) -> None: ...
    def createAction(self, elem) -> None: ...
    def createActionGroup(self, elem) -> None: ...
    widgetTreeItemHandlers: Incomplete
    def traverseWidgetTree(self, elem) -> None: ...
    def createUserInterface(self, elem) -> None: ...
    def addActions(self) -> None: ...
    def setDelayedProps(self) -> None: ...
    def setBuddies(self) -> None: ...
    uiname: Incomplete
    def classname(self, elem) -> None: ...
    def setContext(self, context) -> None:
        """
        Reimplemented by a sub-class if it needs to know the translation
        context.
        """
    def readDefaults(self, elem) -> None: ...
    def setTaborder(self, elem) -> None: ...
    def readResources(self, elem) -> None:
        '''
        Read a "resources" tag and add the module to import to the parser\'s
        list of them.
        '''
    def createConnections(self, elem): ...
    def customWidgets(self, elem): ...
    def createToplevelWidget(self, classname, widgetname) -> None: ...
    def buttonGroups(self, elem) -> None: ...
    def finalize(self) -> None: ...
    def parse(self, filename, resource_suffix): ...
