from .. import command as command, script as script, util as util
from ..script import Script as Script, ScriptDirectory as ScriptDirectory

def staging_env(create: bool = True, template: str = 'generic', sourceless: bool = False): ...
def clear_staging_env() -> None: ...
def script_file_fixture(txt) -> None: ...
def env_file_fixture(txt) -> None: ...
def write_script(scriptdir, rev_id, content, encoding: str = 'ascii', sourceless: bool = False) -> None: ...
def make_sourceless(path, style) -> None: ...
def three_rev_fixture(cfg): ...
def multi_heads_fixture(cfg, a, b, c):
    """Create a multiple head fixture from the three-revs fixture"""
