import abc
from _typeshed import Incomplete
from collections import Mapping

class Trie(Mapping, metaclass=abc.ABCMeta):
    """Abstract base class for tries"""
    def keys(self, prefix: Incomplete | None = None): ...
    def has_keys_with_prefix(self, prefix): ...
    def longest_prefix(self, prefix): ...
    def longest_prefix_item(self, prefix): ...
