from _typeshed import Incomplete
from torch import Tensor as Tensor, nn
from typing import Dict

class LayerNorm(nn.Module):
    dimension: Incomplete
    norm: Incomplete
    def __init__(self, dimension: int) -> None: ...
    def forward(self, features: Dict[str, Tensor]): ...
    def get_sentence_embedding_dimension(self): ...
    def save(self, output_path) -> None: ...
    @staticmethod
    def load(input_path): ...
