from _typeshed import Incomplete
from interpret.api.base import ExplainerMixin as ExplainerMixin, ExplanationMixin as ExplanationMixin

class ExampleExplanation(ExplanationMixin):
    explanation_type: str
    def __init__(self) -> None: ...
    def data(self, key: Incomplete | None = None) -> None: ...
    def visualize(self, key: Incomplete | None = None) -> None: ...

class ExampleDataExplainer(ExplainerMixin):
    available_explanations: Incomplete
    explainer_type: str
    def __init__(self, feature_names: Incomplete | None = None, feature_types: Incomplete | None = None) -> None: ...
    def explain_data(self, X, y, name: Incomplete | None = None): ...

class ExamplePerfExplainer(ExplainerMixin):
    available_explanations: Incomplete
    explainer_type: str
    def __init__(self, model, feature_names: Incomplete | None = None, feature_types: Incomplete | None = None) -> None: ...
    def explain_perf(self, X, y, name: Incomplete | None = None): ...

class ExampleGlassboxExplainer(ExplainerMixin):
    available_explanations: Incomplete
    explainer_type: str
    def __init__(self, feature_names: Incomplete | None = None, feature_types: Incomplete | None = None) -> None: ...
    def fit(self, X, y): ...
    def predict(self, X) -> None: ...
    def explain_local(self, X, y: Incomplete | None = None, name: Incomplete | None = None): ...

class ExampleGreyboxExplainer(ExplainerMixin):
    available_explanations: Incomplete
    explainer_type: str
    def __init__(self, model, data, feature_names: Incomplete | None = None, feature_types: Incomplete | None = None) -> None: ...
    def explain_local(self, X, y: Incomplete | None = None, name: Incomplete | None = None): ...

class ExampleBlackboxExplainer(ExplainerMixin):
    available_explanations: Incomplete
    explainer_type: str
    def __init__(self, model, data, feature_names: Incomplete | None = None, feature_types: Incomplete | None = None) -> None: ...
    def explain_local(self, X, y: Incomplete | None = None, name: Incomplete | None = None): ...

class ExampleVisualizeProvider:
    def render(self, explanation, key: int = -1, **kwargs) -> None: ...
