from _typeshed import Incomplete

__all__ = ['DEFINE', 'DEFINE_flag', 'DEFINE_string', 'DEFINE_boolean', 'DEFINE_bool', 'DEFINE_float', 'DEFINE_integer', 'DEFINE_enum', 'DEFINE_enum_class', 'DEFINE_list', 'DEFINE_spaceseplist', 'DEFINE_multi', 'DEFINE_multi_string', 'DEFINE_multi_integer', 'DEFINE_multi_float', 'DEFINE_multi_enum', 'DEFINE_multi_enum_class', 'DEFINE_alias', 'register_validator', 'validator', 'register_multi_flags_validator', 'multi_flags_validator', 'mark_flag_as_required', 'mark_flags_as_required', 'mark_flags_as_mutual_exclusive', 'mark_bool_flags_as_mutual_exclusive', 'set_default', 'declare_key_flag', 'adopt_module_key_flags', 'disclaim_key_flags', 'Error', 'CantOpenFlagFileError', 'DuplicateFlagError', 'IllegalFlagValueError', 'UnrecognizedFlagError', 'UnparsedFlagAccessError', 'ValidationError', 'FlagNameConflictsWithMethodError', 'Flag', 'BooleanFlag', 'EnumFlag', 'EnumClassFlag', 'MultiFlag', 'MultiEnumClassFlag', 'FlagHolder', 'FlagValues', 'ArgumentParser', 'BooleanParser', 'EnumParser', 'EnumClassParser', 'ArgumentSerializer', 'FloatParser', 'IntegerParser', 'BaseListParser', 'ListParser', 'ListSerializer', 'EnumClassListSerializer', 'CsvListSerializer', 'WhitespaceSeparatedListParser', 'EnumClassSerializer', 'get_help_width', 'text_wrap', 'flag_dict_to_args', 'doc_to_help', 'FLAGS']

DEFINE: Incomplete
DEFINE_flag: Incomplete
DEFINE_string: Incomplete
DEFINE_boolean: Incomplete
DEFINE_bool = DEFINE_boolean
DEFINE_float: Incomplete
DEFINE_integer: Incomplete
DEFINE_enum: Incomplete
DEFINE_enum_class: Incomplete
DEFINE_list: Incomplete
DEFINE_spaceseplist: Incomplete
DEFINE_multi: Incomplete
DEFINE_multi_string: Incomplete
DEFINE_multi_integer: Incomplete
DEFINE_multi_float: Incomplete
DEFINE_multi_enum: Incomplete
DEFINE_multi_enum_class: Incomplete
DEFINE_alias: Incomplete
register_validator: Incomplete
validator: Incomplete
register_multi_flags_validator: Incomplete
multi_flags_validator: Incomplete
mark_flag_as_required: Incomplete
mark_flags_as_required: Incomplete
mark_flags_as_mutual_exclusive: Incomplete
mark_bool_flags_as_mutual_exclusive: Incomplete
set_default: Incomplete
declare_key_flag: Incomplete
adopt_module_key_flags: Incomplete
disclaim_key_flags: Incomplete
Error: Incomplete
CantOpenFlagFileError: Incomplete
DuplicateFlagError: Incomplete
IllegalFlagValueError: Incomplete
UnrecognizedFlagError: Incomplete
UnparsedFlagAccessError: Incomplete
ValidationError: Incomplete
FlagNameConflictsWithMethodError: Incomplete
Flag: Incomplete
BooleanFlag: Incomplete
EnumFlag: Incomplete
EnumClassFlag: Incomplete
MultiFlag: Incomplete
MultiEnumClassFlag: Incomplete
FlagHolder: Incomplete
FlagValues: Incomplete
ArgumentParser: Incomplete
BooleanParser: Incomplete
EnumParser: Incomplete
EnumClassParser: Incomplete
ArgumentSerializer: Incomplete
FloatParser: Incomplete
IntegerParser: Incomplete
BaseListParser: Incomplete
ListParser: Incomplete
ListSerializer: Incomplete
EnumClassListSerializer: Incomplete
CsvListSerializer: Incomplete
WhitespaceSeparatedListParser: Incomplete
EnumClassSerializer: Incomplete
get_help_width: Incomplete
text_wrap: Incomplete
flag_dict_to_args: Incomplete
doc_to_help: Incomplete
FLAGS: Incomplete
