from _typeshed import Incomplete
from typing import Dict, NamedTuple

class Timestamp:
    """A nanosecond-resolution timestamp."""
    sec: Incomplete
    nsec: Incomplete
    def __init__(self, sec: float, nsec: float) -> None: ...
    def __float__(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __gt__(self, other: Timestamp) -> bool: ...

class Exemplar(NamedTuple):
    labels: Dict[str, str]
    value: float
    timestamp: float | Timestamp | None = ...

class Sample(NamedTuple):
    name: str
    labels: Dict[str, str]
    value: float
    timestamp: float | Timestamp | None = ...
    exemplar: Exemplar | None = ...
