import torch
from torch.distributed._tensor.api import DTensor as DTensor
from typing import Iterable, List, Sequence

def unwrap_single_placement(e): ...
def register_impl(func): ...
def register_prop_rule(op): ...
def as_list(x: List[object] | object) -> List[object] | torch.fx.immutable_collections.immutable_list: ...
def normalize_dim(dim: int, ndim: int) -> int: ...
def normalize_dims(dims: int | Sequence[int], ndim: int) -> Sequence[int]:
    """
    normalize a dim or a sequence of dims, so that they
    are all positive.
    """
def prod(xs: Iterable[int]) -> int: ...
