from _typeshed import Incomplete

__all__ = ['PyEnvCfg']

class PyEnvCfg:
    content: Incomplete
    path: Incomplete
    def __init__(self, content, path) -> None: ...
    @classmethod
    def from_folder(cls, folder): ...
    @classmethod
    def from_file(cls, path): ...
    def write(self) -> None: ...
    def refresh(self): ...
    def __setitem__(self, key, value) -> None: ...
    def __getitem__(self, key): ...
    def __contains__(self, item) -> bool: ...
    def update(self, other): ...
