from jax import lax as lax
from jax._src import core as jax_core
from typing import Tuple

def when(condition): ...
def cdiv(a: int, b: int) -> int: ...
def strides_from_shape(shape: Tuple[int, ...]) -> Tuple[int, ...]: ...
def next_power_of_2(x: int) -> int: ...
def pattern_match_scan_to_fori_loop(jaxpr: jax_core.Jaxpr, num_consts: int, num_carry: int) -> tuple[jax_core.Jaxpr, bool]: ...
