from .types import Runtime
from pathlib import Path
from typing import Generator, Tuple

__all__ = ['DotnetCoreRuntime']

class DotnetCoreRuntime(Runtime):
    def __init__(self, runtime_config: Path, dotnet_root: Path, **params: str) -> None: ...
    @property
    def dotnet_root(self) -> Path: ...
    @property
    def is_initialized(self) -> bool: ...
    @property
    def is_shutdown(self) -> bool: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __iter__(self) -> Generator[Tuple[str, str], None, None]: ...
    def shutdown(self) -> None: ...
    def info(self): ...
