from .ffi import ffi as ffi, load_netfx as load_netfx
from .types import Runtime as Runtime, RuntimeInfo as RuntimeInfo, StrOrPath as StrOrPath
from pathlib import Path

class NetFx(Runtime):
    def __init__(self, domain: str | None = None, config_file: Path | None = None) -> None: ...
    def info(self) -> RuntimeInfo: ...
    def shutdown(self) -> None: ...

def initialize() -> None: ...
