from .. import filesystem as filesystem
from ..asyn import AsyncFileSystem as AsyncFileSystem
from _typeshed import Incomplete
from collections.abc import Generator

class DirFileSystem(AsyncFileSystem):
    """Directory prefix filesystem

    The DirFileSystem is a filesystem-wrapper. It assumes every path it is dealing with
    is relative to the `path`. After performing the necessary paths operation it
    delegates everything to the wrapped filesystem.
    """
    protocol: str
    path: Incomplete
    fs: Incomplete
    def __init__(self, path: Incomplete | None = None, fs: Incomplete | None = None, fo: Incomplete | None = None, target_protocol: Incomplete | None = None, target_options: Incomplete | None = None, **storage_options) -> None:
        """
        Parameters
        ----------
        path: str
            Path to the directory.
        fs: AbstractFileSystem
            An instantiated filesystem to wrap.
        target_protocol, target_options:
            if fs is none, construct it from these
        fo: str
            Alternate for path; do not provide both
        """
    @property
    def sep(self): ...
    async def set_session(self, *args, **kwargs): ...
    def rm_file(self, path, **kwargs): ...
    def rm(self, path, *args, **kwargs): ...
    def cp_file(self, path1, path2, **kwargs): ...
    def copy(self, path1, path2, *args, **kwargs): ...
    def pipe(self, path, *args, **kwargs): ...
    def cat_file(self, path, *args, **kwargs): ...
    def cat(self, path, *args, **kwargs): ...
    def put_file(self, lpath, rpath, **kwargs): ...
    def put(self, lpath, rpath, *args, **kwargs): ...
    def get_file(self, rpath, lpath, **kwargs): ...
    def get(self, rpath, *args, **kwargs): ...
    def isfile(self, path): ...
    def isdir(self, path): ...
    def size(self, path): ...
    def exists(self, path): ...
    def info(self, path, **kwargs): ...
    def ls(self, path, detail: bool = True, **kwargs): ...
    def walk(self, path, *args, **kwargs) -> Generator[Incomplete, None, None]: ...
    def glob(self, path, **kwargs): ...
    def du(self, path, *args, **kwargs): ...
    def find(self, path, *args, **kwargs): ...
    def expand_path(self, path, *args, **kwargs): ...
    def mkdir(self, path, *args, **kwargs): ...
    def makedirs(self, path, *args, **kwargs): ...
    def rmdir(self, path): ...
    def mv_file(self, path1, path2, **kwargs): ...
    def touch(self, path, **kwargs): ...
    def created(self, path): ...
    def modified(self, path): ...
    def sign(self, path, *args, **kwargs): ...
    def open(self, path, *args, **kwargs): ...
