from ._angularaxis import AngularaxisValidator as AngularaxisValidator
from ._bargap import BargapValidator as BargapValidator
from ._barmode import BarmodeValidator as BarmodeValidator
from ._bgcolor import BgcolorValidator as BgcolorValidator
from ._domain import DomainValidator as DomainValidator
from ._gridshape import GridshapeValidator as GridshapeValidator
from ._hole import HoleValidator as HoleValidator
from ._radialaxis import RadialaxisValidator as RadialaxisValidator
from ._sector import SectorValidator as SectorValidator
from ._uirevision import UirevisionValidator as UirevisionValidator
