from _typeshed import Incomplete
from dataclasses import dataclass
from torchgen.api.translate import translate as translate
from torchgen.api.types import BaseCType as BaseCType, Binding as Binding, CType as CType, Expr as Expr, NamedCType as NamedCType, StructuredImplSignature as StructuredImplSignature, VectorizedCType as VectorizedCType, opmath_t as opmath_t, scalar_t as scalar_t
from torchgen.api.ufunc import UfunctorBindings as UfunctorBindings
from torchgen.context import with_native_function as with_native_function
from torchgen.model import Argument as Argument, BaseTy as BaseTy, BaseType as BaseType, DispatchKey as DispatchKey, NativeFunctionsGroup as NativeFunctionsGroup, ScalarType as ScalarType, UfuncKey as UfuncKey
from torchgen.utils import OrderedSet as OrderedSet
from typing import Dict, List, Sequence, Tuple

@dataclass(frozen=True)
class UfunctorSignature:
    g: NativeFunctionsGroup
    scalar_tensor_idx: int | None
    name: str
    def arguments(self) -> UfunctorBindings: ...
    def fields(self) -> List[Binding]: ...
    def returns_type(self) -> CType: ...
    def decl_fields(self) -> str: ...
    def inline_defn_ctor(self) -> str: ...
    def decl_apply(self) -> str: ...
    def __init__(self, g, scalar_tensor_idx, name) -> None: ...

@dataclass(frozen=True)
class UfuncSignature:
    g: NativeFunctionsGroup
    name: str
    compute_t: CType
    def arguments(self) -> List[Binding]: ...
    def call(self, ctx: Sequence[Binding | Expr]) -> str: ...
    def __init__(self, g, name, compute_t) -> None: ...

def eligible_for_binary_scalar_specialization(g: NativeFunctionsGroup) -> bool: ...
def compute_ufunc_cuda_functors(g: NativeFunctionsGroup) -> Tuple[Dict[ScalarType, Dict[UfuncKey, UfunctorSignature]], str]: ...

@dataclass(frozen=True)
class BinaryScalarSpecializationConfig:
    scalar_idx: int
    ctor_tensor: str
    ufunc_key: UfuncKey
    def __init__(self, scalar_idx, ctor_tensor, ufunc_key) -> None: ...

BinaryScalarSpecializationConfigs: Incomplete

def compute_ufunc_cuda_dtype_body(g: NativeFunctionsGroup, dtype: ScalarType, inner_loops: Dict[UfuncKey, UfunctorSignature], parent_ctx: Sequence[Binding]) -> str: ...
def compute_ufunc_cuda(g: NativeFunctionsGroup) -> str: ...

@dataclass(frozen=True)
class StubSignature:
    g: NativeFunctionsGroup
    @property
    def name(self) -> str: ...
    @property
    def kernel_name(self) -> str: ...
    @property
    def type_name(self) -> str: ...
    def arguments(self) -> List[Binding]: ...
    def type(self) -> str: ...
    def dispatch_decl(self) -> str: ...
    def dispatch_defn(self) -> str: ...
    def kernel_defn(self) -> str: ...
    def type_defn(self) -> str: ...
    def call(self, ctx: Sequence[Binding]) -> str: ...
    def direct_call(self, ctx: Sequence[Binding]) -> str: ...
    def __init__(self, g) -> None: ...

def compute_ufunc_cpu(g: NativeFunctionsGroup) -> str: ...
def compute_ufunc_cpu_dtype_body(g: NativeFunctionsGroup, dtype: ScalarType, inner_loops: Dict[UfuncKey, UfuncSignature], parent_ctx: Sequence[Binding]) -> str: ...
def compute_ufunc_cpu_kernel(g: NativeFunctionsGroup) -> str: ...
