from _typeshed import Incomplete

def get_cudnn_mode(mode): ...

class Unserializable:
    inner: Incomplete
    def __init__(self, inner) -> None: ...
    def get(self): ...

def init_dropout_state(dropout, train, dropout_seed, dropout_state): ...
