from _typeshed import Incomplete
from numba import cuda as cuda
from numba.np.ufunc import deviceufunc as deviceufunc
from numba.np.ufunc.deviceufunc import GUFuncCallSteps as GUFuncCallSteps, GeneralizedUFunc as GeneralizedUFunc, UFuncMechanism as UFuncMechanism

class CUDAUFuncDispatcher:
    """
    Invoke the CUDA ufunc specialization for the given inputs.
    """
    functions: Incomplete
    def __init__(self, types_to_retty_kernels, pyfunc) -> None: ...
    def __call__(self, *args, **kws):
        """
        *args: numpy arrays or DeviceArrayBase (created by cuda.to_device).
               Cannot mix the two types in one call.

        **kws:
            stream -- cuda stream; when defined, asynchronous mode is used.
            out    -- output array. Can be a numpy array or DeviceArrayBase
                      depending on the input arguments.  Type must match
                      the input arguments.
        """
    def reduce(self, arg, stream: int = 0): ...

class _CUDAGUFuncCallSteps(GUFuncCallSteps):
    def __init__(self, nin, nout, args, kwargs) -> None: ...
    def is_device_array(self, obj): ...
    def as_device_array(self, obj): ...
    def to_device(self, hostary): ...
    def to_host(self, devary, hostary): ...
    def allocate_device_array(self, shape, dtype): ...
    def launch_kernel(self, kernel, nelem, args) -> None: ...

class CUDAGeneralizedUFunc(GeneralizedUFunc):
    def __init__(self, kernelmap, engine, pyfunc) -> None: ...

class CUDAUFuncMechanism(UFuncMechanism):
    """
    Provide CUDA specialization
    """
    DEFAULT_STREAM: int
    def launch(self, func, count, stream, args) -> None: ...
    def is_device_array(self, obj): ...
    def as_device_array(self, obj): ...
    def to_device(self, hostary, stream): ...
    def to_host(self, devary, stream): ...
    def allocate_device_array(self, shape, dtype, stream): ...
    def broadcast_device(self, ary, shape): ...

vectorizer_stager_source: str

class CUDAVectorize(deviceufunc.DeviceVectorize):
    def build_ufunc(self): ...

class CUDAGUFuncVectorize(deviceufunc.DeviceGUFuncVectorize):
    def build_ufunc(self): ...
