from ..common.utils import isStrSpace as isStrSpace
from .state_block import StateBlock as StateBlock
from _typeshed import Incomplete

LOGGER: Incomplete

def skipBulletListMarker(state: StateBlock, startLine: int) -> int: ...
def skipOrderedListMarker(state: StateBlock, startLine: int) -> int: ...
def markTightParagraphs(state: StateBlock, idx: int) -> None: ...
def list_block(state: StateBlock, startLine: int, endLine: int, silent: bool) -> bool: ...
