from ._automargin import AutomarginValidator as AutomarginValidator
from ._font import FontValidator as FontValidator
from ._pad import PadValidator as PadValidator
from ._text import TextValidator as TextValidator
from ._x import XValidator as XValidator
from ._xanchor import XanchorValidator as XanchorValidator
from ._xref import XrefValidator as XrefValidator
from ._y import YValidator as YValidator
from ._yanchor import YanchorValidator as YanchorValidator
from ._yref import YrefValidator as YrefValidator
