from dataclasses import dataclass
from seaborn._marks.base import Mappable as Mappable, MappableBool as MappableBool, MappableColor as MappableColor, MappableFloat as MappableFloat, MappableStyle as MappableStyle, Mark as Mark, document_properties as document_properties, resolve_color as resolve_color, resolve_properties as resolve_properties

class AreaBase: ...

@dataclass
class Area(AreaBase, Mark):
    """
    A fill mark drawn from a baseline to data values.

    See also
    --------
    Band : A fill mark representing an interval between values.

    Examples
    --------
    .. include:: ../docstrings/objects.Area.rst

    """
    color: MappableColor = ...
    alpha: MappableFloat = ...
    fill: MappableBool = ...
    edgecolor: MappableColor = ...
    edgealpha: MappableFloat = ...
    edgewidth: MappableFloat = ...
    edgestyle: MappableStyle = ...
    baseline: MappableFloat = ...
    def __init__(self, artist_kws, color, alpha, fill, edgecolor, edgealpha, edgewidth, edgestyle, baseline) -> None: ...

@dataclass
class Band(AreaBase, Mark):
    """
    A fill mark representing an interval between values.

    See also
    --------
    Area : A fill mark drawn from a baseline to data values.

    Examples
    --------
    .. include:: ../docstrings/objects.Band.rst

    """
    color: MappableColor = ...
    alpha: MappableFloat = ...
    fill: MappableBool = ...
    edgecolor: MappableColor = ...
    edgealpha: MappableFloat = ...
    edgewidth: MappableFloat = ...
    edgestyle: MappableFloat = ...
    def __init__(self, artist_kws, color, alpha, fill, edgecolor, edgealpha, edgewidth, edgestyle) -> None: ...
