from _typeshed import Incomplete

def find_cudart_versions(build_env: bool = False, build_cuda_version: Incomplete | None = None): ...
def find_cudnn_supported_cuda_versions(build_env: bool = False): ...
