import threading
from _typeshed import Incomplete
from wandb.proto import wandb_internal_pb2 as wandb_internal_pb2
from wandb.sdk.interface.interface_queue import InterfaceQueue as InterfaceQueue
from wandb.sdk.internal import context as context, datastore as datastore, handler as handler, sender as sender, tb_watcher as tb_watcher
from wandb.sdk.internal.settings_static import SettingsStatic as SettingsStatic
from wandb.sdk.lib import filesystem as filesystem
from wandb.util import check_and_warn_old as check_and_warn_old

WANDB_SUFFIX: str
SYNCED_SUFFIX: str
TFEVENT_SUBSTRING: str
TMPDIR: Incomplete

class _LocalRun:
    path: Incomplete
    synced: Incomplete
    offline: Incomplete
    datetime: Incomplete
    def __init__(self, path, synced: Incomplete | None = None) -> None: ...

class SyncThread(threading.Thread):
    def __init__(self, sync_list, project: Incomplete | None = None, entity: Incomplete | None = None, run_id: Incomplete | None = None, view: Incomplete | None = None, verbose: Incomplete | None = None, mark_synced: Incomplete | None = None, app_url: Incomplete | None = None, sync_tensorboard: Incomplete | None = None, log_path: Incomplete | None = None, append: Incomplete | None = None) -> None: ...
    def run(self): ...

class SyncManager:
    def __init__(self, project: Incomplete | None = None, entity: Incomplete | None = None, run_id: Incomplete | None = None, mark_synced: Incomplete | None = None, app_url: Incomplete | None = None, view: Incomplete | None = None, verbose: Incomplete | None = None, sync_tensorboard: Incomplete | None = None, log_path: Incomplete | None = None, append: Incomplete | None = None) -> None: ...
    def status(self) -> None: ...
    def add(self, p) -> None: ...
    def start(self) -> None: ...
    def is_done(self): ...
    def poll(self): ...

def get_runs(include_offline: Incomplete | None = None, include_online: Incomplete | None = None, include_synced: Incomplete | None = None, include_unsynced: Incomplete | None = None, exclude_globs: Incomplete | None = None, include_globs: Incomplete | None = None): ...
def get_run_from_path(path): ...
