from sympy.polys.domains import QQ as QQ, ZZ as ZZ
from sympy.polys.matrices.exceptions import DMDomainError as DMDomainError, DMRankError as DMRankError, DMShapeError as DMShapeError, DMValueError as DMValueError

def ddm_lll(x, delta=...): ...
def ddm_lll_transform(x, delta=...): ...
