from ...utils._clean_x import unify_columns as unify_columns
from ...utils._native import Native as Native
from _typeshed import Incomplete
from collections.abc import Generator

def eval_terms(X, n_samples, feature_names_in, feature_types_in, bins, term_features) -> Generator[Incomplete, None, None]: ...
def ebm_decision_function(X, n_samples, feature_names_in, feature_types_in, bins, intercept, term_scores, term_features, init_score: Incomplete | None = None): ...
def ebm_decision_function_and_explain(X, n_samples, feature_names_in, feature_types_in, bins, intercept, term_scores, term_features, init_score: Incomplete | None = None): ...
def make_bin_weights(X, n_samples, sample_weight, feature_names_in, feature_types_in, bins, term_features): ...
