import typing
from cryptography import exceptions as exceptions, utils as utils
from cryptography.hazmat.backends.openssl import aead as aead
from cryptography.hazmat.backends.openssl.backend import backend as backend
from cryptography.hazmat.bindings._rust import FixedPool as FixedPool

class ChaCha20Poly1305:
    def __init__(self, key: bytes) -> None: ...
    @classmethod
    def generate_key(cls) -> bytes: ...
    def encrypt(self, nonce: bytes, data: bytes, associated_data: bytes | None) -> bytes: ...
    def decrypt(self, nonce: bytes, data: bytes, associated_data: bytes | None) -> bytes: ...

class AESCCM:
    def __init__(self, key: bytes, tag_length: int = 16) -> None: ...
    @classmethod
    def generate_key(cls, bit_length: int) -> bytes: ...
    def encrypt(self, nonce: bytes, data: bytes, associated_data: bytes | None) -> bytes: ...
    def decrypt(self, nonce: bytes, data: bytes, associated_data: bytes | None) -> bytes: ...

class AESGCM:
    def __init__(self, key: bytes) -> None: ...
    @classmethod
    def generate_key(cls, bit_length: int) -> bytes: ...
    def encrypt(self, nonce: bytes, data: bytes, associated_data: bytes | None) -> bytes: ...
    def decrypt(self, nonce: bytes, data: bytes, associated_data: bytes | None) -> bytes: ...

class AESOCB3:
    def __init__(self, key: bytes) -> None: ...
    @classmethod
    def generate_key(cls, bit_length: int) -> bytes: ...
    def encrypt(self, nonce: bytes, data: bytes, associated_data: bytes | None) -> bytes: ...
    def decrypt(self, nonce: bytes, data: bytes, associated_data: bytes | None) -> bytes: ...

class AESSIV:
    def __init__(self, key: bytes) -> None: ...
    @classmethod
    def generate_key(cls, bit_length: int) -> bytes: ...
    def encrypt(self, data: bytes, associated_data: typing.List[bytes] | None) -> bytes: ...
    def decrypt(self, data: bytes, associated_data: typing.List[bytes] | None) -> bytes: ...
