import dataclasses
from types import CodeType, ModuleType
from typing import Any, Dict

@dataclasses.dataclass
class ModuleRecord:
    module: ModuleType
    accessed_attrs: Dict[str, Any] = ...
    def __init__(self, module, accessed_attrs) -> None: ...

@dataclasses.dataclass
class DummyModule:
    name: str
    def __init__(self, name) -> None: ...

@dataclasses.dataclass
class ExecutionRecord:
    code: CodeType
    globals: Dict[str, Any] = ...
    locals: Dict[str, Any] = ...
    builtins: Dict[str, Any] = ...
    code_options: Dict[str, Any] = ...
    def dump(self, f) -> None: ...
    @classmethod
    def load(cls, f): ...
    def __init__(self, code, globals, locals, builtins, code_options) -> None: ...

@dataclasses.dataclass
class ExecutionRecorder:
    MOD_EXCLUDES = ...
    LOCAL_MOD_PREFIX = ...
    code: CodeType
    globals: Dict[str, Any] = ...
    locals: Dict[str, Any] = ...
    builtins: Dict[str, Any] = ...
    code_options: Dict[str, Any] = ...
    name_to_modrec: Dict[str, Any] = ...
    def add_local_var(self, name, var) -> None: ...
    def add_global_var(self, name, var) -> None: ...
    def add_local_mod(self, name, mod) -> None: ...
    def record_module_access(self, mod, name, val) -> None: ...
    def get_record(self): ...
    def __init__(self, code, globals, locals, builtins, code_options, name_to_modrec) -> None: ...
