from . import config as config, reset as reset, utils as utils
from torch.testing._internal.common_utils import IS_WINDOWS as IS_WINDOWS, TEST_WITH_CROSSREF as TEST_WITH_CROSSREF, TEST_WITH_ROCM as TEST_WITH_ROCM, TEST_WITH_TORCHDYNAMO as TEST_WITH_TORCHDYNAMO, TestCase as TorchTestCase

def run_tests(needs=()) -> None: ...

class TestCase(TorchTestCase):
    @classmethod
    def tearDownClass(cls) -> None: ...
    @classmethod
    def setUpClass(cls) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
