import typing
from cryptography import utils as utils
from cryptography.exceptions import AlreadyFinalized as AlreadyFinalized
from cryptography.hazmat.backends.openssl.cmac import _CMACContext
from cryptography.hazmat.primitives import ciphers as ciphers

class CMAC:
    def __init__(self, algorithm: ciphers.BlockCipherAlgorithm, backend: typing.Any = None, ctx: _CMACContext | None = None) -> None: ...
    def update(self, data: bytes) -> None: ...
    def finalize(self) -> bytes: ...
    def verify(self, signature: bytes) -> None: ...
    def copy(self) -> CMAC: ...
