import typing
from cryptography.hazmat.primitives.ciphers import Cipher as Cipher
from cryptography.hazmat.primitives.ciphers.algorithms import AES as AES
from cryptography.hazmat.primitives.ciphers.modes import ECB as ECB
from cryptography.hazmat.primitives.constant_time import bytes_eq as bytes_eq

def aes_key_wrap(wrapping_key: bytes, key_to_wrap: bytes, backend: typing.Any = None) -> bytes: ...
def aes_key_wrap_with_padding(wrapping_key: bytes, key_to_wrap: bytes, backend: typing.Any = None) -> bytes: ...
def aes_key_unwrap_with_padding(wrapping_key: bytes, wrapped_key: bytes, backend: typing.Any = None) -> bytes: ...
def aes_key_unwrap(wrapping_key: bytes, wrapped_key: bytes, backend: typing.Any = None) -> bytes: ...

class InvalidUnwrap(Exception): ...
