from cryptography.exceptions import InvalidSignature as InvalidSignature, UnsupportedAlgorithm as UnsupportedAlgorithm
from cryptography.hazmat.backends.openssl.backend import Backend as Backend
from cryptography.hazmat.primitives import serialization as serialization
from cryptography.hazmat.primitives.asymmetric import ec as ec

class _EllipticCurvePrivateKey(ec.EllipticCurvePrivateKey):
    def __init__(self, backend: Backend, ec_key_cdata, evp_pkey) -> None: ...
    @property
    def curve(self) -> ec.EllipticCurve: ...
    @property
    def key_size(self) -> int: ...
    def exchange(self, algorithm: ec.ECDH, peer_public_key: ec.EllipticCurvePublicKey) -> bytes: ...
    def public_key(self) -> ec.EllipticCurvePublicKey: ...
    def private_numbers(self) -> ec.EllipticCurvePrivateNumbers: ...
    def private_bytes(self, encoding: serialization.Encoding, format: serialization.PrivateFormat, encryption_algorithm: serialization.KeySerializationEncryption) -> bytes: ...
    def sign(self, data: bytes, signature_algorithm: ec.EllipticCurveSignatureAlgorithm) -> bytes: ...

class _EllipticCurvePublicKey(ec.EllipticCurvePublicKey):
    def __init__(self, backend: Backend, ec_key_cdata, evp_pkey) -> None: ...
    @property
    def curve(self) -> ec.EllipticCurve: ...
    @property
    def key_size(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def public_numbers(self) -> ec.EllipticCurvePublicNumbers: ...
    def public_bytes(self, encoding: serialization.Encoding, format: serialization.PublicFormat) -> bytes: ...
    def verify(self, signature: bytes, data: bytes, signature_algorithm: ec.EllipticCurveSignatureAlgorithm) -> None: ...
