from cryptography.exceptions import InvalidSignature as InvalidSignature, UnsupportedAlgorithm as UnsupportedAlgorithm
from cryptography.hazmat.backends.openssl.backend import Backend as Backend
from cryptography.hazmat.primitives import hashes as hashes, serialization as serialization
from cryptography.hazmat.primitives.asymmetric import utils as asym_utils
from cryptography.hazmat.primitives.asymmetric.padding import AsymmetricPadding as AsymmetricPadding, MGF1 as MGF1, OAEP as OAEP, PKCS1v15 as PKCS1v15, PSS as PSS, calculate_max_pss_salt_length as calculate_max_pss_salt_length
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPrivateKey as RSAPrivateKey, RSAPrivateNumbers as RSAPrivateNumbers, RSAPublicKey as RSAPublicKey, RSAPublicNumbers as RSAPublicNumbers

class _RSAPrivateKey(RSAPrivateKey):
    def __init__(self, backend: Backend, rsa_cdata, evp_pkey, *, unsafe_skip_rsa_key_validation: bool) -> None: ...
    @property
    def key_size(self) -> int: ...
    def decrypt(self, ciphertext: bytes, padding: AsymmetricPadding) -> bytes: ...
    def public_key(self) -> RSAPublicKey: ...
    def private_numbers(self) -> RSAPrivateNumbers: ...
    def private_bytes(self, encoding: serialization.Encoding, format: serialization.PrivateFormat, encryption_algorithm: serialization.KeySerializationEncryption) -> bytes: ...
    def sign(self, data: bytes, padding: AsymmetricPadding, algorithm: asym_utils.Prehashed | hashes.HashAlgorithm) -> bytes: ...

class _RSAPublicKey(RSAPublicKey):
    def __init__(self, backend: Backend, rsa_cdata, evp_pkey) -> None: ...
    @property
    def key_size(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def encrypt(self, plaintext: bytes, padding: AsymmetricPadding) -> bytes: ...
    def public_numbers(self) -> RSAPublicNumbers: ...
    def public_bytes(self, encoding: serialization.Encoding, format: serialization.PublicFormat) -> bytes: ...
    def verify(self, signature: bytes, data: bytes, padding: AsymmetricPadding, algorithm: asym_utils.Prehashed | hashes.HashAlgorithm) -> None: ...
    def recover_data_from_signature(self, signature: bytes, padding: AsymmetricPadding, algorithm: hashes.HashAlgorithm | None) -> bytes: ...
