import threading
from .aggregators import aggregate_last as aggregate_last, aggregate_mean as aggregate_mean
from .asset_registry import asset_registry as asset_registry
from .interfaces import Interface as Interface, Metric as Metric, MetricsMonitor as MetricsMonitor
from _typeshed import Incomplete
from wandb.sdk.internal.settings_static import SettingsStatic as SettingsStatic

class ProcessCpuPercent:
    """CPU usage of the process in percent normalized by the number of CPUs."""
    name: str
    pid: Incomplete
    samples: Incomplete
    process: Incomplete
    def __init__(self, pid: int) -> None: ...
    def sample(self) -> None: ...
    def clear(self) -> None: ...
    def aggregate(self) -> dict: ...

class CpuPercent:
    """CPU usage of the system in percent per core."""
    name: str
    samples: Incomplete
    interval: Incomplete
    def __init__(self, interval: float | None = None) -> None: ...
    def sample(self) -> None: ...
    def clear(self) -> None: ...
    def aggregate(self) -> dict: ...

class ProcessCpuThreads:
    """Number of threads used by the process."""
    name: str
    samples: Incomplete
    pid: Incomplete
    process: Incomplete
    def __init__(self, pid: int) -> None: ...
    def sample(self) -> None: ...
    def clear(self) -> None: ...
    def aggregate(self) -> dict: ...

class CPU:
    name: Incomplete
    metrics: Incomplete
    metrics_monitor: Incomplete
    def __init__(self, interface: Interface, settings: SettingsStatic, shutdown_event: threading.Event) -> None: ...
    @classmethod
    def is_available(cls) -> bool: ...
    def probe(self) -> dict: ...
    def start(self) -> None: ...
    def finish(self) -> None: ...
