import threading
from .aggregators import aggregate_mean as aggregate_mean
from .asset_registry import asset_registry as asset_registry
from .interfaces import Interface as Interface, Metric as Metric, MetricsMonitor as MetricsMonitor
from _typeshed import Incomplete
from typing import Deque, List
from wandb.errors.term import termwarn as termwarn
from wandb.sdk.internal.settings_static import SettingsStatic as SettingsStatic

class DiskUsagePercent:
    """Total system disk usage in percent."""
    name: str
    samples: Deque[List[float]]
    paths: Incomplete
    def __init__(self, paths: List[str]) -> None: ...
    def sample(self) -> None: ...
    def clear(self) -> None: ...
    def aggregate(self) -> dict: ...

class DiskUsage:
    """Total system disk usage in GB."""
    name: str
    samples: Deque[List[float]]
    paths: Incomplete
    def __init__(self, paths: List[str]) -> None: ...
    def sample(self) -> None: ...
    def clear(self) -> None: ...
    def aggregate(self) -> dict: ...

class DiskIn:
    """Total system disk read in MB."""
    name: str
    samples: Deque[float]
    read_init: Incomplete
    def __init__(self) -> None: ...
    def sample(self) -> None: ...
    def clear(self) -> None: ...
    def aggregate(self) -> dict: ...

class DiskOut:
    """Total system disk write in MB."""
    name: str
    samples: Deque[float]
    write_init: Incomplete
    def __init__(self) -> None: ...
    def sample(self) -> None: ...
    def clear(self) -> None: ...
    def aggregate(self) -> dict: ...

class Disk:
    name: Incomplete
    settings: Incomplete
    metrics: Incomplete
    metrics_monitor: Incomplete
    def __init__(self, interface: Interface, settings: SettingsStatic, shutdown_event: threading.Event) -> None: ...
    @classmethod
    def is_available(cls) -> bool:
        """Return a new instance of the CPU metrics."""
    def probe(self) -> dict: ...
    def start(self) -> None: ...
    def finish(self) -> None: ...
