from _typeshed import Incomplete

app: Incomplete

class AppRunner:
    app: Incomplete
    base_url: Incomplete
    use_relative_links: Incomplete
    ip: str
    port: int
    def __init__(self, addr: Incomplete | None = None, base_url: Incomplete | None = None, use_relative_links: bool = False) -> None: ...
    def stop(self): ...
    def start(self) -> None: ...
    def ping(self):
        """Returns true if web service reachable, otherwise False."""
    def status(self): ...
    def register(self, ctx, **kwargs) -> None: ...
    def display_link(self, ctx): ...
    def display(self, ctx, width: str = '100%', height: int = 800, open_link: bool = False) -> None: ...

class DispatcherApp:
    base_url: Incomplete
    use_relative_links: Incomplete
    root_path: str
    shutdown_path: str
    favicon_path: str
    favicon_res: Incomplete
    default_app: Incomplete
    pool: Incomplete
    config: Incomplete
    app_pattern: Incomplete
    def __init__(self, base_url: Incomplete | None = None, use_relative_links: bool = False) -> None: ...
    def obj_id(self, obj): ...
    def register(self, ctx, share_tables: Incomplete | None = None) -> None: ...
    def __call__(self, environ, start_response): ...
