from _typeshed import Incomplete

COLORS: Incomplete

def is_multiclass_global_data_dict(data_dict): ...
def is_multiclass_local_data_dict(data_dict): ...
def plot_performance_curve(data_dict, title: str = '', xtitle: str = '', ytitle: str = '', auc_prefix: str = '', baseline: bool = False): ...
def plot_continuous_bar(data_dict, multiclass: bool = False, show_error: bool = True, title: Incomplete | None = None, xtitle: str = '', ytitle: str = ''): ...
def plot_density(data_dict, title: str = '', xtitle: str = '', ytitle: str = '', is_categorical: bool = False, name: str = '', color=...): ...
def plot_line(data_dict, title: Incomplete | None = None, xtitle: str = '', ytitle: str = '', name: str = 'Main', color=...): ...
def plot_bar(data_dict, title: str = '', xtitle: str = '', ytitle: str = ''): ...
def plot_horizontal_bar(data_dict, multiclass: bool = False, title: str = '', xtitle: str = '', ytitle: str = '', start_zero: bool = False): ...
def mli_plot_horizontal_bar(scores, names, values: Incomplete | None = None, perf: Incomplete | None = None, intercept: Incomplete | None = None, title: str = '', xtitle: str = '', ytitle: str = '', start_zero: bool = False): ...
def plot_pairwise_heatmap(data_dict, title: str = '', xtitle: str = '', ytitle: str = ''): ...
def sort_take(data_dict, sort_fn: Incomplete | None = None, sort_target: str = 'scores', reverse_results: bool = False, top_n: Incomplete | None = None): ...
def get_sort_indexes(data, sort_fn: Incomplete | None = None, top_n: Incomplete | None = None): ...
def get_sort_indexes_1d(data, sort_fn: Incomplete | None = None, top_n: Incomplete | None = None): ...
def get_sort_indexes_2d(data, sort_fn: Incomplete | None = None, top_n: Incomplete | None = None): ...
def mli_sort_take(data, sort_indexes, reverse_results: bool = False): ...
def get_explanation_index(explanation_list, explanation_type): ...
def rules_to_html(data_dict, title: str = ''): ...
def plot_ebm_multiple_booleans(feat_names, ebm_global, mpl_style: bool = False, figname: Incomplete | None = None):
    """
    Helper function to plot the effect sizes of many Boolean features on the same figure.
    Args:
        feat_names: list of feature names to be plotted.
        ebm_global: Explanation Object for which the effect sizes should be plotted.
        mpl_style: Boolean, if True the Figure is plotted in matplotlib style.
                    If False, the Figure is plotted as an interactive Plotly figure.
        figname: str name of figure to be saved. If none, the figure is not saved.
    Returns:
        None
    """
