from _typeshed import Incomplete
from flaml.automl.data import TS_TIMESTAMP_COL as TS_TIMESTAMP_COL, concat as concat
from flaml.automl.ml import EstimatorSubclass as EstimatorSubclass, default_cv_score_agg_func as default_cv_score_agg_func, get_val_loss as get_val_loss
from flaml.automl.spark import pd as pd, ps as ps, psDataFrame as psDataFrame, psSeries as psSeries
from flaml.automl.spark.utils import iloc_pandas_on_spark as iloc_pandas_on_spark, len_labels as len_labels, set_option as set_option, spark_kFold as spark_kFold, train_test_split_pyspark as train_test_split_pyspark, unique_pandas_on_spark as unique_pandas_on_spark, unique_value_first_index as unique_value_first_index
from flaml.automl.task.task import TS_FORECAST as TS_FORECAST, TS_FORECASTPANEL as TS_FORECASTPANEL, Task as Task, get_classification_objective as get_classification_objective
from flaml.config import RANDOM_SEED as RANDOM_SEED
from typing import List

logger: Incomplete

class GenericTask(Task):
    @property
    def estimators(self): ...
    def validate_data(self, automl, state, X_train_all, y_train_all, dataframe, label, X_val: Incomplete | None = None, y_val: Incomplete | None = None, groups_val: Incomplete | None = None, groups: Incomplete | None = None) -> None: ...
    is_spark_dataframe: Incomplete
    def prepare_data(self, state, X_train_all, y_train_all, auto_augment, eval_method, split_type, split_ratio, n_splits, data_is_df, sample_weight_full) -> int: ...
    name: Incomplete
    def decide_split_type(self, split_type, y_train_all, fit_kwargs, groups: Incomplete | None = None) -> str: ...
    def preprocess(self, X, transformer: Incomplete | None = None): ...
    def evaluate_model_CV(self, config: dict, estimator: EstimatorSubclass, X_train_all, y_train_all, budget, kf, eval_metric, best_val_loss, cv_score_agg_func: Incomplete | None = None, log_training_metric: bool = False, fit_kwargs: dict | None = None, free_mem_ratio: int = 0): ...
    def default_estimator_list(self, estimator_list: List[str], is_spark_dataframe: bool = False) -> List[str]: ...
    def default_metric(self, metric: str) -> str: ...
    @staticmethod
    def prepare_sample_train_data(automlstate, sample_size): ...
