from transformers import AutoFeatureExtractor as AutoFeatureExtractor, Swinv2Config as Swinv2Config, Swinv2ForImageClassification as Swinv2ForImageClassification

def get_swinv2_config(swinv2_name): ...
def rename_key(name): ...
def convert_state_dict(orig_state_dict, model): ...
def convert_swinv2_checkpoint(swinv2_name, pytorch_dump_folder_path) -> None: ...
