from . import c_ast as c_ast
from _typeshed import Incomplete

class CGenerator:
    """ Uses the same visitor pattern as c_ast.NodeVisitor, but modified to
        return a value from each visit method, using string accumulation in
        generic_visit.
    """
    indent_level: int
    reduce_parentheses: Incomplete
    def __init__(self, reduce_parentheses: bool = False) -> None:
        """ Constructs C-code generator

            reduce_parentheses:
                if True, eliminates needless parentheses on binary operators
        """
    def visit(self, node): ...
    def generic_visit(self, node): ...
    def visit_Constant(self, n): ...
    def visit_ID(self, n): ...
    def visit_Pragma(self, n): ...
    def visit_ArrayRef(self, n): ...
    def visit_StructRef(self, n): ...
    def visit_FuncCall(self, n): ...
    def visit_UnaryOp(self, n): ...
    precedence_map: Incomplete
    def visit_BinaryOp(self, n): ...
    def visit_Assignment(self, n): ...
    def visit_IdentifierType(self, n): ...
    def visit_Decl(self, n, no_type: bool = False): ...
    def visit_DeclList(self, n): ...
    def visit_Typedef(self, n): ...
    def visit_Cast(self, n): ...
    def visit_ExprList(self, n): ...
    def visit_InitList(self, n): ...
    def visit_Enum(self, n): ...
    def visit_Alignas(self, n): ...
    def visit_Enumerator(self, n): ...
    def visit_FuncDef(self, n): ...
    def visit_FileAST(self, n): ...
    def visit_Compound(self, n): ...
    def visit_CompoundLiteral(self, n): ...
    def visit_EmptyStatement(self, n): ...
    def visit_ParamList(self, n): ...
    def visit_Return(self, n): ...
    def visit_Break(self, n): ...
    def visit_Continue(self, n): ...
    def visit_TernaryOp(self, n): ...
    def visit_If(self, n): ...
    def visit_For(self, n): ...
    def visit_While(self, n): ...
    def visit_DoWhile(self, n): ...
    def visit_StaticAssert(self, n): ...
    def visit_Switch(self, n): ...
    def visit_Case(self, n): ...
    def visit_Default(self, n): ...
    def visit_Label(self, n): ...
    def visit_Goto(self, n): ...
    def visit_EllipsisParam(self, n): ...
    def visit_Struct(self, n): ...
    def visit_Typename(self, n): ...
    def visit_Union(self, n): ...
    def visit_NamedInitializer(self, n): ...
    def visit_FuncDecl(self, n): ...
    def visit_ArrayDecl(self, n): ...
    def visit_TypeDecl(self, n): ...
    def visit_PtrDecl(self, n): ...
