from _typeshed import Incomplete
from openai import api_requestor as api_requestor, error as error, util as util
from openai.openai_object import OpenAIObject as OpenAIObject
from openai.util import ApiType as ApiType

class APIResource(OpenAIObject):
    api_prefix: str
    azure_api_prefix: str
    azure_deployments_prefix: str
    @classmethod
    def retrieve(cls, id, api_key: Incomplete | None = None, request_id: Incomplete | None = None, request_timeout: Incomplete | None = None, **params): ...
    @classmethod
    def aretrieve(cls, id, api_key: Incomplete | None = None, request_id: Incomplete | None = None, request_timeout: Incomplete | None = None, **params): ...
    def refresh(self, request_id: Incomplete | None = None, request_timeout: Incomplete | None = None): ...
    async def arefresh(self, request_id: Incomplete | None = None, request_timeout: Incomplete | None = None): ...
    @classmethod
    def class_url(cls): ...
    def instance_url(self, operation: Incomplete | None = None): ...
