from _typeshed import Incomplete
from openai import api_requestor as api_requestor, util as util

def nested_resource_class_methods(resource, path: Incomplete | None = None, operations: Incomplete | None = None, resource_plural: Incomplete | None = None): ...
def anested_resource_class_methods(resource, path: Incomplete | None = None, operations: Incomplete | None = None, resource_plural: Incomplete | None = None): ...
