from .Transitions import TransitionMap as TransitionMap
from _typeshed import Incomplete

maxint: Incomplete
unichr = chr
LOWEST_PRIORITY: Incomplete

class Machine:
    """A collection of Nodes representing an NFA or DFA."""
    states: Incomplete
    initial_states: Incomplete
    next_state_number: int
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    def new_state(self):
        """Add a new state to the machine and return it."""
    def new_initial_state(self, name): ...
    def make_initial_state(self, name, state) -> None: ...
    def get_initial_state(self, name): ...
    def dump(self, file) -> None: ...

class Node:
    """A state of an NFA or DFA."""
    transitions: Incomplete
    action_priority: Incomplete
    action: Incomplete
    number: int
    epsilon_closure: Incomplete
    def __init__(self) -> None: ...
    def destroy(self) -> None: ...
    def add_transition(self, event, new_state) -> None: ...
    def link_to(self, state) -> None:
        """Add an epsilon-move from this state to another state."""
    def set_action(self, action, priority) -> None:
        """Make this an accepting state with the given action. If
        there is already an action, choose the action with highest
        priority."""
    def get_action(self): ...
    def get_action_priority(self): ...
    def is_accepting(self): ...
    def dump(self, file) -> None: ...
    def __lt__(self, other): ...
    def __hash__(self): ...

class FastMachine:
    """
    FastMachine is a deterministic machine represented in a way that
    allows fast scanning.
    """
    initial_states: Incomplete
    states: Incomplete
    next_number: int
    new_state_template: Incomplete
    def __init__(self) -> None: ...
    def __del__(self) -> None: ...
    def new_state(self, action: Incomplete | None = None): ...
    def make_initial_state(self, name, state) -> None: ...
    def add_transitions(self, state, event, new_state, maxint=...) -> None: ...
    def get_initial_state(self, name): ...
    def dump(self, file) -> None: ...
    def dump_state(self, state, file) -> None: ...
    def dump_transitions(self, state, file) -> None: ...
    def chars_to_ranges(self, char_list): ...
    def ranges_to_string(self, range_list): ...
    def range_to_string(self, range_tuple): ...
