from ._exceptions import BaseExceptionGroup as BaseExceptionGroup
from collections.abc import Iterable, Mapping
from contextlib import AbstractContextManager
from types import TracebackType

class _Catcher:
    def __init__(self, handler_map: Mapping[tuple[type[BaseException], ...], _Handler]) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, etype: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None) -> bool: ...
    def handle_exception(self, exc: BaseException) -> BaseException | None: ...

def catch(__handlers: Mapping[type[BaseException] | Iterable[type[BaseException]], _Handler]) -> AbstractContextManager[None]: ...
