from torch.onnx._internal.diagnostics.infra.sarif._address import Address as Address
from torch.onnx._internal.diagnostics.infra.sarif._artifact import Artifact as Artifact
from torch.onnx._internal.diagnostics.infra.sarif._artifact_change import ArtifactChange as ArtifactChange
from torch.onnx._internal.diagnostics.infra.sarif._artifact_content import ArtifactContent as ArtifactContent
from torch.onnx._internal.diagnostics.infra.sarif._artifact_location import ArtifactLocation as ArtifactLocation
from torch.onnx._internal.diagnostics.infra.sarif._attachment import Attachment as Attachment
from torch.onnx._internal.diagnostics.infra.sarif._code_flow import CodeFlow as CodeFlow
from torch.onnx._internal.diagnostics.infra.sarif._configuration_override import ConfigurationOverride as ConfigurationOverride
from torch.onnx._internal.diagnostics.infra.sarif._conversion import Conversion as Conversion
from torch.onnx._internal.diagnostics.infra.sarif._edge import Edge as Edge
from torch.onnx._internal.diagnostics.infra.sarif._edge_traversal import EdgeTraversal as EdgeTraversal
from torch.onnx._internal.diagnostics.infra.sarif._exception import Exception as Exception
from torch.onnx._internal.diagnostics.infra.sarif._external_properties import ExternalProperties as ExternalProperties
from torch.onnx._internal.diagnostics.infra.sarif._external_property_file_reference import ExternalPropertyFileReference as ExternalPropertyFileReference
from torch.onnx._internal.diagnostics.infra.sarif._external_property_file_references import ExternalPropertyFileReferences as ExternalPropertyFileReferences
from torch.onnx._internal.diagnostics.infra.sarif._fix import Fix as Fix
from torch.onnx._internal.diagnostics.infra.sarif._graph import Graph as Graph
from torch.onnx._internal.diagnostics.infra.sarif._graph_traversal import GraphTraversal as GraphTraversal
from torch.onnx._internal.diagnostics.infra.sarif._invocation import Invocation as Invocation
from torch.onnx._internal.diagnostics.infra.sarif._location import Location as Location
from torch.onnx._internal.diagnostics.infra.sarif._location_relationship import LocationRelationship as LocationRelationship
from torch.onnx._internal.diagnostics.infra.sarif._logical_location import LogicalLocation as LogicalLocation
from torch.onnx._internal.diagnostics.infra.sarif._message import Message as Message
from torch.onnx._internal.diagnostics.infra.sarif._multiformat_message_string import MultiformatMessageString as MultiformatMessageString
from torch.onnx._internal.diagnostics.infra.sarif._node import Node as Node
from torch.onnx._internal.diagnostics.infra.sarif._notification import Notification as Notification
from torch.onnx._internal.diagnostics.infra.sarif._physical_location import PhysicalLocation as PhysicalLocation
from torch.onnx._internal.diagnostics.infra.sarif._property_bag import PropertyBag as PropertyBag
from torch.onnx._internal.diagnostics.infra.sarif._rectangle import Rectangle as Rectangle
from torch.onnx._internal.diagnostics.infra.sarif._region import Region as Region
from torch.onnx._internal.diagnostics.infra.sarif._replacement import Replacement as Replacement
from torch.onnx._internal.diagnostics.infra.sarif._reporting_configuration import ReportingConfiguration as ReportingConfiguration
from torch.onnx._internal.diagnostics.infra.sarif._reporting_descriptor import ReportingDescriptor as ReportingDescriptor
from torch.onnx._internal.diagnostics.infra.sarif._reporting_descriptor_reference import ReportingDescriptorReference as ReportingDescriptorReference
from torch.onnx._internal.diagnostics.infra.sarif._reporting_descriptor_relationship import ReportingDescriptorRelationship as ReportingDescriptorRelationship
from torch.onnx._internal.diagnostics.infra.sarif._result import Result as Result
from torch.onnx._internal.diagnostics.infra.sarif._result_provenance import ResultProvenance as ResultProvenance
from torch.onnx._internal.diagnostics.infra.sarif._run import Run as Run
from torch.onnx._internal.diagnostics.infra.sarif._run_automation_details import RunAutomationDetails as RunAutomationDetails
from torch.onnx._internal.diagnostics.infra.sarif._sarif_log import SarifLog as SarifLog
from torch.onnx._internal.diagnostics.infra.sarif._special_locations import SpecialLocations as SpecialLocations
from torch.onnx._internal.diagnostics.infra.sarif._stack import Stack as Stack
from torch.onnx._internal.diagnostics.infra.sarif._stack_frame import StackFrame as StackFrame
from torch.onnx._internal.diagnostics.infra.sarif._suppression import Suppression as Suppression
from torch.onnx._internal.diagnostics.infra.sarif._thread_flow import ThreadFlow as ThreadFlow
from torch.onnx._internal.diagnostics.infra.sarif._thread_flow_location import ThreadFlowLocation as ThreadFlowLocation
from torch.onnx._internal.diagnostics.infra.sarif._tool import Tool as Tool
from torch.onnx._internal.diagnostics.infra.sarif._tool_component import ToolComponent as ToolComponent
from torch.onnx._internal.diagnostics.infra.sarif._tool_component_reference import ToolComponentReference as ToolComponentReference
from torch.onnx._internal.diagnostics.infra.sarif._translation_metadata import TranslationMetadata as TranslationMetadata
from torch.onnx._internal.diagnostics.infra.sarif._version_control_details import VersionControlDetails as VersionControlDetails
from torch.onnx._internal.diagnostics.infra.sarif._web_request import WebRequest as WebRequest
from torch.onnx._internal.diagnostics.infra.sarif._web_response import WebResponse as WebResponse
