import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _property_bag

@dataclasses.dataclass
class Address:
    """A physical or virtual address, or a range of addresses, in an 'addressable region' (memory or a binary file)."""
    absolute_address: int = ...
    fully_qualified_name: str | None = ...
    index: int = ...
    kind: str | None = ...
    length: int | None = ...
    name: str | None = ...
    offset_from_parent: int | None = ...
    parent_index: int = ...
    properties: _property_bag.PropertyBag | None = ...
    relative_address: int | None = ...
    def __init__(self, absolute_address, fully_qualified_name, index, kind, length, name, offset_from_parent, parent_index, properties, relative_address) -> None: ...
