import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _message, _property_bag

@dataclasses.dataclass
class ArtifactLocation:
    """Specifies the location of an artifact."""
    description: _message.Message | None = ...
    index: int = ...
    properties: _property_bag.PropertyBag | None = ...
    uri: str | None = ...
    uri_base_id: str | None = ...
    def __init__(self, description, index, properties, uri, uri_base_id) -> None: ...
