import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _artifact_location, _property_bag, _replacement
from typing import List

@dataclasses.dataclass
class ArtifactChange:
    """A change to a single artifact."""
    artifact_location: _artifact_location.ArtifactLocation = ...
    replacements: List[_replacement.Replacement] = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, artifact_location, replacements, properties) -> None: ...
