import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _message, _property_bag, _thread_flow
from typing import List

@dataclasses.dataclass
class CodeFlow:
    """A set of threadFlows which together describe a pattern of code execution relevant to detecting a result."""
    thread_flows: List[_thread_flow.ThreadFlow] = ...
    message: _message.Message | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, thread_flows, message, properties) -> None: ...
