import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _artifact_location, _invocation, _property_bag, _tool
from typing import List

@dataclasses.dataclass
class Conversion:
    """Describes how a converter transformed the output of a static analysis tool from the analysis tool's native output format into the SARIF format."""
    tool: _tool.Tool = ...
    analysis_tool_log_files: List[_artifact_location.ArtifactLocation] | None = ...
    invocation: _invocation.Invocation | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, tool, analysis_tool_log_files, invocation, properties) -> None: ...
