import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _exception, _property_bag, _stack
from typing import List

@dataclasses.dataclass
class Exception:
    """Describes a runtime exception encountered during the execution of an analysis tool."""
    inner_exceptions: List[_exception.Exception] | None = ...
    kind: str | None = ...
    message: str | None = ...
    properties: _property_bag.PropertyBag | None = ...
    stack: _stack.Stack | None = ...
    def __init__(self, inner_exceptions, kind, message, properties, stack) -> None: ...
