import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _artifact_location, _property_bag

@dataclasses.dataclass
class ExternalPropertyFileReference:
    """Contains information that enables a SARIF consumer to locate the external property file that contains the value of an externalized property associated with the run."""
    guid: str | None = ...
    item_count: int = ...
    location: _artifact_location.ArtifactLocation | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, guid, item_count, location, properties) -> None: ...
