import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _external_property_file_reference, _property_bag
from typing import List

@dataclasses.dataclass
class ExternalPropertyFileReferences:
    """References to external property files that should be inlined with the content of a root log file."""
    addresses: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    artifacts: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    conversion: _external_property_file_reference.ExternalPropertyFileReference | None = ...
    driver: _external_property_file_reference.ExternalPropertyFileReference | None = ...
    extensions: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    externalized_properties: _external_property_file_reference.ExternalPropertyFileReference | None = ...
    graphs: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    invocations: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    logical_locations: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    policies: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    properties: _property_bag.PropertyBag | None = ...
    results: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    taxonomies: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    thread_flow_locations: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    translations: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    web_requests: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    web_responses: List[_external_property_file_reference.ExternalPropertyFileReference] | None = ...
    def __init__(self, addresses, artifacts, conversion, driver, extensions, externalized_properties, graphs, invocations, logical_locations, policies, properties, results, taxonomies, thread_flow_locations, translations, web_requests, web_responses) -> None: ...
