import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _artifact_change, _message, _property_bag
from typing import List

@dataclasses.dataclass
class Fix:
    """A proposed fix for the problem represented by a result object. A fix specifies a set of artifacts to modify. For each artifact, it specifies a set of bytes to remove, and provides a set of new bytes to replace them."""
    artifact_changes: List[_artifact_change.ArtifactChange] = ...
    description: _message.Message | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, artifact_changes, description, properties) -> None: ...
