import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _edge, _message, _node, _property_bag
from typing import List

@dataclasses.dataclass
class Graph:
    """A network of nodes and directed edges that describes some aspect of the structure of the code (for example, a call graph)."""
    description: _message.Message | None = ...
    edges: List[_edge.Edge] | None = ...
    nodes: List[_node.Node] | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, description, edges, nodes, properties) -> None: ...
