import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _artifact_location, _configuration_override, _notification, _property_bag
from typing import Any, List

@dataclasses.dataclass
class Invocation:
    """The runtime environment of the analysis tool run."""
    execution_successful: bool = ...
    account: str | None = ...
    arguments: List[str] | None = ...
    command_line: str | None = ...
    end_time_utc: str | None = ...
    environment_variables: Any = ...
    executable_location: _artifact_location.ArtifactLocation | None = ...
    exit_code: int | None = ...
    exit_code_description: str | None = ...
    exit_signal_name: str | None = ...
    exit_signal_number: int | None = ...
    machine: str | None = ...
    notification_configuration_overrides: List[_configuration_override.ConfigurationOverride] | None = ...
    process_id: int | None = ...
    process_start_failure_message: str | None = ...
    properties: _property_bag.PropertyBag | None = ...
    response_files: List[_artifact_location.ArtifactLocation] | None = ...
    rule_configuration_overrides: List[_configuration_override.ConfigurationOverride] | None = ...
    start_time_utc: str | None = ...
    stderr: _artifact_location.ArtifactLocation | None = ...
    stdin: _artifact_location.ArtifactLocation | None = ...
    stdout: _artifact_location.ArtifactLocation | None = ...
    stdout_stderr: _artifact_location.ArtifactLocation | None = ...
    tool_configuration_notifications: List[_notification.Notification] | None = ...
    tool_execution_notifications: List[_notification.Notification] | None = ...
    working_directory: _artifact_location.ArtifactLocation | None = ...
    def __init__(self, execution_successful, account, arguments, command_line, end_time_utc, environment_variables, executable_location, exit_code, exit_code_description, exit_signal_name, exit_signal_number, machine, notification_configuration_overrides, process_id, process_start_failure_message, properties, response_files, rule_configuration_overrides, start_time_utc, stderr, stdin, stdout, stdout_stderr, tool_configuration_notifications, tool_execution_notifications, working_directory) -> None: ...
