import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _property_bag

@dataclasses.dataclass
class MultiformatMessageString:
    """A message string or message format string rendered in multiple formats."""
    text: str = ...
    markdown: str | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, text, markdown, properties) -> None: ...
