import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _location, _message, _node, _property_bag
from typing import List

@dataclasses.dataclass
class Node:
    """Represents a node in a graph."""
    id: str = ...
    children: List[_node.Node] | None = ...
    label: _message.Message | None = ...
    location: _location.Location | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, id, children, label, location, properties) -> None: ...
