import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _exception, _location, _message, _property_bag, _reporting_descriptor_reference
from typing import List, Literal

@dataclasses.dataclass
class Notification:
    """Describes a condition relevant to the tool itself, as opposed to being relevant to a target being analyzed by the tool."""
    message: _message.Message = ...
    associated_rule: _reporting_descriptor_reference.ReportingDescriptorReference | None = ...
    descriptor: _reporting_descriptor_reference.ReportingDescriptorReference | None = ...
    exception: _exception.Exception | None = ...
    level: Literal['none', 'note', 'warning', 'error'] = ...
    locations: List[_location.Location] | None = ...
    properties: _property_bag.PropertyBag | None = ...
    thread_id: int | None = ...
    time_utc: str | None = ...
    def __init__(self, message, associated_rule, descriptor, exception, level, locations, properties, thread_id, time_utc) -> None: ...
