import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _artifact_content, _message, _property_bag

@dataclasses.dataclass
class Region:
    """A region within an artifact where a result was detected."""
    byte_length: int | None = ...
    byte_offset: int = ...
    char_length: int | None = ...
    char_offset: int = ...
    end_column: int | None = ...
    end_line: int | None = ...
    message: _message.Message | None = ...
    properties: _property_bag.PropertyBag | None = ...
    snippet: _artifact_content.ArtifactContent | None = ...
    source_language: str | None = ...
    start_column: int | None = ...
    start_line: int | None = ...
    def __init__(self, byte_length, byte_offset, char_length, char_offset, end_column, end_line, message, properties, snippet, source_language, start_column, start_line) -> None: ...
