import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _message, _property_bag, _reporting_descriptor_reference
from typing import List

@dataclasses.dataclass
class ReportingDescriptorRelationship:
    """Information about the relation of one reporting descriptor to another."""
    target: _reporting_descriptor_reference.ReportingDescriptorReference = ...
    description: _message.Message | None = ...
    kinds: List[str] = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, target, description, kinds, properties) -> None: ...
