import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _multiformat_message_string, _property_bag, _reporting_configuration, _reporting_descriptor_relationship
from typing import Any, List

@dataclasses.dataclass
class ReportingDescriptor:
    """Metadata that describes a specific report produced by the tool, as part of the analysis it provides or its runtime reporting."""
    id: str = ...
    default_configuration: _reporting_configuration.ReportingConfiguration | None = ...
    deprecated_guids: List[str] | None = ...
    deprecated_ids: List[str] | None = ...
    deprecated_names: List[str] | None = ...
    full_description: _multiformat_message_string.MultiformatMessageString | None = ...
    guid: str | None = ...
    help: _multiformat_message_string.MultiformatMessageString | None = ...
    help_uri: str | None = ...
    message_strings: Any = ...
    name: str | None = ...
    properties: _property_bag.PropertyBag | None = ...
    relationships: List[_reporting_descriptor_relationship.ReportingDescriptorRelationship] | None = ...
    short_description: _multiformat_message_string.MultiformatMessageString | None = ...
    def __init__(self, id, default_configuration, deprecated_guids, deprecated_ids, deprecated_names, full_description, guid, help, help_uri, message_strings, name, properties, relationships, short_description) -> None: ...
