import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _message, _property_bag

@dataclasses.dataclass
class RunAutomationDetails:
    """Information that describes a run's identity and role within an engineering system process."""
    correlation_guid: str | None = ...
    description: _message.Message | None = ...
    guid: str | None = ...
    id: str | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, correlation_guid, description, guid, id, properties) -> None: ...
