import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _external_properties, _property_bag, _run
from typing import List, Literal

@dataclasses.dataclass
class SarifLog:
    """Static Analysis Results Format (SARIF) Version 2.1.0 JSON Schema: a standard format for the output of static analysis tools."""
    runs: List[_run.Run] = ...
    version: Literal['2.1.0'] = ...
    schema_uri: str | None = ...
    inline_external_properties: List[_external_properties.ExternalProperties] | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, runs, version, schema_uri, inline_external_properties, properties) -> None: ...
