import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _message, _property_bag, _stack_frame
from typing import List

@dataclasses.dataclass
class Stack:
    """A call stack that is relevant to a result."""
    frames: List[_stack_frame.StackFrame] = ...
    message: _message.Message | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, frames, message, properties) -> None: ...
