import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _location, _property_bag
from typing import List

@dataclasses.dataclass
class StackFrame:
    """A function call within a stack trace."""
    location: _location.Location | None = ...
    module: str | None = ...
    parameters: List[str] | None = ...
    properties: _property_bag.PropertyBag | None = ...
    thread_id: int | None = ...
    def __init__(self, location, module, parameters, properties, thread_id) -> None: ...
