import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _location, _property_bag
from typing import Literal

@dataclasses.dataclass
class Suppression:
    """A suppression that is relevant to a result."""
    kind: Literal['inSource', 'external'] = ...
    guid: str | None = ...
    justification: str | None = ...
    location: _location.Location | None = ...
    properties: _property_bag.PropertyBag | None = ...
    state: Literal['accepted', 'underReview', 'rejected'] | None = ...
    def __init__(self, kind, guid, justification, location, properties, state) -> None: ...
