import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _location, _property_bag, _reporting_descriptor_reference, _stack, _web_request, _web_response
from typing import Any, List, Literal

@dataclasses.dataclass
class ThreadFlowLocation:
    """A location visited by an analysis tool while simulating or monitoring the execution of a program."""
    execution_order: int = ...
    execution_time_utc: str | None = ...
    importance: Literal['important', 'essential', 'unimportant'] = ...
    index: int = ...
    kinds: List[str] | None = ...
    location: _location.Location | None = ...
    module: str | None = ...
    nesting_level: int | None = ...
    properties: _property_bag.PropertyBag | None = ...
    stack: _stack.Stack | None = ...
    state: Any = ...
    taxa: List[_reporting_descriptor_reference.ReportingDescriptorReference] | None = ...
    web_request: _web_request.WebRequest | None = ...
    web_response: _web_response.WebResponse | None = ...
    def __init__(self, execution_order, execution_time_utc, importance, index, kinds, location, module, nesting_level, properties, stack, state, taxa, web_request, web_response) -> None: ...
