import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _message, _property_bag, _thread_flow_location
from typing import Any, List

@dataclasses.dataclass
class ThreadFlow:
    """Describes a sequence of code locations that specify a path through a single thread of execution such as an operating system or fiber."""
    locations: List[_thread_flow_location.ThreadFlowLocation] = ...
    id: str | None = ...
    immutable_state: Any = ...
    initial_state: Any = ...
    message: _message.Message | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, locations, id, immutable_state, initial_state, message, properties) -> None: ...
