import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _property_bag

@dataclasses.dataclass
class ToolComponentReference:
    """Identifies a particular toolComponent object, either the driver or an extension."""
    guid: str | None = ...
    index: int = ...
    name: str | None = ...
    properties: _property_bag.PropertyBag | None = ...
    def __init__(self, guid, index, name, properties) -> None: ...
