import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _artifact_location, _property_bag

@dataclasses.dataclass
class VersionControlDetails:
    """Specifies the information necessary to retrieve a desired revision from a version control system."""
    repository_uri: str = ...
    as_of_time_utc: str | None = ...
    branch: str | None = ...
    mapped_to: _artifact_location.ArtifactLocation | None = ...
    properties: _property_bag.PropertyBag | None = ...
    revision_id: str | None = ...
    revision_tag: str | None = ...
    def __init__(self, repository_uri, as_of_time_utc, branch, mapped_to, properties, revision_id, revision_tag) -> None: ...
