import dataclasses
from torch.onnx._internal.diagnostics.infra.sarif import _artifact_content, _property_bag
from typing import Any

@dataclasses.dataclass
class WebResponse:
    """Describes the response to an HTTP request."""
    body: _artifact_content.ArtifactContent | None = ...
    headers: Any = ...
    index: int = ...
    no_response_received: bool | None = ...
    properties: _property_bag.PropertyBag | None = ...
    protocol: str | None = ...
    reason_phrase: str | None = ...
    status_code: int | None = ...
    version: str | None = ...
    def __init__(self, body, headers, index, no_response_received, properties, protocol, reason_phrase, status_code, version) -> None: ...
