from _typeshed import Incomplete
from mypyc.analysis.blockfreq import frequently_executed_blocks as frequently_executed_blocks
from mypyc.codegen.emit import DEBUG_ERRORS as DEBUG_ERRORS, Emitter as Emitter, TracebackAndGotoHandler as TracebackAndGotoHandler, c_array_initializer as c_array_initializer
from mypyc.common import MODULE_PREFIX as MODULE_PREFIX, NATIVE_PREFIX as NATIVE_PREFIX, REG_PREFIX as REG_PREFIX, STATIC_PREFIX as STATIC_PREFIX, TYPE_PREFIX as TYPE_PREFIX
from mypyc.ir.class_ir import ClassIR as ClassIR
from mypyc.ir.func_ir import FUNC_CLASSMETHOD as FUNC_CLASSMETHOD, FUNC_STATICMETHOD as FUNC_STATICMETHOD, FuncDecl as FuncDecl, FuncIR as FuncIR, all_values as all_values
from mypyc.ir.ops import Assign as Assign, AssignMulti as AssignMulti, BasicBlock as BasicBlock, Box as Box, Branch as Branch, Call as Call, CallC as CallC, Cast as Cast, ComparisonOp as ComparisonOp, ControlOp as ControlOp, DecRef as DecRef, ERR_FALSE as ERR_FALSE, Extend as Extend, Float as Float, FloatComparisonOp as FloatComparisonOp, FloatNeg as FloatNeg, FloatOp as FloatOp, GetAttr as GetAttr, GetElementPtr as GetElementPtr, Goto as Goto, IncRef as IncRef, InitStatic as InitStatic, IntOp as IntOp, Integer as Integer, KeepAlive as KeepAlive, LoadAddress as LoadAddress, LoadErrorValue as LoadErrorValue, LoadGlobal as LoadGlobal, LoadLiteral as LoadLiteral, LoadMem as LoadMem, LoadStatic as LoadStatic, MethodCall as MethodCall, NAMESPACE_MODULE as NAMESPACE_MODULE, NAMESPACE_STATIC as NAMESPACE_STATIC, NAMESPACE_TYPE as NAMESPACE_TYPE, Op as Op, OpVisitor as OpVisitor, RaiseStandardError as RaiseStandardError, Register as Register, Return as Return, SetAttr as SetAttr, SetMem as SetMem, Truncate as Truncate, TupleGet as TupleGet, TupleSet as TupleSet, Unborrow as Unborrow, Unbox as Unbox, Unreachable as Unreachable, Value as Value
from mypyc.ir.pprint import generate_names_for_ir as generate_names_for_ir
from mypyc.ir.rtypes import RArray as RArray, RStruct as RStruct, RTuple as RTuple, RType as RType, is_int32_rprimitive as is_int32_rprimitive, is_int64_rprimitive as is_int64_rprimitive, is_int_rprimitive as is_int_rprimitive, is_pointer_rprimitive as is_pointer_rprimitive, is_tagged as is_tagged
from typing import Final

def native_function_type(fn: FuncIR, emitter: Emitter) -> str: ...
def native_function_header(fn: FuncDecl, emitter: Emitter) -> str: ...
def generate_native_function(fn: FuncIR, emitter: Emitter, source_path: str, module_name: str) -> None: ...

class FunctionEmitterVisitor(OpVisitor[None]):
    emitter: Incomplete
    names: Incomplete
    declarations: Incomplete
    source_path: Incomplete
    module_name: Incomplete
    literals: Incomplete
    rare: bool
    next_block: Incomplete
    ops: Incomplete
    op_index: int
    def __init__(self, emitter: Emitter, declarations: Emitter, source_path: str, module_name: str) -> None: ...
    def temp_name(self) -> str: ...
    def visit_goto(self, op: Goto) -> None: ...
    def visit_branch(self, op: Branch) -> None: ...
    def visit_return(self, op: Return) -> None: ...
    def visit_tuple_set(self, op: TupleSet) -> None: ...
    def visit_assign(self, op: Assign) -> None: ...
    def visit_assign_multi(self, op: AssignMulti) -> None: ...
    def visit_load_error_value(self, op: LoadErrorValue) -> None: ...
    def visit_load_literal(self, op: LoadLiteral) -> None: ...
    def get_attr_expr(self, obj: str, op: GetAttr | SetAttr, decl_cl: ClassIR) -> str:
        """Generate attribute accessor for normal (non-property) access.

        This either has a form like obj->attr_name for attributes defined in non-trait
        classes, and *(obj + attr_offset) for attributes defined by traits. We also
        insert all necessary C casts here.
        """
    def visit_get_attr(self, op: GetAttr) -> None: ...
    def next_branch(self) -> Branch | None: ...
    def visit_set_attr(self, op: SetAttr) -> None: ...
    PREFIX_MAP: Final[Incomplete]
    def visit_load_static(self, op: LoadStatic) -> None: ...
    def visit_init_static(self, op: InitStatic) -> None: ...
    def visit_tuple_get(self, op: TupleGet) -> None: ...
    def get_dest_assign(self, dest: Value) -> str: ...
    def visit_call(self, op: Call) -> None:
        """Call native function."""
    def visit_method_call(self, op: MethodCall) -> None:
        """Call native method."""
    def visit_inc_ref(self, op: IncRef) -> None: ...
    def visit_dec_ref(self, op: DecRef) -> None: ...
    def visit_box(self, op: Box) -> None: ...
    def visit_cast(self, op: Cast) -> None: ...
    def visit_unbox(self, op: Unbox) -> None: ...
    def visit_unreachable(self, op: Unreachable) -> None: ...
    def visit_raise_standard_error(self, op: RaiseStandardError) -> None: ...
    def visit_call_c(self, op: CallC) -> None: ...
    def visit_truncate(self, op: Truncate) -> None: ...
    def visit_extend(self, op: Extend) -> None: ...
    def visit_load_global(self, op: LoadGlobal) -> None: ...
    def visit_int_op(self, op: IntOp) -> None: ...
    def visit_comparison_op(self, op: ComparisonOp) -> None: ...
    def visit_float_op(self, op: FloatOp) -> None: ...
    def visit_float_neg(self, op: FloatNeg) -> None: ...
    def visit_float_comparison_op(self, op: FloatComparisonOp) -> None: ...
    def visit_load_mem(self, op: LoadMem) -> None: ...
    def visit_set_mem(self, op: SetMem) -> None: ...
    def visit_get_element_ptr(self, op: GetElementPtr) -> None: ...
    def visit_load_address(self, op: LoadAddress) -> None: ...
    def visit_keep_alive(self, op: KeepAlive) -> None: ...
    def visit_unborrow(self, op: Unborrow) -> None: ...
    def label(self, label: BasicBlock) -> str: ...
    def reg(self, reg: Value) -> str: ...
    def ctype(self, rtype: RType) -> str: ...
    def c_error_value(self, rtype: RType) -> str: ...
    def c_undefined_value(self, rtype: RType) -> str: ...
    def emit_line(self, line: str, *, ann: object = None) -> None: ...
    def emit_lines(self, *lines: str) -> None: ...
    def emit_inc_ref(self, dest: str, rtype: RType) -> None: ...
    def emit_dec_ref(self, dest: str, rtype: RType, is_xdec: bool) -> None: ...
    def emit_declaration(self, line: str) -> None: ...
    def emit_traceback(self, op: Branch) -> None: ...
    def emit_attribute_error(self, op: Branch, class_name: str, attr: str) -> None: ...
    def emit_signed_int_cast(self, type: RType) -> str: ...
    def emit_unsigned_int_cast(self, type: RType) -> str: ...
