from ._events import Event, InformationalResponse, Request, Response
from ._headers import Headers
from ._util import Sentinel
from typing import Any, Callable, Dict, Tuple, Type

__all__ = ['WRITERS']

Writer = Callable[[bytes], Any]

class BodyWriter:
    def __call__(self, event: Event, write: Writer) -> None: ...
    def send_data(self, data: bytes, write: Writer) -> None: ...
    def send_eom(self, headers: Headers, write: Writer) -> None: ...

class ContentLengthWriter(BodyWriter):
    def __init__(self, length: int) -> None: ...
    def send_data(self, data: bytes, write: Writer) -> None: ...
    def send_eom(self, headers: Headers, write: Writer) -> None: ...

class ChunkedWriter(BodyWriter):
    def send_data(self, data: bytes, write: Writer) -> None: ...
    def send_eom(self, headers: Headers, write: Writer) -> None: ...

class Http10Writer(BodyWriter):
    def send_data(self, data: bytes, write: Writer) -> None: ...
    def send_eom(self, headers: Headers, write: Writer) -> None: ...
WritersType = Dict[Tuple[Type[Sentinel], Type[Sentinel]] | Type[Sentinel], Dict[str, Type[BodyWriter]] | Callable[[InformationalResponse | Response, Writer], None] | Callable[[Request, Writer], None]]
WRITERS: WritersType
