from typed_ast import ast27 as ast27, ast3 as ast3

def py2to3(ast):
    """Converts a typed Python 2.7 ast to a typed Python 3.5 ast.  The returned
        ast is a valid Python 3 ast with two exceptions:

        - `arg` objects may contain Tuple objects instead of just identifiers
           in the case of Python 2 function definitions/lambdas that use the tuple
           unpacking syntax.
        - `Raise` objects will have a `traceback` attribute added if the 3
           argument version of the Python 2 raise is used.


    Strange and Rare Uncovered Edge Cases:
        - Raise: if the second argument to a raise statement is a tuple, its
          contents are unpacked as arguments to the exception constructor.  This
          case is handled correctly if it's a literal tuple, but not if it's any
          other sort of tuple expression.
    """

class _AST2To3(ast27.NodeTransformer):
    def __init__(self) -> None: ...
    def visit(self, node):
        """Visit a node."""
    def maybe_visit(self, node): ...
    def generic_visit(self, node): ...
    def visit_list(self, l): ...
    def visit_FunctionDef(self, n): ...
    def visit_ClassDef(self, n): ...
    def visit_TryExcept(self, n): ...
    def visit_TryFinally(self, n): ...
    def visit_ExceptHandler(self, n): ...
    def visit_Print(self, n): ...
    def visit_Raise(self, n): ...
    def visit_Exec(self, n): ...
    def visit_Repr(self, n): ...
    def visit_With(self, n): ...
    def visit_Call(self, n): ...
    def visit_Ellipsis(self, n): ...
    def visit_arguments(self, n): ...
    def visit_Str(self, s): ...
    def visit_Num(self, n): ...
