from _typeshed import Incomplete
from mypy.nodes import MatchStmt as MatchStmt, NameExpr as NameExpr
from mypy.patterns import AsPattern as AsPattern, ClassPattern as ClassPattern, MappingPattern as MappingPattern, OrPattern as OrPattern, Pattern as Pattern, SequencePattern as SequencePattern, SingletonPattern as SingletonPattern, ValuePattern as ValuePattern
from mypy.traverser import TraverserVisitor
from mypyc.ir.ops import BasicBlock as BasicBlock, Value as Value
from mypyc.ir.rtypes import object_rprimitive as object_rprimitive
from mypyc.irbuild.builder import IRBuilder as IRBuilder
from mypyc.primitives.dict_ops import dict_copy as dict_copy, dict_del_item as dict_del_item, mapping_has_key as mapping_has_key, supports_mapping_protocol as supports_mapping_protocol
from mypyc.primitives.generic_ops import generic_ssize_t_len_op as generic_ssize_t_len_op
from mypyc.primitives.list_ops import sequence_get_item as sequence_get_item, sequence_get_slice as sequence_get_slice, supports_sequence_protocol as supports_sequence_protocol
from mypyc.primitives.misc_ops import fast_isinstance_op as fast_isinstance_op, slow_isinstance_op as slow_isinstance_op
from typing import Generator, List, Tuple

MATCHABLE_BUILTINS: Incomplete

class MatchVisitor(TraverserVisitor):
    builder: IRBuilder
    code_block: BasicBlock
    next_block: BasicBlock
    final_block: BasicBlock
    subject: Value
    match: MatchStmt
    as_pattern: AsPattern | None
    def __init__(self, builder: IRBuilder, match_node: MatchStmt) -> None: ...
    def build_match_body(self, index: int) -> None: ...
    def visit_match_stmt(self, m: MatchStmt) -> None: ...
    def visit_value_pattern(self, pattern: ValuePattern) -> None: ...
    def visit_or_pattern(self, pattern: OrPattern) -> None: ...
    def visit_class_pattern(self, pattern: ClassPattern) -> None: ...
    def visit_as_pattern(self, pattern: AsPattern) -> None: ...
    def visit_singleton_pattern(self, pattern: SingletonPattern) -> None: ...
    def visit_mapping_pattern(self, pattern: MappingPattern) -> None: ...
    def visit_sequence_pattern(self, seq_pattern: SequencePattern) -> None: ...
    def bind_as_pattern(self, value: Value, new_block: bool = False) -> None: ...
    def enter_subpattern(self, subject: Value) -> Generator[None, None, None]: ...

def prep_sequence_pattern(seq_pattern: SequencePattern) -> Tuple[int | None, NameExpr | None, List[Pattern]]: ...
