from mypy.nodes import AssertStmt as AssertStmt, AssertTypeExpr as AssertTypeExpr, AssignmentExpr as AssignmentExpr, AssignmentStmt as AssignmentStmt, AwaitExpr as AwaitExpr, Block as Block, BreakStmt as BreakStmt, BytesExpr as BytesExpr, CallExpr as CallExpr, CastExpr as CastExpr, ClassDef as ClassDef, ComparisonExpr as ComparisonExpr, ComplexExpr as ComplexExpr, ConditionalExpr as ConditionalExpr, ContinueStmt as ContinueStmt, Decorator as Decorator, DelStmt as DelStmt, DictExpr as DictExpr, DictionaryComprehension as DictionaryComprehension, EllipsisExpr as EllipsisExpr, EnumCallExpr as EnumCallExpr, ExpressionStmt as ExpressionStmt, FloatExpr as FloatExpr, ForStmt as ForStmt, FuncDef as FuncDef, GeneratorExpr as GeneratorExpr, GlobalDecl as GlobalDecl, IfStmt as IfStmt, Import as Import, ImportAll as ImportAll, ImportFrom as ImportFrom, IndexExpr as IndexExpr, IntExpr as IntExpr, LambdaExpr as LambdaExpr, ListComprehension as ListComprehension, ListExpr as ListExpr, MatchStmt as MatchStmt, MemberExpr as MemberExpr, MypyFile as MypyFile, NameExpr as NameExpr, NamedTupleExpr as NamedTupleExpr, NewTypeExpr as NewTypeExpr, NonlocalDecl as NonlocalDecl, OpExpr as OpExpr, OperatorAssignmentStmt as OperatorAssignmentStmt, OverloadedFuncDef as OverloadedFuncDef, ParamSpecExpr as ParamSpecExpr, PassStmt as PassStmt, PromoteExpr as PromoteExpr, RaiseStmt as RaiseStmt, ReturnStmt as ReturnStmt, RevealExpr as RevealExpr, SetComprehension as SetComprehension, SetExpr as SetExpr, SliceExpr as SliceExpr, StarExpr as StarExpr, StrExpr as StrExpr, SuperExpr as SuperExpr, TempNode as TempNode, TryStmt as TryStmt, TupleExpr as TupleExpr, TypeAliasExpr as TypeAliasExpr, TypeApplication as TypeApplication, TypeVarExpr as TypeVarExpr, TypeVarTupleExpr as TypeVarTupleExpr, TypedDictExpr as TypedDictExpr, UnaryExpr as UnaryExpr, Var as Var, WhileStmt as WhileStmt, WithStmt as WithStmt, YieldExpr as YieldExpr, YieldFromExpr as YieldFromExpr
from mypyc.ir.ops import Value as Value
from mypyc.irbuild.builder import IRBuilder as IRBuilder, IRVisitor as IRVisitor, UnsupportedException as UnsupportedException
from mypyc.irbuild.classdef import transform_class_def as transform_class_def
from mypyc.irbuild.expression import transform_assignment_expr as transform_assignment_expr, transform_bytes_expr as transform_bytes_expr, transform_call_expr as transform_call_expr, transform_comparison_expr as transform_comparison_expr, transform_complex_expr as transform_complex_expr, transform_conditional_expr as transform_conditional_expr, transform_dict_expr as transform_dict_expr, transform_dictionary_comprehension as transform_dictionary_comprehension, transform_ellipsis as transform_ellipsis, transform_float_expr as transform_float_expr, transform_generator_expr as transform_generator_expr, transform_index_expr as transform_index_expr, transform_int_expr as transform_int_expr, transform_list_comprehension as transform_list_comprehension, transform_list_expr as transform_list_expr, transform_member_expr as transform_member_expr, transform_name_expr as transform_name_expr, transform_op_expr as transform_op_expr, transform_set_comprehension as transform_set_comprehension, transform_set_expr as transform_set_expr, transform_slice_expr as transform_slice_expr, transform_str_expr as transform_str_expr, transform_super_expr as transform_super_expr, transform_tuple_expr as transform_tuple_expr, transform_unary_expr as transform_unary_expr
from mypyc.irbuild.function import transform_decorator as transform_decorator, transform_func_def as transform_func_def, transform_lambda_expr as transform_lambda_expr, transform_overloaded_func_def as transform_overloaded_func_def
from mypyc.irbuild.statement import transform_assert_stmt as transform_assert_stmt, transform_assignment_stmt as transform_assignment_stmt, transform_await_expr as transform_await_expr, transform_block as transform_block, transform_break_stmt as transform_break_stmt, transform_continue_stmt as transform_continue_stmt, transform_del_stmt as transform_del_stmt, transform_expression_stmt as transform_expression_stmt, transform_for_stmt as transform_for_stmt, transform_if_stmt as transform_if_stmt, transform_import as transform_import, transform_import_all as transform_import_all, transform_import_from as transform_import_from, transform_match_stmt as transform_match_stmt, transform_operator_assignment_stmt as transform_operator_assignment_stmt, transform_raise_stmt as transform_raise_stmt, transform_return_stmt as transform_return_stmt, transform_try_stmt as transform_try_stmt, transform_while_stmt as transform_while_stmt, transform_with_stmt as transform_with_stmt, transform_yield_expr as transform_yield_expr, transform_yield_from_expr as transform_yield_from_expr
from typing import NoReturn

class IRBuilderVisitor(IRVisitor):
    """Mypy node visitor that dispatches to node transform implementations.

    This class should have no non-trivial logic.

    This visitor is separated from the rest of code to improve modularity and
    to avoid import cycles.

    This is based on the visitor pattern
    (https://en.wikipedia.org/wiki/Visitor_pattern).
    """
    builder: IRBuilder
    def visit_mypy_file(self, mypyfile: MypyFile) -> None: ...
    def visit_class_def(self, cdef: ClassDef) -> None: ...
    def visit_import(self, node: Import) -> None: ...
    def visit_import_from(self, node: ImportFrom) -> None: ...
    def visit_import_all(self, node: ImportAll) -> None: ...
    def visit_func_def(self, fdef: FuncDef) -> None: ...
    def visit_overloaded_func_def(self, o: OverloadedFuncDef) -> None: ...
    def visit_decorator(self, dec: Decorator) -> None: ...
    def visit_block(self, block: Block) -> None: ...
    def visit_expression_stmt(self, stmt: ExpressionStmt) -> None: ...
    def visit_return_stmt(self, stmt: ReturnStmt) -> None: ...
    def visit_assignment_stmt(self, stmt: AssignmentStmt) -> None: ...
    def visit_operator_assignment_stmt(self, stmt: OperatorAssignmentStmt) -> None: ...
    def visit_if_stmt(self, stmt: IfStmt) -> None: ...
    def visit_while_stmt(self, stmt: WhileStmt) -> None: ...
    def visit_for_stmt(self, stmt: ForStmt) -> None: ...
    def visit_break_stmt(self, stmt: BreakStmt) -> None: ...
    def visit_continue_stmt(self, stmt: ContinueStmt) -> None: ...
    def visit_raise_stmt(self, stmt: RaiseStmt) -> None: ...
    def visit_try_stmt(self, stmt: TryStmt) -> None: ...
    def visit_with_stmt(self, stmt: WithStmt) -> None: ...
    def visit_pass_stmt(self, stmt: PassStmt) -> None: ...
    def visit_assert_stmt(self, stmt: AssertStmt) -> None: ...
    def visit_del_stmt(self, stmt: DelStmt) -> None: ...
    def visit_global_decl(self, stmt: GlobalDecl) -> None: ...
    def visit_nonlocal_decl(self, stmt: NonlocalDecl) -> None: ...
    def visit_match_stmt(self, stmt: MatchStmt) -> None: ...
    def visit_name_expr(self, expr: NameExpr) -> Value: ...
    def visit_member_expr(self, expr: MemberExpr) -> Value: ...
    def visit_super_expr(self, expr: SuperExpr) -> Value: ...
    def visit_call_expr(self, expr: CallExpr) -> Value: ...
    def visit_unary_expr(self, expr: UnaryExpr) -> Value: ...
    def visit_op_expr(self, expr: OpExpr) -> Value: ...
    def visit_index_expr(self, expr: IndexExpr) -> Value: ...
    def visit_conditional_expr(self, expr: ConditionalExpr) -> Value: ...
    def visit_comparison_expr(self, expr: ComparisonExpr) -> Value: ...
    def visit_int_expr(self, expr: IntExpr) -> Value: ...
    def visit_float_expr(self, expr: FloatExpr) -> Value: ...
    def visit_complex_expr(self, expr: ComplexExpr) -> Value: ...
    def visit_str_expr(self, expr: StrExpr) -> Value: ...
    def visit_bytes_expr(self, expr: BytesExpr) -> Value: ...
    def visit_ellipsis(self, expr: EllipsisExpr) -> Value: ...
    def visit_list_expr(self, expr: ListExpr) -> Value: ...
    def visit_tuple_expr(self, expr: TupleExpr) -> Value: ...
    def visit_dict_expr(self, expr: DictExpr) -> Value: ...
    def visit_set_expr(self, expr: SetExpr) -> Value: ...
    def visit_list_comprehension(self, expr: ListComprehension) -> Value: ...
    def visit_set_comprehension(self, expr: SetComprehension) -> Value: ...
    def visit_dictionary_comprehension(self, expr: DictionaryComprehension) -> Value: ...
    def visit_slice_expr(self, expr: SliceExpr) -> Value: ...
    def visit_generator_expr(self, expr: GeneratorExpr) -> Value: ...
    def visit_lambda_expr(self, expr: LambdaExpr) -> Value: ...
    def visit_yield_expr(self, expr: YieldExpr) -> Value: ...
    def visit_yield_from_expr(self, o: YieldFromExpr) -> Value: ...
    def visit_await_expr(self, o: AwaitExpr) -> Value: ...
    def visit_assignment_expr(self, o: AssignmentExpr) -> Value: ...
    def visit_enum_call_expr(self, o: EnumCallExpr) -> Value: ...
    def visit__promote_expr(self, o: PromoteExpr) -> Value: ...
    def visit_namedtuple_expr(self, o: NamedTupleExpr) -> Value: ...
    def visit_newtype_expr(self, o: NewTypeExpr) -> Value: ...
    def visit_temp_node(self, o: TempNode) -> Value: ...
    def visit_type_alias_expr(self, o: TypeAliasExpr) -> Value: ...
    def visit_type_application(self, o: TypeApplication) -> Value: ...
    def visit_type_var_expr(self, o: TypeVarExpr) -> Value: ...
    def visit_paramspec_expr(self, o: ParamSpecExpr) -> Value: ...
    def visit_type_var_tuple_expr(self, o: TypeVarTupleExpr) -> Value: ...
    def visit_typeddict_expr(self, o: TypedDictExpr) -> Value: ...
    def visit_reveal_expr(self, o: RevealExpr) -> Value: ...
    def visit_var(self, o: Var) -> None: ...
    def visit_cast_expr(self, o: CastExpr) -> Value: ...
    def visit_assert_type_expr(self, o: AssertTypeExpr) -> Value: ...
    def visit_star_expr(self, o: StarExpr) -> Value: ...
    def bail(self, msg: str, line: int) -> NoReturn:
        """Reports an error and aborts compilation up until the last accept() call

        (accept() catches the UnsupportedException and keeps on
        processing. This allows errors to be non-blocking without always
        needing to write handling for them.
        """
