from _typeshed import Incomplete
from torch.autograd import profiler as profiler
from torch.utils.collect_env import get_env_info as get_env_info

def redirect_argv(new_argv) -> None: ...
def compiled_with_cuda(sysinfo): ...

env_summary: Incomplete

def run_env_analysis(): ...
def run_cprofile(code, globs, launch_blocking: bool = False): ...

cprof_summary: Incomplete

def print_cprofile_summary(prof, sortby: str = 'tottime', topk: int = 15) -> None: ...
def run_autograd_prof(code, globs): ...

autograd_prof_summary: Incomplete

def print_autograd_prof_summary(prof, mode, sortby: str = 'cpu_time', topk: int = 15): ...

descript: Incomplete

def parse_args(): ...
def cpu_time_total(autograd_prof): ...
def main() -> None: ...
