from _typeshed import Incomplete
from torch.distributed._shard.sharded_tensor import ShardedTensor as ShardedTensor

def binary_cmp(cmp_fun, types, args, kwargs: Incomplete | None = None, process_group: Incomplete | None = None): ...
def equal(types, args, kwargs, process_group): ...
def allclose(types, args, kwargs, process_group): ...
