from _typeshed import Incomplete
from torch.distributed import rpc as rpc
from torch.testing._internal.common_distributed import MultiProcessTestCase as MultiProcessTestCase, TEST_SKIPS as TEST_SKIPS, tp_transports as tp_transports

TEST_GPU_NUM: int

class ShardedTensorTestBase(MultiProcessTestCase):
    @property
    def world_size(self): ...
    def init_pg(self, backend: str = 'nccl') -> None: ...
    def init_rpc(self) -> None: ...
    def init_comms(self, init_rpc: bool = True, backend: str = 'nccl') -> None: ...
    def destroy_comms(self, destroy_rpc: bool = True) -> None: ...
    def setUp(self) -> None: ...
    def assert_sharded_tensor_equal(self, st1, st2) -> None: ...

def with_comms(func: Incomplete | None = None, init_rpc: bool = True, backend: str = 'nccl'): ...
