import collections.abc
from _typeshed import Incomplete
from typing import NamedTuple

__all__ = ['Cache', 'FIFOCache', 'LFUCache', 'LRUCache', 'MRUCache', 'RRCache', 'TLRUCache', 'TTLCache', 'cached', 'cachedmethod']

class _DefaultSize:
    def __getitem__(self, _): ...
    def __setitem__(self, _, value) -> None: ...
    def pop(self, _): ...

class Cache(collections.abc.MutableMapping):
    """Mutable mapping to serve as a simple cache or cache base class."""
    def __init__(self, maxsize, getsizeof: Incomplete | None = None) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, key) -> bool: ...
    def __missing__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def get(self, key, default: Incomplete | None = None): ...
    def pop(self, key, default=...): ...
    def setdefault(self, key, default: Incomplete | None = None): ...
    @property
    def maxsize(self):
        """The maximum size of the cache."""
    @property
    def currsize(self):
        """The current size of the cache."""
    @staticmethod
    def getsizeof(value):
        """Return the size of a cache element's value."""

class FIFOCache(Cache):
    """First In First Out (FIFO) cache implementation."""
    def __init__(self, maxsize, getsizeof: Incomplete | None = None) -> None: ...
    def __setitem__(self, key, value, cache_setitem=...) -> None: ...
    def __delitem__(self, key, cache_delitem=...) -> None: ...
    def popitem(self):
        """Remove and return the `(key, value)` pair first inserted."""

class LFUCache(Cache):
    """Least Frequently Used (LFU) cache implementation."""
    def __init__(self, maxsize, getsizeof: Incomplete | None = None) -> None: ...
    def __getitem__(self, key, cache_getitem=...): ...
    def __setitem__(self, key, value, cache_setitem=...) -> None: ...
    def __delitem__(self, key, cache_delitem=...) -> None: ...
    def popitem(self):
        """Remove and return the `(key, value)` pair least frequently used."""

class LRUCache(Cache):
    """Least Recently Used (LRU) cache implementation."""
    def __init__(self, maxsize, getsizeof: Incomplete | None = None) -> None: ...
    def __getitem__(self, key, cache_getitem=...): ...
    def __setitem__(self, key, value, cache_setitem=...) -> None: ...
    def __delitem__(self, key, cache_delitem=...) -> None: ...
    def popitem(self):
        """Remove and return the `(key, value)` pair least recently used."""

class MRUCache(Cache):
    """Most Recently Used (MRU) cache implementation."""
    def __init__(self, maxsize, getsizeof: Incomplete | None = None) -> None: ...
    def __getitem__(self, key, cache_getitem=...): ...
    def __setitem__(self, key, value, cache_setitem=...) -> None: ...
    def __delitem__(self, key, cache_delitem=...) -> None: ...
    def popitem(self):
        """Remove and return the `(key, value)` pair most recently used."""

class RRCache(Cache):
    """Random Replacement (RR) cache implementation."""
    def __init__(self, maxsize, choice=..., getsizeof: Incomplete | None = None) -> None: ...
    @property
    def choice(self):
        """The `choice` function used by the cache."""
    def popitem(self):
        """Remove and return a random `(key, value)` pair."""

class _TimedCache(Cache):
    """Base class for time aware cache implementations."""
    class _Timer:
        def __init__(self, timer) -> None: ...
        def __call__(self): ...
        def __enter__(self): ...
        def __exit__(self, *exc) -> None: ...
        def __reduce__(self): ...
        def __getattr__(self, name): ...
    def __init__(self, maxsize, timer=..., getsizeof: Incomplete | None = None) -> None: ...
    def __len__(self, cache_len=...) -> int: ...
    @property
    def currsize(self): ...
    @property
    def timer(self):
        """The timer function used by the cache."""
    def clear(self) -> None: ...
    def get(self, *args, **kwargs): ...
    def pop(self, *args, **kwargs): ...
    def setdefault(self, *args, **kwargs): ...

class TTLCache(_TimedCache):
    """LRU Cache implementation with per-item time-to-live (TTL) value."""
    class _Link:
        key: Incomplete
        expires: Incomplete
        def __init__(self, key: Incomplete | None = None, expires: Incomplete | None = None) -> None: ...
        def __reduce__(self): ...
        def unlink(self) -> None: ...
    def __init__(self, maxsize, ttl, timer=..., getsizeof: Incomplete | None = None) -> None: ...
    def __contains__(self, key) -> bool: ...
    def __getitem__(self, key, cache_getitem=...): ...
    def __setitem__(self, key, value, cache_setitem=...) -> None: ...
    def __delitem__(self, key, cache_delitem=...) -> None: ...
    def __iter__(self): ...
    @property
    def ttl(self):
        """The time-to-live value of the cache's items."""
    def expire(self, time: Incomplete | None = None) -> None:
        """Remove expired items from the cache."""
    def popitem(self):
        """Remove and return the `(key, value)` pair least recently used that
        has not already expired.

        """

class TLRUCache(_TimedCache):
    """Time aware Least Recently Used (TLRU) cache implementation."""
    class _Item:
        key: Incomplete
        expires: Incomplete
        removed: bool
        def __init__(self, key: Incomplete | None = None, expires: Incomplete | None = None) -> None: ...
        def __lt__(self, other): ...
    def __init__(self, maxsize, ttu, timer=..., getsizeof: Incomplete | None = None) -> None: ...
    def __contains__(self, key) -> bool: ...
    def __getitem__(self, key, cache_getitem=...): ...
    def __setitem__(self, key, value, cache_setitem=...) -> None: ...
    def __delitem__(self, key, cache_delitem=...) -> None: ...
    def __iter__(self): ...
    @property
    def ttu(self):
        """The local time-to-use function used by the cache."""
    def expire(self, time: Incomplete | None = None) -> None:
        """Remove expired items from the cache."""
    def popitem(self):
        """Remove and return the `(key, value)` pair least recently used that
        has not already expired.

        """

class _CacheInfo(NamedTuple):
    hits: Incomplete
    misses: Incomplete
    maxsize: Incomplete
    currsize: Incomplete

def cached(cache, key=..., lock: Incomplete | None = None, info: bool = False):
    """Decorator to wrap a function with a memoizing callable that saves
    results in a cache.

    """
def cachedmethod(cache, key=..., lock: Incomplete | None = None):
    """Decorator to wrap a class or instance method with a memoizing
    callable that saves results in a cache.

    """
