from _typeshed import Incomplete
from jedi import debug as debug
from jedi.inference.base_value import ValueSet as ValueSet, ValueWrapper as ValueWrapper, iterator_to_value_set as iterator_to_value_set
from jedi.inference.cache import inference_state_function_cache as inference_state_function_cache
from jedi.inference.compiled.value import EmptyCompiledName as EmptyCompiledName
from jedi.inference.filters import AttributeOverwrite as AttributeOverwrite, DictFilter as DictFilter
from jedi.inference.gradual.base import GenericClass as GenericClass
from jedi.inference.gradual.generics import TupleGenericManager as TupleGenericManager
from jedi.inference.names import BaseTreeParamName as BaseTreeParamName, NameWrapper as NameWrapper
from jedi.inference.signature import AbstractSignature as AbstractSignature
from jedi.inference.value.instance import TreeInstance as TreeInstance
from jedi.inference.value.klass import ClassMixin as ClassMixin

mapping: Incomplete

class DjangoModelName(NameWrapper):
    def __init__(self, cls, name, is_instance) -> None: ...
    def infer(self): ...

def is_django_model_base(value): ...
def get_metaclass_filters(func): ...
def tree_name_to_values(func): ...
def get_metaclass_signatures(func): ...

class ManagerWrapper(ValueWrapper):
    def py__getitem__(self, index_value_set, contextualized_node): ...

class GenericManagerWrapper(AttributeOverwrite, ClassMixin):
    def py__get__on_class(self, calling_instance, instance, class_value): ...
    def with_generics(self, generics_tuple): ...

class FieldWrapper(ValueWrapper):
    def py__getitem__(self, index_value_set, contextualized_node): ...

class GenericFieldWrapper(AttributeOverwrite, ClassMixin):
    def py__get__on_class(self, calling_instance, instance, class_value): ...

class DjangoModelSignature(AbstractSignature):
    def __init__(self, value, field_names) -> None: ...
    def get_param_names(self, resolve_stars: bool = False): ...

class DjangoParamName(BaseTreeParamName):
    def __init__(self, field_name) -> None: ...
    def get_kind(self): ...
    def infer(self): ...

class QuerySetMethodWrapper(ValueWrapper):
    def __init__(self, method, model_cls) -> None: ...
    def py__get__(self, instance, class_value): ...

class QuerySetBoundMethodWrapper(ValueWrapper):
    def __init__(self, method, model_cls) -> None: ...
    def get_signatures(self): ...
