from jedi.inference.base_value import NO_VALUES as NO_VALUES, ValueSet as ValueSet
from jedi.inference.cache import inference_state_method_cache as inference_state_method_cache
from jedi.inference.filters import ParserTreeFilter as ParserTreeFilter
from jedi.inference.helpers import infer_call_of_leaf as infer_call_of_leaf
from jedi.inference.imports import goto_import as goto_import, load_module_from_path as load_module_from_path

def execute(callback): ...
def infer_anonymous_param(func): ...
def goto_anonymous_param(func): ...
def complete_param_names(func): ...

class FixtureFilter(ParserTreeFilter): ...
