from . import config as config, utils as utils
from _typeshed import Incomplete
from torch import Tensor as Tensor
from torch._decomp import core_aten_decompositions as core_aten_decompositions, get_decompositions as get_decompositions
from torch._decomp.decompositions import pw_cast_for_opmath as pw_cast_for_opmath
from torch.utils._mode_utils import no_dispatch as no_dispatch

log: Incomplete
aten: Incomplete
inductor_decompositions: Incomplete
decompositions: Incomplete

def register_decomposition(ops): ...
def clamp(x, min: Incomplete | None = None, max: Incomplete | None = None): ...
def floordiv(a, b): ...
def get_alignment_size(x): ...
def check_device(a: Tensor, b: Tensor): ...
def get_padded_length(x, alignment_size): ...
def pad_dim(x, padded_length, dim): ...
def addmm(input, mat1, mat2, *, beta: int = 1, alpha: int = 1): ...
def pad_addmm(input, mat1, mat2, m_padded_length, k_padded_length, n_padded_length): ...
def should_pad_bench(mat1, mat2, op, input: Incomplete | None = None): ...
def mm_decomp(mat1, mat2): ...
def pad_mm(mat1, mat2, m_padded_length, k_padded_length, n_padded_length): ...
def bmm_decomp(mat1, mat2): ...
def pad_bmm(mat1, mat2, m_padded_length, k_padded_length, n_padded_length): ...
def convolution_backward(grad_output, input, weight, bias_sizes, stride, padding, dilation, transposed, output_padding, groups, output_mask): ...
def log2(x): ...
def round_dec(x, decimals: int = 0): ...
def all(input): ...
def all_dim(input, dim, keeepdim: bool = False): ...
def copy(self, src, non_blocking: bool = False): ...
def baddbmm(self, batch1, batch2, beta: int = 1, alpha: int = 1): ...
def conj_physical(self): ...
def lift(self): ...
def bernoulli(self, *, generator: Incomplete | None = None): ...

extra_random_decomps: Incomplete
register_extra_random_decomp: Incomplete

def bernoulli_(self, p: float = 0.5): ...
def bernoulli_p(self, p: float = 0.5, *, generator: Incomplete | None = None): ...
def fast_random_decomps(): ...
def select_decomp_table():
    """decomps can change based on config"""
