class OperatorIssue(RuntimeError):
    @staticmethod
    def operator_str(target, args, kwargs): ...

class MissingOperatorWithoutDecomp(OperatorIssue):
    def __init__(self, target, args, kwargs) -> None: ...

class MissingOperatorWithDecomp(OperatorIssue):
    def __init__(self, target, args, kwargs) -> None: ...

class LoweringException(OperatorIssue):
    def __init__(self, exc, target, args, kwargs) -> None: ...

class InvalidCxxCompiler(RuntimeError):
    def __init__(self) -> None: ...

class CppCompileError(RuntimeError):
    def __init__(self, cmd, output) -> None: ...
