from .cells import cell_len as cell_len
from .console import Console as Console, ConsoleOptions as ConsoleOptions, JustifyMethod as JustifyMethod, OverflowMethod as OverflowMethod, RenderResult as RenderResult, RenderableType as RenderableType
from .measure import Measurement as Measurement
from .text import Text as Text
from typing import Iterable, Iterator, List, TypeVar, overload

T = TypeVar('T')

class Renderables:
    """A list subclass which renders its contents to the console."""
    def __init__(self, renderables: Iterable['RenderableType'] | None = None) -> None: ...
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        """Console render method to insert line-breaks."""
    def __rich_measure__(self, console: Console, options: ConsoleOptions) -> Measurement: ...
    def append(self, renderable: RenderableType) -> None: ...
    def __iter__(self) -> Iterable['RenderableType']: ...

class Lines:
    """A list subclass which can render to the console."""
    def __init__(self, lines: Iterable['Text'] = ()) -> None: ...
    def __iter__(self) -> Iterator['Text']: ...
    @overload
    def __getitem__(self, index: int) -> Text: ...
    @overload
    def __getitem__(self, index: slice) -> List['Text']: ...
    def __setitem__(self, index: int, value: Text) -> Lines: ...
    def __len__(self) -> int: ...
    def __rich_console__(self, console: Console, options: ConsoleOptions) -> RenderResult:
        """Console render method to insert line-breaks."""
    def append(self, line: Text) -> None: ...
    def extend(self, lines: Iterable['Text']) -> None: ...
    def pop(self, index: int = -1) -> Text: ...
    def justify(self, console: Console, width: int, justify: JustifyMethod = 'left', overflow: OverflowMethod = 'fold') -> None:
        '''Justify and overflow text to a given width.

        Args:
            console (Console): Console instance.
            width (int): Number of characters per line.
            justify (str, optional): Default justify method for text: "left", "center", "full" or "right". Defaults to "left".
            overflow (str, optional): Default overflow for text: "crop", "fold", or "ellipsis". Defaults to "fold".

        '''
