from _typeshed import Incomplete
from collections.abc import Generator
from parso import file_io

class AbstractFolderIO:
    path: Incomplete
    def __init__(self, path) -> None: ...
    def get_base_name(self) -> None: ...
    def list(self) -> None: ...
    def get_file_io(self, name) -> None: ...
    def get_parent_folder(self) -> None: ...

class FolderIO(AbstractFolderIO):
    def get_base_name(self): ...
    def list(self): ...
    def get_file_io(self, name): ...
    def get_parent_folder(self): ...
    def walk(self) -> Generator[Incomplete, None, None]: ...

class FileIOFolderMixin:
    def get_parent_folder(self): ...

class ZipFileIO(file_io.KnownContentFileIO, FileIOFolderMixin):
    """For .zip and .egg archives"""
    def __init__(self, path, code, zip_path) -> None: ...
    def get_last_modified(self): ...

class FileIO(file_io.FileIO, FileIOFolderMixin): ...
class KnownContentFileIO(file_io.KnownContentFileIO, FileIOFolderMixin): ...
