from transformers import NystromformerConfig as NystromformerConfig, NystromformerForMaskedLM as NystromformerForMaskedLM

def rename_key(orig_key): ...
def convert_checkpoint_helper(config, orig_state_dict): ...
def convert_nystromformer_checkpoint(checkpoint_path, nystromformer_config_file, pytorch_dump_path) -> None: ...
