from _typeshed import Incomplete
from absl.testing import parameterized
from rouge_score import rouge_scorer as rouge_scorer, test_util as test_util, tokenizers as tokenizers

class RougeScorerTest(parameterized.TestCase):
    targets: Incomplete
    predictions: Incomplete
    def setUp(self) -> None: ...
    def testInvalidRougeTypes(self, rouge_type) -> None: ...
    def testValidRougeTypes(self, rouge_type) -> None: ...
    def testRouge1(self) -> None: ...
    def testRouge1Multi(self) -> None: ...
    def testRougeAllMulti(self) -> None: ...
    def testRougeEmpty(self, rouge_type) -> None: ...
    def testRouge2(self) -> None: ...
    def testRougeLConsecutive(self) -> None: ...
    def testRougeLNonConsecutive(self) -> None: ...
    def testMultipleRougeTypes(self) -> None: ...
    def testRouge1AgainstRouge155(self) -> None: ...
    def testRouge1AgainstRouge155WithStemming(self) -> None: ...
    def testRouge2AgainstRouge155(self) -> None: ...
    def testRouge2AgainstRouge155WithStemming(self) -> None: ...
    def testRougeLAgainstRouge155(self) -> None: ...
    def testRougeLSumAgainstRouge155WithStemming(self) -> None: ...
    def testRougeLSumSentenceSplitting(self) -> None: ...
    def testLcsTable(self): ...
    def testUnionLcs(self) -> None: ...
    def testSummaryLevelLcs(self) -> None: ...
    def testRougeLsum(self) -> None: ...
    def testRougeLsumLarge(self) -> None: ...
    def testRougeTokenizerInit(self) -> None: ...
