from mlflow.exceptions import MlflowException as MlflowException
from mlflow.utils.uri import get_databricks_profile_uri_from_artifact_uri as get_databricks_profile_uri_from_artifact_uri, is_databricks_uri as is_databricks_uri
from typing import NamedTuple

def is_using_databricks_registry(uri): ...

class ParsedModelUri(NamedTuple):
    name: str
    version: str | None = ...
    stage: str | None = ...
    alias: str | None = ...

def get_model_name_and_version(client, models_uri): ...
