from numpy.typing import ArrayLike as ArrayLike

def l2(x: ArrayLike, y: ArrayLike) -> float: ...
def cosine(x: ArrayLike, y: ArrayLike) -> float: ...
def ip(x: ArrayLike, y: ArrayLike) -> float: ...
