from torchgen import gen as gen
from torchgen.context import native_function_manager as native_function_manager
from torchgen.model import DispatchKey as DispatchKey, NativeFunctionsGroup as NativeFunctionsGroup, NativeFunctionsViewGroup as NativeFunctionsViewGroup
from torchgen.static_runtime import config as config, generator as generator
from typing import Sequence, TypeVar

NativeGroupT = TypeVar('NativeGroupT', bound=NativeFunctionsGroup | NativeFunctionsViewGroup)

def group_functions_by_op_name(grouped_native_functions: Sequence[NativeGroupT]) -> Sequence[Sequence[NativeGroupT]]: ...
def clang_format(cpp_file_path: str) -> None: ...
def write_cpp(cpp_ops: Sequence[str], file_path: str) -> None: ...
def write_test_cpp(cpp_ops: Sequence[str], file_path: str) -> None: ...
def main() -> None: ...
