from ..core import BaseRenderer as BaseRenderer
from ..util import safe_entity as safe_entity, striptags as striptags
from _typeshed import Incomplete

class HTMLRenderer(BaseRenderer):
    """A renderer for converting Markdown to HTML."""
    NAME: str
    HARMFUL_PROTOCOLS: Incomplete
    GOOD_DATA_PROTOCOLS: Incomplete
    def __init__(self, escape: bool = True, allow_harmful_protocols: Incomplete | None = None) -> None: ...
    def render_token(self, token, state): ...
    def safe_url(self, url: str) -> str:
        """Ensure the given URL is safe. This method is used for rendering
        links, images, and etc.
        """
    def text(self, text: str) -> str: ...
    def emphasis(self, text: str) -> str: ...
    def strong(self, text: str) -> str: ...
    def link(self, text: str, url: str, title: Incomplete | None = None) -> str: ...
    def image(self, text: str, url: str, title: Incomplete | None = None) -> str: ...
    def codespan(self, text: str) -> str: ...
    def linebreak(self) -> str: ...
    def softbreak(self) -> str: ...
    def inline_html(self, html: str) -> str: ...
    def paragraph(self, text: str) -> str: ...
    def heading(self, text: str, level: int, **attrs) -> str: ...
    def blank_line(self) -> str: ...
    def thematic_break(self) -> str: ...
    def block_text(self, text: str) -> str: ...
    def block_code(self, code: str, info: Incomplete | None = None) -> str: ...
    def block_quote(self, text: str) -> str: ...
    def block_html(self, html: str) -> str: ...
    def block_error(self, text: str) -> str: ...
    def list(self, text: str, ordered: bool, **attrs) -> str: ...
    def list_item(self, text: str) -> str: ...
