from transformers import VideoMAEConfig as VideoMAEConfig, VideoMAEFeatureExtractor as VideoMAEFeatureExtractor, VideoMAEForPreTraining as VideoMAEForPreTraining, VideoMAEForVideoClassification as VideoMAEForVideoClassification

def get_videomae_config(model_name): ...
def rename_key(name): ...
def convert_state_dict(orig_state_dict, config): ...
def prepare_video(): ...
def convert_videomae_checkpoint(checkpoint_url, pytorch_dump_folder_path, model_name, push_to_hub) -> None: ...
