import os
from _typeshed import Incomplete
from responses import BaseResponse as BaseResponse, FirstMatchRegistry as FirstMatchRegistry, HTTPAdapter as HTTPAdapter, PreparedRequest as PreparedRequest, RequestsMock as RequestsMock, Response as Response, _F, models as models
from responses.registries import OrderedRegistry as OrderedRegistry
from typing import Any, Callable, List, Type

class Recorder(RequestsMock):
    def __init__(self, *, target: str = 'requests.adapters.HTTPAdapter.send', registry: Type[FirstMatchRegistry] = ...) -> None: ...
    def reset(self) -> None: ...
    def record(self, *, file_path: str | bytes | os.PathLike[Any] = 'response.yaml') -> Callable[[_F], _F] | _F: ...
    def dump_to_file(self, *, file_path: str | bytes | os.PathLike[Any], registered: List[BaseResponse]) -> None: ...
    def stop(self, allow_assert: bool = True) -> None: ...

recorder: Incomplete
record: Incomplete
