from openai.upload_progress import BufferReader as BufferReader
from openai.validators import apply_necessary_remediation as apply_necessary_remediation, apply_validators as apply_validators, get_validators as get_validators, read_any_format as read_any_format, write_out_file as write_out_file

class bcolors:
    HEADER: str
    OKBLUE: str
    OKGREEN: str
    WARNING: str
    FAIL: str
    ENDC: str
    BOLD: str
    UNDERLINE: str

def organization_info(obj): ...
def display(obj) -> None: ...
def display_error(e) -> None: ...

class Engine:
    @classmethod
    def get(cls, args) -> None: ...
    @classmethod
    def update(cls, args) -> None: ...
    @classmethod
    def generate(cls, args) -> None: ...
    @classmethod
    def list(cls, args) -> None: ...

class ChatCompletion:
    @classmethod
    def create(cls, args): ...

class Completion:
    @classmethod
    def create(cls, args): ...

class Deployment:
    @classmethod
    def get(cls, args) -> None: ...
    @classmethod
    def delete(cls, args) -> None: ...
    @classmethod
    def list(cls, args) -> None: ...
    @classmethod
    def create(cls, args) -> None: ...

class Model:
    @classmethod
    def get(cls, args) -> None: ...
    @classmethod
    def delete(cls, args) -> None: ...
    @classmethod
    def list(cls, args) -> None: ...

class File:
    @classmethod
    def create(cls, args) -> None: ...
    @classmethod
    def get(cls, args) -> None: ...
    @classmethod
    def delete(cls, args) -> None: ...
    @classmethod
    def list(cls, args) -> None: ...

class Image:
    @classmethod
    def create(cls, args) -> None: ...
    @classmethod
    def create_variation(cls, args) -> None: ...
    @classmethod
    def create_edit(cls, args) -> None: ...

class Audio:
    @classmethod
    def transcribe(cls, args) -> None: ...
    @classmethod
    def translate(cls, args) -> None: ...

class FineTune:
    @classmethod
    def list(cls, args) -> None: ...
    @classmethod
    def create(cls, args) -> None: ...
    @classmethod
    def get(cls, args) -> None: ...
    @classmethod
    def results(cls, args) -> None: ...
    @classmethod
    def events(cls, args) -> None: ...
    @classmethod
    def follow(cls, args) -> None: ...
    @classmethod
    def cancel(cls, args) -> None: ...
    @classmethod
    def delete(cls, args) -> None: ...
    @classmethod
    def prepare_data(cls, args) -> None: ...

class WandbLogger:
    @classmethod
    def sync(cls, args) -> None: ...

def tools_register(parser) -> None: ...
def api_register(parser) -> None: ...
def wandb_register(parser) -> None: ...
