from _typeshed import Incomplete

class OpenAIResponse:
    data: Incomplete
    def __init__(self, data, headers) -> None: ...
    @property
    def request_id(self) -> str | None: ...
    @property
    def retry_after(self) -> int | None: ...
    @property
    def operation_location(self) -> str | None: ...
    @property
    def organization(self) -> str | None: ...
    @property
    def response_ms(self) -> int | None: ...
