import io
from _typeshed import Incomplete

class CancelledError(Exception):
    msg: Incomplete
    def __init__(self, msg) -> None: ...

class BufferReader(io.BytesIO):
    def __init__(self, buf: bytes = b'', desc: Incomplete | None = None) -> None: ...
    def __len__(self) -> int: ...
    def read(self, n: int = -1): ...

def progress(total, desc): ...
def MB(i): ...
