from _typeshed import Incomplete
from dash.testing.errors import TestingTimeoutError as TestingTimeoutError

logger: Incomplete

def until(wait_cond, timeout, poll: float = 0.1, msg: str = 'expected condition not met within timeout'): ...
def until_not(wait_cond, timeout, poll: float = 0.1, msg: str = 'expected condition met within timeout'): ...

class contains_text:
    selector: Incomplete
    text: Incomplete
    timeout: Incomplete
    def __init__(self, selector, text, timeout) -> None: ...
    def __call__(self, driver): ...
    def message(self, driver): ...

class contains_class:
    selector: Incomplete
    classname: Incomplete
    def __init__(self, selector, classname) -> None: ...
    def __call__(self, driver): ...

class text_to_equal:
    selector: Incomplete
    text: Incomplete
    timeout: Incomplete
    def __init__(self, selector, text, timeout) -> None: ...
    def __call__(self, driver): ...
    def message(self, driver): ...

class style_to_equal:
    selector: Incomplete
    style: Incomplete
    val: Incomplete
    def __init__(self, selector, style, val) -> None: ...
    def __call__(self, driver): ...

class class_to_equal:
    selector: Incomplete
    classname: Incomplete
    def __init__(self, selector, classname) -> None: ...
    def __call__(self, driver): ...
