from _typeshed import Incomplete
from sympy.core.cache import USE_CACHE as USE_CACHE, clear_cache as clear_cache
from sympy.external.gmpy import GROUND_TYPES as GROUND_TYPES, HAS_GMPY as HAS_GMPY
from sympy.external.importtools import version_tuple as version_tuple
from sympy.utilities.misc import ARCH as ARCH

sp: Incomplete

def process_split(config, items) -> None: ...
def pytest_report_header(config): ...
def pytest_terminal_summary(terminalreporter) -> None: ...
def pytest_addoption(parser) -> None: ...
def pytest_collection_modifyitems(config, items) -> None:
    """ pytest hook. """
def file_clear_cache() -> None: ...
def check_disabled(request) -> None: ...
