import numpy as np
from pandas._typing import npt as npt
from pandas.core.dtypes.common import is_bool_dtype as is_bool_dtype, is_float_dtype as is_float_dtype, is_integer_dtype as is_integer_dtype

def cumsum(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = True): ...
def cumprod(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = True): ...
def cummin(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = True): ...
def cummax(values: np.ndarray, mask: npt.NDArray[np.bool_], *, skipna: bool = True): ...
