from _typeshed import Incomplete
from debugpy import adapter as adapter, common as common
from debugpy.adapter import components as components, servers as servers
from debugpy.common import log as log, messaging as messaging, sockets as sockets

class Launcher(components.Component):
    """Handles the launcher side of a debug session."""
    message_handler: Incomplete
    pid: Incomplete
    exit_code: Incomplete
    def __init__(self, session, stream) -> None: ...
    def process_event(self, event) -> None: ...
    def output_event(self, event) -> None: ...
    def exited_event(self, event) -> None: ...
    def terminated_event(self, event) -> None: ...
    def terminate_debuggee(self) -> None: ...

def spawn_debuggee(session, start_request, python, launcher_path, adapter_host, args, shell_expand_args, cwd, console, console_title, sudo): ...
