from _typeshed import Incomplete
from jax import config as config
from jax._src import array as array, test_util as jtu
from jax.experimental.array_serialization import serialization as serialization
from jax.sharding import GSPMDSharding as GSPMDSharding, NamedSharding as NamedSharding

prev_xla_flags: Incomplete

def setUpModule() -> None: ...
def tearDownModule() -> None: ...

class CheckpointTest(jtu.JaxTestCase):
    def test_memory_consumption(self): ...
    def test_checkpointing_with_path_variant(self): ...
    def test_checkpointing_jax_array(self): ...
    def test_checkpointing_with_bigger_shape_jax_array(self): ...
    def test_checkpointing_scalar_jax_array(self): ...
    def test_deserialize_tensorstore_array_jax_array(self) -> None: ...
    def test_spec_has_metadata(self) -> None: ...
    def test_spec_has_no_metadata(self) -> None: ...
    def test_empty_spec_has_no_metadata(self) -> None: ...
    def test_get_tensorstore_spec_ocdbt(self, path) -> None: ...
    def test_get_tensorstore_spec_not_absolute_path(self) -> None: ...
