from django.http.response import HttpResponse as HttpResponse
from sentry_sdk import Hub as Hub
from sentry_sdk._types import TYPE_CHECKING as TYPE_CHECKING
from sentry_sdk.consts import OP as OP
from sentry_sdk.integrations.asgi import SentryAsgiMiddleware as SentryAsgiMiddleware
from typing import Any

def patch_django_asgi_handler_impl(cls) -> None: ...
def patch_get_response_async(cls, _before_get_response: Any) -> None: ...
def patch_channels_asgi_handler_impl(cls) -> None: ...
def wrap_async_view(hub: Hub, callback: Any) -> Any: ...
