from _typeshed import Incomplete
from transformers import DPTConfig as DPTConfig, DPTFeatureExtractor as DPTFeatureExtractor, DPTForDepthEstimation as DPTForDepthEstimation, DPTForSemanticSegmentation as DPTForSemanticSegmentation
from transformers.utils import logging as logging

logger: Incomplete

def get_dpt_config(checkpoint_url): ...
def remove_ignore_keys_(state_dict) -> None: ...
def rename_key(name): ...
def read_in_q_k_v(state_dict, config) -> None: ...
def prepare_img(): ...
def convert_dpt_checkpoint(checkpoint_url, pytorch_dump_folder_path, push_to_hub, model_name) -> None:
    """
    Copy/paste/tweak model's weights to our DPT structure.
    """
