from .common import CPython, CPythonPosix
from .cpython3 import CPython3
from _typeshed import Incomplete
from abc import ABCMeta, abstractmethod
from collections.abc import Generator

__all__ = ['CPythonmacOsFramework', 'CPython3macOsFramework']

class CPythonmacOsFramework(CPython, metaclass=ABCMeta):
    @classmethod
    def can_describe(cls, interpreter): ...
    def create(self) -> None: ...
    @abstractmethod
    def current_mach_o_image_path(self): ...
    @abstractmethod
    def desired_mach_o_image_path(self): ...

class CPython3macOsFramework(CPythonmacOsFramework, CPython3, CPythonPosix):
    def current_mach_o_image_path(self): ...
    def desired_mach_o_image_path(self): ...
    @classmethod
    def sources(cls, interpreter) -> Generator[Incomplete, Incomplete, Incomplete]: ...
    @property
    def reload_code(self): ...
