from _typeshed import Incomplete
from torch._guards import Source as Source
from torch.multiprocessing.reductions import StorageWeakRef as StorageWeakRef
from torch.utils.weak import WeakIdRef as WeakIdRef

def safe_is_leaf(t): ...
def safe_grad(t): ...
def assert_eq(a, b) -> None: ...
def assert_metadata_eq(assert_eq, m1, m2, *, skip_symbolic: bool = False): ...

class MetaConverter:
    storage_memo: Incomplete
    tensor_memo: Incomplete
    maybe_storages_to_delete: Incomplete
    check_expired_frequency: int
    check_expired_count: int
    hit: int
    miss: int
    del_hook: Incomplete
    arg_cnt: int
    def __init__(self) -> None: ...
    def successful(self): ...
    def check_for_expired_weak_storages(self) -> None: ...
    def get_tensor_memo(self, t): ...
    def set_tensor_memo(self, t, v) -> None: ...
    def meta_storage(self, s, callback): ...
    def meta_tensor(self, t, shape_env: Incomplete | None = None, callback=..., source: Source | None = None): ...
    def __call__(self, t, shape_env: Incomplete | None = None, *, callback=..., ignore_subclass: bool = False, source: Incomplete | None = None): ...
