from tflite_runtime import metrics_interface as metrics_interface
from typing import Optional, Text

class TFLiteMetrics(metrics_interface.TFLiteMetricsInterface):
    """TFLite metrics helper."""
    def __init__(self, model_hash: Optional[Text] = None, model_path: Optional[Text] = None) -> None: ...
    def increase_counter_debugger_creation(self) -> None: ...
    def increase_counter_interpreter_creation(self) -> None: ...
    def increase_counter_converter_attempt(self) -> None: ...
    def increase_counter_converter_success(self) -> None: ...
    def set_converter_param(self, name, value) -> None: ...
    def set_converter_error(self, error_data) -> None: ...
    def set_converter_latency(self, value) -> None: ...

class TFLiteConverterMetrics(TFLiteMetrics):
    """Similar to TFLiteMetrics but specialized for converter."""
    def __del__(self) -> None: ...
    def set_export_required(self) -> None: ...
    def export_metrics(self) -> None: ...
