from _typeshed import Incomplete

__all__ = ['PeriodicMonitoringThread']

class MonitorWarning(RuntimeWarning):
    """The type of warnings we emit."""

class _MonitorEntry:
    function: Incomplete
    period: Incomplete
    last_run_time: int
    def __init__(self, function, period) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class PeriodicMonitoringThread:
    inactive_sleep_time: float
    min_sleep_time: float
    min_memory_monitor_period: int
    should_run: bool
    monitor_thread_ident: Incomplete
    pid: Incomplete
    def __init__(self, hub) -> None: ...
    @property
    def hub(self): ...
    def monitoring_functions(self): ...
    def add_monitoring_function(self, function, period) -> None: ...
    def calculate_sleep_time(self): ...
    def kill(self) -> None: ...
    def __call__(self) -> None: ...
    def monitor_blocking(self, hub): ...
    def ignore_current_greenlet_blocking(self) -> None: ...
    def monitor_current_greenlet_blocking(self) -> None: ...
    def can_monitor_memory_usage(self): ...
    def install_monitor_memory_usage(self) -> None: ...
    def monitor_memory_usage(self, _hub): ...
