from dataclasses import dataclass
from fontTools.designspaceLib import AxisDescriptor as AxisDescriptor, DesignSpaceDocument as DesignSpaceDocument, DesignSpaceDocumentError as DesignSpaceDocumentError, RangeAxisSubsetDescriptor as RangeAxisSubsetDescriptor, SimpleLocationDict as SimpleLocationDict, ValueAxisSubsetDescriptor as ValueAxisSubsetDescriptor, VariableFontDescriptor as VariableFontDescriptor
from typing import Dict, List

def clamp(value, minimum, maximum): ...

@dataclass
class Range:
    minimum: float
    maximum: float
    default: float = ...
    def __post_init__(self) -> None: ...
    def __contains__(self, value: float | Range) -> bool: ...
    def intersection(self, other: Range) -> Range | None: ...
    def __init__(self, minimum, maximum, default) -> None: ...
Region = Dict[str, Range | float]
ConditionSet = Dict[str, Range]
Rule = List[ConditionSet]
Rules = Dict[str, Rule]

def locationInRegion(location: SimpleLocationDict, region: Region) -> bool: ...
def regionInRegion(region: Region, superRegion: Region) -> bool: ...
def userRegionToDesignRegion(doc: DesignSpaceDocument, userRegion: Region) -> Region: ...
def getVFUserRegion(doc: DesignSpaceDocument, vf: VariableFontDescriptor) -> Region: ...
