from _typeshed import Incomplete
from collections.abc import Generator
from jsonschema._utils import ensure_list as ensure_list, equal as equal, extras_msg as extras_msg, find_additional_properties as find_additional_properties, find_evaluated_item_indexes_by_schema as find_evaluated_item_indexes_by_schema, find_evaluated_property_keys_by_schema as find_evaluated_property_keys_by_schema, unbool as unbool, uniq as uniq
from jsonschema.exceptions import FormatError as FormatError, ValidationError as ValidationError

def patternProperties(validator, patternProperties, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def propertyNames(validator, propertyNames, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def additionalProperties(validator, aP, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def items(validator, items, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def additionalItems(validator, aI, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def const(validator, const, instance, schema) -> Generator[Incomplete, None, None]: ...
def contains(validator, contains, instance, schema) -> Generator[Incomplete, None, None]: ...
def exclusiveMinimum(validator, minimum, instance, schema) -> Generator[Incomplete, None, None]: ...
def exclusiveMaximum(validator, maximum, instance, schema) -> Generator[Incomplete, None, None]: ...
def minimum(validator, minimum, instance, schema) -> Generator[Incomplete, None, None]: ...
def maximum(validator, maximum, instance, schema) -> Generator[Incomplete, None, None]: ...
def multipleOf(validator, dB, instance, schema) -> Generator[Incomplete, None, None]: ...
def minItems(validator, mI, instance, schema) -> Generator[Incomplete, None, None]: ...
def maxItems(validator, mI, instance, schema) -> Generator[Incomplete, None, None]: ...
def uniqueItems(validator, uI, instance, schema) -> Generator[Incomplete, None, None]: ...
def pattern(validator, patrn, instance, schema) -> Generator[Incomplete, None, None]: ...
def format(validator, format, instance, schema) -> Generator[Incomplete, None, None]: ...
def minLength(validator, mL, instance, schema) -> Generator[Incomplete, None, None]: ...
def maxLength(validator, mL, instance, schema) -> Generator[Incomplete, None, None]: ...
def dependentRequired(validator, dependentRequired, instance, schema) -> Generator[Incomplete, None, None]: ...
def dependentSchemas(validator, dependentSchemas, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def enum(validator, enums, instance, schema) -> Generator[Incomplete, None, None]: ...
def ref(validator, ref, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def dynamicRef(validator, dynamicRef, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def type(validator, types, instance, schema) -> Generator[Incomplete, None, None]: ...
def properties(validator, properties, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def required(validator, required, instance, schema) -> Generator[Incomplete, None, None]: ...
def minProperties(validator, mP, instance, schema) -> Generator[Incomplete, None, None]: ...
def maxProperties(validator, mP, instance, schema) -> Generator[Incomplete, None, None]: ...
def allOf(validator, allOf, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def anyOf(validator, anyOf, instance, schema) -> Generator[Incomplete, None, None]: ...
def oneOf(validator, oneOf, instance, schema) -> Generator[Incomplete, None, None]: ...
def not_(validator, not_schema, instance, schema) -> Generator[Incomplete, None, None]: ...
def if_(validator, if_schema, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
def unevaluatedItems(validator, unevaluatedItems, instance, schema) -> Generator[Incomplete, None, None]: ...
def unevaluatedProperties(validator, unevaluatedProperties, instance, schema) -> Generator[Incomplete, None, None]: ...
def prefixItems(validator, prefixItems, instance, schema) -> Generator[Incomplete, Incomplete, None]: ...
