from _typeshed import Incomplete
from fontTools.pens.basePen import AbstractPen

__all__ = ['TeePen']

class TeePen(AbstractPen):
    """Pen multiplexing drawing to one or more pens.

    Use either as TeePen(pen1, pen2, ...) or TeePen(iterableOfPens)."""
    pens: Incomplete
    def __init__(self, *pens) -> None: ...
    def moveTo(self, p0) -> None: ...
    def lineTo(self, p1) -> None: ...
    def qCurveTo(self, *points) -> None: ...
    def curveTo(self, *points) -> None: ...
    def closePath(self) -> None: ...
    def endPath(self) -> None: ...
    def addComponent(self, glyphName, transformation) -> None: ...
