from transformers import SegformerImageProcessor as SegformerImageProcessor, SwinConfig as SwinConfig, UperNetConfig as UperNetConfig, UperNetForSemanticSegmentation as UperNetForSemanticSegmentation

def get_upernet_config(model_name): ...
def create_rename_keys(config): ...
def rename_key(dct, old, new) -> None: ...
def read_in_q_k_v(state_dict, backbone_config) -> None: ...
def correct_unfold_reduction_order(x): ...
def reverse_correct_unfold_reduction_order(x): ...
def correct_unfold_norm_order(x): ...
def reverse_correct_unfold_norm_order(x): ...
def convert_upernet_checkpoint(model_name, pytorch_dump_folder_path, push_to_hub) -> None: ...
