from transformers import ConvNextConfig as ConvNextConfig, SegformerImageProcessor as SegformerImageProcessor, UperNetConfig as UperNetConfig, UperNetForSemanticSegmentation as UperNetForSemanticSegmentation

def get_upernet_config(model_name): ...
def create_rename_keys(config): ...
def rename_key(dct, old, new) -> None: ...
def convert_upernet_checkpoint(model_name, pytorch_dump_folder_path, push_to_hub) -> None: ...
