from . import test_libcython_in_gdb as test_libcython_in_gdb
from .test_libcython_in_gdb import inferior_python_version as inferior_python_version
from Cython.Debugger import libcython as libcython, libpython as libpython
from _typeshed import Incomplete

class TestPrettyPrinters(test_libcython_in_gdb.DebugTestCase):
    """
    Test whether types of Python objects are correctly inferred and that
    the right libpython.PySomeTypeObjectPtr classes are instantiated.

    Also test whether values are appropriately formatted (don't be too
    laborious as Lib/test/test_gdb.py already covers this extensively).

    Don't take care of decreffing newly allocated objects as a new
    interpreter is started for every test anyway.
    """
    def setUp(self) -> None: ...
    def get_pyobject(self, code): ...
    def pyobject_fromcode(self, code, gdbvar: Incomplete | None = None): ...
    def get_repr(self, pyobject): ...
    def alloc_bytestring(self, string, gdbvar: Incomplete | None = None): ...
    def alloc_unicodestring(self, string, gdbvar: Incomplete | None = None): ...
    def test_bytestring(self) -> None: ...
    def test_unicode(self) -> None: ...
    def test_int(self) -> None: ...
    def test_long(self) -> None: ...
    def test_frame_type(self) -> None: ...
