from _typeshed import Incomplete
from transformers import CLIPTokenizer as CLIPTokenizer, CLIPTokenizerFast as CLIPTokenizerFast, VideoMAEFeatureExtractor as VideoMAEFeatureExtractor, XCLIPConfig as XCLIPConfig, XCLIPModel as XCLIPModel, XCLIPProcessor as XCLIPProcessor, XCLIPTextConfig as XCLIPTextConfig, XCLIPVisionConfig as XCLIPVisionConfig

def get_xclip_config(model_name, num_frames): ...
def rename_key(name): ...
def convert_state_dict(orig_state_dict, config): ...
def prepare_video(num_frames): ...
def convert_xclip_checkpoint(model_name, pytorch_dump_folder_path: Incomplete | None = None, push_to_hub: bool = False) -> None: ...
