from .via_disk_folder import AppDataDiskFolder, PyInfoStoreDisk
from _typeshed import Incomplete

__all__ = ['ReadOnlyAppData']

class ReadOnlyAppData(AppDataDiskFolder):
    can_update: bool
    lock: Incomplete
    def __init__(self, folder: str) -> None: ...
    def reset(self) -> None: ...
    def py_info_clear(self) -> None: ...
    def py_info(self, path): ...
    def embed_update_log(self, distribution, for_py_version) -> None: ...

class _PyInfoStoreDiskReadOnly(PyInfoStoreDisk):
    def write(self, content) -> None: ...
