from .base import AppData, ContentStore
from _typeshed import Incomplete
from abc import ABCMeta
from collections.abc import Generator

__all__ = ['AppDataDiskFolder', 'JSONStoreDisk', 'PyInfoStoreDisk']

class AppDataDiskFolder(AppData):
    """Store the application data on the disk within a folder layout."""
    transient: bool
    can_update: bool
    lock: Incomplete
    def __init__(self, folder) -> None: ...
    def reset(self) -> None: ...
    def close(self) -> None:
        """Do nothing."""
    def locked(self, path) -> Generator[Incomplete, None, None]: ...
    def extract(self, path, to_folder) -> Generator[Incomplete, None, None]: ...
    @property
    def py_info_at(self): ...
    def py_info(self, path): ...
    def py_info_clear(self) -> None:
        """clear py info."""
    def embed_update_log(self, distribution, for_py_version): ...
    @property
    def house(self): ...
    def wheel_image(self, for_py_version, name): ...

class JSONStoreDisk(ContentStore, metaclass=ABCMeta):
    in_folder: Incomplete
    key: Incomplete
    msg: Incomplete
    msg_args: Incomplete
    def __init__(self, in_folder, key, msg, msg_args) -> None: ...
    @property
    def file(self): ...
    def exists(self): ...
    def read(self): ...
    def remove(self) -> None: ...
    def locked(self) -> Generator[None, None, None]: ...
    def write(self, content) -> None: ...

class PyInfoStoreDisk(JSONStoreDisk):
    def __init__(self, in_folder, path) -> None: ...

class EmbedDistributionUpdateStoreDisk(JSONStoreDisk):
    def __init__(self, in_folder, distribution) -> None: ...
