from nltk.ccg.combinator import *
from nltk.ccg.logic import *
from nltk.sem.logic import *
from _typeshed import Incomplete
from collections.abc import Generator
from nltk.ccg.combinator import BackwardApplication as BackwardApplication, BackwardBx as BackwardBx, BackwardComposition as BackwardComposition, BackwardSx as BackwardSx, BackwardT as BackwardT, ForwardApplication as ForwardApplication, ForwardComposition as ForwardComposition, ForwardSubstitution as ForwardSubstitution, ForwardT as ForwardT
from nltk.ccg.lexicon import Token as Token, fromstring as fromstring
from nltk.parse import ParserI as ParserI
from nltk.parse.chart import AbstractChartRule as AbstractChartRule, Chart as Chart, EdgeI as EdgeI
from nltk.tree import Tree as Tree

class CCGEdge(EdgeI):
    def __init__(self, span, categ, rule) -> None: ...
    def lhs(self): ...
    def span(self): ...
    def start(self): ...
    def end(self): ...
    def length(self): ...
    def rhs(self): ...
    def dot(self): ...
    def is_complete(self): ...
    def is_incomplete(self): ...
    def nextsym(self) -> None: ...
    def categ(self): ...
    def rule(self): ...

class CCGLeafEdge(EdgeI):
    """
    Class representing leaf edges in a CCG derivation.
    """
    def __init__(self, pos, token, leaf) -> None: ...
    def lhs(self): ...
    def span(self): ...
    def start(self): ...
    def end(self): ...
    def length(self): ...
    def rhs(self): ...
    def dot(self): ...
    def is_complete(self): ...
    def is_incomplete(self): ...
    def nextsym(self) -> None: ...
    def token(self): ...
    def categ(self): ...
    def leaf(self): ...

class BinaryCombinatorRule(AbstractChartRule):
    """
    Class implementing application of a binary combinator to a chart.
    Takes the directed combinator to apply.
    """
    NUMEDGES: int
    def __init__(self, combinator) -> None: ...
    def apply(self, chart, grammar, left_edge, right_edge) -> Generator[Incomplete, None, None]: ...

class ForwardTypeRaiseRule(AbstractChartRule):
    """
    Class for applying forward type raising
    """
    NUMEDGES: int
    def __init__(self) -> None: ...
    def apply(self, chart, grammar, left_edge, right_edge) -> Generator[Incomplete, None, None]: ...

class BackwardTypeRaiseRule(AbstractChartRule):
    """
    Class for applying backward type raising.
    """
    NUMEDGES: int
    def __init__(self) -> None: ...
    def apply(self, chart, grammar, left_edge, right_edge) -> Generator[Incomplete, None, None]: ...

ApplicationRuleSet: Incomplete
CompositionRuleSet: Incomplete
SubstitutionRuleSet: Incomplete
TypeRaiseRuleSet: Incomplete
DefaultRuleSet: Incomplete

class CCGChartParser(ParserI):
    """
    Chart parser for CCGs.
    Based largely on the ChartParser class from NLTK.
    """
    def __init__(self, lexicon, rules, trace: int = 0) -> None: ...
    def lexicon(self): ...
    def parse(self, tokens): ...

class CCGChart(Chart):
    def __init__(self, tokens) -> None: ...

def compute_semantics(children, edge): ...
def printCCGDerivation(tree) -> None: ...
def printCCGTree(lwidth, tree): ...

lex: Incomplete

def demo() -> None: ...
