from typing import Any, Type

class KeyBasedCompareMixin:
    """Provides comparison capabilities that is based on a key"""
    def __init__(self, key: Any, defining_class: Type['KeyBasedCompareMixin']) -> None: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
