from _typeshed import Incomplete
from dataclasses import dataclass

@dataclass
class UnsupportedAliasMutationException(RuntimeError):
    reason: str
    def __init__(self, reason) -> None: ...

cond: Incomplete

def trace_cond(proxy_mode, func_overload, pred, true_fn, false_fn, operands): ...
def cond_dense(pred, true_fn, false_fn, operands): ...
def cond_autograd(pred, true_fn, false_fn, *operands): ...
def inner(pred, true_fn, false_fn, operands): ...
def cond_fake_tensor_mode(pred, true_fn, false_fn, operands): ...
def cond_python_dispatcher(*args): ...
def cond_functionalize(interpreter, pred, true_fn, false_fn, inputs):
    """
    Functionalization implementation for torch.cond. Currently:
      1. We don't allow any input mutation inside the branches
      2. Our check for above condition is not exhaustive
    """
