from transformers import TimesformerConfig as TimesformerConfig, TimesformerForVideoClassification as TimesformerForVideoClassification, VideoMAEFeatureExtractor as VideoMAEFeatureExtractor

def get_timesformer_config(model_name): ...
def rename_key(name): ...
def convert_state_dict(orig_state_dict, config): ...
def prepare_video(): ...
def convert_timesformer_checkpoint(checkpoint_url, pytorch_dump_folder_path, model_name, push_to_hub) -> None: ...
