from _typeshed import Incomplete
from nltk.data import load as load

def brown_tagset(tagpattern: Incomplete | None = None) -> None: ...
def claws5_tagset(tagpattern: Incomplete | None = None) -> None: ...
def upenn_tagset(tagpattern: Incomplete | None = None) -> None: ...
