from _typeshed import Incomplete
from win32com.server.policy import DesignatedWrapPolicy

class FileOperationProgressSink(DesignatedWrapPolicy):
    newItem: Incomplete
    def __init__(self) -> None: ...
    def PreDeleteItem(self, flags, item): ...
    def PostDeleteItem(self, flags, item, hr_delete, newly_created) -> None: ...

def create_sink(): ...
