from nni.common import load as load

def get_next_parameter(): ...
def get_experiment_id(): ...
def get_trial_id(): ...
def get_sequence_id(): ...
def send_metric(string) -> None: ...
def init_params(params) -> None: ...
def get_last_metric(): ...
