amax_docstring: str
amin_docstring: str
argmax_docstring: str
argmin_docstring: str
cumprod_docstring: str
cumsum_docstring: str
log_softmax_docstring: str
logsumexp_docstring: str
mean_docstring: str
median_docstring: str
norm_docstring: str
normalize_docstring: str
prod_docstring: str
softmax_docstring: str
softmin_docstring: str
std_docstring: str
sum_docstring: str
var_docstring: str
