import typing
from _typeshed import Incomplete

def cryptography_has_set_cert_cb() -> typing.List[str]: ...
def cryptography_has_ssl_st() -> typing.List[str]: ...
def cryptography_has_tls_st() -> typing.List[str]: ...
def cryptography_has_evp_pkey_dhx() -> typing.List[str]: ...
def cryptography_has_mem_functions() -> typing.List[str]: ...
def cryptography_has_x509_store_ctx_get_issuer() -> typing.List[str]: ...
def cryptography_has_ed448() -> typing.List[str]: ...
def cryptography_has_ed25519() -> typing.List[str]: ...
def cryptography_has_poly1305() -> typing.List[str]: ...
def cryptography_has_evp_digestfinal_xof() -> typing.List[str]: ...
def cryptography_has_fips() -> typing.List[str]: ...
def cryptography_has_ssl_sigalgs() -> typing.List[str]: ...
def cryptography_has_psk() -> typing.List[str]: ...
def cryptography_has_psk_tlsv13() -> typing.List[str]: ...
def cryptography_has_custom_ext() -> typing.List[str]: ...
def cryptography_has_tlsv13_functions() -> typing.List[str]: ...
def cryptography_has_raw_key() -> typing.List[str]: ...
def cryptography_has_engine() -> typing.List[str]: ...
def cryptography_has_verified_chain() -> typing.List[str]: ...
def cryptography_has_srtp() -> typing.List[str]: ...
def cryptography_has_providers() -> typing.List[str]: ...
def cryptography_has_op_no_renegotiation() -> typing.List[str]: ...
def cryptography_has_dtls_get_data_mtu() -> typing.List[str]: ...
def cryptography_has_300_fips() -> typing.List[str]: ...
def cryptography_has_ssl_cookie() -> typing.List[str]: ...
def cryptography_has_pkcs7_funcs() -> typing.List[str]: ...
def cryptography_has_bn_flags() -> typing.List[str]: ...
def cryptography_has_evp_pkey_dh() -> typing.List[str]: ...
def cryptography_has_300_evp_cipher() -> typing.List[str]: ...
def cryptography_has_unexpected_eof_while_reading() -> typing.List[str]: ...
def cryptography_has_pkcs12_set_mac() -> typing.List[str]: ...
def cryptography_has_ssl_op_ignore_unexpected_eof() -> typing.List[str]: ...
def cryptography_has_get_extms_support() -> typing.List[str]: ...
def cryptography_has_evp_pkey_set_peer_ex() -> typing.List[str]: ...
def cryptography_has_evp_aead() -> typing.List[str]: ...

CONDITIONAL_NAMES: Incomplete
