import argparse
from _typeshed import Incomplete
from wandb import trigger as trigger
from wandb.util import add_import_hook as add_import_hook, get_optional_module as get_optional_module

class ArgumentException(Exception): ...

class SafeArgumentParser(argparse.ArgumentParser):
    def error(self, message) -> None: ...

def set_entity(value, env: Incomplete | None = None) -> None: ...
def magic_install(init_args: Incomplete | None = None) -> None: ...
