from _typeshed import Incomplete
from typing import Callable, Generic
from typing_extensions import ParamSpec

logger: Incomplete
P = ParamSpec('P')

class CallbackRegistry(Generic[P]):
    name: Incomplete
    callback_list: Incomplete
    def __init__(self, name: str) -> None: ...
    def add_callback(self, cb: Callable[P, None]) -> None: ...
    def fire_callbacks(self, *args: P.args, **kwargs: P.kwargs) -> None: ...

CUDAEventCreationCallbacks: CallbackRegistry[int]
CUDAEventDeletionCallbacks: CallbackRegistry[int]
CUDAEventRecordCallbacks: CallbackRegistry[int, int]
CUDAEventWaitCallbacks: CallbackRegistry[int, int]
CUDAMemoryAllocationCallbacks: CallbackRegistry[int]
CUDAMemoryDeallocationCallbacks: CallbackRegistry[int]
CUDAStreamCreationCallbacks: CallbackRegistry[int]
CUDADeviceSynchronizationCallbacks: CallbackRegistry[[]]
CUDAStreamSynchronizationCallbacks: CallbackRegistry[int]
CUDAEventSynchronizationCallbacks: CallbackRegistry[int]

def register_callback_for_cuda_event_creation(cb: Callable[[int], None]) -> None: ...
def register_callback_for_cuda_event_deletion(cb: Callable[[int], None]) -> None: ...
def register_callback_for_cuda_event_record(cb: Callable[[int, int], None]) -> None: ...
def register_callback_for_cuda_event_wait(cb: Callable[[int, int], None]) -> None: ...
def register_callback_for_cuda_memory_allocation(cb: Callable[[int], None]) -> None: ...
def register_callback_for_cuda_memory_deallocation(cb: Callable[[int], None]) -> None: ...
def register_callback_for_cuda_stream_creation(cb: Callable[[int], None]) -> None: ...
def register_callback_for_cuda_device_synchronization(cb: Callable[[], None]) -> None: ...
def register_callback_for_cuda_stream_synchronization(cb: Callable[[int], None]) -> None: ...
def register_callback_for_cuda_event_synchronization(cb: Callable[[int], None]) -> None: ...
