from ..packages.backports.makefile import backport_makefile
from _typeshed import Incomplete

__all__ = ['inject_into_urllib3', 'extract_from_urllib3']

class UnsupportedExtension(Exception): ...

def inject_into_urllib3() -> None:
    """Monkey-patch urllib3 with PyOpenSSL-backed SSL-support."""
def extract_from_urllib3() -> None:
    """Undo monkey-patching by :func:`inject_into_urllib3`."""

class WrappedSocket:
    """API-compatibility wrapper for Python OpenSSL's Connection-class.

    Note: _makefile_refs, _drop() and _reuse() are needed for the garbage
    collector of pypy.
    """
    connection: Incomplete
    socket: Incomplete
    suppress_ragged_eofs: Incomplete
    def __init__(self, connection, socket, suppress_ragged_eofs: bool = True) -> None: ...
    def fileno(self): ...
    def recv(self, *args, **kwargs): ...
    def recv_into(self, *args, **kwargs): ...
    def settimeout(self, timeout): ...
    def sendall(self, data) -> None: ...
    def shutdown(self) -> None: ...
    def close(self): ...
    def getpeercert(self, binary_form: bool = False): ...
    def version(self): ...
makefile = backport_makefile

class PyOpenSSLContext:
    """
    I am a wrapper class for the PyOpenSSL ``Context`` object. I am responsible
    for translating the interface of the standard library ``SSLContext`` object
    to calls into PyOpenSSL.
    """
    protocol: Incomplete
    check_hostname: bool
    def __init__(self, protocol) -> None: ...
    @property
    def options(self): ...
    @options.setter
    def options(self, value) -> None: ...
    @property
    def verify_mode(self): ...
    @verify_mode.setter
    def verify_mode(self, value) -> None: ...
    def set_default_verify_paths(self) -> None: ...
    def set_ciphers(self, ciphers) -> None: ...
    def load_verify_locations(self, cafile: Incomplete | None = None, capath: Incomplete | None = None, cadata: Incomplete | None = None) -> None: ...
    def load_cert_chain(self, certfile, keyfile: Incomplete | None = None, password: Incomplete | None = None): ...
    def set_alpn_protocols(self, protocols): ...
    def wrap_socket(self, sock, server_side: bool = False, do_handshake_on_connect: bool = True, suppress_ragged_eofs: bool = True, server_hostname: Incomplete | None = None): ...
