from datetime import timedelta

DEFAULT_RPC_TIMEOUT_SEC: float
DEFAULT_INIT_METHOD: str
DEFAULT_SHUTDOWN_TIMEOUT: float
DEFAULT_NUM_WORKER_THREADS: int
DEFAULT_PROCESS_GROUP_TIMEOUT: timedelta
UNSET_RPC_TIMEOUT: float
