from _typeshed import Incomplete

np: Incomplete

class ArgTypeAndIndex:
    @classmethod
    def GetRootAsArgTypeAndIndex(cls, buf, offset): ...
    @classmethod
    def ArgTypeAndIndexBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def ArgType(self): ...
    def Index(self): ...

def ArgTypeAndIndexStart(builder) -> None: ...
def ArgTypeAndIndexAddArgType(builder, argType) -> None: ...
def ArgTypeAndIndexAddIndex(builder, index) -> None: ...
def ArgTypeAndIndexEnd(builder): ...
