from _typeshed import Incomplete

np: Incomplete

class Checkpoint:
    @classmethod
    def GetRootAsCheckpoint(cls, buf, offset): ...
    @classmethod
    def CheckpointBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Version(self): ...
    def ModuleState(self): ...
    def OptimizerGroups(self, j): ...
    def OptimizerGroupsLength(self): ...
    def OptimizerGroupsIsNone(self): ...
    def PropertyBag(self): ...

def CheckpointStart(builder) -> None: ...
def CheckpointAddVersion(builder, version) -> None: ...
def CheckpointAddModuleState(builder, moduleState) -> None: ...
def CheckpointAddOptimizerGroups(builder, optimizerGroups) -> None: ...
def CheckpointStartOptimizerGroupsVector(builder, numElems): ...
def CheckpointAddPropertyBag(builder, propertyBag) -> None: ...
def CheckpointEnd(builder): ...
