from _typeshed import Incomplete

np: Incomplete

class DeprecatedNodeIndexAndKernelDefHash:
    @classmethod
    def GetRootAsDeprecatedNodeIndexAndKernelDefHash(cls, buf, offset): ...
    @classmethod
    def DeprecatedNodeIndexAndKernelDefHashBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def NodeIndex(self): ...
    def KernelDefHash(self): ...

def DeprecatedNodeIndexAndKernelDefHashStart(builder) -> None: ...
def DeprecatedNodeIndexAndKernelDefHashAddNodeIndex(builder, nodeIndex) -> None: ...
def DeprecatedNodeIndexAndKernelDefHashAddKernelDefHash(builder, kernelDefHash) -> None: ...
def DeprecatedNodeIndexAndKernelDefHashEnd(builder): ...
