from _typeshed import Incomplete

np: Incomplete

class DimensionValue:
    @classmethod
    def GetRootAsDimensionValue(cls, buf, offset): ...
    @classmethod
    def DimensionValueBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def DimType(self): ...
    def DimValue(self): ...
    def DimParam(self): ...

def DimensionValueStart(builder) -> None: ...
def DimensionValueAddDimType(builder, dimType) -> None: ...
def DimensionValueAddDimValue(builder, dimValue) -> None: ...
def DimensionValueAddDimParam(builder, dimParam) -> None: ...
def DimensionValueEnd(builder): ...
