from _typeshed import Incomplete

np: Incomplete

class Graph:
    @classmethod
    def GetRootAsGraph(cls, buf, offset): ...
    @classmethod
    def GraphBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Initializers(self, j): ...
    def InitializersLength(self): ...
    def InitializersIsNone(self): ...
    def NodeArgs(self, j): ...
    def NodeArgsLength(self): ...
    def NodeArgsIsNone(self): ...
    def Nodes(self, j): ...
    def NodesLength(self): ...
    def NodesIsNone(self): ...
    def MaxNodeIndex(self): ...
    def NodeEdges(self, j): ...
    def NodeEdgesLength(self): ...
    def NodeEdgesIsNone(self): ...
    def Inputs(self, j): ...
    def InputsLength(self): ...
    def InputsIsNone(self): ...
    def Outputs(self, j): ...
    def OutputsLength(self): ...
    def OutputsIsNone(self): ...
    def SparseInitializers(self, j): ...
    def SparseInitializersLength(self): ...
    def SparseInitializersIsNone(self): ...
    def RuntimeOptimizations(self): ...

def GraphStart(builder) -> None: ...
def GraphAddInitializers(builder, initializers) -> None: ...
def GraphStartInitializersVector(builder, numElems): ...
def GraphAddNodeArgs(builder, nodeArgs) -> None: ...
def GraphStartNodeArgsVector(builder, numElems): ...
def GraphAddNodes(builder, nodes) -> None: ...
def GraphStartNodesVector(builder, numElems): ...
def GraphAddMaxNodeIndex(builder, maxNodeIndex) -> None: ...
def GraphAddNodeEdges(builder, nodeEdges) -> None: ...
def GraphStartNodeEdgesVector(builder, numElems): ...
def GraphAddInputs(builder, inputs) -> None: ...
def GraphStartInputsVector(builder, numElems): ...
def GraphAddOutputs(builder, outputs) -> None: ...
def GraphStartOutputsVector(builder, numElems): ...
def GraphAddSparseInitializers(builder, sparseInitializers) -> None: ...
def GraphStartSparseInitializersVector(builder, numElems): ...
def GraphAddRuntimeOptimizations(builder, runtimeOptimizations) -> None: ...
def GraphEnd(builder): ...
