from _typeshed import Incomplete

np: Incomplete

class InferenceSession:
    @classmethod
    def GetRootAsInferenceSession(cls, buf, offset): ...
    @classmethod
    def InferenceSessionBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def OrtVersion(self): ...
    def Model(self): ...
    def KernelTypeStrResolver(self): ...

def InferenceSessionStart(builder) -> None: ...
def InferenceSessionAddOrtVersion(builder, ortVersion) -> None: ...
def InferenceSessionAddModel(builder, model) -> None: ...
def InferenceSessionAddKernelTypeStrResolver(builder, kernelTypeStrResolver) -> None: ...
def InferenceSessionEnd(builder): ...
