from _typeshed import Incomplete

np: Incomplete

class KernelTypeStrResolver:
    @classmethod
    def GetRootAsKernelTypeStrResolver(cls, buf, offset): ...
    @classmethod
    def KernelTypeStrResolverBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def OpKernelTypeStrArgs(self, j): ...
    def OpKernelTypeStrArgsLength(self): ...
    def OpKernelTypeStrArgsIsNone(self): ...

def KernelTypeStrResolverStart(builder) -> None: ...
def KernelTypeStrResolverAddOpKernelTypeStrArgs(builder, opKernelTypeStrArgs) -> None: ...
def KernelTypeStrResolverStartOpKernelTypeStrArgsVector(builder, numElems): ...
def KernelTypeStrResolverEnd(builder): ...
