from _typeshed import Incomplete

np: Incomplete

class ModuleState:
    @classmethod
    def GetRootAsModuleState(cls, buf, offset): ...
    @classmethod
    def ModuleStateBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def RequiresGradParams(self, j): ...
    def RequiresGradParamsLength(self): ...
    def RequiresGradParamsIsNone(self): ...
    def FrozenParams(self, j): ...
    def FrozenParamsLength(self): ...
    def FrozenParamsIsNone(self): ...

def ModuleStateStart(builder) -> None: ...
def ModuleStateAddRequiresGradParams(builder, requiresGradParams) -> None: ...
def ModuleStateStartRequiresGradParamsVector(builder, numElems): ...
def ModuleStateAddFrozenParams(builder, frozenParams) -> None: ...
def ModuleStateStartFrozenParamsVector(builder, numElems): ...
def ModuleStateEnd(builder): ...
