from _typeshed import Incomplete

np: Incomplete

class NodeEdge:
    @classmethod
    def GetRootAsNodeEdge(cls, buf, offset): ...
    @classmethod
    def NodeEdgeBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def NodeIndex(self): ...
    def InputEdges(self, j): ...
    def InputEdgesLength(self): ...
    def InputEdgesIsNone(self): ...
    def OutputEdges(self, j): ...
    def OutputEdgesLength(self): ...
    def OutputEdgesIsNone(self): ...

def NodeEdgeStart(builder) -> None: ...
def NodeEdgeAddNodeIndex(builder, nodeIndex) -> None: ...
def NodeEdgeAddInputEdges(builder, inputEdges) -> None: ...
def NodeEdgeStartInputEdgesVector(builder, numElems): ...
def NodeEdgeAddOutputEdges(builder, outputEdges) -> None: ...
def NodeEdgeStartOutputEdgesVector(builder, numElems): ...
def NodeEdgeEnd(builder): ...
