from _typeshed import Incomplete

np: Incomplete

class Node:
    @classmethod
    def GetRootAsNode(cls, buf, offset): ...
    @classmethod
    def NodeBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Name(self): ...
    def DocString(self): ...
    def Domain(self): ...
    def SinceVersion(self): ...
    def Index(self): ...
    def OpType(self): ...
    def Type(self): ...
    def ExecutionProviderType(self): ...
    def Inputs(self, j): ...
    def InputsLength(self): ...
    def InputsIsNone(self): ...
    def Outputs(self, j): ...
    def OutputsLength(self): ...
    def OutputsIsNone(self): ...
    def Attributes(self, j): ...
    def AttributesLength(self): ...
    def AttributesIsNone(self): ...
    def InputArgCounts(self, j): ...
    def InputArgCountsAsNumpy(self): ...
    def InputArgCountsLength(self): ...
    def InputArgCountsIsNone(self): ...
    def ImplicitInputs(self, j): ...
    def ImplicitInputsLength(self): ...
    def ImplicitInputsIsNone(self): ...

def NodeStart(builder) -> None: ...
def NodeAddName(builder, name) -> None: ...
def NodeAddDocString(builder, docString) -> None: ...
def NodeAddDomain(builder, domain) -> None: ...
def NodeAddSinceVersion(builder, sinceVersion) -> None: ...
def NodeAddIndex(builder, index) -> None: ...
def NodeAddOpType(builder, opType) -> None: ...
def NodeAddType(builder, type) -> None: ...
def NodeAddExecutionProviderType(builder, executionProviderType) -> None: ...
def NodeAddInputs(builder, inputs) -> None: ...
def NodeStartInputsVector(builder, numElems): ...
def NodeAddOutputs(builder, outputs) -> None: ...
def NodeStartOutputsVector(builder, numElems): ...
def NodeAddAttributes(builder, attributes) -> None: ...
def NodeStartAttributesVector(builder, numElems): ...
def NodeAddInputArgCounts(builder, inputArgCounts) -> None: ...
def NodeStartInputArgCountsVector(builder, numElems): ...
def NodeAddImplicitInputs(builder, implicitInputs) -> None: ...
def NodeStartImplicitInputsVector(builder, numElems): ...
def NodeEnd(builder): ...
