from _typeshed import Incomplete

np: Incomplete

class OperatorSetId:
    @classmethod
    def GetRootAsOperatorSetId(cls, buf, offset): ...
    @classmethod
    def OperatorSetIdBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Domain(self): ...
    def Version(self): ...

def OperatorSetIdStart(builder) -> None: ...
def OperatorSetIdAddDomain(builder, domain) -> None: ...
def OperatorSetIdAddVersion(builder, version) -> None: ...
def OperatorSetIdEnd(builder): ...
