from _typeshed import Incomplete

np: Incomplete

class ParameterOptimizerState:
    @classmethod
    def GetRootAsParameterOptimizerState(cls, buf, offset): ...
    @classmethod
    def ParameterOptimizerStateBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def ParamName(self): ...
    def Momentums(self, j): ...
    def MomentumsLength(self): ...
    def MomentumsIsNone(self): ...

def ParameterOptimizerStateStart(builder) -> None: ...
def ParameterOptimizerStateAddParamName(builder, paramName) -> None: ...
def ParameterOptimizerStateAddMomentums(builder, momentums) -> None: ...
def ParameterOptimizerStateStartMomentumsVector(builder, numElems): ...
def ParameterOptimizerStateEnd(builder): ...
