from _typeshed import Incomplete

np: Incomplete

class RuntimeOptimizationRecord:
    @classmethod
    def GetRootAsRuntimeOptimizationRecord(cls, buf, offset): ...
    @classmethod
    def RuntimeOptimizationRecordBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def ActionId(self): ...
    def NodesToOptimizeIndices(self): ...
    def ProducedOpIds(self, j): ...
    def ProducedOpIdsLength(self): ...
    def ProducedOpIdsIsNone(self): ...

def RuntimeOptimizationRecordStart(builder) -> None: ...
def RuntimeOptimizationRecordAddActionId(builder, actionId) -> None: ...
def RuntimeOptimizationRecordAddNodesToOptimizeIndices(builder, nodesToOptimizeIndices) -> None: ...
def RuntimeOptimizationRecordAddProducedOpIds(builder, producedOpIds) -> None: ...
def RuntimeOptimizationRecordStartProducedOpIdsVector(builder, numElems): ...
def RuntimeOptimizationRecordEnd(builder): ...
