from _typeshed import Incomplete

np: Incomplete

class RuntimeOptimizations:
    @classmethod
    def GetRootAsRuntimeOptimizations(cls, buf, offset): ...
    @classmethod
    def RuntimeOptimizationsBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Records(self, j): ...
    def RecordsLength(self): ...
    def RecordsIsNone(self): ...

def RuntimeOptimizationsStart(builder) -> None: ...
def RuntimeOptimizationsAddRecords(builder, records) -> None: ...
def RuntimeOptimizationsStartRecordsVector(builder, numElems): ...
def RuntimeOptimizationsEnd(builder): ...
