from _typeshed import Incomplete

np: Incomplete

class Tensor:
    @classmethod
    def GetRootAsTensor(cls, buf, offset): ...
    @classmethod
    def TensorBufferHasIdentifier(cls, buf, offset, size_prefixed: bool = False): ...
    def Init(self, buf, pos) -> None: ...
    def Name(self): ...
    def DocString(self): ...
    def Dims(self, j): ...
    def DimsAsNumpy(self): ...
    def DimsLength(self): ...
    def DimsIsNone(self): ...
    def DataType(self): ...
    def RawData(self, j): ...
    def RawDataAsNumpy(self): ...
    def RawDataLength(self): ...
    def RawDataIsNone(self): ...
    def StringData(self, j): ...
    def StringDataLength(self): ...
    def StringDataIsNone(self): ...

def TensorStart(builder) -> None: ...
def TensorAddName(builder, name) -> None: ...
def TensorAddDocString(builder, docString) -> None: ...
def TensorAddDims(builder, dims) -> None: ...
def TensorStartDimsVector(builder, numElems): ...
def TensorAddDataType(builder, dataType) -> None: ...
def TensorAddRawData(builder, rawData) -> None: ...
def TensorStartRawDataVector(builder, numElems): ...
def TensorAddStringData(builder, stringData) -> None: ...
def TensorStartStringDataVector(builder, numElems): ...
def TensorEnd(builder): ...
