from _typeshed import Incomplete
from transformers import DetrFeatureExtractor as DetrFeatureExtractor, TableTransformerConfig as TableTransformerConfig, TableTransformerForObjectDetection as TableTransformerForObjectDetection
from transformers.utils import logging as logging

logger: Incomplete
rename_keys: Incomplete

def rename_key(state_dict, old, new) -> None: ...
def rename_backbone_keys(state_dict): ...
def read_in_q_k_v(state_dict) -> None: ...
def resize(image, checkpoint_url): ...
def normalize(image): ...
def convert_table_transformer_checkpoint(checkpoint_url, pytorch_dump_folder_path, push_to_hub) -> None:
    """
    Copy/paste/tweak model's weights to our DETR structure.
    """
