import abc
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing_extensions import Literal

@dataclass
class Device(ABC, metaclass=abc.ABCMeta):
    node_id: str
    status: Literal['idle', 'busy', 'unknown'] = ...
    def __eq__(self, o) -> bool: ...
    def __lt__(self, o) -> bool: ...
    def set_status(self, status) -> None: ...
    @abstractmethod
    def device_repr(self) -> str: ...
    def __init__(self, node_id, status) -> None: ...

@dataclass
class GPUDevice(Device):
    gpu_id: str = ...
    node_id = ...
    status = ...
    def __init__(self, node_id, gpu_id, status: str = 'idle') -> None: ...
    def __eq__(self, o: Device) -> bool: ...
    def __lt__(self, o: Device) -> bool: ...
    def __hash__(self) -> int: ...
    def device_repr(self): ...

@dataclass
class CPUDevice(Device):
    node_id = ...
    device = ...
    def __init__(self, node_id) -> None: ...
    def device_repr(self): ...
