import numpy as np
from _typeshed import Incomplete
from pandas._libs import lib as lib
from pandas._libs.tslibs import get_unit_from_dtype as get_unit_from_dtype, is_supported_unit as is_supported_unit
from pandas._typing import AxisInt as AxisInt, Dtype as Dtype, NpDtype as NpDtype, Scalar as Scalar, npt as npt
from pandas.core import arraylike as arraylike, nanops as nanops, ops as ops
from pandas.core.arraylike import OpsMixin as OpsMixin
from pandas.core.arrays._mixins import NDArrayBackedExtensionArray as NDArrayBackedExtensionArray
from pandas.core.construction import ensure_wrapped_if_datetimelike as ensure_wrapped_if_datetimelike
from pandas.core.dtypes.astype import astype_array as astype_array
from pandas.core.dtypes.cast import construct_1d_object_array_from_listlike as construct_1d_object_array_from_listlike
from pandas.core.dtypes.common import is_dtype_equal as is_dtype_equal, pandas_dtype as pandas_dtype
from pandas.core.dtypes.dtypes import PandasDtype as PandasDtype
from pandas.core.dtypes.missing import isna as isna
from pandas.core.strings.object_array import ObjectStringArrayMixin as ObjectStringArrayMixin

class PandasArray(OpsMixin, NDArrayBackedExtensionArray, ObjectStringArrayMixin):
    """
    A pandas ExtensionArray for NumPy data.

    This is mostly for internal compatibility, and is not especially
    useful on its own.

    Parameters
    ----------
    values : ndarray
        The NumPy ndarray to wrap. Must be 1-dimensional.
    copy : bool, default False
        Whether to copy `values`.

    Attributes
    ----------
    None

    Methods
    -------
    None
    """
    __array_priority__: int
    def __init__(self, values: np.ndarray | PandasArray, copy: bool = False) -> None: ...
    @property
    def dtype(self) -> PandasDtype: ...
    def __array__(self, dtype: NpDtype | None = None) -> np.ndarray: ...
    def __array_ufunc__(self, ufunc: np.ufunc, method: str, *inputs, **kwargs): ...
    def astype(self, dtype, copy: bool = True): ...
    def isna(self) -> np.ndarray: ...
    def any(self, *, axis: AxisInt | None = None, out: Incomplete | None = None, keepdims: bool = False, skipna: bool = True): ...
    def all(self, *, axis: AxisInt | None = None, out: Incomplete | None = None, keepdims: bool = False, skipna: bool = True): ...
    def min(self, *, axis: AxisInt | None = None, skipna: bool = True, **kwargs) -> Scalar: ...
    def max(self, *, axis: AxisInt | None = None, skipna: bool = True, **kwargs) -> Scalar: ...
    def sum(self, *, axis: AxisInt | None = None, skipna: bool = True, min_count: int = 0, **kwargs) -> Scalar: ...
    def prod(self, *, axis: AxisInt | None = None, skipna: bool = True, min_count: int = 0, **kwargs) -> Scalar: ...
    def mean(self, *, axis: AxisInt | None = None, dtype: NpDtype | None = None, out: Incomplete | None = None, keepdims: bool = False, skipna: bool = True): ...
    def median(self, *, axis: AxisInt | None = None, out: Incomplete | None = None, overwrite_input: bool = False, keepdims: bool = False, skipna: bool = True): ...
    def std(self, *, axis: AxisInt | None = None, dtype: NpDtype | None = None, out: Incomplete | None = None, ddof: int = 1, keepdims: bool = False, skipna: bool = True): ...
    def var(self, *, axis: AxisInt | None = None, dtype: NpDtype | None = None, out: Incomplete | None = None, ddof: int = 1, keepdims: bool = False, skipna: bool = True): ...
    def sem(self, *, axis: AxisInt | None = None, dtype: NpDtype | None = None, out: Incomplete | None = None, ddof: int = 1, keepdims: bool = False, skipna: bool = True): ...
    def kurt(self, *, axis: AxisInt | None = None, dtype: NpDtype | None = None, out: Incomplete | None = None, keepdims: bool = False, skipna: bool = True): ...
    def skew(self, *, axis: AxisInt | None = None, dtype: NpDtype | None = None, out: Incomplete | None = None, keepdims: bool = False, skipna: bool = True): ...
    def to_numpy(self, dtype: npt.DTypeLike | None = None, copy: bool = False, na_value: object = ...) -> np.ndarray: ...
    def __invert__(self) -> PandasArray: ...
    def __neg__(self) -> PandasArray: ...
    def __pos__(self) -> PandasArray: ...
    def __abs__(self) -> PandasArray: ...
