from ..utils import DummyObject as DummyObject, requires_backends as requires_backends

class AlbertTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BarthezTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BartphoTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BertGenerationTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BigBirdTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class CamembertTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class CpmTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class DebertaV2Tokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FNetTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class GPTSw3Tokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class LayoutXLMTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class M2M100Tokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MarianTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MBart50Tokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MBartTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MLukeTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MT5Tokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class NllbTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class PegasusTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class PLBartTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class ReformerTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class RemBertTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class Speech2TextTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class T5Tokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class XGLMTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class XLMProphetNetTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class XLMRobertaTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class XLNetTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...
