from ..utils import DummyObject as DummyObject, requires_backends as requires_backends
from _typeshed import Incomplete

class TensorFlowBenchmarkArguments(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TensorFlowBenchmark(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFForcedBOSTokenLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFForcedEOSTokenLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGenerationMixin(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLogitsProcessorList(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLogitsWarper(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMinLengthLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFNoBadWordsLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFNoRepeatNGramLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRepetitionPenaltyLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTemperatureLogitsWarper(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTopKLogitsWarper(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTopPLogitsWarper(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

def tf_top_k_top_p_filtering(*args, **kwargs) -> None: ...

class KerasMetricCallback(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class PushToHubCallback(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_LAYOUTLM_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFLayoutLMForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLayoutLMForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLayoutLMForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLayoutLMForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLayoutLMMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLayoutLMModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLayoutLMPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSequenceSummary(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSharedEmbeddings(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

def shape_list(*args, **kwargs) -> None: ...

TF_ALBERT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFAlbertForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAlbertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAlbertForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAlbertForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAlbertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAlbertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAlbertMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAlbertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAlbertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_MODEL_FOR_CAUSAL_LM_MAPPING: Incomplete
TF_MODEL_FOR_DOCUMENT_QUESTION_ANSWERING_MAPPING: Incomplete
TF_MODEL_FOR_IMAGE_CLASSIFICATION_MAPPING: Incomplete
TF_MODEL_FOR_MASKED_IMAGE_MODELING_MAPPING: Incomplete
TF_MODEL_FOR_MASKED_LM_MAPPING: Incomplete
TF_MODEL_FOR_MULTIPLE_CHOICE_MAPPING: Incomplete
TF_MODEL_FOR_NEXT_SENTENCE_PREDICTION_MAPPING: Incomplete
TF_MODEL_FOR_PRETRAINING_MAPPING: Incomplete
TF_MODEL_FOR_QUESTION_ANSWERING_MAPPING: Incomplete
TF_MODEL_FOR_SEMANTIC_SEGMENTATION_MAPPING: Incomplete
TF_MODEL_FOR_SEQ_TO_SEQ_CAUSAL_LM_MAPPING: Incomplete
TF_MODEL_FOR_SEQUENCE_CLASSIFICATION_MAPPING: Incomplete
TF_MODEL_FOR_SPEECH_SEQ_2_SEQ_MAPPING: Incomplete
TF_MODEL_FOR_TABLE_QUESTION_ANSWERING_MAPPING: Incomplete
TF_MODEL_FOR_TOKEN_CLASSIFICATION_MAPPING: Incomplete
TF_MODEL_FOR_VISION_2_SEQ_MAPPING: Incomplete
TF_MODEL_MAPPING: Incomplete
TF_MODEL_WITH_LM_HEAD_MAPPING: Incomplete

class TFAutoModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForDocumentQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForNextSentencePrediction(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForSemanticSegmentation(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForSeq2SeqLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForSpeechSeq2Seq(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForTableQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelForVision2Seq(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFAutoModelWithLMHead(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBartForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBartForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBartModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBartPretrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_BERT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFBertEmbeddings(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertForNextSentencePrediction(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertLMHeadModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBlenderbotForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBlenderbotModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBlenderbotPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBlenderbotSmallForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBlenderbotSmallModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFBlenderbotSmallPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_CAMEMBERT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFCamembertForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCamembertForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCamembertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCamembertForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCamembertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCamembertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCamembertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCamembertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_CLIP_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFCLIPModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCLIPPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCLIPTextModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCLIPVisionModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_CONVBERT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFConvBertForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFConvBertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFConvBertForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFConvBertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFConvBertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFConvBertLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFConvBertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFConvBertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFConvNextForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFConvNextModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFConvNextPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_CTRL_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFCTRLForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCTRLLMHeadModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCTRLModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCTRLPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_CVT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFCvtForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCvtModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFCvtPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFData2VecVisionForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFData2VecVisionForSemanticSegmentation(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFData2VecVisionModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFData2VecVisionPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_DEBERTA_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFDebertaForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDebertaForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDebertaForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDebertaForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDebertaModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDebertaPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_DEBERTA_V2_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFDebertaV2ForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDebertaV2ForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDebertaV2ForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDebertaV2ForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDebertaV2Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDebertaV2PreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_DEIT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFDeiTForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDeiTForImageClassificationWithTeacher(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDeiTForMaskedImageModeling(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDeiTModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDeiTPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_DISTILBERT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFDistilBertForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDistilBertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDistilBertForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDistilBertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDistilBertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDistilBertMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDistilBertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDistilBertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_DPR_CONTEXT_ENCODER_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete
TF_DPR_QUESTION_ENCODER_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete
TF_DPR_READER_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFDPRContextEncoder(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDPRPretrainedContextEncoder(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDPRPretrainedQuestionEncoder(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDPRPretrainedReader(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDPRQuestionEncoder(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFDPRReader(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_ELECTRA_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFElectraForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFElectraForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFElectraForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFElectraForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFElectraForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFElectraForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFElectraModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFElectraPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFEncoderDecoderModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

ESM_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFEsmForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFEsmForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFEsmForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFEsmModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFEsmPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_FLAUBERT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFFlaubertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFlaubertForQuestionAnsweringSimple(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFlaubertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFlaubertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFlaubertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFlaubertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFlaubertWithLMHeadModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_FUNNEL_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFFunnelBaseModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFunnelForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFunnelForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFunnelForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFunnelForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFunnelForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFunnelForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFunnelModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFFunnelPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_GPT2_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFGPT2DoubleHeadsModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGPT2ForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGPT2LMHeadModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGPT2MainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGPT2Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGPT2PreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGPTJForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGPTJForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGPTJForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGPTJModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGPTJPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_GROUPVIT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFGroupViTModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGroupViTPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGroupViTTextModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFGroupViTVisionModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_HUBERT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFHubertForCTC(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFHubertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFHubertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_LAYOUTLMV3_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFLayoutLMv3ForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLayoutLMv3ForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLayoutLMv3ForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLayoutLMv3Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLayoutLMv3PreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLEDForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLEDModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLEDPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_LONGFORMER_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFLongformerForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLongformerForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLongformerForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLongformerForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLongformerForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLongformerModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLongformerPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLongformerSelfAttention(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_LXMERT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFLxmertForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLxmertMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLxmertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLxmertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFLxmertVisualFeatureEncoder(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMarianModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMarianMTModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMarianPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMBartForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMBartModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMBartPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_MOBILEBERT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete
TF_MOBILEVIT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFMobileBertForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileBertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileBertForNextSentencePrediction(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileBertForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileBertForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileBertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileBertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileBertMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileBertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileBertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileViTForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileViTForSemanticSegmentation(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileViTModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMobileViTPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_MPNET_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFMPNetForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMPNetForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMPNetForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMPNetForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMPNetForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMPNetMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMPNetModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMPNetPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMT5EncoderModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMT5ForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFMT5Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_OPENAI_GPT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFOpenAIGPTDoubleHeadsModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFOpenAIGPTForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFOpenAIGPTLMHeadModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFOpenAIGPTMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFOpenAIGPTModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFOpenAIGPTPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFOPTForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFOPTModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFOPTPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFPegasusForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFPegasusModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFPegasusPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRagModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRagPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRagSequenceForGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRagTokenForGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_REGNET_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFRegNetForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRegNetModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRegNetPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_REMBERT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFRemBertForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRemBertForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRemBertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRemBertForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRemBertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRemBertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRemBertLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRemBertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRemBertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_RESNET_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFResNetForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFResNetModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFResNetPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_ROBERTA_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFRobertaForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_ROBERTA_PRELAYERNORM_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFRobertaPreLayerNormForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaPreLayerNormForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaPreLayerNormForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaPreLayerNormForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaPreLayerNormForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaPreLayerNormForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaPreLayerNormMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaPreLayerNormModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRobertaPreLayerNormPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_ROFORMER_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFRoFormerForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRoFormerForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRoFormerForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRoFormerForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRoFormerForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRoFormerForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRoFormerLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRoFormerModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFRoFormerPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_SEGFORMER_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFSegformerDecodeHead(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSegformerForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSegformerForSemanticSegmentation(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSegformerModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSegformerPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_SPEECH_TO_TEXT_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFSpeech2TextForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSpeech2TextModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSpeech2TextPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_SWIN_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFSwinForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSwinForMaskedImageModeling(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSwinModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFSwinPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_T5_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFT5EncoderModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFT5ForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFT5Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFT5PreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_TAPAS_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFTapasForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTapasForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTapasForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTapasModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTapasPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_TRANSFO_XL_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFAdaptiveEmbedding(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTransfoXLForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTransfoXLLMHeadModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTransfoXLMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTransfoXLModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFTransfoXLPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFVisionEncoderDecoderModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFViTForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFViTModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFViTPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFViTMAEForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFViTMAEModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFViTMAEPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_WAV_2_VEC_2_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFWav2Vec2ForCTC(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFWav2Vec2Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFWav2Vec2PreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_WHISPER_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFWhisperForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFWhisperModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFWhisperPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_XGLM_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFXGLMForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXGLMModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXGLMPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_XLM_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFXLMForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMForQuestionAnsweringSimple(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMWithLMHeadModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_XLM_ROBERTA_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFXLMRobertaForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMRobertaForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMRobertaForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMRobertaForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMRobertaForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMRobertaForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMRobertaModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLMRobertaPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

TF_XLNET_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class TFXLNetForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLNetForQuestionAnsweringSimple(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLNetForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLNetForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLNetLMHeadModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLNetMainLayer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLNetModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class TFXLNetPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class AdamWeightDecay(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class GradientAccumulator(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class WarmUp(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

def create_optimizer(*args, **kwargs) -> None: ...

class TFTrainer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...
