from ..utils import DummyObject as DummyObject, requires_backends as requires_backends

class AlbertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BartTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BarthezTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BigBirdTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BlenderbotTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BlenderbotSmallTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class BloomTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class CamembertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class CLIPTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class CodeGenTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class ConvBertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class CpmTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class DebertaTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class DebertaV2TokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class DistilBertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class DPRContextEncoderTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class DPRQuestionEncoderTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class DPRReaderTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class ElectraTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FNetTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FunnelTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class GPT2TokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class GPTNeoXTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class GPTNeoXJapaneseTokenizer(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class HerbertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class LayoutLMTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class LayoutLMv2TokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class LayoutLMv3TokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class LayoutXLMTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class LEDTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class LongformerTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class LxmertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MarkupLMTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MBartTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MBart50TokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MobileBertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MPNetTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MT5TokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class MvpTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class NllbTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class OpenAIGPTTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class PegasusTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class RealmTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class ReformerTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class RemBertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class RetriBertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class RobertaTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class RoFormerTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class SplinterTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class SqueezeBertTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class T5TokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class XGLMTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class XLMRobertaTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class XLNetTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class PreTrainedTokenizerFast(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...
