from ..utils import DummyObject as DummyObject, requires_backends as requires_backends
from _typeshed import Incomplete

class FlaxForcedBOSTokenLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxForcedEOSTokenLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGenerationMixin(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxLogitsProcessorList(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxLogitsWarper(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMinLengthLogitsProcessor(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxTemperatureLogitsWarper(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxTopKLogitsWarper(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxTopPLogitsWarper(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAlbertForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAlbertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAlbertForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAlbertForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAlbertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAlbertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAlbertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAlbertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

FLAX_MODEL_FOR_CAUSAL_LM_MAPPING: Incomplete
FLAX_MODEL_FOR_IMAGE_CLASSIFICATION_MAPPING: Incomplete
FLAX_MODEL_FOR_MASKED_LM_MAPPING: Incomplete
FLAX_MODEL_FOR_MULTIPLE_CHOICE_MAPPING: Incomplete
FLAX_MODEL_FOR_NEXT_SENTENCE_PREDICTION_MAPPING: Incomplete
FLAX_MODEL_FOR_PRETRAINING_MAPPING: Incomplete
FLAX_MODEL_FOR_QUESTION_ANSWERING_MAPPING: Incomplete
FLAX_MODEL_FOR_SEQ_TO_SEQ_CAUSAL_LM_MAPPING: Incomplete
FLAX_MODEL_FOR_SEQUENCE_CLASSIFICATION_MAPPING: Incomplete
FLAX_MODEL_FOR_TOKEN_CLASSIFICATION_MAPPING: Incomplete
FLAX_MODEL_FOR_VISION_2_SEQ_MAPPING: Incomplete
FLAX_MODEL_MAPPING: Incomplete

class FlaxAutoModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForNextSentencePrediction(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForSeq2SeqLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxAutoModelForVision2Seq(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBartDecoderPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBartForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBartForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBartForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBartForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBartModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBartPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBeitForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBeitForMaskedImageModeling(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBeitModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBeitPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBertForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBertForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBertForNextSentencePrediction(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBertForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBertForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBigBirdForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBigBirdForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBigBirdForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBigBirdForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBigBirdForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBigBirdForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBigBirdForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBigBirdModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBigBirdPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBlenderbotForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBlenderbotModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBlenderbotPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBlenderbotSmallForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBlenderbotSmallModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxBlenderbotSmallPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxCLIPModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxCLIPPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxCLIPTextModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxCLIPTextPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxCLIPVisionModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxCLIPVisionPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxDistilBertForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxDistilBertForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxDistilBertForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxDistilBertForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxDistilBertForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxDistilBertModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxDistilBertPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxElectraForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxElectraForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxElectraForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxElectraForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxElectraForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxElectraForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxElectraForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxElectraModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxElectraPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxEncoderDecoderModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGPT2LMHeadModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGPT2Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGPT2PreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGPTNeoForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGPTNeoModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGPTNeoPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGPTJForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGPTJModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxGPTJPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxLongT5ForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxLongT5Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxLongT5PreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMarianModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMarianMTModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMarianPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMBartForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMBartForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMBartForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMBartModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMBartPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMT5EncoderModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMT5ForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxMT5Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxOPTForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxOPTModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxOPTPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxPegasusForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxPegasusModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxPegasusPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaPreLayerNormForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaPreLayerNormForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaPreLayerNormForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaPreLayerNormForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaPreLayerNormForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaPreLayerNormForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaPreLayerNormModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRobertaPreLayerNormPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRoFormerForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRoFormerForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRoFormerForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRoFormerForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRoFormerForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRoFormerModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxRoFormerPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxSpeechEncoderDecoderModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxT5EncoderModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxT5ForConditionalGeneration(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxT5Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxT5PreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxVisionEncoderDecoderModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxVisionTextDualEncoderModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxViTForImageClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxViTModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxViTPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxWav2Vec2ForCTC(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxWav2Vec2ForPreTraining(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxWav2Vec2Model(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxWav2Vec2PreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxXGLMForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxXGLMModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxXGLMPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

FLAX_XLM_ROBERTA_PRETRAINED_MODEL_ARCHIVE_LIST: Incomplete

class FlaxXLMRobertaForCausalLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxXLMRobertaForMaskedLM(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxXLMRobertaForMultipleChoice(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxXLMRobertaForQuestionAnswering(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxXLMRobertaForSequenceClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxXLMRobertaForTokenClassification(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxXLMRobertaModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...

class FlaxXLMRobertaPreTrainedModel(metaclass=DummyObject):
    def __init__(self, *args, **kwargs) -> None: ...
