from _typeshed import Incomplete

class TrialShortNamer:
    PREFIX: str
    DEFAULTS: Incomplete
    NAMING_INFO: Incomplete
    @classmethod
    def set_defaults(cls, prefix, defaults) -> None: ...
    @staticmethod
    def shortname_for_word(info, word): ...
    @staticmethod
    def shortname_for_key(info, param_name): ...
    @staticmethod
    def add_new_param_name(info, param_name) -> None: ...
    @classmethod
    def build_naming_info(cls) -> None: ...
    @classmethod
    def shortname(cls, params): ...
    @classmethod
    def parse_repr(cls, repr): ...
