import threading
from .connection import Pipe as Pipe
from _typeshed import Incomplete
from queue import Queue as Queue
from threading import Barrier as Barrier, BoundedSemaphore as BoundedSemaphore, Condition as Condition, Event as Event, Lock as Lock, RLock as RLock, Semaphore as Semaphore

__all__ = ['Process', 'current_process', 'active_children', 'freeze_support', 'Lock', 'RLock', 'Semaphore', 'BoundedSemaphore', 'Condition', 'Event', 'Barrier', 'Queue', 'Manager', 'Pipe', 'Pool', 'JoinableQueue']

class DummyProcess(threading.Thread):
    def __init__(self, group: Incomplete | None = None, target: Incomplete | None = None, name: Incomplete | None = None, args=(), kwargs={}) -> None: ...
    def start(self) -> None: ...
    @property
    def exitcode(self): ...
Process = DummyProcess
current_process = threading.current_thread

def active_children(): ...
def freeze_support() -> None: ...

class Namespace:
    def __init__(self, **kwds) -> None: ...
dict = dict
list = list

class Value:
    def __init__(self, typecode, value, lock: bool = True) -> None: ...
    @property
    def value(self): ...
    @value.setter
    def value(self, value) -> None: ...

def Manager(): ...
def Pool(processes: Incomplete | None = None, initializer: Incomplete | None = None, initargs=()): ...
JoinableQueue = Queue
