from _typeshed import Incomplete

__all__ = ['Client', 'Listener', 'Pipe']

class Listener:
    def __init__(self, address: Incomplete | None = None, family: Incomplete | None = None, backlog: int = 1) -> None: ...
    def accept(self): ...
    def close(self) -> None: ...
    @property
    def address(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...

def Client(address): ...
def Pipe(duplex: bool = True): ...

class Connection:
    send: Incomplete
    recv: Incomplete
    def __init__(self, _in, _out) -> None: ...
    def poll(self, timeout: float = 0.0): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
