from sentry_sdk._types import Breadcrumb, BreadcrumbHint, Event, ExcInfo, Hint, MeasurementUnit
from sentry_sdk.hub import Hub
from sentry_sdk.scope import Scope
from sentry_sdk.tracing import NoOpSpan, Span, Transaction
from typing import Any, Callable, ContextManager, Dict, TypeVar, overload

__all__ = ['capture_event', 'capture_message', 'capture_exception', 'add_breadcrumb', 'configure_scope', 'push_scope', 'flush', 'last_event_id', 'start_span', 'start_transaction', 'set_tag', 'set_context', 'set_extra', 'set_user', 'set_level', 'set_measurement', 'get_current_span', 'get_traceparent', 'get_baggage', 'continue_trace']

T = TypeVar('T')
F = TypeVar('F', bound=Callable[..., Any])

def capture_event(event: Event, hint: Hint | None = None, scope: Any | None = None, **scope_args: Any) -> str | None: ...
def capture_message(message: str, level: str | None = None, scope: Any | None = None, **scope_args: Any) -> str | None: ...
def capture_exception(error: BaseException | ExcInfo | None = None, scope: Any | None = None, **scope_args: Any) -> str | None: ...
def add_breadcrumb(crumb: Breadcrumb | None = None, hint: BreadcrumbHint | None = None, **kwargs: Any) -> None: ...
@overload
def configure_scope() -> ContextManager[Scope]: ...
@overload
def configure_scope(callback: Callable[[Scope], None]) -> None: ...
@overload
def push_scope() -> ContextManager[Scope]: ...
@overload
def push_scope(callback: Callable[[Scope], None]) -> None: ...
def set_tag(key: str, value: Any) -> None: ...
def set_context(key: str, value: Dict[str, Any]) -> None: ...
def set_extra(key: str, value: Any) -> None: ...
def set_user(value: Dict[str, Any] | None) -> None: ...
def set_level(value: str) -> None: ...
def flush(timeout: float | None = None, callback: Callable[[int, float], None] | None = None) -> None: ...
def last_event_id() -> str | None: ...
def start_span(span: Span | None = None, **kwargs: Any) -> Span: ...
def start_transaction(transaction: Transaction | None = None, **kwargs: Any) -> Transaction | NoOpSpan: ...
def set_measurement(name: str, value: float, unit: MeasurementUnit = '') -> None: ...
def get_current_span(hub: Hub | None = None) -> Span | None:
    """
    Returns the currently active span if there is one running, otherwise `None`
    """
def get_traceparent() -> str | None:
    """
    Returns the traceparent either from the active span or from the scope.
    """
def get_baggage() -> str | None:
    """
    Returns Baggage either from the active span or from the scope.
    """
def continue_trace(environ_or_headers: Dict[str, Any], op: str | None = None, name: str | None = None, source: str | None = None) -> Transaction:
    """
    Sets the propagation context from environment or headers and returns a transaction.
    """
