import logging
from logging import LogRecord
from sentry_sdk import utils as utils
from sentry_sdk.hub import Hub as Hub
from sentry_sdk.utils import logger as logger

class _HubBasedClientFilter(logging.Filter):
    def filter(self, record: LogRecord) -> bool: ...

def init_debug_support() -> None: ...
def configure_logger() -> None: ...
def configure_debug_hub() -> None: ...
