from _typeshed import Incomplete
from sentry_sdk._compat import string_types as string_types
from sentry_sdk._types import Event as Event, TYPE_CHECKING as TYPE_CHECKING
from sentry_sdk.utils import AnnotatedValue as AnnotatedValue, capture_internal_exceptions as capture_internal_exceptions, iter_event_frames as iter_event_frames
from typing import Any, Dict, List

DEFAULT_DENYLIST: Incomplete

class EventScrubber:
    denylist: Incomplete
    def __init__(self, denylist: List[str] | None = None) -> None: ...
    def scrub_dict(self, d: Dict[str, Any]) -> None: ...
    def scrub_request(self, event: Event) -> None: ...
    def scrub_extra(self, event: Event) -> None: ...
    def scrub_user(self, event: Event) -> None: ...
    def scrub_breadcrumbs(self, event: Event) -> None: ...
    def scrub_frames(self, event: Event) -> None: ...
    def scrub_spans(self, event: Event) -> None: ...
    def scrub_event(self, event: Event) -> None: ...
