from _typeshed import Incomplete
from paramiko.common import byte_chr as byte_chr, byte_ord as byte_ord, max_byte as max_byte, zero_byte as zero_byte
from paramiko.sftp import int64 as int64
from paramiko.util import b as b

class BERException(Exception): ...

class BER:
    """
    Robey's tiny little attempt at a BER decoder.
    """
    content: Incomplete
    idx: int
    def __init__(self, content=...) -> None: ...
    def asbytes(self): ...
    def decode(self): ...
    def decode_next(self): ...
    @staticmethod
    def decode_sequence(data): ...
    def encode_tlv(self, ident, val) -> None: ...
    def encode(self, x) -> None: ...
    @staticmethod
    def encode_sequence(data): ...
