import typing
import uuid
from _typeshed import Incomplete

T = typing.TypeVar('T')

class Convertor(typing.Generic[T]):
    regex: typing.ClassVar[str]
    def convert(self, value: str) -> T: ...
    def to_string(self, value: T) -> str: ...

class StringConvertor(Convertor):
    regex: str
    def convert(self, value: str) -> str: ...
    def to_string(self, value: str) -> str: ...

class PathConvertor(Convertor):
    regex: str
    def convert(self, value: str) -> str: ...
    def to_string(self, value: str) -> str: ...

class IntegerConvertor(Convertor):
    regex: str
    def convert(self, value: str) -> int: ...
    def to_string(self, value: int) -> str: ...

class FloatConvertor(Convertor):
    regex: str
    def convert(self, value: str) -> float: ...
    def to_string(self, value: float) -> str: ...

class UUIDConvertor(Convertor):
    regex: str
    def convert(self, value: str) -> uuid.UUID: ...
    def to_string(self, value: uuid.UUID) -> str: ...

CONVERTOR_TYPES: Incomplete

def register_url_convertor(key: str, convertor: Convertor) -> None: ...
