import typing
from _typeshed import Incomplete
from dataclasses import dataclass
from enum import Enum
from starlette.datastructures import FormData as FormData, Headers as Headers, UploadFile as UploadFile

class FormMessage(Enum):
    FIELD_START: int
    FIELD_NAME: int
    FIELD_DATA: int
    FIELD_END: int
    END: int

@dataclass
class MultipartPart:
    content_disposition: bytes | None = ...
    field_name: str = ...
    data: bytes = ...
    file: UploadFile | None = ...
    item_headers: typing.List[typing.Tuple[bytes, bytes]] = ...
    def __init__(self, content_disposition, field_name, data, file, item_headers) -> None: ...

class MultiPartException(Exception):
    message: Incomplete
    def __init__(self, message: str) -> None: ...

class FormParser:
    headers: Incomplete
    stream: Incomplete
    messages: Incomplete
    def __init__(self, headers: Headers, stream: typing.AsyncGenerator[bytes, None]) -> None: ...
    def on_field_start(self) -> None: ...
    def on_field_name(self, data: bytes, start: int, end: int) -> None: ...
    def on_field_data(self, data: bytes, start: int, end: int) -> None: ...
    def on_field_end(self) -> None: ...
    def on_end(self) -> None: ...
    async def parse(self) -> FormData: ...

class MultiPartParser:
    max_file_size: Incomplete
    headers: Incomplete
    stream: Incomplete
    max_files: Incomplete
    max_fields: Incomplete
    items: Incomplete
    def __init__(self, headers: Headers, stream: typing.AsyncGenerator[bytes, None], *, max_files: int | float = 1000, max_fields: int | float = 1000) -> None: ...
    def on_part_begin(self) -> None: ...
    def on_part_data(self, data: bytes, start: int, end: int) -> None: ...
    def on_part_end(self) -> None: ...
    def on_header_field(self, data: bytes, start: int, end: int) -> None: ...
    def on_header_value(self, data: bytes, start: int, end: int) -> None: ...
    def on_header_end(self) -> None: ...
    def on_headers_finished(self) -> None: ...
    def on_end(self) -> None: ...
    async def parse(self) -> FormData: ...
