import typing
from _typeshed import Incomplete
from starlette._utils import AwaitableOrContextManager as AwaitableOrContextManager, AwaitableOrContextManagerWrapper as AwaitableOrContextManagerWrapper
from starlette.datastructures import Address as Address, FormData as FormData, Headers as Headers, QueryParams as QueryParams, State as State, URL as URL
from starlette.exceptions import HTTPException as HTTPException
from starlette.formparsers import FormParser as FormParser, MultiPartException as MultiPartException, MultiPartParser as MultiPartParser
from starlette.routing import Router as Router
from starlette.types import Message as Message, Receive as Receive, Scope as Scope, Send as Send

SERVER_PUSH_HEADERS_TO_COPY: Incomplete

def cookie_parser(cookie_string: str) -> typing.Dict[str, str]:
    """
    This function parses a ``Cookie`` HTTP header into a dict of key/value pairs.

    It attempts to mimic browser cookie parsing behavior: browsers and web servers
    frequently disregard the spec (RFC 6265) when setting and reading cookies,
    so we attempt to suit the common scenarios here.

    This function has been adapted from Django 3.1.0.
    Note: we are explicitly _NOT_ using `SimpleCookie.load` because it is based
    on an outdated spec and will fail on lots of input we want to support
    """

class ClientDisconnect(Exception): ...

class HTTPConnection(typing.Mapping[str, typing.Any]):
    """
    A base class for incoming HTTP connections, that is used to provide
    any functionality that is common to both `Request` and `WebSocket`.
    """
    scope: Incomplete
    def __init__(self, scope: Scope, receive: Receive | None = None) -> None: ...
    def __getitem__(self, key: str) -> typing.Any: ...
    def __iter__(self) -> typing.Iterator[str]: ...
    def __len__(self) -> int: ...
    __eq__: Incomplete
    __hash__: Incomplete
    @property
    def app(self) -> typing.Any: ...
    @property
    def url(self) -> URL: ...
    @property
    def base_url(self) -> URL: ...
    @property
    def headers(self) -> Headers: ...
    @property
    def query_params(self) -> QueryParams: ...
    @property
    def path_params(self) -> typing.Dict[str, typing.Any]: ...
    @property
    def cookies(self) -> typing.Dict[str, str]: ...
    @property
    def client(self) -> Address | None: ...
    @property
    def session(self) -> typing.Dict[str, typing.Any]: ...
    @property
    def auth(self) -> typing.Any: ...
    @property
    def user(self) -> typing.Any: ...
    @property
    def state(self) -> State: ...
    def url_for(self, __name: str, **path_params: typing.Any) -> URL: ...

async def empty_receive() -> typing.NoReturn: ...
async def empty_send(message: Message) -> typing.NoReturn: ...

class Request(HTTPConnection):
    def __init__(self, scope: Scope, receive: Receive = ..., send: Send = ...) -> None: ...
    @property
    def method(self) -> str: ...
    @property
    def receive(self) -> Receive: ...
    async def stream(self) -> typing.AsyncGenerator[bytes, None]: ...
    async def body(self) -> bytes: ...
    async def json(self) -> typing.Any: ...
    def form(self, *, max_files: int | float = 1000, max_fields: int | float = 1000) -> AwaitableOrContextManager[FormData]: ...
    async def close(self) -> None: ...
    async def is_disconnected(self) -> bool: ...
    async def send_push_promise(self, path: str) -> None: ...
