from _typeshed import Incomplete
from abc import ABC

class BaseLongCallbackManager(ABC):
    UNDEFINED: Incomplete
    managers: Incomplete
    functions: Incomplete
    cache_by: Incomplete
    func_registry: Incomplete
    def __init__(self, cache_by) -> None: ...
    def terminate_job(self, job) -> None: ...
    def terminate_unhealthy_job(self, job) -> None: ...
    def job_running(self, job) -> None: ...
    def make_job_fn(self, fn, progress, key: Incomplete | None = None) -> None: ...
    def call_job_fn(self, key, job_fn, args, context) -> None: ...
    def get_progress(self, key) -> None: ...
    def result_ready(self, key) -> None: ...
    def get_result(self, key, job) -> None: ...
    def build_cache_key(self, fn, args, cache_args_to_ignore): ...
    def register(self, key, fn, progress) -> None: ...
    @staticmethod
    def register_func(fn, progress, callback_id): ...
    @staticmethod
    def hash_function(fn, callback_id: str = ''): ...
