import asyncio
from .tcp_helpers import tcp_nodelay as tcp_nodelay
from _typeshed import Incomplete

class BaseProtocol(asyncio.Protocol):
    transport: Incomplete
    def __init__(self, loop: asyncio.AbstractEventLoop) -> None: ...
    @property
    def connected(self) -> bool:
        """Return True if the connection is open."""
    def pause_writing(self) -> None: ...
    def resume_writing(self) -> None: ...
    def pause_reading(self) -> None: ...
    def resume_reading(self) -> None: ...
    def connection_made(self, transport: asyncio.BaseTransport) -> None: ...
    def connection_lost(self, exc: BaseException | None) -> None: ...
