import asyncio
from .client_exceptions import ClientError as ClientError
from .client_reqrep import ClientResponse as ClientResponse
from .helpers import call_later as call_later, set_result as set_result
from .http import WSCloseCode as WSCloseCode, WSMessage as WSMessage, WSMsgType as WSMsgType, WS_CLOSED_MESSAGE as WS_CLOSED_MESSAGE, WS_CLOSING_MESSAGE as WS_CLOSING_MESSAGE, WebSocketError as WebSocketError
from .http_websocket import WebSocketWriter as WebSocketWriter
from .streams import EofStream as EofStream, FlowControlDataQueue as FlowControlDataQueue
from .typedefs import DEFAULT_JSON_DECODER as DEFAULT_JSON_DECODER, DEFAULT_JSON_ENCODER as DEFAULT_JSON_ENCODER, JSONDecoder as JSONDecoder, JSONEncoder as JSONEncoder
from typing import Any

class ClientWebSocketResponse:
    def __init__(self, reader: FlowControlDataQueue[WSMessage], writer: WebSocketWriter, protocol: str | None, response: ClientResponse, timeout: float, autoclose: bool, autoping: bool, loop: asyncio.AbstractEventLoop, *, receive_timeout: float | None = None, heartbeat: float | None = None, compress: int = 0, client_notakeover: bool = False) -> None: ...
    @property
    def closed(self) -> bool: ...
    @property
    def close_code(self) -> int | None: ...
    @property
    def protocol(self) -> str | None: ...
    @property
    def compress(self) -> int: ...
    @property
    def client_notakeover(self) -> bool: ...
    def get_extra_info(self, name: str, default: Any = None) -> Any:
        """extra info from connection transport"""
    def exception(self) -> BaseException | None: ...
    async def ping(self, message: bytes = b'') -> None: ...
    async def pong(self, message: bytes = b'') -> None: ...
    async def send_str(self, data: str, compress: int | None = None) -> None: ...
    async def send_bytes(self, data: bytes, compress: int | None = None) -> None: ...
    async def send_json(self, data: Any, compress: int | None = None, *, dumps: JSONEncoder = ...) -> None: ...
    async def close(self, *, code: int = ..., message: bytes = b'') -> bool: ...
    async def receive(self, timeout: float | None = None) -> WSMessage: ...
    async def receive_str(self, *, timeout: float | None = None) -> str: ...
    async def receive_bytes(self, *, timeout: float | None = None) -> bytes: ...
    async def receive_json(self, *, loads: JSONDecoder = ..., timeout: float | None = None) -> Any: ...
    def __aiter__(self) -> ClientWebSocketResponse: ...
    async def __anext__(self) -> WSMessage: ...
