import asyncio
from .abc import AbstractCookieJar, ClearCookiePredicate
from .typedefs import LooseCookies, PathLike, StrOrURL
from _typeshed import Incomplete
from http.cookies import BaseCookie, Morsel, SimpleCookie
from typing import Iterator, List
from yarl import URL

__all__ = ['CookieJar', 'DummyCookieJar']

class CookieJar(AbstractCookieJar):
    """Implements cookie storage adhering to RFC 6265."""
    DATE_TOKENS_RE: Incomplete
    DATE_HMS_TIME_RE: Incomplete
    DATE_DAY_OF_MONTH_RE: Incomplete
    DATE_MONTH_RE: Incomplete
    DATE_YEAR_RE: Incomplete
    MAX_TIME: Incomplete
    MAX_32BIT_TIME: Incomplete
    def __init__(self, *, unsafe: bool = False, quote_cookie: bool = True, treat_as_secure_origin: StrOrURL | List[StrOrURL] | None = None, loop: asyncio.AbstractEventLoop | None = None) -> None: ...
    def save(self, file_path: PathLike) -> None: ...
    def load(self, file_path: PathLike) -> None: ...
    def clear(self, predicate: ClearCookiePredicate | None = None) -> None: ...
    def clear_domain(self, domain: str) -> None: ...
    def __iter__(self) -> Iterator[Morsel[str]]: ...
    def __len__(self) -> int: ...
    def update_cookies(self, cookies: LooseCookies, response_url: URL = ...) -> None:
        """Update cookies."""
    def filter_cookies(self, request_url: URL = ...) -> BaseCookie[str] | SimpleCookie[str]:
        """Returns this jar's cookies filtered by their attributes."""

class DummyCookieJar(AbstractCookieJar):
    """Implements a dummy cookie storage.

    It can be used with the ClientSession when no cookie processing is needed.

    """
    def __init__(self, *, loop: asyncio.AbstractEventLoop | None = None) -> None: ...
    def __iter__(self) -> Iterator[Morsel[str]]: ...
    def __len__(self) -> int: ...
    def clear(self, predicate: ClearCookiePredicate | None = None) -> None: ...
    def clear_domain(self, domain: str) -> None: ...
    def update_cookies(self, cookies: LooseCookies, response_url: URL = ...) -> None: ...
    def filter_cookies(self, request_url: URL) -> BaseCookie[str]: ...
