from .client import ClientSession
from .client_reqrep import ClientResponse
from .typedefs import Protocol
from aiosignal import Signal
from multidict import CIMultiDict
from types import SimpleNamespace
from typing import Awaitable, Type
from yarl import URL

__all__ = ['TraceConfig', 'TraceRequestStartParams', 'TraceRequestEndParams', 'TraceRequestExceptionParams', 'TraceConnectionQueuedStartParams', 'TraceConnectionQueuedEndParams', 'TraceConnectionCreateStartParams', 'TraceConnectionCreateEndParams', 'TraceConnectionReuseconnParams', 'TraceDnsResolveHostStartParams', 'TraceDnsResolveHostEndParams', 'TraceDnsCacheHitParams', 'TraceDnsCacheMissParams', 'TraceRequestRedirectParams', 'TraceRequestChunkSentParams', 'TraceResponseChunkReceivedParams', 'TraceRequestHeadersSentParams']

class _SignalCallback(Protocol[_ParamT_contra]):
    def __call__(self, __client_session: ClientSession, __trace_config_ctx: SimpleNamespace, __params: _ParamT_contra) -> Awaitable[None]: ...

class TraceConfig:
    """First-class used to trace requests launched via ClientSession objects."""
    def __init__(self, trace_config_ctx_factory: Type[SimpleNamespace] = ...) -> None: ...
    def trace_config_ctx(self, trace_request_ctx: SimpleNamespace | None = None) -> SimpleNamespace:
        """Return a new trace_config_ctx instance"""
    def freeze(self) -> None: ...
    @property
    def on_request_start(self) -> Signal[_SignalCallback[TraceRequestStartParams]]: ...
    @property
    def on_request_chunk_sent(self) -> Signal[_SignalCallback[TraceRequestChunkSentParams]]: ...
    @property
    def on_response_chunk_received(self) -> Signal[_SignalCallback[TraceResponseChunkReceivedParams]]: ...
    @property
    def on_request_end(self) -> Signal[_SignalCallback[TraceRequestEndParams]]: ...
    @property
    def on_request_exception(self) -> Signal[_SignalCallback[TraceRequestExceptionParams]]: ...
    @property
    def on_request_redirect(self) -> Signal[_SignalCallback[TraceRequestRedirectParams]]: ...
    @property
    def on_connection_queued_start(self) -> Signal[_SignalCallback[TraceConnectionQueuedStartParams]]: ...
    @property
    def on_connection_queued_end(self) -> Signal[_SignalCallback[TraceConnectionQueuedEndParams]]: ...
    @property
    def on_connection_create_start(self) -> Signal[_SignalCallback[TraceConnectionCreateStartParams]]: ...
    @property
    def on_connection_create_end(self) -> Signal[_SignalCallback[TraceConnectionCreateEndParams]]: ...
    @property
    def on_connection_reuseconn(self) -> Signal[_SignalCallback[TraceConnectionReuseconnParams]]: ...
    @property
    def on_dns_resolvehost_start(self) -> Signal[_SignalCallback[TraceDnsResolveHostStartParams]]: ...
    @property
    def on_dns_resolvehost_end(self) -> Signal[_SignalCallback[TraceDnsResolveHostEndParams]]: ...
    @property
    def on_dns_cache_hit(self) -> Signal[_SignalCallback[TraceDnsCacheHitParams]]: ...
    @property
    def on_dns_cache_miss(self) -> Signal[_SignalCallback[TraceDnsCacheMissParams]]: ...
    @property
    def on_request_headers_sent(self) -> Signal[_SignalCallback[TraceRequestHeadersSentParams]]: ...

class TraceRequestStartParams:
    """Parameters sent by the `on_request_start` signal"""
    method: str
    url: URL
    headers: CIMultiDict[str]
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceRequestChunkSentParams:
    """Parameters sent by the `on_request_chunk_sent` signal"""
    method: str
    url: URL
    chunk: bytes
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceResponseChunkReceivedParams:
    """Parameters sent by the `on_response_chunk_received` signal"""
    method: str
    url: URL
    chunk: bytes
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceRequestEndParams:
    """Parameters sent by the `on_request_end` signal"""
    method: str
    url: URL
    headers: CIMultiDict[str]
    response: ClientResponse
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceRequestExceptionParams:
    """Parameters sent by the `on_request_exception` signal"""
    method: str
    url: URL
    headers: CIMultiDict[str]
    exception: BaseException
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceRequestRedirectParams:
    """Parameters sent by the `on_request_redirect` signal"""
    method: str
    url: URL
    headers: CIMultiDict[str]
    response: ClientResponse
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceConnectionQueuedStartParams:
    """Parameters sent by the `on_connection_queued_start` signal"""
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceConnectionQueuedEndParams:
    """Parameters sent by the `on_connection_queued_end` signal"""
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceConnectionCreateStartParams:
    """Parameters sent by the `on_connection_create_start` signal"""
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceConnectionCreateEndParams:
    """Parameters sent by the `on_connection_create_end` signal"""
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceConnectionReuseconnParams:
    """Parameters sent by the `on_connection_reuseconn` signal"""
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceDnsResolveHostStartParams:
    """Parameters sent by the `on_dns_resolvehost_start` signal"""
    host: str
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceDnsResolveHostEndParams:
    """Parameters sent by the `on_dns_resolvehost_end` signal"""
    host: str
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceDnsCacheHitParams:
    """Parameters sent by the `on_dns_cache_hit` signal"""
    host: str
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceDnsCacheMissParams:
    """Parameters sent by the `on_dns_cache_miss` signal"""
    host: str
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TraceRequestHeadersSentParams:
    """Parameters sent by the `on_request_headers_sent` signal"""
    method: str
    url: URL
    headers: CIMultiDict[str]
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class Trace:
    """Internal dependency holder class.

    Used to keep together the main dependencies used
    at the moment of send a signal.
    """
    def __init__(self, session: ClientSession, trace_config: TraceConfig, trace_config_ctx: SimpleNamespace) -> None: ...
    async def send_request_start(self, method: str, url: URL, headers: CIMultiDict[str]) -> None: ...
    async def send_request_chunk_sent(self, method: str, url: URL, chunk: bytes) -> None: ...
    async def send_response_chunk_received(self, method: str, url: URL, chunk: bytes) -> None: ...
    async def send_request_end(self, method: str, url: URL, headers: CIMultiDict[str], response: ClientResponse) -> None: ...
    async def send_request_exception(self, method: str, url: URL, headers: CIMultiDict[str], exception: BaseException) -> None: ...
    async def send_request_redirect(self, method: str, url: URL, headers: CIMultiDict[str], response: ClientResponse) -> None: ...
    async def send_connection_queued_start(self) -> None: ...
    async def send_connection_queued_end(self) -> None: ...
    async def send_connection_create_start(self) -> None: ...
    async def send_connection_create_end(self) -> None: ...
    async def send_connection_reuseconn(self) -> None: ...
    async def send_dns_resolvehost_start(self, host: str) -> None: ...
    async def send_dns_resolvehost_end(self, host: str) -> None: ...
    async def send_dns_cache_hit(self, host: str) -> None: ...
    async def send_dns_cache_miss(self, host: str) -> None: ...
    async def send_request_headers(self, method: str, url: URL, headers: CIMultiDict[str]) -> None: ...
