import asyncio
import datetime
import enum
from .abc import AbstractStreamWriter
from .helpers import ETag, HeadersMixin
from .payload import Payload
from .typedefs import JSONEncoder, LooseHeaders
from .web_request import BaseRequest
from concurrent.futures import Executor
from http.cookies import SimpleCookie
from multidict import CIMultiDict, istr
from typing import Any, Iterator, Mapping, MutableMapping, Tuple

__all__ = ['ContentCoding', 'StreamResponse', 'Response', 'json_response']

BaseClass = MutableMapping[str, Any]

class ContentCoding(enum.Enum):
    deflate: str
    gzip: str
    identity: str

class StreamResponse(BaseClass, HeadersMixin):
    def __init__(self, *, status: int = 200, reason: str | None = None, headers: LooseHeaders | None = None) -> None: ...
    @property
    def prepared(self) -> bool: ...
    @property
    def task(self) -> asyncio.Task[None] | None: ...
    @property
    def status(self) -> int: ...
    @property
    def chunked(self) -> bool: ...
    @property
    def compression(self) -> bool: ...
    @property
    def reason(self) -> str: ...
    def set_status(self, status: int, reason: str | None = None, _RESPONSES: Mapping[int, Tuple[str, str]] = ...) -> None: ...
    @property
    def keep_alive(self) -> bool | None: ...
    def force_close(self) -> None: ...
    @property
    def body_length(self) -> int: ...
    @property
    def output_length(self) -> int: ...
    def enable_chunked_encoding(self, chunk_size: int | None = None) -> None:
        """Enables automatic chunked transfer encoding."""
    def enable_compression(self, force: bool | ContentCoding | None = None) -> None:
        """Enables response compression encoding."""
    @property
    def headers(self) -> CIMultiDict[str]: ...
    @property
    def cookies(self) -> SimpleCookie[str]: ...
    def set_cookie(self, name: str, value: str, *, expires: str | None = None, domain: str | None = None, max_age: int | str | None = None, path: str = '/', secure: bool | None = None, httponly: bool | None = None, version: str | None = None, samesite: str | None = None) -> None:
        """Set or update response cookie.

        Sets new cookie or updates existent with new value.
        Also updates only those params which are not None.
        """
    def del_cookie(self, name: str, *, domain: str | None = None, path: str = '/') -> None:
        """Delete cookie.

        Creates new empty expired cookie.
        """
    @property
    def content_length(self) -> int | None: ...
    @content_length.setter
    def content_length(self, value: int | None) -> None: ...
    @property
    def content_type(self) -> str: ...
    @content_type.setter
    def content_type(self, value: str) -> None: ...
    @property
    def charset(self) -> str | None: ...
    @charset.setter
    def charset(self, value: str | None) -> None: ...
    @property
    def last_modified(self) -> datetime.datetime | None:
        """The value of Last-Modified HTTP header, or None.

        This header is represented as a `datetime` object.
        """
    @last_modified.setter
    def last_modified(self, value: int | float | datetime.datetime | str | None) -> None: ...
    @property
    def etag(self) -> ETag | None: ...
    @etag.setter
    def etag(self, value: ETag | str | None) -> None: ...
    async def prepare(self, request: BaseRequest) -> AbstractStreamWriter | None: ...
    async def write(self, data: bytes) -> None: ...
    async def drain(self) -> None: ...
    async def write_eof(self, data: bytes = b'') -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Response(StreamResponse):
    def __init__(self, *, body: Any = None, status: int = 200, reason: str | None = None, text: str | None = None, headers: LooseHeaders | None = None, content_type: str | None = None, charset: str | None = None, zlib_executor_size: int | None = None, zlib_executor: Executor | None = None) -> None: ...
    @property
    def body(self) -> bytes | Payload | None: ...
    @body.setter
    def body(self, body: bytes, CONTENT_TYPE: istr = ..., CONTENT_LENGTH: istr = ...) -> None: ...
    @property
    def text(self) -> str | None: ...
    content_type: str
    charset: str
    @text.setter
    def text(self, text: str) -> None: ...
    @property
    def content_length(self) -> int | None: ...
    @content_length.setter
    def content_length(self, value: int | None) -> None: ...
    async def write_eof(self, data: bytes = b'') -> None: ...

def json_response(data: Any = ..., *, text: str | None = None, body: bytes | None = None, status: int = 200, reason: str | None = None, headers: LooseHeaders | None = None, content_type: str = 'application/json', dumps: JSONEncoder = ...) -> Response: ...
