from .abc import AbstractStreamWriter
from .http import WSMessage, WSMsgType as WSMsgType
from .typedefs import JSONDecoder, JSONEncoder
from .web_request import BaseRequest
from .web_response import StreamResponse
from typing import Any, Iterable

__all__ = ['WebSocketResponse', 'WebSocketReady', 'WSMsgType']

class WebSocketReady:
    ok: bool
    protocol: str | None
    def __bool__(self) -> bool: ...
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class WebSocketResponse(StreamResponse):
    def __init__(self, *, timeout: float = 10.0, receive_timeout: float | None = None, autoclose: bool = True, autoping: bool = True, heartbeat: float | None = None, protocols: Iterable[str] = (), compress: bool = True, max_msg_size: int = ...) -> None: ...
    async def prepare(self, request: BaseRequest) -> AbstractStreamWriter: ...
    def can_prepare(self, request: BaseRequest) -> WebSocketReady: ...
    @property
    def closed(self) -> bool: ...
    @property
    def close_code(self) -> int | None: ...
    @property
    def ws_protocol(self) -> str | None: ...
    @property
    def compress(self) -> bool: ...
    def exception(self) -> BaseException | None: ...
    async def ping(self, message: bytes = b'') -> None: ...
    async def pong(self, message: bytes = b'') -> None: ...
    async def send_str(self, data: str, compress: bool | None = None) -> None: ...
    async def send_bytes(self, data: bytes, compress: bool | None = None) -> None: ...
    async def send_json(self, data: Any, compress: bool | None = None, *, dumps: JSONEncoder = ...) -> None: ...
    async def write_eof(self) -> None: ...
    async def close(self, *, code: int = ..., message: bytes = b'') -> bool: ...
    async def receive(self, timeout: float | None = None) -> WSMessage: ...
    async def receive_str(self, *, timeout: float | None = None) -> str: ...
    async def receive_bytes(self, *, timeout: float | None = None) -> bytes: ...
    async def receive_json(self, *, loads: JSONDecoder = ..., timeout: float | None = None) -> Any: ...
    async def write(self, data: bytes) -> None: ...
    def __aiter__(self) -> WebSocketResponse: ...
    async def __anext__(self) -> WSMessage: ...
