import abc
from .abc import AbstractView
from .typedefs import PathLike
from .web_urldispatcher import AbstractRoute, UrlDispatcher
from typing import Any, Dict, Iterator, List, Sequence, Type, overload

__all__ = ['AbstractRouteDef', 'RouteDef', 'StaticDef', 'RouteTableDef', 'head', 'options', 'get', 'post', 'patch', 'put', 'delete', 'route', 'view', 'static']

class AbstractRouteDef(abc.ABC, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def register(self, router: UrlDispatcher) -> List[AbstractRoute]: ...

class RouteDef(AbstractRouteDef):
    method: str
    path: str
    handler: _HandlerType
    kwargs: Dict[str, Any]
    def register(self, router: UrlDispatcher) -> List[AbstractRoute]: ...
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class StaticDef(AbstractRouteDef):
    prefix: str
    path: PathLike
    kwargs: Dict[str, Any]
    def register(self, router: UrlDispatcher) -> List[AbstractRoute]: ...
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

def route(method: str, path: str, handler: _HandlerType, **kwargs: Any) -> RouteDef: ...
def head(path: str, handler: _HandlerType, **kwargs: Any) -> RouteDef: ...
def options(path: str, handler: _HandlerType, **kwargs: Any) -> RouteDef: ...
def get(path: str, handler: _HandlerType, *, name: str | None = None, allow_head: bool = True, **kwargs: Any) -> RouteDef: ...
def post(path: str, handler: _HandlerType, **kwargs: Any) -> RouteDef: ...
def put(path: str, handler: _HandlerType, **kwargs: Any) -> RouteDef: ...
def patch(path: str, handler: _HandlerType, **kwargs: Any) -> RouteDef: ...
def delete(path: str, handler: _HandlerType, **kwargs: Any) -> RouteDef: ...
def view(path: str, handler: Type[AbstractView], **kwargs: Any) -> RouteDef: ...
def static(prefix: str, path: PathLike, **kwargs: Any) -> StaticDef: ...

class RouteTableDef(Sequence[AbstractRouteDef]):
    """Route definition table"""
    def __init__(self) -> None: ...
    @overload
    def __getitem__(self, index: int) -> AbstractRouteDef: ...
    @overload
    def __getitem__(self, index: slice) -> List[AbstractRouteDef]: ...
    def __iter__(self) -> Iterator[AbstractRouteDef]: ...
    def __len__(self) -> int: ...
    def __contains__(self, item: object) -> bool: ...
    def route(self, method: str, path: str, **kwargs: Any) -> _Deco: ...
    def head(self, path: str, **kwargs: Any) -> _Deco: ...
    def get(self, path: str, **kwargs: Any) -> _Deco: ...
    def post(self, path: str, **kwargs: Any) -> _Deco: ...
    def put(self, path: str, **kwargs: Any) -> _Deco: ...
    def patch(self, path: str, **kwargs: Any) -> _Deco: ...
    def delete(self, path: str, **kwargs: Any) -> _Deco: ...
    def options(self, path: str, **kwargs: Any) -> _Deco: ...
    def view(self, path: str, **kwargs: Any) -> _Deco: ...
    def static(self, prefix: str, path: PathLike, **kwargs: Any) -> None: ...
