import asyncio
from .web_protocol import RequestHandler, _RequestFactory, _RequestHandler
from _typeshed import Incomplete
from typing import Any, List

__all__ = ['Server']

class Server:
    requests_count: int
    request_handler: Incomplete
    request_factory: Incomplete
    def __init__(self, handler: _RequestHandler, *, request_factory: _RequestFactory | None = None, loop: asyncio.AbstractEventLoop | None = None, **kwargs: Any) -> None: ...
    @property
    def connections(self) -> List[RequestHandler]: ...
    def connection_made(self, handler: RequestHandler, transport: asyncio.Transport) -> None: ...
    def connection_lost(self, handler: RequestHandler, exc: BaseException | None = None) -> None: ...
    async def shutdown(self, timeout: float | None = None) -> None: ...
    def __call__(self) -> RequestHandler: ...
