from keras.integration_test.models.input_spec import InputSpec as InputSpec

TIMESTEPS: int
INPUT_DIM: int
OUTPUT_DIM: int
NUM_RNN_LAYERS: int
RNN_UNITS: int

def get_input_preprocessor() -> None: ...
def get_data_spec(batch_size): ...
def ctc_loss(y_true, y_pred): ...
def get_model(build: bool = False, compile: bool = False, jit_compile: bool = False, include_preprocessing: bool = True): ...
def get_custom_objects(): ...
