from _typeshed import Incomplete
from keras.integration_test.models.input_spec import InputSpec as InputSpec

IMG_SIZE: Incomplete

def get_data_spec(batch_size): ...
def get_input_preprocessor(): ...
def get_model(build: bool = False, compile: bool = False, jit_compile: bool = False, include_preprocessing: bool = True): ...
def get_custom_objects(): ...
