from _typeshed import Incomplete
from gevent._ffi.loop import AbstractCallbacks, AbstractLoop, EVENTS

__all__ = ['get_version', 'get_header_version', 'supported_backends', 'recommended_backends', 'embeddable_backends', 'time', 'loop']

class _Callbacks(AbstractCallbacks):
    def python_check_callback(self, *args) -> None: ...
    def python_prepare_callback(self, _loop_ptr, watcher_ptr, _events) -> None: ...
GEVENT_CORE_EVENTS = EVENTS

def get_version(): ...
def get_header_version(): ...
def supported_backends(): ...
def recommended_backends(): ...
def embeddable_backends(): ...
def time(): ...

class loop(AbstractLoop):
    approx_timer_resolution: float
    error_handler: Incomplete
    def __init__(self, flags: Incomplete | None = None, default: Incomplete | None = None) -> None: ...
    def destroy(self) -> None: ...
    @property
    def MAXPRI(self): ...
    @property
    def MINPRI(self): ...
    def run(self, nowait: bool = False, once: bool = False) -> None: ...
    def reinit(self) -> None: ...
    def ref(self) -> None: ...
    def unref(self) -> None: ...
    def break_(self, how=...) -> None: ...
    def verify(self) -> None: ...
    def now(self): ...
    def update_now(self) -> None: ...
    @property
    def iteration(self): ...
    @property
    def depth(self): ...
    @property
    def backend_int(self): ...
    @property
    def backend(self): ...
    @property
    def pendingcnt(self): ...
    def closing_fd(self, fd): ...
    def install_sigchld(self) -> None: ...
    def reset_sigchld(self) -> None: ...
    def fileno(self): ...
    @property
    def activecnt(self): ...
