from ..public import PanelMetricsHelper as PanelMetricsHelper
from .validators import TypeValidator as TypeValidator, UNDEFINED_TYPE as UNDEFINED_TYPE, Validator as Validator
from _typeshed import Incomplete
from typing import Any, Callable, Dict, Generic, List, Tuple, TypeVar

T = TypeVar('T')
V = TypeVar('V')
Func = Callable[[T], V]

def generate_name(length: int = 12) -> str:
    """Generate a random name.

    This implementation roughly based the following snippet in core:
    https://github.com/wandb/core/blob/master/lib/js/cg/src/utils/string.ts#L39-L44.
    """
def coalesce(*arg: Any) -> Any:
    """Return the first non-none value in the list of arguments.

    Similar to ?? in C#.
    """
def nested_get(json: dict, keys: str) -> Any:
    """Get the element at the terminal node of a nested JSON dict based on `path`.

    The first item of the path can be an object.
    """
def nested_set(json: dict, keys: str, value: Any) -> None:
    """Set the element at the terminal node of a nested JSON dict based on `path`.

    The first item of the path can be an object.

    If nodes do not exist, they are created along the way.
    """

class Property(Generic[T]):
    """Property descriptor with a default getter and setter."""
    fget: Incomplete
    fset: Incomplete
    name: str
    def __init__(self, fget: Func | None = None, fset: Func | None = None) -> None: ...
    def __set_name__(self, owner: Any, name: str) -> None: ...
    def __get__(self, obj: Any, objtype: Any | None = None) -> T: ...
    def __set__(self, obj: Any, value: Any) -> None: ...
    def getter(self, fget: Func) -> Func: ...
    def setter(self, fset: Func) -> Func: ...
    def default_fget(self, obj: Any) -> Any: ...
    def default_fset(self, obj: Any, value: Any) -> None: ...

class Validated(Property):
    validators: Incomplete
    def __init__(self, *args: Func, validators: List[Validator] | None = None, **kwargs: Func) -> None: ...
    def __set__(self, instance: Any, value: Any) -> None: ...

class Typed(Validated):
    type: Incomplete
    validators: Incomplete
    def __set_name__(self, owner: Any, name: str) -> None: ...

class JSONLinked(Property):
    """Property that is linked to one or more JSON keys."""
    path_or_name: Incomplete
    def __init__(self, *args: Func, json_path: str | List[str] | None = None, **kwargs: Func) -> None: ...
    def __set_name__(self, owner: Any, name: str) -> None: ...
    def getter(self, fget: Func) -> Func: ...
    def setter(self, fset: Func) -> Func: ...
    def default_fget(self, obj: Any) -> Any | List[Any]: ...
    def default_fset(self, obj: Any, value: Any) -> None: ...

class Attr(Typed, JSONLinked):
    def getter(self, fget: Func) -> Func: ...
    def setter(self, fset: Func) -> Func: ...

class SubclassOnlyABC:
    def __new__(cls, *args: Any, **kwargs: Any) -> T: ...

class ShortReprMixin: ...

class Base(SubclassOnlyABC, ShortReprMixin):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def spec(self) -> Dict[str, Any]: ...
    @classmethod
    def from_json(cls, spec: Dict[str, Any]) -> T: ...

class Panel(Base, SubclassOnlyABC):
    layout: dict
    panel_metrics_helper: Incomplete
    def __init__(self, layout: Dict[str, int] | None = None, *args: Any, **kwargs: Any) -> None: ...
    @property
    def view_type(self) -> str: ...
    @property
    def config(self) -> Dict[str, Any]: ...
    @layout.setter
    def layout(self, d: Dict[str, int]) -> None: ...

class Block(Base, SubclassOnlyABC): ...

def fix_collisions(panels: List[Panel]) -> List[Panel]: ...
def collides(p1: Panel, p2: Panel) -> bool: ...
def shift(p1: Panel, p2: Panel) -> Tuple[Panel, Panel]: ...

class InlineLaTeX(Base):
    latex: str
    def __init__(self, latex: str = '', *args, **kwargs) -> None: ...
    @property
    def spec(self) -> dict: ...

class InlineCode(Base):
    code: str
    def __init__(self, code: str = '', *args, **kwargs) -> None: ...
    @property
    def spec(self) -> dict: ...

class Link(Base):
    text: str
    url: str
    def __init__(self, text, url, *args, **kwargs) -> None: ...
    @property
    def spec(self) -> dict: ...

def weave_inputs(spec): ...
