import abc
import wandb.vendor.watchdog_0_9_0.observers.api as wd_api
from _typeshed import Incomplete
from typing import Any
from wandb import util as util
from wandb.sdk.interface.interface import GlobStr as GlobStr, PolicyName as PolicyName
from wandb.sdk.internal.file_pusher import FilePusher as FilePusher
from wandb.sdk.internal.settings_static import SettingsStatic as SettingsStatic
from wandb.sdk.lib.paths import LogicalPath as LogicalPath

PathStr = str
logger: Incomplete

class FileEventHandler(abc.ABC, metaclass=abc.ABCMeta):
    file_path: Incomplete
    save_name: Incomplete
    def __init__(self, file_path: PathStr, save_name: LogicalPath, file_pusher: FilePusher, *args: Any, **kwargs: Any) -> None: ...
    @property
    @abc.abstractmethod
    def policy(self) -> PolicyName: ...
    @abc.abstractmethod
    def on_modified(self, force: bool = False) -> None: ...
    @abc.abstractmethod
    def finish(self) -> None: ...
    def on_renamed(self, new_path: PathStr, new_name: LogicalPath) -> None: ...

class PolicyNow(FileEventHandler):
    """This policy only uploads files now."""
    def on_modified(self, force: bool = False) -> None: ...
    def finish(self) -> None: ...
    @property
    def policy(self) -> PolicyName: ...

class PolicyEnd(FileEventHandler):
    """This policy only updates at the end of the run."""
    def on_modified(self, force: bool = False) -> None: ...
    def finish(self) -> None: ...
    @property
    def policy(self) -> PolicyName: ...

class PolicyLive(FileEventHandler):
    """Event handler that uploads respecting throttling.

    Uploads files every RATE_LIMIT_SECONDS, which changes as the size increases to deal
    with throttling.
    """
    RATE_LIMIT_SECONDS: int
    unit_dict: Incomplete
    RATE_LIMIT_SIZE_INCREASE: float
    def __init__(self, file_path: PathStr, save_name: LogicalPath, file_pusher: FilePusher, settings: SettingsStatic | None = None, *args: Any, **kwargs: Any) -> None: ...
    @property
    def current_size(self) -> int: ...
    @classmethod
    def min_wait_for_size(cls, size: int) -> float: ...
    def should_update(self) -> bool: ...
    def on_modified(self, force: bool = False) -> None: ...
    def save_file(self) -> None: ...
    def finish(self) -> None: ...
    @property
    def policy(self) -> PolicyName: ...

class DirWatcher:
    def __init__(self, settings: SettingsStatic, file_pusher: FilePusher, file_dir: PathStr | None = None) -> None: ...
    @property
    def emitter(self) -> wd_api.EventEmitter | None: ...
    def update_policy(self, path: GlobStr, policy: PolicyName) -> None: ...
    def finish(self) -> None: ...
