from _typeshed import Incomplete
from transformers import CLIPConfig as CLIPConfig, CLIPModel as CLIPModel

def copy_attn_layer(hf_attn_layer, pt_attn_layer) -> None: ...
def copy_mlp(hf_mlp, pt_mlp) -> None: ...
def copy_linear(hf_linear, pt_linear) -> None: ...
def copy_layer(hf_layer, pt_layer) -> None: ...
def copy_layers(hf_layers, pt_layers) -> None: ...
def copy_encoder(hf_encoder, pt_model) -> None: ...
def copy_text_model_and_projection(hf_model, pt_model) -> None: ...
def copy_vison_model_and_projection(hf_model, pt_model) -> None: ...
def convert_clip_checkpoint(checkpoint_path, pytorch_dump_folder_path, config_path: Incomplete | None = None) -> None:
    """
    Copy/paste/tweak model's weights to transformers design.
    """
