import threading
from _typeshed import Incomplete

__all__ = ['app']

class CollocationsView:
    queue: Incomplete
    model: Incomplete
    top: Incomplete
    after: Incomplete
    def __init__(self) -> None: ...
    def set_result_size(self, **kwargs) -> None: ...
    current_page: int
    def reset_current_page(self) -> None: ...
    def handle_error_loading_corpus(self, event) -> None: ...
    def handle_corpus_loaded(self, event) -> None: ...
    def corpus_selected(self, *args) -> None: ...
    def previous(self) -> None: ...
    def __next__(self) -> None: ...
    def load_corpus(self, selection) -> None: ...
    def freeze_editable(self) -> None: ...
    def clear_results_box(self) -> None: ...
    def fire_event(self, event) -> None: ...
    def destroy(self, *e) -> None: ...
    def mainloop(self, *args, **kwargs) -> None: ...
    def unfreeze_editable(self) -> None: ...
    def set_paging_button_states(self) -> None: ...
    def write_results(self, results) -> None: ...

class CollocationsModel:
    result_count: Incomplete
    selected_corpus: Incomplete
    collocations: Incomplete
    CORPORA: Incomplete
    DEFAULT_CORPUS: Incomplete
    queue: Incomplete
    def __init__(self, queue) -> None: ...
    result_pages: Incomplete
    results_returned: int
    def reset_results(self) -> None: ...
    def load_corpus(self, name) -> None: ...
    def non_default_corpora(self): ...
    def is_last_page(self, number): ...
    def next(self, page): ...
    def prev(self, page): ...
    class LoadCorpus(threading.Thread):
        def __init__(self, name, model) -> None: ...
        def run(self) -> None: ...

def app() -> None: ...
