from _typeshed import Incomplete

__all__ = ['app']

class ShiftReduceApp:
    '''
    A graphical tool for exploring the shift-reduce parser.  The tool
    displays the parser\'s stack and the remaining text, and allows the
    user to control the parser\'s operation.  In particular, the user
    can shift tokens onto the stack, and can perform reductions on the
    top elements of the stack.  A "step" button simply steps through
    the parsing process, performing the operations that
    ``nltk.parse.ShiftReduceParser`` would use.
    '''
    def __init__(self, grammar, sent, trace: int = 0) -> None: ...
    def destroy(self, *e) -> None: ...
    def reset(self, *e) -> None: ...
    def step(self, *e): ...
    def shift(self, *e): ...
    def reduce(self, *e): ...
    def undo(self, *e) -> None: ...
    def postscript(self, *e) -> None: ...
    def mainloop(self, *args, **kwargs) -> None:
        """
        Enter the Tkinter mainloop.  This function must be called if
        this demo is created from a non-interactive program (e.g.
        from a secript); otherwise, the demo will close as soon as
        the script completes.
        """
    def resize(self, size: Incomplete | None = None) -> None: ...
    def help(self, *e) -> None: ...
    def about(self, *e) -> None: ...
    def edit_grammar(self, *e) -> None: ...
    def set_grammar(self, grammar) -> None: ...
    def edit_sentence(self, *e) -> None: ...
    def set_sentence(self, sent) -> None: ...

def app() -> None:
    """
    Create a shift reduce parser app, using a simple grammar and
    text.
    """
