from _typeshed import Incomplete
from fontTools.misc.intTools import bit_count as bit_count
from fontTools.misc.roundTools import noRound as noRound, otRound as otRound
from fontTools.varLib.builder import buildVarData as buildVarData, buildVarRegion as buildVarRegion, buildVarRegionList as buildVarRegionList, buildVarStore as buildVarStore
from fontTools.varLib.models import supportScalar as supportScalar

NO_VARIATION_INDEX: Incomplete

class OnlineVarStoreBuilder:
    def __init__(self, axisTags) -> None: ...
    def setModel(self, model) -> None: ...
    def setSupports(self, supports) -> None: ...
    def finish(self, optimize: bool = True): ...
    def storeMasters(self, master_values, *, round=...): ...
    def storeMastersMany(self, master_values_list, *, round=...): ...
    def storeDeltas(self, deltas, *, round=...): ...
    def storeDeltasMany(self, deltas_list, *, round=...): ...

def VarData_addItem(self, deltas, *, round=...) -> None: ...
def VarRegion_get_support(self, fvar_axes): ...
def VarStore___bool__(self): ...

class VarStoreInstancer:
    fvar_axes: Incomplete
    def __init__(self, varstore, fvar_axes, location={}) -> None: ...
    location: Incomplete
    def setLocation(self, location) -> None: ...
    @staticmethod
    def interpolateFromDeltasAndScalars(deltas, scalars): ...
    def __getitem__(self, varidx): ...
    def interpolateFromDeltas(self, varDataIndex, deltas): ...

def VarStore_subset_varidxes(self, varIdxes, optimize: bool = True, retainFirstMap: bool = False, advIdxes=..., *, VarData: str = 'VarData'): ...
def VarStore_prune_regions(self, *, VarData: str = 'VarData', VarRegionList: str = 'VarRegionList') -> None:
    """Remove unused VarRegions."""
def Object_collect_device_varidxes(self, varidxes) -> None: ...
def Object_remap_device_varidxes(self, varidxes_map) -> None: ...

class _Encoding:
    chars: Incomplete
    width: Incomplete
    columns: Incomplete
    overhead: Incomplete
    items: Incomplete
    def __init__(self, chars) -> None: ...
    def append(self, row) -> None: ...
    def extend(self, lst) -> None: ...
    def get_room(self):
        """Maximum number of bytes that can be added to characteristic
        while still being beneficial to merge it into another one."""
    room: Incomplete
    def get_gain(self):
        """Maximum possible byte gain from merging this into another
        characteristic."""
    gain: Incomplete
    def gain_sort_key(self): ...
    def width_sort_key(self): ...
    def gain_from_merging(self, other_encoding): ...

class _EncodingDict(dict):
    def __missing__(self, chars): ...
    def add_row(self, row) -> None: ...

def VarStore_optimize(self, use_NO_VARIATION_INDEX: bool = True, quantization: int = 1):
    """Optimize storage. Returns mapping from old VarIdxes to new ones."""
def main(args: Incomplete | None = None) -> None:
    """Optimize a font's GDEF variation store"""
