from ._bsr import bsr_matrix as bsr_matrix
from ._coo import coo_matrix as coo_matrix
from ._csc import csc_matrix as csc_matrix
from ._csr import csr_matrix as csr_matrix
from ._dia import dia_matrix as dia_matrix
from ._dok import dok_matrix as dok_matrix
from ._lil import lil_matrix as lil_matrix

class _sparray:
    """This class provides a base class for all sparse arrays.

    It cannot be instantiated.  Most of the work is provided by subclasses.
    """
    def __mul__(self, *args, **kwargs): ...
    def __rmul__(self, *args, **kwargs): ...
    def __pow__(self, *args, **kwargs): ...

class bsr_array(_sparray, bsr_matrix): ...
class coo_array(_sparray, coo_matrix): ...
class csc_array(_sparray, csc_matrix): ...
class csr_array(_sparray, csr_matrix): ...
class dia_array(_sparray, dia_matrix): ...
class dok_array(_sparray, dok_matrix): ...
class lil_array(_sparray, lil_matrix): ...
