from _typeshed import Incomplete
from argparse import ArgumentDefaultsHelpFormatter, ArgumentParser, Namespace

__all__ = ['HelpFormatter', 'VirtualEnvConfigParser', 'VirtualEnvOptions']

class VirtualEnvOptions(Namespace):
    def __init__(self, **kwargs) -> None: ...
    def set_src(self, key, value, src) -> None: ...
    def __setattr__(self, key, value) -> None: ...
    def get_source(self, key): ...
    @property
    def verbosity(self): ...

class VirtualEnvConfigParser(ArgumentParser):
    """Custom option parser which updates its defaults by checking the configuration files and environmental vars."""
    file_config: Incomplete
    epilog_list: Incomplete
    env: Incomplete
    options: Incomplete
    def __init__(self, options: Incomplete | None = None, env: Incomplete | None = None, *args, **kwargs) -> None: ...
    def enable_help(self) -> None: ...
    def parse_known_args(self, args: Incomplete | None = None, namespace: Incomplete | None = None): ...

class HelpFormatter(ArgumentDefaultsHelpFormatter):
    def __init__(self, prog) -> None: ...
