from _typeshed import Incomplete
from sentry_sdk import configure_scope as configure_scope
from sentry_sdk._types import Event as Event, Hint as Hint, TYPE_CHECKING as TYPE_CHECKING
from sentry_sdk.hub import Hub as Hub
from sentry_sdk.integrations import Integration as Integration
from sentry_sdk.utils import capture_internal_exceptions as capture_internal_exceptions
from typing import Any

class SparkIntegration(Integration):
    identifier: str
    @staticmethod
    def setup_once() -> None: ...

def patch_spark_context_init() -> None: ...

class SparkListener:
    def onApplicationEnd(self, applicationEnd: Any) -> None: ...
    def onApplicationStart(self, applicationStart: Any) -> None: ...
    def onBlockManagerAdded(self, blockManagerAdded: Any) -> None: ...
    def onBlockManagerRemoved(self, blockManagerRemoved: Any) -> None: ...
    def onBlockUpdated(self, blockUpdated: Any) -> None: ...
    def onEnvironmentUpdate(self, environmentUpdate: Any) -> None: ...
    def onExecutorAdded(self, executorAdded: Any) -> None: ...
    def onExecutorBlacklisted(self, executorBlacklisted: Any) -> None: ...
    def onExecutorBlacklistedForStage(self, executorBlacklistedForStage: Any) -> None: ...
    def onExecutorMetricsUpdate(self, executorMetricsUpdate: Any) -> None: ...
    def onExecutorRemoved(self, executorRemoved: Any) -> None: ...
    def onJobEnd(self, jobEnd: Any) -> None: ...
    def onJobStart(self, jobStart: Any) -> None: ...
    def onNodeBlacklisted(self, nodeBlacklisted: Any) -> None: ...
    def onNodeBlacklistedForStage(self, nodeBlacklistedForStage: Any) -> None: ...
    def onNodeUnblacklisted(self, nodeUnblacklisted: Any) -> None: ...
    def onOtherEvent(self, event: Any) -> None: ...
    def onSpeculativeTaskSubmitted(self, speculativeTask: Any) -> None: ...
    def onStageCompleted(self, stageCompleted: Any) -> None: ...
    def onStageSubmitted(self, stageSubmitted: Any) -> None: ...
    def onTaskEnd(self, taskEnd: Any) -> None: ...
    def onTaskGettingResult(self, taskGettingResult: Any) -> None: ...
    def onTaskStart(self, taskStart: Any) -> None: ...
    def onUnpersistRDD(self, unpersistRDD: Any) -> None: ...
    class Java:
        implements: Incomplete

class SentryListener(SparkListener):
    hub: Incomplete
    def __init__(self) -> None: ...
    def onJobStart(self, jobStart: Any) -> None: ...
    def onJobEnd(self, jobEnd: Any) -> None: ...
    def onStageSubmitted(self, stageSubmitted: Any) -> None: ...
    def onStageCompleted(self, stageCompleted: Any) -> None: ...
