from . import DefaultTable as DefaultTable
from _typeshed import Incomplete
from fontTools.misc.textTools import safeEval as safeEval

class table_C_O_L_R_(DefaultTable.DefaultTable):
    """This table is structured so that you can treat it like a dictionary keyed by glyph name.

    ``ttFont['COLR'][<glyphName>]`` will return the color layers for any glyph.

    ``ttFont['COLR'][<glyphName>] = <value>`` will set the color layers for any glyph.
    """
    version: Incomplete
    ColorLayers: Incomplete
    table: Incomplete
    def decompile(self, data, ttFont) -> None: ...
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
    def __getitem__(self, glyphName): ...
    def __setitem__(self, glyphName, value) -> None: ...
    def __delitem__(self, glyphName) -> None: ...

class LayerRecord:
    name: Incomplete
    colorID: Incomplete
    def __init__(self, name: Incomplete | None = None, colorID: Incomplete | None = None) -> None: ...
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, eltname, attrs, content, ttFont) -> None: ...
