from . import Options as Options, PyrexTypes as PyrexTypes
from ..CodeWriter import ExpressionWriter as ExpressionWriter
from .Errors import warning as warning
from .StringEncoding import EncodedString as EncodedString
from .Visitor import CythonTransform as CythonTransform
from _typeshed import Incomplete

class AnnotationWriter(ExpressionWriter):
    """
    A Cython code writer for Python expressions in argument/variable annotations.
    """
    description: Incomplete
    incomplete: bool
    def __init__(self, description: Incomplete | None = None) -> None:
        """description is optional. If specified it is used in
        warning messages for the nodes that don't convert to string properly.
        If not specified then no messages are generated.
        """
    def visit_Node(self, node) -> None: ...
    def visit_LambdaNode(self, node) -> None: ...
    def visit_UnicodeNode(self, node) -> None: ...
    def visit_AnnotationNode(self, node) -> None: ...

class EmbedSignature(CythonTransform):
    class_name: Incomplete
    class_node: Incomplete
    def __init__(self, context) -> None: ...
    def __call__(self, node): ...
    def visit_ClassDefNode(self, node): ...
    def visit_LambdaNode(self, node): ...
    def visit_DefNode(self, node): ...
    def visit_CFuncDefNode(self, node): ...
    def visit_PropertyNode(self, node): ...
