from . import DebugFlags as DebugFlags, Options as Options
from ..Utils import open_new_file as open_new_file
from _typeshed import Incomplete
from collections.abc import Generator

class _threadlocal: ...

threadlocal: Incomplete

class PyrexError(Exception): ...
class PyrexWarning(Exception): ...
class CannotSpecialize(PyrexError): ...

def context(position): ...
def format_position(position): ...
def format_error(message, position): ...

class CompileError(PyrexError):
    position: Incomplete
    message_only: Incomplete
    formatted_message: Incomplete
    reported: bool
    args: Incomplete
    def __init__(self, position: Incomplete | None = None, message: str = '') -> None: ...

class CompileWarning(PyrexWarning):
    position: Incomplete
    def __init__(self, position: Incomplete | None = None, message: str = '') -> None: ...

class InternalError(Exception):
    message_only: Incomplete
    def __init__(self, message) -> None: ...

class AbortError(Exception):
    message_only: Incomplete
    def __init__(self, message) -> None: ...

class CompilerCrash(CompileError):
    message_only: Incomplete
    args: Incomplete
    def __init__(self, pos, context, message, cause, stacktrace: Incomplete | None = None) -> None: ...

class NoElementTreeInstalledException(PyrexError):
    """raised when the user enabled options.gdb_debug but no ElementTree
    implementation was found
    """

def open_listing_file(path, echo_to_stderr: bool = True) -> None: ...
def close_listing_file() -> None: ...
def report_error(err, use_stack: bool = True) -> None: ...
def error(position, message): ...

LEVEL: int

def performance_hint(position, message, env): ...
def message(position, message, level: int = 1): ...
def warning(position, message, level: int = 0): ...
def warn_once(position, message, level: int = 0): ...
def hold_errors(): ...
def release_errors(ignore: bool = False) -> None: ...
def held_errors(): ...
def local_errors(ignore: bool = False) -> Generator[Incomplete, None, None]: ...
def init_thread() -> None: ...
def reset() -> None: ...
def get_errors_count(): ...
