from .PyrexTypes import CStructOrUnionType as CStructOrUnionType, CType as CType, CTypedefType as CTypedefType
from _typeshed import Incomplete

pythran_is_pre_0_9: Incomplete
pythran_is_pre_0_9_6: Incomplete
pythran_builtins: str

def has_np_pythran(env): ...
def is_pythran_supported_dtype(type_): ...
def pythran_type(Ty, ptype: str = 'ndarray'): ...
def type_remove_ref(ty): ...
def pythran_binop_type(op, tA, tB): ...
def pythran_unaryop_type(op, type_): ...
def pythran_indexing_type(type_, indices): ...
def pythran_indexing_code(indices): ...
def np_func_to_list(func): ...
def pythran_is_numpy_func_supported(name): ...
def pythran_functor(func): ...
def pythran_func_type(func, args): ...
def to_pythran(op, ptype: Incomplete | None = None): ...
def is_type(type_, types): ...
def is_pythran_supported_node_or_none(node): ...
def is_pythran_supported_type(type_): ...
def is_pythran_supported_operation_type(type_): ...
def is_pythran_expr(type_): ...
def is_pythran_buffer(type_): ...
def pythran_get_func_include_file(func): ...
def include_pythran_generic(env) -> None: ...
