from .. import Utils as Utils
from ..Plex.Errors import UnrecognizedInput as UnrecognizedInput
from ..Plex.Scanners import Scanner as Scanner
from .Errors import CompileError as CompileError, error as error, hold_errors as hold_errors, release_errors as release_errors, warning as warning
from .Future import print_function as print_function
from .Lexicon import IDENT as IDENT, any_string_prefix as any_string_prefix, make_lexicon as make_lexicon
from _typeshed import Incomplete
from collections.abc import Generator

debug_scanner: int
trace_scanner: int
scanner_debug_flags: int
scanner_dump_file: Incomplete
lexicon: Incomplete

def get_lexicon(): ...

py_reserved_words: Incomplete
pyx_reserved_words: Incomplete

class CompileTimeScope:
    entries: Incomplete
    outer: Incomplete
    def __init__(self, outer: Incomplete | None = None) -> None: ...
    def declare(self, name, value) -> None: ...
    def update(self, other) -> None: ...
    def lookup_here(self, name): ...
    def __contains__(self, name) -> bool: ...
    def lookup(self, name): ...

def initial_compile_time_env(): ...

class SourceDescriptor:
    """
    A SourceDescriptor should be considered immutable.
    """
    filename: Incomplete
    in_utility_code: bool
    def set_file_type_from_name(self, filename) -> None: ...
    def is_cython_file(self): ...
    def is_python_file(self): ...
    def get_escaped_description(self): ...
    def __gt__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __copy__(self): ...
    def __deepcopy__(self, memo): ...

class FileSourceDescriptor(SourceDescriptor):
    '''
    Represents a code source. A code source is a more generic abstraction
    for a "filename" (as sometimes the code doesn\'t come from a file).
    Instances of code sources are passed to Scanner.__init__ as the
    optional name argument and will be passed back when asking for
    the position()-tuple.
    '''
    path_description: Incomplete
    filename: Incomplete
    file_path: Incomplete
    def __init__(self, filename, path_description: Incomplete | None = None) -> None: ...
    def get_lines(self, encoding: Incomplete | None = None, error_handling: Incomplete | None = None): ...
    def get_description(self): ...
    def get_error_description(self): ...
    def get_filenametable_entry(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class StringSourceDescriptor(SourceDescriptor):
    """
    Instances of this class can be used instead of a filenames if the
    code originates from a string object.
    """
    name: Incomplete
    codelines: Incomplete
    def __init__(self, name, code) -> None: ...
    def get_lines(self, encoding: Incomplete | None = None, error_handling: Incomplete | None = None): ...
    def get_description(self): ...
    get_error_description = get_description
    def get_filenametable_entry(self): ...
    def __hash__(self): ...
    def __eq__(self, other): ...

class PyrexScanner(Scanner):
    in_python_file: bool
    keywords: Incomplete
    async_enabled: int
    context: Incomplete
    included_files: Incomplete
    compile_time_env: Incomplete
    compile_time_eval: Incomplete
    compile_time_expr: Incomplete
    parse_comments: Incomplete
    source_encoding: Incomplete
    trace: Incomplete
    indentation_stack: Incomplete
    indentation_char: Incomplete
    bracket_nesting_level: int
    put_back_on_failure: Incomplete
    sy: str
    def __init__(self, file, filename, parent_scanner: Incomplete | None = None, scope: Incomplete | None = None, context: Incomplete | None = None, source_encoding: Incomplete | None = None, parse_comments: bool = True, initial_pos: Incomplete | None = None) -> None: ...
    def normalize_ident(self, text) -> None: ...
    def commentline(self, text) -> None: ...
    def strip_underscores(self, text, symbol) -> None: ...
    def current_level(self): ...
    def open_bracket_action(self, text): ...
    def close_bracket_action(self, text): ...
    def newline_action(self, text) -> None: ...
    string_states: Incomplete
    def begin_string_action(self, text) -> None: ...
    def end_string_action(self, text) -> None: ...
    def unclosed_string_action(self, text) -> None: ...
    def indentation_action(self, text) -> None: ...
    def eof_action(self, text) -> None: ...
    systring: Incomplete
    def next(self) -> None: ...
    last_token_position_tuple: Incomplete
    def peek(self): ...
    def put_back(self, sy, systring, pos) -> None: ...
    def error(self, message, pos: Incomplete | None = None, fatal: bool = True) -> None: ...
    def error_at_scanpos(self, message) -> None: ...
    def expect(self, what, message: Incomplete | None = None) -> None: ...
    def expect_keyword(self, what, message: Incomplete | None = None) -> None: ...
    def expected(self, what, message: Incomplete | None = None) -> None: ...
    def expect_indent(self) -> None: ...
    def expect_dedent(self) -> None: ...
    def expect_newline(self, message: str = 'Expected a newline', ignore_semicolon: bool = False) -> None: ...
    def enter_async(self) -> None: ...
    def exit_async(self) -> None: ...

def tentatively_scan(scanner) -> Generator[Incomplete, None, None]: ...
