from dataclasses import dataclass
from sempy.fabric._client._rest_client import FabricRestClient as FabricRestClient, OperationStart as OperationStart
from sempy.fabric._token_provider import TokenProvider as TokenProvider
from sempy.fabric.exceptions import FabricHTTPException as FabricHTTPException

@dataclass
class JobStatus:
    status: str
    retry_after: int

class _FabricRestAPI:
    def __init__(self, token_provider: TokenProvider | None = None) -> None: ...
    def get_my_workspace_id(self) -> str: ...
    def create_workspace(self, display_name: str, capacity_id: str | None = None, description: str | None = None) -> str: ...
    def delete_workspace(self, workspace_id: str): ...
    def create_item(self, workspace_id: str, payload, lro_max_attempts: int, lro_operation_name: str) -> str: ...
    def create_lakehouse(self, workspace_id: str, display_name: str, description: str | None = None, lro_max_attempts: int = 10) -> str: ...
    def delete_item(self, workspace_id: str, artifact_id: str): ...
    def create_notebook(self, workspace_id: str, display_name: str, description: str | None = None, content: str | None = None, lro_max_attempts: int = 10) -> str: ...
    def run_item_job(self, workspace_id: str, item_id: str, jobType: str, executionData: dict | None = None) -> OperationStart: ...
    def run_notebook_job(self, workspace_id: str, notebook_id: str) -> OperationStart: ...
    def get_job_status(self, workspace_id: str, item_id: str, run_id: str) -> JobStatus: ...
    def list_items(self, workspace_id: str, type: str | None = None) -> list: ...
    def list_workspaces(self) -> list: ...
    def list_capacities(self): ...
