import abc
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from collections.abc import Generator
from torch._C._functorch import CFunctionalizeInterpreterPtr as CFunctionalizeInterpreterPtr, CGradInterpreterPtr as CGradInterpreterPtr, CInterpreter as CInterpreter, CJvpInterpreterPtr as CJvpInterpreterPtr, CVmapInterpreterPtr as CVmapInterpreterPtr, RandomnessType as RandomnessType, TransformType as TransformType, pop_dynamic_layer_stack as pop_dynamic_layer_stack, push_dynamic_layer_stack as push_dynamic_layer_stack
from typing import Any

class FuncTorchInterpreter(ABC, metaclass=abc.ABCMeta):
    def __init__(self, cptr: Any) -> None: ...
    @abstractmethod
    def process(self, op, args, kwargs): ...
    def lower(self): ...
    def level(self): ...
    def key(self): ...

def temporarily_pop_interpreter_stack() -> Generator[None, None, None]: ...

class VmapInterpreter(FuncTorchInterpreter):
    def __init__(self, cdata: CInterpreter) -> None: ...
    def process(self, op, args, kwargs): ...
    def batch_size(self): ...
    def randomness(self): ...

def nested(*contexts) -> Generator[Incomplete, None, None]: ...

class GradInterpreter(FuncTorchInterpreter):
    def __init__(self, cdata: CInterpreter) -> None: ...
    def lift(self, args, kwargs): ...
    def process(self, op, args, kwargs): ...
    def lower(self): ...
    def prev_grad_mode(self): ...

class JvpInterpreter(FuncTorchInterpreter):
    def __init__(self, cdata: CInterpreter) -> None: ...
    def lift(self, args, kwargs): ...
    def process(self, op, args, kwargs): ...
    def lower(self): ...
    def prev_fwd_grad_mode(self): ...

class FunctionalizeInterpreter(FuncTorchInterpreter):
    def __init__(self, cdata: CInterpreter) -> None: ...
    def process(self, op, args, kwargs): ...
    def functionalize_add_back_views(self): ...

def coerce_cinterpreter(cinterpreter: CInterpreter) -> FuncTorchInterpreter: ...
def retrieve_current_functorch_interpreter(): ...
def dispatch_functorch(op, args, kwargs): ...
