from collections.abc import Generator
from torch._C._functorch import get_single_level_autograd_function_allowed as get_single_level_autograd_function_allowed, set_single_level_autograd_function_allowed as set_single_level_autograd_function_allowed, unwrap_if_dead as unwrap_if_dead

def enable_single_level_autograd_function() -> Generator[None, None, None]: ...
def unwrap_dead_wrappers(args): ...
def exposed_in(module): ...
