from .types_base import Binding as Binding, CType as CType, Expr as Expr
from dataclasses import dataclass
from torchgen.api import cpp as cpp, dispatcher as dispatcher, functionalization as functionalization, native as native, structured as structured, translate as translate
from torchgen.model import BackendIndex as BackendIndex, FunctionSchema as FunctionSchema, NativeFunction as NativeFunction, NativeFunctionsGroup as NativeFunctionsGroup, NativeFunctionsViewGroup as NativeFunctionsViewGroup
from typing import Iterator, List, Sequence, Set

@dataclass(frozen=True)
class CppSignature:
    """
    A CppSignature represents a single overload in the C++ API.  For
    any given function schema, there may be multiple CppSignatures
    corresponding to it, based on how we desugar to C++.  See also
    CppSignatureGroup.
    """
    func: FunctionSchema
    method: bool
    faithful: bool
    symint: bool
    cpp_no_default_args: Set[str]
    fallback_binding: bool = ...
    def arguments(self) -> Sequence[Binding]: ...
    def name(self, *, suppress_symint_suffix: bool = False) -> str: ...
    def decl(self, *, name: str | None = None, prefix: str = '', is_redispatching_fn: bool = False, suppress_symint_suffix: bool = False) -> str: ...
    def defn(self, *, name: str | None = None, prefix: str = '', is_redispatching_fn: bool = False) -> str: ...
    def ptr_type(self) -> str: ...
    def type(self) -> str: ...
    def __init__(self, func, method, faithful, symint, cpp_no_default_args, fallback_binding) -> None: ...

@dataclass(frozen=True)
class CppSignatureGroup:
    func: FunctionSchema
    signature: CppSignature
    faithful_signature: CppSignature | None
    symint_signature: CppSignature | None
    symint_faithful_signature: CppSignature | None
    def most_faithful_signature(self) -> CppSignature: ...
    def signatures(self, *, symint: bool = True) -> Iterator[CppSignature]: ...
    @staticmethod
    def from_native_function(f: NativeFunction, *, method: bool, fallback_binding: bool = False) -> CppSignatureGroup: ...
    def __init__(self, func, signature, faithful_signature, symint_signature, symint_faithful_signature) -> None: ...

@dataclass(frozen=True)
class DispatcherSignature:
    func: FunctionSchema
    prefix: str = ...
    symint: bool = ...
    def arguments(self) -> List[Binding]: ...
    def name(self) -> str: ...
    def decl(self, name: str | None = None) -> str: ...
    def defn(self, name: str | None = None, *, is_redispatching_fn: bool = False) -> str: ...
    def exprs(self) -> List[Expr]: ...
    def returns_type(self) -> CType: ...
    def ptr_type(self) -> str: ...
    def type(self) -> str: ...
    @staticmethod
    def from_schema(func: FunctionSchema, *, prefix: str = '', symint: bool = True) -> DispatcherSignature: ...
    def __init__(self, func, prefix, symint) -> None: ...

@dataclass(frozen=True)
class NativeSignature:
    func: FunctionSchema
    symint: bool
    prefix: str = ...
    def name(self) -> str: ...
    def decl(self, name: str | None = None) -> str: ...
    def defn(self, name: str | None = None) -> str: ...
    def ptr_type(self) -> str: ...
    def arguments(self) -> List[Binding]: ...
    def returns_type(self) -> CType: ...
    def dispatcher_exprs(self) -> List[Expr]: ...
    def __init__(self, func, symint, prefix) -> None: ...

@dataclass(frozen=True)
class ViewInverseSignature:
    g: NativeFunctionsViewGroup
    def name(self) -> str: ...
    def decl(self) -> str: ...
    def __init__(self, g) -> None: ...

@dataclass(frozen=True)
class FunctionalizationLambda:
    g: NativeFunctionsViewGroup
    is_reverse: bool
    def captures(self) -> List[Expr]: ...
    def decl(self) -> str: ...
    def inner_call(self, *, reapply_views: bool | None = None) -> str: ...
    @staticmethod
    def from_func(g: NativeFunctionsViewGroup, *, is_reverse: bool) -> FunctionalizationLambda: ...
    def __init__(self, g, is_reverse) -> None: ...

@dataclass(frozen=True)
class StructuredImplSignature:
    g: NativeFunctionsGroup
    name: str
    def defn(self, name: str | None = None) -> str: ...
    def arguments(self) -> List[Binding]: ...
    def __init__(self, g, name) -> None: ...

def kernel_signature(f: NativeFunction, backend_index: BackendIndex, *, prefix: str = '') -> NativeSignature | DispatcherSignature: ...
