from pyspark.pandas.exceptions import PandasNotImplementedError as PandasNotImplementedError

def unsupported_function(class_name, method_name, deprecated: bool = False, reason: str = ''): ...
def unsupported_property(class_name, property_name, deprecated: bool = False, reason: str = ''): ...
