import requests
from _typeshed import Incomplete
from chromadb.auth import AbstractCredentials as AbstractCredentials, AuthInfoType as AuthInfoType, ClientAuthCredentialsProvider as ClientAuthCredentialsProvider, ClientAuthProtocolAdapter as ClientAuthProtocolAdapter, ClientAuthProvider as ClientAuthProvider, ServerAuthCredentialsProvider as ServerAuthCredentialsProvider
from chromadb.auth.registry import register_provider as register_provider, resolve_provider as resolve_provider
from chromadb.config import System as System
from pydantic import SecretStr
from typing import Any, TypeVar

T = TypeVar('T')
logger: Incomplete

class HtpasswdServerAuthCredentialsProvider(ServerAuthCredentialsProvider):
    bc: Incomplete
    def __init__(self, system: System) -> None: ...
    def validate_credentials(self, credentials: AbstractCredentials[T]) -> bool: ...

class HtpasswdFileServerAuthCredentialsProvider(HtpasswdServerAuthCredentialsProvider):
    def __init__(self, system: System) -> None: ...

class HtpasswdConfigurationServerAuthCredentialsProvider(HtpasswdServerAuthCredentialsProvider):
    def __init__(self, system: System) -> None: ...

class RequestsClientAuthProtocolAdapter(ClientAuthProtocolAdapter[requests.PreparedRequest]):
    class _Session(requests.Session):
        def __init__(self, protocol_adapter: ClientAuthProtocolAdapter[requests.PreparedRequest]) -> None: ...
        def send(self, request: requests.PreparedRequest, **kwargs: Any) -> requests.Response: ...
    def __init__(self, system: System) -> None: ...
    @property
    def session(self) -> requests.Session: ...
    def inject_credentials(self, injection_context: requests.PreparedRequest) -> None: ...

class ConfigurationClientAuthCredentialsProvider(ClientAuthCredentialsProvider[SecretStr]):
    def __init__(self, system: System) -> None: ...
    def get_credentials(self) -> SecretStr: ...
