from _typeshed import Incomplete
from keras.distribute import keras_correctness_test_base as keras_correctness_test_base
from keras.optimizers.legacy import gradient_descent as gradient_descent
from keras.testing_infra import test_utils as test_utils

class DistributionStrategyCnnCorrectnessTest(keras_correctness_test_base.TestDistributionStrategyCorrectnessBase):
    def get_model(self, initial_weights: Incomplete | None = None, distribution: Incomplete | None = None, input_shapes: Incomplete | None = None): ...
    def get_data(self): ...
    def get_data_with_partial_last_batch_eval(self): ...
    def test_cnn_correctness(self, distribution, use_numpy, use_validation_data) -> None: ...
    def test_cnn_with_batch_norm_correctness(self, distribution, use_numpy, use_validation_data) -> None: ...
    def test_cnn_with_sync_batch_norm_correctness(self, distribution, use_numpy, use_validation_data) -> None: ...
    def test_cnn_correctness_with_partial_last_batch_eval(self, distribution, use_numpy, use_validation_data) -> None: ...
    def test_cnn_with_batch_norm_correctness_and_partial_last_batch_eval(self, distribution, use_numpy, use_validation_data) -> None: ...
