import keras
import tensorflow.compat.v2 as tf
from _typeshed import Incomplete
from keras.distribute import model_collection_base as model_collection_base
from keras.optimizers.legacy import gradient_descent as gradient_descent

class SimpleFunctionalModel(model_collection_base.ModelAndInput):
    """A simple functional model and its inputs."""
    def get_model(self, **kwargs): ...
    def get_data(self): ...
    def get_batch_size(self): ...

class SimpleSequentialModel(model_collection_base.ModelAndInput):
    """A simple sequential model and its inputs."""
    def get_model(self, **kwargs): ...
    def get_data(self): ...
    def get_batch_size(self): ...

class _SimpleModel(keras.Model):
    def __init__(self) -> None: ...
    def call(self, inputs): ...

class SimpleSubclassModel(model_collection_base.ModelAndInput):
    """A simple subclass model and its data."""
    def get_model(self, **kwargs): ...
    def get_data(self): ...
    def get_batch_size(self): ...

class _SimpleModule(tf.Module):
    v: Incomplete
    def __init__(self) -> None: ...
    def __call__(self, x): ...

class SimpleTFModuleModel(model_collection_base.ModelAndInput):
    """A simple model based on tf.Module and its data."""
    def get_model(self, **kwargs): ...
    def get_data(self): ...
    def get_batch_size(self): ...
