import numpy
from optuna._imports import try_import as try_import
from typing import List, Tuple

class _Fanova:
    def __init__(self, n_trees: int, max_depth: int, min_samples_split: int | float, min_samples_leaf: int | float, seed: int | None) -> None: ...
    def fit(self, X: numpy.ndarray, y: numpy.ndarray, search_spaces: numpy.ndarray, column_to_encoded_columns: List[numpy.ndarray]) -> None: ...
    def get_importance(self, features: Tuple[int, ...]) -> Tuple[float, float]: ...
