import numpy
import sklearn.tree

class _FanovaTree:
    def __init__(self, tree: sklearn.tree._tree.Tree, search_spaces: numpy.ndarray) -> None: ...
    @property
    def variance(self) -> float: ...
    def get_marginal_variance(self, features: numpy.ndarray) -> float: ...
