from .aad_client_base import AadClientBase as AadClientBase
from .aadclient_certificate import AadClientCertificate as AadClientCertificate
from .pipeline import build_pipeline as build_pipeline
from azure.core.credentials import AccessToken as AccessToken
from azure.core.pipeline import Pipeline as Pipeline
from azure.core.pipeline.transport import HttpRequest as HttpRequest
from typing import Any, Iterable

class AadClient(AadClientBase):
    def __enter__(self): ...
    def __exit__(self, *args) -> None: ...
    def close(self) -> None: ...
    def obtain_token_by_authorization_code(self, scopes: Iterable[str], code: str, redirect_uri: str, client_secret: str | None = None, **kwargs: Any) -> AccessToken: ...
    def obtain_token_by_client_certificate(self, scopes: Iterable[str], certificate: AadClientCertificate, **kwargs: Any) -> AccessToken: ...
    def obtain_token_by_client_secret(self, scopes: Iterable[str], secret: str, **kwargs: Any) -> AccessToken: ...
    def obtain_token_by_jwt_assertion(self, scopes: Iterable[str], assertion: str, **kwargs: Any) -> AccessToken: ...
    def obtain_token_by_refresh_token(self, scopes: Iterable[str], refresh_token: str, **kwargs: Any) -> AccessToken: ...
    def obtain_token_on_behalf_of(self, scopes: Iterable[str], client_credential: str | AadClientCertificate, user_assertion: str, **kwargs: Any) -> AccessToken: ...
