import abc
from .. import CredentialUnavailableError as CredentialUnavailableError
from .._internal.get_token_mixin import GetTokenMixin as GetTokenMixin
from .._internal.managed_identity_client import ManagedIdentityClient as ManagedIdentityClient
from azure.core.credentials import AccessToken as AccessToken
from typing import Any

class ManagedIdentityBase(GetTokenMixin, metaclass=abc.ABCMeta):
    """Base class for internal credentials using ManagedIdentityClient"""
    def __init__(self, **kwargs: Any) -> None: ...
    @abc.abstractmethod
    def get_client(self, **kwargs: Any) -> ManagedIdentityClient | None: ...
    @abc.abstractmethod
    def get_unavailable_message(self) -> str: ...
    def __enter__(self): ...
    def __exit__(self, *args) -> None: ...
    def close(self) -> None: ...
    def get_token(self, *scopes: str, claims: str | None = None, tenant_id: str | None = None, **kwargs: Any) -> AccessToken: ...
