from _typeshed import Incomplete
from grpc.beta import implementations as implementations, interfaces as interfaces
from grpc.framework.foundation import callable_util as callable_util, future as future

class _ChannelReadyFuture(future.Future):
    def __init__(self, channel) -> None: ...
    def cancel(self): ...
    def cancelled(self): ...
    def running(self): ...
    def done(self): ...
    def result(self, timeout: Incomplete | None = None) -> None: ...
    def exception(self, timeout: Incomplete | None = None) -> None: ...
    def traceback(self, timeout: Incomplete | None = None) -> None: ...
    def add_done_callback(self, fn) -> None: ...
    def start(self) -> None: ...
    def __del__(self) -> None: ...

def channel_ready_future(channel):
    """Creates a future.Future tracking when an implementations.Channel is ready.

  Cancelling the returned future.Future does not tell the given
  implementations.Channel to abandon attempts it may have been making to
  connect; cancelling merely deactivates the return future.Future's
  subscription to the given implementations.Channel's connectivity.

  Args:
    channel: An implementations.Channel.

  Returns:
    A future.Future that matures when the given Channel has connectivity
      interfaces.ChannelConnectivity.READY.
  """
