import dataclasses
import torch
import torch._C._onnx as _C_onnx
from typing import Mapping, Sequence, Set, Type

@dataclasses.dataclass
class ExportOptions:
    """Arguments used by :func:`torch.onnx.export`.

    TODO: Adopt this in `torch.onnx.export` api to replace keyword arguments.
    """
    export_params: bool = ...
    verbose: bool = ...
    training: _C_onnx.TrainingMode = ...
    input_names: Sequence[str] | None = ...
    output_names: Sequence[str] | None = ...
    operator_export_type: _C_onnx.OperatorExportTypes = ...
    opset_version: int | None = ...
    do_constant_folding: bool = ...
    dynamic_axes: Mapping[str, Mapping[int, str] | Sequence[int]] | None = ...
    keep_initializers_as_inputs: bool | None = ...
    custom_opsets: Mapping[str, int] | None = ...
    export_modules_as_functions: bool | Set[Type[torch.nn.Module]] = ...
    def __init__(self, export_params, verbose, training, input_names, output_names, operator_export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, custom_opsets, export_modules_as_functions) -> None: ...
