from _typeshed import Incomplete
from torch.onnx import symbolic_helper as symbolic_helper
from torch.onnx._globals import GLOBALS as GLOBALS
from torch.onnx._internal import jit_utils as jit_utils, registration as registration

def hardswish(g: jit_utils.GraphContext, self): ...
def tril(g: jit_utils.GraphContext, self, diagonal, out: Incomplete | None = None): ...
def triu(g: jit_utils.GraphContext, self, diagonal, out: Incomplete | None = None): ...
def reshape(g: jit_utils.GraphContext, self, shape): ...
def batch_norm(g: jit_utils.GraphContext, input, weight, bias, running_mean, running_var, training, momentum, eps, cudnn_enabled): ...
def quantized_hardswish(g: jit_utils.GraphContext, x, op_scale, op_zero_point): ...
