from _typeshed import Incomplete
from torch.onnx import symbolic_helper as symbolic_helper
from torch.onnx._internal import jit_utils as jit_utils, registration as registration

def aten__is_(g: jit_utils.GraphContext, self, other): ...
def aten__isnot_(g: jit_utils.GraphContext, self, other): ...
def bernoulli(g: jit_utils.GraphContext, input, p: Incomplete | None = None, generator: Incomplete | None = None, out: Incomplete | None = None): ...
def prim_unchecked_cast(g: jit_utils.GraphContext, self): ...
