from collections.abc import Generator
from typing import Any, Dict, List

__all__ = ['preserve_node_meta', 'has_preserved_node_meta', 'set_stack_trace', 'format_stack', 'set_current_meta', 'get_current_meta']

def preserve_node_meta() -> Generator[None, None, None]: ...
def set_stack_trace(stack: List[str]): ...
def format_stack() -> List[str]: ...
def has_preserved_node_meta() -> bool: ...
def set_current_meta(meta: Dict[str, Any]): ...
def get_current_meta() -> Dict[str, Any]: ...
