import threading
from collections.abc import Generator

class LoadContext(threading.local):
    """A context for loading a model."""
    def __init__(self) -> None: ...
    def set_load_options(self, load_options) -> None: ...
    def clear_load_options(self) -> None: ...
    def load_options(self): ...
    def in_load_context(self): ...

def load_context(load_options) -> Generator[None, None, None]: ...
def get_load_options():
    """Returns the load options under a load context."""
def in_load_context():
    """Returns whether under a load context."""
