from .scoped_name import ScopedName as ScopedName
from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List

class AccessSpecifier(Enum):
    """ The class access specifiers. """
    PRIVATE: int
    PROTECTED: int
    PUBLIC: int

class ArgumentType(Enum):
    """ The types of either C/C++ or Python arguments.  The numerical values of
    these can occur in generated code so so types must always be appended and
    old (unused) types must never be removed.
    """
    NONE: int
    DEFINED: int
    CLASS: int
    STRUCT: int
    VOID: int
    ENUM: int
    TEMPLATE: int
    SIGNAL_UNUSED: int
    SLOT_UNUSED: int
    RXCON_UNUSED: int
    RXDIS_UNUSED: int
    SLOTCON_UNUSED: int
    SLOTDIS_UNUSED: int
    USTRING: int
    STRING: int
    SHORT: int
    USHORT: int
    CINT: int
    INT: int
    UINT: int
    LONG: int
    ULONG: int
    FLOAT: int
    CFLOAT: int
    DOUBLE: int
    CDOUBLE: int
    BOOL: int
    MAPPED: int
    PYOBJECT: int
    PYTUPLE: int
    PYLIST: int
    PYDICT: int
    PYCALLABLE: int
    PYSLICE: int
    QOBJECT_UNUSED: int
    FUNCTION: int
    PYTYPE: int
    ELLIPSIS: int
    LONGLONG: int
    ULONGLONG: int
    ANYSLOT_UNUSED: int
    CBOOL: int
    SSTRING: int
    WSTRING: int
    FAKE_VOID: int
    SSIZE: int
    ASCII_STRING: int
    LATIN1_STRING: int
    UTF8_STRING: int
    BYTE: int
    SBYTE: int
    UBYTE: int
    CAPSULE: int
    PYBUFFER: int
    SIZE: int
    PYENUM: int
    UNION: int
    HASH: int

class ArrayArgument(Enum):
    """ The array support provided by an argument. """
    ARRAY: int
    ARRAY_SIZE: int
    NONE: int

class ClassKey(Enum):
    """ The key that identifies a particular type of class. """
    CLASS: int
    STRUCT: int
    UNION: int

class DocstringFormat(Enum):
    """ The formatting applied to the text of the docstring. """
    DEINDENTED: int
    RAW: int

class DocstringSignature(Enum):
    """ The position of the automatically generated function or method
    signature relative to the docstring text.  In the context of a class's
    docstring then it applies to all the class's ctors.
    """
    APPENDED: int
    DISCARDED: int
    PREPENDED: int

class EnumBaseType(Enum):
    """ The different base types fo an enum. """
    ENUM: int
    FLAG: int
    INT_ENUM: int
    INT_FLAG: int
    UNSIGNED_INT_ENUM: int

class GILAction(Enum):
    """ The action to take with the GIL when calling C/C++ code. """
    DEFAULT: int
    HOLD: int
    RELEASE: int

class IfaceFileType(Enum):
    """ The type of an interface file. """
    EXCEPTION: int
    MAPPED_TYPE: int
    NAMESPACE: int
    CLASS: int

class KwArgs(Enum):
    """ The level of support for passing argument as keyword arguments. """
    ALL: int
    NONE: int
    OPTIONAL: int

class PyQtMethodSpecifier(Enum):
    """ The PyQt-specific method specifier. """
    SIGNAL: int
    SLOT: int

class PySlot(Enum):
    """ The Python slots corresponding to entries in a type object. """
    STR: int
    INT: int
    FLOAT: int
    LEN: int
    CONTAINS: int
    ADD: int
    CONCAT: int
    SUB: int
    MUL: int
    REPEAT: int
    MOD: int
    FLOORDIV: int
    TRUEDIV: int
    AND: int
    OR: int
    XOR: int
    LSHIFT: int
    RSHIFT: int
    IADD: int
    ICONCAT: int
    ISUB: int
    IMUL: int
    IREPEAT: int
    IMOD: int
    IFLOORDIV: int
    ITRUEDIV: int
    IAND: int
    IOR: int
    IXOR: int
    ILSHIFT: int
    IRSHIFT: int
    INVERT: int
    CALL: int
    GETITEM: int
    SETITEM: int
    DELITEM: int
    LT: int
    LE: int
    EQ: int
    NE: int
    GT: int
    GE: int
    BOOL: int
    NEG: int
    POS: int
    ABS: int
    REPR: int
    HASH: int
    INDEX: int
    ITER: int
    NEXT: int
    SETATTR: int
    DELATTR: int
    MATMUL: int
    IMATMUL: int
    AWAIT: int
    AITER: int
    ANEXT: int

class QualifierType(Enum):
    """ The type of a qualifier used in %If/%End directives. """
    FEATURE: int
    PLATFORM: int
    TIME: int

class Transfer(Enum):
    """ The different types of ownership transfer. """
    NONE: int
    TRANSFER: int
    TRANSFER_BACK: int
    TRANSFER_THIS: int

class ValueType(Enum):
    """ The different types of a value in an expression. """
    QCHAR: int
    STRING: int
    NUMERIC: int
    REAL: int
    SCOPED: int
    FCALL: int
    EMPTY: int

@dataclass
class Argument:
    """ Encapsulate a callable argument (or return value or variable type). """
    type: ArgumentType
    allow_none: bool = ...
    array: ArrayArgument = ...
    default_value: List['Value'] | None = ...
    definition: Any = ...
    derefs: List[bool] = ...
    disallow_none: bool = ...
    get_wrapper: bool = ...
    is_const: bool = ...
    is_constrained: bool = ...
    is_in: bool = ...
    is_out: bool = ...
    is_reference: bool = ...
    key: int | None = ...
    name: CachedName | None = ...
    no_copy: bool = ...
    original_typedef: WrappedTypedef | None = ...
    result_size: bool = ...
    scopes_stripped: int = ...
    source_location: SourceLocation | None = ...
    transfer: Transfer = ...
    type_hints: TypeHints | None = ...
    def __init__(self, type, allow_none, array, default_value, definition, derefs, disallow_none, get_wrapper, is_const, is_constrained, is_in, is_out, is_reference, key, name, no_copy, original_typedef, result_size, scopes_stripped, source_location, transfer, type_hints) -> None: ...

@dataclass
class CachedName:
    """ Encapsulate a name that may be needed as a string in the generated
    code.
    """
    name: str
    is_substring: bool = ...
    offset: int = ...
    used: bool = ...
    def __init__(self, name, is_substring, offset, used) -> None: ...

@dataclass
class CodeBlock:
    """ Encapsulate a code block, ie. the literal body of a directive. """
    sip_file: str
    line_nr: int = ...
    text: str = ...
    def __init__(self, sip_file, line_nr, text) -> None: ...

@dataclass
class Constructor:
    """ Encapsulate a constructor. """
    access_specifier: AccessSpecifier
    py_signature: Signature
    cpp_signature: Signature | None = ...
    deprecated: bool = ...
    docstring: Docstring | None = ...
    gil_action: GILAction = ...
    is_cast: bool = ...
    kw_args: KwArgs = ...
    method_code: CodeBlock | None = ...
    no_type_hint: bool = ...
    posthook: str | None = ...
    prehook: str | None = ...
    premethod_code: CodeBlock | None = ...
    raises_py_exception: bool = ...
    throw_args: ThrowArguments | None = ...
    transfer: Transfer = ...
    def __init__(self, access_specifier, py_signature, cpp_signature, deprecated, docstring, gil_action, is_cast, kw_args, method_code, no_type_hint, posthook, prehook, premethod_code, raises_py_exception, throw_args, transfer) -> None: ...

@dataclass
class Docstring:
    """ Encapsulate a docstring. """
    signature: DocstringSignature
    text: str
    def __init__(self, signature, text) -> None: ...

@dataclass
class Extract:
    """ Encapsulate a part of an extract. """
    id: str
    order: int
    text: str
    def __init__(self, id, order, text) -> None: ...

@dataclass
class FunctionCall:
    """ Encapsulate a call to a function in an expression. """
    result: Argument
    args: List[List['Value']]
    def __init__(self, result, args) -> None: ...

@dataclass
class IfaceFile:
    """ Encapsulate an interface file, ie. a generated source file. """
    type: IfaceFileType
    cpp_name: CachedName | None = ...
    file_extension: str | None = ...
    fq_cpp_name: ScopedName | None = ...
    type_nr: int = ...
    module: Module | None = ...
    needed: bool = ...
    type_header_code: List[CodeBlock] = ...
    used: List['IfaceFile'] = ...
    def __init__(self, type, cpp_name, file_extension, fq_cpp_name, type_nr, module, needed, type_header_code, used) -> None: ...

@dataclass
class License:
    """ Encapsulate a license. """
    type: str
    licensee: str | None = ...
    timestamp: str | None = ...
    signature: str | None = ...
    def __init__(self, type, licensee, timestamp, signature) -> None: ...

@dataclass
class MappedType:
    """ Encapsulate a mapped type. """
    iface_file: IfaceFile
    type: Argument
    convert_from_type_code: CodeBlock | None = ...
    convert_to_type_code: CodeBlock | None = ...
    cpp_name: CachedName | None = ...
    handles_none: bool = ...
    instance_code: CodeBlock | None = ...
    members: List['Member'] = ...
    needs_user_state: bool = ...
    no_assignment_operator: bool = ...
    no_copy_ctor: bool = ...
    no_default_ctor: bool = ...
    no_release: bool = ...
    overloads: List['Overload'] = ...
    py_name: CachedName | None = ...
    pyqt_flags: int = ...
    release_code: CodeBlock | None = ...
    type_code: List[CodeBlock] = ...
    type_hint_code: CodeBlock | None = ...
    type_hints: TypeHints | None = ...
    def __init__(self, iface_file, type, convert_from_type_code, convert_to_type_code, cpp_name, handles_none, instance_code, members, needs_user_state, no_assignment_operator, no_copy_ctor, no_default_ctor, no_release, overloads, py_name, pyqt_flags, release_code, type_code, type_hint_code, type_hints) -> None: ...

@dataclass
class MappedTypeTemplate:
    """ Encapsulate a mapped type template. """
    mapped_type: MappedType
    signature: Signature
    def __init__(self, mapped_type, signature) -> None: ...

@dataclass
class Member:
    """ Encapsulate a member function. """
    module: Module
    py_name: CachedName
    allow_keyword_args: bool = ...
    has_protected: bool = ...
    is_numeric: bool = ...
    is_sequence: bool = ...
    namespace_iface_file: IfaceFile | None = ...
    no_arg_parser: bool = ...
    py_slot: PySlot | None = ...
    def __init__(self, module, py_name, allow_keyword_args, has_protected, is_numeric, is_sequence, namespace_iface_file, no_arg_parser, py_slot) -> None: ...

@dataclass
class Module:
    """ Encapsulate a module. """
    all_imports: List['Module'] = ...
    call_super_init: bool = ...
    copying: List[CodeBlock] = ...
    default_docstring_format: DocstringFormat = ...
    default_docstring_signature: DocstringSignature = ...
    default_exception: WrappedException | None = ...
    default_metatype: CachedName | None = ...
    default_supertype: CachedName | None = ...
    default_virtual_error_handler: str | None = ...
    docstring: Docstring | None = ...
    fq_py_name: CachedName | None = ...
    global_functions: List[Member] = ...
    has_delayed_dtors: bool = ...
    imports: List['Module'] = ...
    initialisation_code: List[CodeBlock] = ...
    license: License | None = ...
    module_code: List[CodeBlock] = ...
    module_header_code: List[CodeBlock] = ...
    next_key: int = ...
    nr_exceptions: int = ...
    needed_types: List[Argument] = ...
    nr_typedefs: int = ...
    nr_virtual_error_handlers: int = ...
    overloads: List['Overload'] = ...
    postinitialisation_code: List[CodeBlock] = ...
    proxies: List['WrappedClass'] = ...
    preinitialisation_code: List[CodeBlock] = ...
    py_name: str | None = ...
    py_ssize_t_clean: bool = ...
    qualifiers: List['Qualifier'] = ...
    type_hint_code: List[CodeBlock] = ...
    unit_code: List[CodeBlock] = ...
    unit_postinclude_code: List[CodeBlock] = ...
    use_arg_names: bool = ...
    use_limited_api: bool = ...
    used: List[IfaceFile] = ...
    def __init__(self, all_imports, call_super_init, copying, default_docstring_format, default_docstring_signature, default_exception, default_metatype, default_supertype, default_virtual_error_handler, docstring, fq_py_name, global_functions, has_delayed_dtors, imports, initialisation_code, license, module_code, module_header_code, next_key, nr_exceptions, needed_types, nr_typedefs, nr_virtual_error_handlers, overloads, postinitialisation_code, proxies, preinitialisation_code, py_name, py_ssize_t_clean, qualifiers, type_hint_code, unit_code, unit_postinclude_code, use_arg_names, use_limited_api, used) -> None: ...

@dataclass
class Overload:
    """ Encapsulate an overloaded member function. """
    access_specifier: AccessSpecifier | None
    common: Member
    cpp_name: str
    cpp_signature: Signature
    py_signature: Signature
    abort_on_exception: bool = ...
    access_is_really_protected: bool = ...
    deprecated: bool = ...
    docstring: Docstring | None = ...
    factory: bool = ...
    gil_action: GILAction = ...
    is_abstract: bool = ...
    is_auto_generated: bool = ...
    is_complementary: bool = ...
    is_const: bool = ...
    is_delattr: bool = ...
    is_final: bool = ...
    is_global: bool = ...
    dont_deref_self: bool = ...
    is_reflected: bool = ...
    is_static: bool = ...
    is_virtual: bool = ...
    is_virtual_reimplementation: bool = ...
    kw_args: KwArgs = ...
    method_code: CodeBlock | None = ...
    new_thread: bool = ...
    no_type_hint: bool = ...
    no_virtual_error_handler: bool = ...
    posthook: str | None = ...
    prehook: str | None = ...
    premethod_code: CodeBlock | None = ...
    pyqt_method_specifier: PyQtMethodSpecifier | None = ...
    raises_py_exception: bool = ...
    source_location: SourceLocation | None = ...
    throw_args: ThrowArguments | None = ...
    transfer: Transfer = ...
    virtual_call_code: CodeBlock | None = ...
    virtual_catcher_code: CodeBlock | None = ...
    virtual_error_handler: str | None = ...
    def __init__(self, access_specifier, common, cpp_name, cpp_signature, py_signature, abort_on_exception, access_is_really_protected, deprecated, docstring, factory, gil_action, is_abstract, is_auto_generated, is_complementary, is_const, is_delattr, is_final, is_global, dont_deref_self, is_reflected, is_static, is_virtual, is_virtual_reimplementation, kw_args, method_code, new_thread, no_type_hint, no_virtual_error_handler, posthook, prehook, premethod_code, pyqt_method_specifier, raises_py_exception, source_location, throw_args, transfer, virtual_call_code, virtual_catcher_code, virtual_error_handler) -> None: ...

@dataclass
class Property:
    """ Encapsulate a property. """
    getter: str
    name: CachedName
    docstring: Docstring | None = ...
    setter: str | None = ...
    def __init__(self, getter, name, docstring, setter) -> None: ...

@dataclass
class Qualifier:
    """ Encapsulate a qualifier used in %If/%End directives. """
    module: Module
    name: str
    type: QualifierType
    enabled_by_default: bool = ...
    order: int = ...
    timeline: int = ...
    def __init__(self, module, name, type, enabled_by_default, order, timeline) -> None: ...

@dataclass
class Signature:
    """ Encapsulate a signature (including the optional result). """
    args: List[Argument] = ...
    result: Argument | None = ...
    def __init__(self, args, result) -> None: ...

@dataclass
class SourceLocation:
    """ Encapsulate a location in a .sip source file. """
    sip_file: str
    column: int = ...
    line: int = ...
    def __init__(self, sip_file, column, line) -> None: ...

@dataclass
class Specification:
    """ Encapsulate a parsed .sip file. """
    abi_version: tuple
    is_strict: bool
    sip_module: str | None
    c_bindings: bool = ...
    classes: List['WrappedClass'] = ...
    enums: List['WrappedEnum'] = ...
    exceptions: List['WrappedException'] = ...
    exported_header_code: List[CodeBlock] = ...
    exported_type_hint_code: List[CodeBlock] = ...
    extracts: List[Extract] = ...
    iface_files: List[IfaceFile] = ...
    is_composite: bool = ...
    mapped_type_templates: List[MappedTypeTemplate] = ...
    mapped_types: List[MappedType] = ...
    module: Module = ...
    name_cache: Dict[int, List[CachedName]] = ...
    nr_virtual_handlers: int = ...
    plugins: List[str] = ...
    pyqt_qobject: WrappedClass | None = ...
    typedefs: List['WrappedTypedef'] = ...
    variables: List['WrappedVariable'] = ...
    virtual_error_handlers: List['VirtualErrorHandler'] = ...
    virtual_handlers: List['VirtualHandler'] = ...
    def __hash__(self):
        """ Reimplemented so a Specification object can be used as a dict key.
        """
    def __init__(self, abi_version, is_strict, sip_module, c_bindings, classes, enums, exceptions, exported_header_code, exported_type_hint_code, extracts, iface_files, is_composite, mapped_type_templates, mapped_types, module, name_cache, nr_virtual_handlers, plugins, pyqt_qobject, typedefs, variables, virtual_error_handlers, virtual_handlers) -> None: ...

@dataclass
class Template:
    """ Encapsulate a template. """
    cpp_name: ScopedName
    types: Signature
    def __init__(self, cpp_name, types) -> None: ...

@dataclass
class ThrowArguments:
    """ Encapsulate the arguments to a C++ throw(). """
    arguments: List['WrappedException'] | None = ...
    def __init__(self, arguments) -> None: ...

@dataclass
class TypeHints:
    """ Encapsulate a set of PEP 484 type hints for a type. """
    hint_in: str | None
    hint_out: str | None
    default_value: str | None
    def __init__(self, hint_in, hint_out, default_value) -> None: ...

@dataclass
class Value:
    """ Encapsulate a literal value. """
    value_type: ValueType
    value: str | int | float | FunctionCall | ScopedName | None
    binary_operator: str | None = ...
    cast: ScopedName | None = ...
    unary_operator: str | None = ...
    def __init__(self, value_type, value, binary_operator, cast, unary_operator) -> None: ...

@dataclass
class VirtualErrorHandler:
    """ Encapsulate a virtual error handler. """
    code: CodeBlock
    module: Module
    name: str
    handler_nr: int = ...
    def __init__(self, code, module, name, handler_nr) -> None: ...

@dataclass
class VirtualHandler:
    """ Encapsulate a virtual overload handler. (resolver) """
    cpp_signature: Signature
    py_signature: Signature
    virtual_catcher_code: CodeBlock | None
    virtual_error_handler: VirtualErrorHandler
    abort_on_exception: bool = ...
    handler_nr: int = ...
    transfer_result: bool = ...
    def __init__(self, cpp_signature, py_signature, virtual_catcher_code, virtual_error_handler, abort_on_exception, handler_nr, transfer_result) -> None: ...

@dataclass
class VirtualOverload:
    """ Encapsulate a virtual overloaded member function. (resolver) """
    overload: Overload
    handler: VirtualHandler | None
    def __init__(self, overload, handler) -> None: ...

@dataclass
class VisibleMember:
    """ Encapsulate a visible member function. (resolver) """
    member: Member
    scope: WrappedClass
    def __init__(self, member, scope) -> None: ...

@dataclass
class WrappedClass:
    """ Encapsulate a wrapped C/C++ namespace/class/struct/union. """
    iface_file: IfaceFile
    py_name: CachedName
    scope: WrappedClass | None
    bi_get_buffer_code: CodeBlock | None = ...
    bi_release_buffer_code: CodeBlock | None = ...
    can_create: bool = ...
    cannot_assign: bool = ...
    cannot_copy: bool = ...
    casts: List[Argument] = ...
    class_key: ClassKey | None = ...
    convert_from_type_code: CodeBlock | None = ...
    convert_to_subclass_code: CodeBlock | None = ...
    convert_to_type_code: CodeBlock | None = ...
    ctors: List[Constructor] = ...
    dealloc_code: List[CodeBlock] = ...
    default_ctor: Constructor | None = ...
    delay_dtor: bool = ...
    deprecated: bool = ...
    docstring: Docstring | None = ...
    dtor: AccessSpecifier | None = ...
    dtor_gil_action: GILAction = ...
    dtor_throw_args: ThrowArguments | None = ...
    dtor_virtual_catcher_code: CodeBlock | None = ...
    export_derived: bool = ...
    external: bool = ...
    finalisation_code: CodeBlock | None = ...
    gc_clear_code: CodeBlock | None = ...
    gc_traverse_code: CodeBlock | None = ...
    handles_none: bool = ...
    has_nonlazy_method: bool = ...
    has_shadow: bool = ...
    has_variable_handlers: bool = ...
    instance_code: CodeBlock | None = ...
    is_abstract: bool = ...
    is_hidden_namespace: bool = ...
    is_incomplete: bool = ...
    is_opaque: bool = ...
    is_protected: bool = ...
    is_qobject: bool = ...
    len_cpp_name: str | None = ...
    members: List[Member] = ...
    metatype: CachedName | None = ...
    mixin: bool = ...
    mro: List['WrappedClass'] = ...
    needs_array_helper: bool = ...
    needs_copy_helper: bool = ...
    needs_shadow: bool = ...
    no_default_ctors: bool = ...
    no_type_hint: bool = ...
    no_type_name: bool = ...
    overloads: List[Overload] = ...
    pickle_code: CodeBlock | None = ...
    properties: List[Property] = ...
    pyqt_flags: int = ...
    pyqt_flags_enums: List[str] | None = ...
    pyqt_interface: str | None = ...
    pyqt_no_qmetaobject: bool = ...
    real_class: WrappedClass | None = ...
    subclass_base: WrappedClass | None = ...
    superclasses: List['WrappedClass'] = ...
    supertype: CachedName | None = ...
    template: Template | None = ...
    type_code: List[CodeBlock] = ...
    type_hint_code: CodeBlock | None = ...
    type_hints: TypeHints | None = ...
    virtual_error_handler: str | None = ...
    virtual_overloads: List[VirtualOverload] = ...
    visible_members: List[VisibleMember] = ...
    def __init__(self, iface_file, py_name, scope, bi_get_buffer_code, bi_release_buffer_code, can_create, cannot_assign, cannot_copy, casts, class_key, convert_from_type_code, convert_to_subclass_code, convert_to_type_code, ctors, dealloc_code, default_ctor, delay_dtor, deprecated, docstring, dtor, dtor_gil_action, dtor_throw_args, dtor_virtual_catcher_code, export_derived, external, finalisation_code, gc_clear_code, gc_traverse_code, handles_none, has_nonlazy_method, has_shadow, has_variable_handlers, instance_code, is_abstract, is_hidden_namespace, is_incomplete, is_opaque, is_protected, is_qobject, len_cpp_name, members, metatype, mixin, mro, needs_array_helper, needs_copy_helper, needs_shadow, no_default_ctors, no_type_hint, no_type_name, overloads, pickle_code, properties, pyqt_flags, pyqt_flags_enums, pyqt_interface, pyqt_no_qmetaobject, real_class, subclass_base, superclasses, supertype, template, type_code, type_hint_code, type_hints, virtual_error_handler, virtual_overloads, visible_members) -> None: ...

@dataclass
class WrappedEnum:
    """ Encapsulate a wrapped enum. """
    base_type: EnumBaseType
    fq_cpp_name: ScopedName | None
    module: Module
    cached_fq_cpp_name: CachedName | None = ...
    is_protected: bool = ...
    is_scoped: bool = ...
    members: List['WrappedEnumMember'] = ...
    needed: bool = ...
    no_scope: bool = ...
    no_type_hint: bool = ...
    overloads: List['Overload'] = ...
    py_name: CachedName | None = ...
    scope: MappedType | WrappedClass | None = ...
    slots: List[Member] = ...
    type_nr: int = ...
    def __init__(self, base_type, fq_cpp_name, module, cached_fq_cpp_name, is_protected, is_scoped, members, needed, no_scope, no_type_hint, overloads, py_name, scope, slots, type_nr) -> None: ...

@dataclass
class WrappedEnumMember:
    """ Encapsulate a member of a wrapped enum. """
    cpp_name: str
    py_name: CachedName
    scope: WrappedEnum
    no_type_hint: bool = ...
    def __init__(self, cpp_name, py_name, scope, no_type_hint) -> None: ...

@dataclass
class WrappedException:
    """ Encapsulate a wrapped exception. """
    iface_file: IfaceFile
    raise_code: CodeBlock
    builtin_base_exception: str | None = ...
    class_exception: WrappedClass | None = ...
    defined_base_exception: WrappedException | None = ...
    exception_nr: int = ...
    needed: bool = ...
    py_name: str | None = ...
    def __init__(self, iface_file, raise_code, builtin_base_exception, class_exception, defined_base_exception, exception_nr, needed, py_name) -> None: ...

@dataclass
class WrappedTypedef:
    """ Encapsulate a wrapped typedef. """
    fq_cpp_name: ScopedName
    module: Module
    scope: WrappedClass | None
    type: Argument
    no_type_name: bool = ...
    def __init__(self, fq_cpp_name, module, scope, type, no_type_name) -> None: ...

@dataclass
class WrappedVariable:
    """ Encapsulate a wrapped variable. """
    fq_cpp_name: ScopedName
    module: Module
    py_name: CachedName
    scope: WrappedClass | None
    type: Argument
    access_code: CodeBlock | None = ...
    get_code: CodeBlock | None = ...
    is_static: bool = ...
    needs_handler: bool = ...
    no_type_hint: bool = ...
    no_setter: bool = ...
    set_code: CodeBlock | None = ...
    def __init__(self, fq_cpp_name, module, py_name, scope, type, access_code, get_code, is_static, needs_handler, no_type_hint, no_setter, set_code) -> None: ...
