import matplotlib.axes as maxes
from _typeshed import Incomplete
from matplotlib.artist import Artist

class SimpleChainedObjects:
    def __init__(self, objects) -> None: ...
    def __getattr__(self, k): ...
    def __call__(self, *args, **kwargs) -> None: ...

class Axes(maxes.Axes):
    class AxisDict(dict):
        axes: Incomplete
        def __init__(self, axes) -> None: ...
        def __getitem__(self, k): ...
        def __call__(self, *v, **kwargs): ...
    @property
    def axis(self): ...
    def clear(self) -> None: ...

class SimpleAxisArtist(Artist):
    line: Incomplete
    def __init__(self, axis, axisnum, spine) -> None: ...
    @property
    def major_ticks(self): ...
    @property
    def major_ticklabels(self): ...
    @property
    def label(self): ...
    def set_visible(self, b) -> None: ...
    def set_label(self, txt) -> None: ...
    def toggle(self, all: Incomplete | None = None, ticks: Incomplete | None = None, ticklabels: Incomplete | None = None, label: Incomplete | None = None) -> None: ...
