from _typeshed import Incomplete
from scipy.fft import dct as dct, dctn as dctn, dst as dst, dstn as dstn, fftfreq as fftfreq, fftshift as fftshift, get_workers as get_workers, hfft2 as hfft2, hfftn as hfftn, idct as idct, idctn as idctn, idst as idst, idstn as idstn, ifftshift as ifftshift, ihfft2 as ihfft2, ihfftn as ihfftn, rfftfreq as rfftfreq, set_workers as set_workers

__all__ = ['fft', 'ifft', 'fft2', 'ifft2', 'fftn', 'ifftn', 'rfft', 'irfft', 'rfft2', 'irfft2', 'rfftn', 'irfftn', 'hfft', 'ihfft', 'hfft2', 'ihfft2', 'hfftn', 'ihfftn', 'dct', 'idct', 'dst', 'idst', 'dctn', 'idctn', 'dstn', 'idstn', 'fftshift', 'ifftshift', 'fftfreq', 'rfftfreq', 'get_workers', 'set_workers', 'next_fast_len']

class _cpu_max_threads_count:
    cpu_count: Incomplete
    max_threads_count: Incomplete
    def __init__(self) -> None: ...
    def get_cpu_count(self): ...
    def get_max_threads_count(self): ...

class Workers:
    workers: Incomplete
    n_threads: Incomplete
    def __init__(self, workers) -> None: ...
    prev_num_threads: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(self, *args) -> None: ...

def fft(a, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, overwrite_x: bool = False, workers: Incomplete | None = None): ...
def ifft(a, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, overwrite_x: bool = False, workers: Incomplete | None = None): ...
def fft2(a, s: Incomplete | None = None, axes=(-2, -1), norm: Incomplete | None = None, overwrite_x: bool = False, workers: Incomplete | None = None): ...
def ifft2(a, s: Incomplete | None = None, axes=(-2, -1), norm: Incomplete | None = None, overwrite_x: bool = False, workers: Incomplete | None = None): ...
def fftn(a, s: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, overwrite_x: bool = False, workers: Incomplete | None = None): ...
def ifftn(a, s: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, overwrite_x: bool = False, workers: Incomplete | None = None): ...
def rfft(a, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, workers: Incomplete | None = None): ...
def irfft(a, n: Incomplete | None = None, axis: int = -1, norm: Incomplete | None = None, workers: Incomplete | None = None): ...
def rfft2(a, s: Incomplete | None = None, axes=(-2, -1), norm: Incomplete | None = None, workers: Incomplete | None = None): ...
def irfft2(a, s: Incomplete | None = None, axes=(-2, -1), norm: Incomplete | None = None, workers: Incomplete | None = None): ...
def rfftn(a, s: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, workers: Incomplete | None = None): ...
def irfftn(a, s: Incomplete | None = None, axes: Incomplete | None = None, norm: Incomplete | None = None, workers: Incomplete | None = None): ...

# Names in __all__ with no definition:
#   hfft
#   ihfft
#   next_fast_len
