from .algorithms import get_default_algorithms as get_default_algorithms, has_crypto as has_crypto, requires_cryptography as requires_cryptography
from .exceptions import InvalidKeyError as InvalidKeyError, PyJWKError as PyJWKError, PyJWKSetError as PyJWKSetError, PyJWTError as PyJWTError
from .types import JWKDict as JWKDict
from _typeshed import Incomplete
from typing import Any

class PyJWK:
    Algorithm: Incomplete
    key: Incomplete
    def __init__(self, jwk_data: JWKDict, algorithm: str | None = None) -> None: ...
    @staticmethod
    def from_dict(obj: JWKDict, algorithm: str | None = None) -> PyJWK: ...
    @staticmethod
    def from_json(data: str, algorithm: None = None) -> PyJWK: ...
    @property
    def key_type(self) -> str | None: ...
    @property
    def key_id(self) -> str | None: ...
    @property
    def public_key_use(self) -> str | None: ...

class PyJWKSet:
    keys: Incomplete
    def __init__(self, keys: list[JWKDict]) -> None: ...
    @staticmethod
    def from_dict(obj: dict[str, Any]) -> PyJWKSet: ...
    @staticmethod
    def from_json(data: str) -> PyJWKSet: ...
    def __getitem__(self, kid: str) -> PyJWK: ...

class PyJWTSetWithTimestamp:
    jwk_set: Incomplete
    timestamp: Incomplete
    def __init__(self, jwk_set: PyJWKSet) -> None: ...
    def get_jwk_set(self) -> PyJWKSet: ...
    def get_timestamp(self) -> float: ...
