from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve as EllipticCurve

def force_bytes(value: bytes | str) -> bytes: ...
def base64url_decode(input: bytes | str) -> bytes: ...
def base64url_encode(input: bytes) -> bytes: ...
def to_base64url_uint(val: int) -> bytes: ...
def from_base64url_uint(val: bytes | str) -> int: ...
def number_to_bytes(num: int, num_bytes: int) -> bytes: ...
def bytes_to_number(string: bytes) -> int: ...
def bytes_from_int(val: int) -> bytes: ...
def der_to_raw_signature(der_sig: bytes, curve: EllipticCurve) -> bytes: ...
def raw_to_der_signature(raw_sig: bytes, curve: EllipticCurve) -> bytes: ...
def is_pem_format(key: bytes) -> bool: ...
def is_ssh_key(key: bytes) -> bool: ...
