from _typeshed import Incomplete

def validate_slice(obj) -> None: ...

class Patch:
    """
    Patch a callback output value

    Act like a proxy of the output prop value on the frontend.

    Supported prop types: Dictionaries and lists.
    """
    def __init__(self, location: Incomplete | None = None, parent: Incomplete | None = None) -> None: ...
    def __getitem__(self, item): ...
    def __getattr__(self, item): ...
    def __setattr__(self, key, value) -> None: ...
    def __delattr__(self, item) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iadd__(self, other): ...
    def __isub__(self, other): ...
    def __imul__(self, other): ...
    def __itruediv__(self, other): ...
    def __ior__(self, other): ...
    def __iter__(self): ...
    def append(self, item) -> None:
        """Add the item to the end of a list"""
    def prepend(self, item) -> None:
        """Add the item to the start of a list"""
    def insert(self, index, item) -> None:
        """Add the item at the index of a list"""
    def clear(self) -> None:
        """Remove all items in a list"""
    def reverse(self) -> None:
        """Reversal of the order of items in a list"""
    def extend(self, item) -> None:
        """Add all the items to the end of a list"""
    def remove(self, item) -> None:
        """filter the item out of a list on the frontend"""
    def update(self, E: Incomplete | None = None, **F) -> None:
        """Merge a dict or keyword arguments with another dictionary"""
    def sort(self) -> None: ...
    def to_plotly_json(self): ...
