import collections
from _typeshed import Incomplete
from dash.types import RendererHooks as RendererHooks

logger: Incomplete

def to_json(value): ...
def interpolate_str(template, **data): ...
def format_tag(tag_name, attributes, inner: str = '', closed: bool = False, opened: bool = False, sanitize: bool = False): ...
def generate_hash(): ...
def patch_collections_abc(member): ...

class AttributeDict(dict):
    """Dictionary subclass enabling attribute lookup/assignment of keys/values.

    For example::
        >>> m = AttributeDict({'foo': 'bar'})
        >>> m.foo
        'bar'
        >>> m.foo = 'not bar'
        >>> m['foo']
        'not bar'
    ``AttributeDict`` objects also provide ``.first()`` which acts like
    ``.get()`` but accepts multiple keys as arguments, and returns the value of
    the first hit, e.g.::
        >>> m = AttributeDict({'foo': 'bar', 'biz': 'baz'})
        >>> m.first('wrong', 'incorrect', 'foo', 'biz')
        'bar'
    """
    def __setattr__(self, key, value) -> None: ...
    def __getattr__(self, key): ...
    def set_read_only(self, names, msg: str = 'Attribute is read-only') -> None:
        """
        Designate named attributes as read-only with the corresponding msg

        Method is additive. Making additional calls to this method will update
        existing messages and add to the current set of _read_only names.
        """
    def finalize(self, msg: str = 'Object is final: No new keys may be added.') -> None:
        """Prevent any new keys being set."""
    def __setitem__(self, key, val) -> None: ...
    def update(self, other) -> None: ...
    def first(self, *names): ...

def create_callback_id(output, inputs): ...
def split_callback_id(callback_id): ...
def stringify_id(id_): ...
def inputs_to_dict(inputs_list): ...
def convert_to_AttributeDict(nested_list): ...
def inputs_to_vals(inputs): ...
def run_command_with_process(cmd) -> None: ...
def compute_md5(path): ...
def job(msg: str = ''): ...
def gen_salt(chars): ...

class OrderedSet(collections.abc.MutableSet):
    def __init__(self, *args) -> None: ...
    def add(self, value) -> None: ...
    def discard(self, value) -> None: ...
    def __contains__(self, x) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...

def coerce_to_list(obj): ...
def clean_property_name(name: str): ...
def hooks_to_js_object(hooks: RendererHooks | None) -> str: ...
def parse_version(version): ...
def get_caller_name(name: str): ...
