from _typeshed import Incomplete

def floats(*args, **kwargs): ...
def assume_not_overflowing(tensor, qparams): ...
def qparams(draw, dtypes: Incomplete | None = None, scale_min: Incomplete | None = None, scale_max: Incomplete | None = None, zero_point_min: Incomplete | None = None, zero_point_max: Incomplete | None = None): ...
def array_shapes(draw, min_dims: int = 1, max_dims: Incomplete | None = None, min_side: int = 1, max_side: Incomplete | None = None, max_numel: Incomplete | None = None):
    """Return a strategy for array shapes (tuples of int >= 1)."""
def tensor(draw, shapes: Incomplete | None = None, elements: Incomplete | None = None, qparams: Incomplete | None = None): ...
def per_channel_tensor(draw, shapes: Incomplete | None = None, elements: Incomplete | None = None, qparams: Incomplete | None = None): ...
def tensor_conv(draw, spatial_dim: int = 2, batch_size_range=(1, 4), input_channels_per_group_range=(3, 7), output_channels_per_group_range=(3, 7), feature_map_range=(6, 12), kernel_range=(3, 7), max_groups: int = 1, can_be_transposed: bool = False, elements: Incomplete | None = None, qparams: Incomplete | None = None): ...

hypothesis_version: Incomplete
current_settings: Incomplete

def assert_deadline_disabled() -> None: ...
