from _typeshed import Incomplete
from torch import inf as inf
from torch.jit.annotations import BroadcastingList2 as BroadcastingList2, BroadcastingList3 as BroadcastingList3
from torch.testing._internal.common_nn import module_tests as module_tests, new_module_tests as new_module_tests
from torch.testing._internal.common_utils import is_iterable_of_tensors as is_iterable_of_tensors
from typing import Any, Dict, List, NamedTuple

L: int
M: int
S: int

def unpack_variables(args): ...

class dont_convert(tuple): ...

class non_differentiable(NamedTuple):
    tensor: Incomplete

def create_input(call_args, requires_grad: bool = True, non_contiguous: bool = False, call_kwargs: Incomplete | None = None, dtype=..., device: Incomplete | None = None): ...

nn_functional_tests: Incomplete
script_template: str

def value_to_literal(value): ...
def get_call(method_name, func_type, args, kwargs): ...
def get_constant(x): ...
def get_script_args(args): ...
def gen_script_fn_and_args(method_name, func_type, *args, **kwargs): ...
def create_script_fn(self, method_name, func_type): ...

class SplitInputs:
    all_tensors: List[Any]
    tensor_args: List[Any]
    nontensor_args: List[Any]
    arg_types: List[str]
    tensor_kwargs: Dict[str, Any]
    kwarg_order: List[str]
    nontensor_kwargs: Dict[str, Any]
    kwarg_types: Dict[str, Any]
    def __init__(self, args, kwargs) -> None: ...
    def nontensors_match(self, other: SplitInputs): ...

def partial_apply_nontensors(fn, args, kwargs): ...
def create_traced_fn(self, fn, cache_traced_fn: bool = False): ...

EXCLUDE_SCRIPT: Incomplete

def get_nn_functional_compiled_fn_and_inputs(name, self_size, args, variant_name: str = '', *extra_args): ...

additional_module_tests: Incomplete
EXCLUDE_SCRIPT_MODULES: Incomplete
script_method_template: str

def create_script_module(self, nn_module, constructor_args, *args, **kwargs): ...
def check_alias_annotation(method_name, args, kwargs, *, aten_name, func_type: str = 'method') -> None: ...
def get_nn_module_name_from_kwargs(**kwargs): ...
def get_nn_mod_test_name(**kwargs): ...
def get_nn_module_class_from_kwargs(**kwargs): ...
def try_get_nn_module_compiled_mod_and_inputs(*args, **kwargs): ...
def get_all_nn_module_tests(): ...
