import typing
from _typeshed import Incomplete
from cryptography.hazmat.bindings._rust import openssl as rust_openssl

class UnsupportedAlgorithm(Exception):
    def __init__(self, message: str, reason: _Reasons | None = None) -> None: ...

class AlreadyFinalized(Exception): ...
class AlreadyUpdated(Exception): ...
class NotYetFinalized(Exception): ...
class InvalidTag(Exception): ...
class InvalidSignature(Exception): ...

class InternalError(Exception):
    err_code: Incomplete
    def __init__(self, msg: str, err_code: typing.List[rust_openssl.OpenSSLError]) -> None: ...

class InvalidKey(Exception): ...
