from _typeshed import Incomplete
from enum import Enum as Enum, IntEnum as IntEnum, IntFlag as IntFlag

__all__ = ['ContextOption', 'IO_THREADS', 'MAX_SOCKETS', 'SOCKET_LIMIT', 'THREAD_PRIORITY', 'THREAD_SCHED_POLICY', 'MAX_MSGSZ', 'MSG_T_SIZE', 'THREAD_AFFINITY_CPU_ADD', 'THREAD_AFFINITY_CPU_REMOVE', 'THREAD_NAME_PREFIX', 'DeviceType', 'STREAMER', 'FORWARDER', 'QUEUE', 'Enum', 'Errno', 'EAGAIN', 'EFAULT', 'EINVAL', 'ENOTSUP', 'EPROTONOSUPPORT', 'ENOBUFS', 'ENETDOWN', 'EADDRINUSE', 'EADDRNOTAVAIL', 'ECONNREFUSED', 'EINPROGRESS', 'ENOTSOCK', 'EMSGSIZE', 'EAFNOSUPPORT', 'ENETUNREACH', 'ECONNABORTED', 'ECONNRESET', 'ENOTCONN', 'ETIMEDOUT', 'EHOSTUNREACH', 'ENETRESET', 'EFSM', 'ENOCOMPATPROTO', 'ETERM', 'EMTHREAD', 'Event', 'PROTOCOL_ERROR_WS_UNSPECIFIED', 'PROTOCOL_ERROR_ZMTP_UNSPECIFIED', 'PROTOCOL_ERROR_ZMTP_UNEXPECTED_COMMAND', 'PROTOCOL_ERROR_ZMTP_INVALID_SEQUENCE', 'PROTOCOL_ERROR_ZMTP_KEY_EXCHANGE', 'PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_UNSPECIFIED', 'PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_MESSAGE', 'PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_HELLO', 'PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_INITIATE', 'PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_ERROR', 'PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_READY', 'PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_WELCOME', 'PROTOCOL_ERROR_ZMTP_INVALID_METADATA', 'PROTOCOL_ERROR_ZMTP_CRYPTOGRAPHIC', 'PROTOCOL_ERROR_ZMTP_MECHANISM_MISMATCH', 'PROTOCOL_ERROR_ZAP_UNSPECIFIED', 'PROTOCOL_ERROR_ZAP_MALFORMED_REPLY', 'PROTOCOL_ERROR_ZAP_BAD_REQUEST_ID', 'PROTOCOL_ERROR_ZAP_BAD_VERSION', 'PROTOCOL_ERROR_ZAP_INVALID_STATUS_CODE', 'PROTOCOL_ERROR_ZAP_INVALID_METADATA', 'EVENT_CONNECTED', 'EVENT_CONNECT_DELAYED', 'EVENT_CONNECT_RETRIED', 'EVENT_LISTENING', 'EVENT_BIND_FAILED', 'EVENT_ACCEPTED', 'EVENT_ACCEPT_FAILED', 'EVENT_CLOSED', 'EVENT_CLOSE_FAILED', 'EVENT_DISCONNECTED', 'EVENT_MONITOR_STOPPED', 'EVENT_HANDSHAKE_FAILED_NO_DETAIL', 'EVENT_HANDSHAKE_SUCCEEDED', 'EVENT_HANDSHAKE_FAILED_PROTOCOL', 'EVENT_HANDSHAKE_FAILED_AUTH', 'EVENT_ALL_V1', 'EVENT_ALL', 'EVENT_PIPES_STATS', 'EVENT_ALL_V2', 'Flag', 'DONTWAIT', 'SNDMORE', 'NOBLOCK', 'IntEnum', 'IntFlag', 'MessageOption', 'MORE', 'SHARED', 'SRCFD', 'PollEvent', 'POLLIN', 'POLLOUT', 'POLLERR', 'POLLPRI', 'ReconnectStop', 'RECONNECT_STOP_CONN_REFUSED', 'RECONNECT_STOP_HANDSHAKE_FAILED', 'RECONNECT_STOP_AFTER_DISCONNECT', 'SecurityMechanism', 'NULL', 'PLAIN', 'CURVE', 'GSSAPI', 'SocketOption', 'HWM', 'AFFINITY', 'ROUTING_ID', 'SUBSCRIBE', 'UNSUBSCRIBE', 'RATE', 'RECOVERY_IVL', 'SNDBUF', 'RCVBUF', 'RCVMORE', 'FD', 'EVENTS', 'TYPE', 'LINGER', 'RECONNECT_IVL', 'BACKLOG', 'RECONNECT_IVL_MAX', 'MAXMSGSIZE', 'SNDHWM', 'RCVHWM', 'MULTICAST_HOPS', 'RCVTIMEO', 'SNDTIMEO', 'LAST_ENDPOINT', 'ROUTER_MANDATORY', 'TCP_KEEPALIVE', 'TCP_KEEPALIVE_CNT', 'TCP_KEEPALIVE_IDLE', 'TCP_KEEPALIVE_INTVL', 'IMMEDIATE', 'XPUB_VERBOSE', 'ROUTER_RAW', 'IPV6', 'MECHANISM', 'PLAIN_SERVER', 'PLAIN_USERNAME', 'PLAIN_PASSWORD', 'CURVE_SERVER', 'CURVE_PUBLICKEY', 'CURVE_SECRETKEY', 'CURVE_SERVERKEY', 'PROBE_ROUTER', 'REQ_CORRELATE', 'REQ_RELAXED', 'CONFLATE', 'ZAP_DOMAIN', 'ROUTER_HANDOVER', 'TOS', 'CONNECT_ROUTING_ID', 'GSSAPI_SERVER', 'GSSAPI_PRINCIPAL', 'GSSAPI_SERVICE_PRINCIPAL', 'GSSAPI_PLAINTEXT', 'HANDSHAKE_IVL', 'SOCKS_PROXY', 'XPUB_NODROP', 'BLOCKY', 'XPUB_MANUAL', 'XPUB_WELCOME_MSG', 'STREAM_NOTIFY', 'INVERT_MATCHING', 'HEARTBEAT_IVL', 'HEARTBEAT_TTL', 'HEARTBEAT_TIMEOUT', 'XPUB_VERBOSER', 'CONNECT_TIMEOUT', 'TCP_MAXRT', 'THREAD_SAFE', 'MULTICAST_MAXTPDU', 'VMCI_BUFFER_SIZE', 'VMCI_BUFFER_MIN_SIZE', 'VMCI_BUFFER_MAX_SIZE', 'VMCI_CONNECT_TIMEOUT', 'USE_FD', 'GSSAPI_PRINCIPAL_NAMETYPE', 'GSSAPI_SERVICE_PRINCIPAL_NAMETYPE', 'BINDTODEVICE', 'IDENTITY', 'CONNECT_RID', 'TCP_ACCEPT_FILTER', 'IPC_FILTER_PID', 'IPC_FILTER_UID', 'IPC_FILTER_GID', 'IPV4ONLY', 'DELAY_ATTACH_ON_CONNECT', 'FAIL_UNROUTABLE', 'ROUTER_BEHAVIOR', 'ZAP_ENFORCE_DOMAIN', 'LOOPBACK_FASTPATH', 'METADATA', 'MULTICAST_LOOP', 'ROUTER_NOTIFY', 'XPUB_MANUAL_LAST_VALUE', 'SOCKS_USERNAME', 'SOCKS_PASSWORD', 'IN_BATCH_SIZE', 'OUT_BATCH_SIZE', 'WSS_KEY_PEM', 'WSS_CERT_PEM', 'WSS_TRUST_PEM', 'WSS_HOSTNAME', 'WSS_TRUST_SYSTEM', 'ONLY_FIRST_SUBSCRIBE', 'RECONNECT_STOP', 'HELLO_MSG', 'DISCONNECT_MSG', 'PRIORITY', 'SocketType', 'PAIR', 'PUB', 'SUB', 'REQ', 'REP', 'DEALER', 'ROUTER', 'PULL', 'PUSH', 'XPUB', 'XSUB', 'STREAM', 'XREQ', 'XREP', 'SERVER', 'CLIENT', 'RADIO', 'DISH', 'GATHER', 'SCATTER', 'DGRAM', 'PEER', 'CHANNEL']

class Errno(IntEnum):
    """libzmq error codes

    .. versionadded:: 23
    """
    EAGAIN: Incomplete
    EFAULT: Incomplete
    EINVAL: Incomplete
    ENOTSUP: Incomplete
    EPROTONOSUPPORT: Incomplete
    ENOBUFS: Incomplete
    ENETDOWN: Incomplete
    EADDRINUSE: Incomplete
    EADDRNOTAVAIL: Incomplete
    ECONNREFUSED: Incomplete
    EINPROGRESS: Incomplete
    ENOTSOCK: Incomplete
    EMSGSIZE: Incomplete
    EAFNOSUPPORT: Incomplete
    ENETUNREACH: Incomplete
    ECONNABORTED: Incomplete
    ECONNRESET: Incomplete
    ENOTCONN: Incomplete
    ETIMEDOUT: Incomplete
    EHOSTUNREACH: Incomplete
    ENETRESET: Incomplete
    EFSM: Incomplete
    ENOCOMPATPROTO: Incomplete
    ETERM: Incomplete
    EMTHREAD: Incomplete

class ContextOption(IntEnum):
    """Options for Context.get/set

    .. versionadded:: 23
    """
    IO_THREADS: int
    MAX_SOCKETS: int
    SOCKET_LIMIT: int
    THREAD_PRIORITY: int
    THREAD_SCHED_POLICY: int
    MAX_MSGSZ: int
    MSG_T_SIZE: int
    THREAD_AFFINITY_CPU_ADD: int
    THREAD_AFFINITY_CPU_REMOVE: int
    THREAD_NAME_PREFIX: int

class SocketType(IntEnum):
    """zmq socket types

    .. versionadded:: 23
    """
    PAIR: int
    PUB: int
    SUB: int
    REQ: int
    REP: int
    DEALER: int
    ROUTER: int
    PULL: int
    PUSH: int
    XPUB: int
    XSUB: int
    STREAM: int
    XREQ = DEALER
    XREP = ROUTER
    SERVER: int
    CLIENT: int
    RADIO: int
    DISH: int
    GATHER: int
    SCATTER: int
    DGRAM: int
    PEER: int
    CHANNEL: int

class _OptType(Enum):
    int: str
    int64: str
    bytes: str
    fd: str

class SocketOption(IntEnum):
    """Options for Socket.get/set

    .. versionadded:: 23
    """
    def __new__(cls, value: int, opt_type: _OptType = ...):
        """Attach option type as `._opt_type`"""
    HWM: int
    AFFINITY: Incomplete
    ROUTING_ID: Incomplete
    SUBSCRIBE: Incomplete
    UNSUBSCRIBE: Incomplete
    RATE: int
    RECOVERY_IVL: int
    SNDBUF: int
    RCVBUF: int
    RCVMORE: int
    FD: Incomplete
    EVENTS: int
    TYPE: int
    LINGER: int
    RECONNECT_IVL: int
    BACKLOG: int
    RECONNECT_IVL_MAX: int
    MAXMSGSIZE: Incomplete
    SNDHWM: int
    RCVHWM: int
    MULTICAST_HOPS: int
    RCVTIMEO: int
    SNDTIMEO: int
    LAST_ENDPOINT: Incomplete
    ROUTER_MANDATORY: int
    TCP_KEEPALIVE: int
    TCP_KEEPALIVE_CNT: int
    TCP_KEEPALIVE_IDLE: int
    TCP_KEEPALIVE_INTVL: int
    IMMEDIATE: int
    XPUB_VERBOSE: int
    ROUTER_RAW: int
    IPV6: int
    MECHANISM: int
    PLAIN_SERVER: int
    PLAIN_USERNAME: Incomplete
    PLAIN_PASSWORD: Incomplete
    CURVE_SERVER: int
    CURVE_PUBLICKEY: Incomplete
    CURVE_SECRETKEY: Incomplete
    CURVE_SERVERKEY: Incomplete
    PROBE_ROUTER: int
    REQ_CORRELATE: int
    REQ_RELAXED: int
    CONFLATE: int
    ZAP_DOMAIN: Incomplete
    ROUTER_HANDOVER: int
    TOS: int
    CONNECT_ROUTING_ID: Incomplete
    GSSAPI_SERVER: int
    GSSAPI_PRINCIPAL: Incomplete
    GSSAPI_SERVICE_PRINCIPAL: Incomplete
    GSSAPI_PLAINTEXT: int
    HANDSHAKE_IVL: int
    SOCKS_PROXY: Incomplete
    XPUB_NODROP: int
    BLOCKY: int
    XPUB_MANUAL: int
    XPUB_WELCOME_MSG: Incomplete
    STREAM_NOTIFY: int
    INVERT_MATCHING: int
    HEARTBEAT_IVL: int
    HEARTBEAT_TTL: int
    HEARTBEAT_TIMEOUT: int
    XPUB_VERBOSER: int
    CONNECT_TIMEOUT: int
    TCP_MAXRT: int
    THREAD_SAFE: int
    MULTICAST_MAXTPDU: int
    VMCI_BUFFER_SIZE: Incomplete
    VMCI_BUFFER_MIN_SIZE: Incomplete
    VMCI_BUFFER_MAX_SIZE: Incomplete
    VMCI_CONNECT_TIMEOUT: int
    USE_FD: int
    GSSAPI_PRINCIPAL_NAMETYPE: int
    GSSAPI_SERVICE_PRINCIPAL_NAMETYPE: int
    BINDTODEVICE: Incomplete
    IDENTITY = ROUTING_ID
    CONNECT_RID = CONNECT_ROUTING_ID
    TCP_ACCEPT_FILTER: Incomplete
    IPC_FILTER_PID: int
    IPC_FILTER_UID: int
    IPC_FILTER_GID: int
    IPV4ONLY: int
    DELAY_ATTACH_ON_CONNECT = IMMEDIATE
    FAIL_UNROUTABLE = ROUTER_MANDATORY
    ROUTER_BEHAVIOR = ROUTER_MANDATORY
    ZAP_ENFORCE_DOMAIN: int
    LOOPBACK_FASTPATH: int
    METADATA: Incomplete
    MULTICAST_LOOP: int
    ROUTER_NOTIFY: int
    XPUB_MANUAL_LAST_VALUE: int
    SOCKS_USERNAME: Incomplete
    SOCKS_PASSWORD: Incomplete
    IN_BATCH_SIZE: int
    OUT_BATCH_SIZE: int
    WSS_KEY_PEM: Incomplete
    WSS_CERT_PEM: Incomplete
    WSS_TRUST_PEM: Incomplete
    WSS_HOSTNAME: Incomplete
    WSS_TRUST_SYSTEM: int
    ONLY_FIRST_SUBSCRIBE: int
    RECONNECT_STOP: int
    HELLO_MSG: Incomplete
    DISCONNECT_MSG: Incomplete
    PRIORITY: int

class MessageOption(IntEnum):
    """Options on zmq.Frame objects

    .. versionadded:: 23
    """
    MORE: int
    SHARED: int
    SRCFD: int

class Flag(IntFlag):
    """Send/recv flags

    .. versionadded:: 23
    """
    DONTWAIT: int
    SNDMORE: int
    NOBLOCK = DONTWAIT

class SecurityMechanism(IntEnum):
    """Security mechanisms (as returned by ``socket.get(zmq.MECHANISM)``)

    .. versionadded:: 23
    """
    NULL: int
    PLAIN: int
    CURVE: int
    GSSAPI: int

class ReconnectStop(IntEnum):
    """Select behavior for socket.reconnect_stop

    .. versionadded:: 25
    """
    CONN_REFUSED: int
    HANDSHAKE_FAILED: int
    AFTER_DISCONNECT: int

class Event(IntFlag):
    """Socket monitoring events

    .. versionadded:: 23
    """
    PROTOCOL_ERROR_WS_UNSPECIFIED: int
    PROTOCOL_ERROR_ZMTP_UNSPECIFIED: int
    PROTOCOL_ERROR_ZMTP_UNEXPECTED_COMMAND: int
    PROTOCOL_ERROR_ZMTP_INVALID_SEQUENCE: int
    PROTOCOL_ERROR_ZMTP_KEY_EXCHANGE: int
    PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_UNSPECIFIED: int
    PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_MESSAGE: int
    PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_HELLO: int
    PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_INITIATE: int
    PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_ERROR: int
    PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_READY: int
    PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_WELCOME: int
    PROTOCOL_ERROR_ZMTP_INVALID_METADATA: int
    PROTOCOL_ERROR_ZMTP_CRYPTOGRAPHIC: int
    PROTOCOL_ERROR_ZMTP_MECHANISM_MISMATCH: int
    PROTOCOL_ERROR_ZAP_UNSPECIFIED: int
    PROTOCOL_ERROR_ZAP_MALFORMED_REPLY: int
    PROTOCOL_ERROR_ZAP_BAD_REQUEST_ID: int
    PROTOCOL_ERROR_ZAP_BAD_VERSION: int
    PROTOCOL_ERROR_ZAP_INVALID_STATUS_CODE: int
    PROTOCOL_ERROR_ZAP_INVALID_METADATA: int
    CONNECTED: int
    CONNECT_DELAYED: int
    CONNECT_RETRIED: int
    LISTENING: int
    BIND_FAILED: int
    ACCEPTED: int
    ACCEPT_FAILED: int
    CLOSED: int
    CLOSE_FAILED: int
    DISCONNECTED: int
    MONITOR_STOPPED: int
    HANDSHAKE_FAILED_NO_DETAIL: int
    HANDSHAKE_SUCCEEDED: int
    HANDSHAKE_FAILED_PROTOCOL: int
    HANDSHAKE_FAILED_AUTH: int
    ALL_V1: int
    ALL = ALL_V1
    PIPES_STATS: int
    ALL_V2: Incomplete

class PollEvent(IntFlag):
    """Which events to poll for in poll methods

    .. versionadded: 23
    """
    POLLIN: int
    POLLOUT: int
    POLLERR: int
    POLLPRI: int

class DeviceType(IntEnum):
    """Device type constants for zmq.device

    .. versionadded: 23
    """
    STREAMER: int
    FORWARDER: int
    QUEUE: int

IO_THREADS: int
MAX_SOCKETS: int
SOCKET_LIMIT: int
THREAD_PRIORITY: int
THREAD_SCHED_POLICY: int
MAX_MSGSZ: int
MSG_T_SIZE: int
THREAD_AFFINITY_CPU_ADD: int
THREAD_AFFINITY_CPU_REMOVE: int
THREAD_NAME_PREFIX: int
STREAMER: int
FORWARDER: int
QUEUE: int
EAGAIN: int
EFAULT: int
EINVAL: int
ENOTSUP: int
EPROTONOSUPPORT: int
ENOBUFS: int
ENETDOWN: int
EADDRINUSE: int
EADDRNOTAVAIL: int
ECONNREFUSED: int
EINPROGRESS: int
ENOTSOCK: int
EMSGSIZE: int
EAFNOSUPPORT: int
ENETUNREACH: int
ECONNABORTED: int
ECONNRESET: int
ENOTCONN: int
ETIMEDOUT: int
EHOSTUNREACH: int
ENETRESET: int
EFSM: int
ENOCOMPATPROTO: int
ETERM: int
EMTHREAD: int
PROTOCOL_ERROR_WS_UNSPECIFIED: int
PROTOCOL_ERROR_ZMTP_UNSPECIFIED: int
PROTOCOL_ERROR_ZMTP_UNEXPECTED_COMMAND: int
PROTOCOL_ERROR_ZMTP_INVALID_SEQUENCE: int
PROTOCOL_ERROR_ZMTP_KEY_EXCHANGE: int
PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_UNSPECIFIED: int
PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_MESSAGE: int
PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_HELLO: int
PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_INITIATE: int
PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_ERROR: int
PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_READY: int
PROTOCOL_ERROR_ZMTP_MALFORMED_COMMAND_WELCOME: int
PROTOCOL_ERROR_ZMTP_INVALID_METADATA: int
PROTOCOL_ERROR_ZMTP_CRYPTOGRAPHIC: int
PROTOCOL_ERROR_ZMTP_MECHANISM_MISMATCH: int
PROTOCOL_ERROR_ZAP_UNSPECIFIED: int
PROTOCOL_ERROR_ZAP_MALFORMED_REPLY: int
PROTOCOL_ERROR_ZAP_BAD_REQUEST_ID: int
PROTOCOL_ERROR_ZAP_BAD_VERSION: int
PROTOCOL_ERROR_ZAP_INVALID_STATUS_CODE: int
PROTOCOL_ERROR_ZAP_INVALID_METADATA: int
EVENT_CONNECTED: int
EVENT_CONNECT_DELAYED: int
EVENT_CONNECT_RETRIED: int
EVENT_LISTENING: int
EVENT_BIND_FAILED: int
EVENT_ACCEPTED: int
EVENT_ACCEPT_FAILED: int
EVENT_CLOSED: int
EVENT_CLOSE_FAILED: int
EVENT_DISCONNECTED: int
EVENT_MONITOR_STOPPED: int
EVENT_HANDSHAKE_FAILED_NO_DETAIL: int
EVENT_HANDSHAKE_SUCCEEDED: int
EVENT_HANDSHAKE_FAILED_PROTOCOL: int
EVENT_HANDSHAKE_FAILED_AUTH: int
EVENT_ALL_V1: int
EVENT_ALL: int
EVENT_PIPES_STATS: int
EVENT_ALL_V2: int
DONTWAIT: int
SNDMORE: int
NOBLOCK: int
MORE: int
SHARED: int
SRCFD: int
POLLIN: int
POLLOUT: int
POLLERR: int
POLLPRI: int
RECONNECT_STOP_CONN_REFUSED: int
RECONNECT_STOP_HANDSHAKE_FAILED: int
RECONNECT_STOP_AFTER_DISCONNECT: int
NULL: int
PLAIN: int
CURVE: int
GSSAPI: int
HWM: int
AFFINITY: int
ROUTING_ID: int
SUBSCRIBE: int
UNSUBSCRIBE: int
RATE: int
RECOVERY_IVL: int
SNDBUF: int
RCVBUF: int
RCVMORE: int
FD: int
EVENTS: int
TYPE: int
LINGER: int
RECONNECT_IVL: int
BACKLOG: int
RECONNECT_IVL_MAX: int
MAXMSGSIZE: int
SNDHWM: int
RCVHWM: int
MULTICAST_HOPS: int
RCVTIMEO: int
SNDTIMEO: int
LAST_ENDPOINT: int
ROUTER_MANDATORY: int
TCP_KEEPALIVE: int
TCP_KEEPALIVE_CNT: int
TCP_KEEPALIVE_IDLE: int
TCP_KEEPALIVE_INTVL: int
IMMEDIATE: int
XPUB_VERBOSE: int
ROUTER_RAW: int
IPV6: int
MECHANISM: int
PLAIN_SERVER: int
PLAIN_USERNAME: int
PLAIN_PASSWORD: int
CURVE_SERVER: int
CURVE_PUBLICKEY: int
CURVE_SECRETKEY: int
CURVE_SERVERKEY: int
PROBE_ROUTER: int
REQ_CORRELATE: int
REQ_RELAXED: int
CONFLATE: int
ZAP_DOMAIN: int
ROUTER_HANDOVER: int
TOS: int
CONNECT_ROUTING_ID: int
GSSAPI_SERVER: int
GSSAPI_PRINCIPAL: int
GSSAPI_SERVICE_PRINCIPAL: int
GSSAPI_PLAINTEXT: int
HANDSHAKE_IVL: int
SOCKS_PROXY: int
XPUB_NODROP: int
BLOCKY: int
XPUB_MANUAL: int
XPUB_WELCOME_MSG: int
STREAM_NOTIFY: int
INVERT_MATCHING: int
HEARTBEAT_IVL: int
HEARTBEAT_TTL: int
HEARTBEAT_TIMEOUT: int
XPUB_VERBOSER: int
CONNECT_TIMEOUT: int
TCP_MAXRT: int
THREAD_SAFE: int
MULTICAST_MAXTPDU: int
VMCI_BUFFER_SIZE: int
VMCI_BUFFER_MIN_SIZE: int
VMCI_BUFFER_MAX_SIZE: int
VMCI_CONNECT_TIMEOUT: int
USE_FD: int
GSSAPI_PRINCIPAL_NAMETYPE: int
GSSAPI_SERVICE_PRINCIPAL_NAMETYPE: int
BINDTODEVICE: int
IDENTITY: int
CONNECT_RID: int
TCP_ACCEPT_FILTER: int
IPC_FILTER_PID: int
IPC_FILTER_UID: int
IPC_FILTER_GID: int
IPV4ONLY: int
DELAY_ATTACH_ON_CONNECT: int
FAIL_UNROUTABLE: int
ROUTER_BEHAVIOR: int
ZAP_ENFORCE_DOMAIN: int
LOOPBACK_FASTPATH: int
METADATA: int
MULTICAST_LOOP: int
ROUTER_NOTIFY: int
XPUB_MANUAL_LAST_VALUE: int
SOCKS_USERNAME: int
SOCKS_PASSWORD: int
IN_BATCH_SIZE: int
OUT_BATCH_SIZE: int
WSS_KEY_PEM: int
WSS_CERT_PEM: int
WSS_TRUST_PEM: int
WSS_HOSTNAME: int
WSS_TRUST_SYSTEM: int
ONLY_FIRST_SUBSCRIBE: int
RECONNECT_STOP: int
HELLO_MSG: int
DISCONNECT_MSG: int
PRIORITY: int
PAIR: int
PUB: int
SUB: int
REQ: int
REP: int
DEALER: int
ROUTER: int
PULL: int
PUSH: int
XPUB: int
XSUB: int
STREAM: int
XREQ: int
XREP: int
SERVER: int
CLIENT: int
RADIO: int
DISH: int
GATHER: int
SCATTER: int
DGRAM: int
PEER: int
CHANNEL: int
