from wandb import util as util
from wandb.sdk.lib import deprecate as deprecate

def deprecation_notice() -> None: ...
def test_missing(**kwargs): ...
def test_fitted(model): ...
def encode_labels(df): ...
def test_types(**kwargs): ...
