from _typeshed import Incomplete
from collections.abc import Generator
from debugpy.common import log as log
from debugpy.server import api as api

TARGET: str
HELP: Incomplete

class Options:
    mode: Incomplete
    address: Incomplete
    log_to: Incomplete
    log_to_stderr: bool
    target: Incomplete
    target_kind: Incomplete
    wait_for_client: bool
    adapter_access_token: Incomplete

options: Incomplete

def in_range(parser, start, stop): ...

pid: Incomplete

def print_help_and_exit(switch, it) -> None: ...
def print_version_and_exit(switch, it) -> None: ...
def set_arg(varname, parser=...): ...
def set_const(varname, value): ...
def set_address(mode): ...
def set_config(arg, it) -> None: ...
def set_target(kind, parser=..., positional: bool = False): ...

switches: Incomplete

def consume_argv() -> Generator[Incomplete, None, None]: ...
def parse_argv() -> None: ...
def start_debugging(argv_0) -> None: ...
def run_file() -> None: ...
def run_module() -> None: ...
def run_code() -> None: ...
def attach_to_pid(): ...
def main() -> None: ...
