import abc
import typing
from cryptography.x509.name import Name as Name
from cryptography.x509.oid import ObjectIdentifier as ObjectIdentifier

class UnsupportedGeneralNameType(Exception): ...

class GeneralName(metaclass=abc.ABCMeta):
    @property
    @abc.abstractmethod
    def value(self) -> typing.Any:
        """
        Return the value of the object
        """

class RFC822Name(GeneralName):
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DNSName(GeneralName):
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class UniformResourceIdentifier(GeneralName):
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DirectoryName(GeneralName):
    def __init__(self, value: Name) -> None: ...
    @property
    def value(self) -> Name: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class RegisteredID(GeneralName):
    def __init__(self, value: ObjectIdentifier) -> None: ...
    @property
    def value(self) -> ObjectIdentifier: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class IPAddress(GeneralName):
    def __init__(self, value: _IPAddressTypes) -> None: ...
    @property
    def value(self) -> _IPAddressTypes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class OtherName(GeneralName):
    def __init__(self, type_id: ObjectIdentifier, value: bytes) -> None: ...
    @property
    def type_id(self) -> ObjectIdentifier: ...
    @property
    def value(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
