from _typeshed import Incomplete
from jedi.inference.compiled.getattr_static import getattr_static as getattr_static
from pathlib import Path
from typing import NamedTuple, Tuple

ALLOWED_GETITEM_TYPES: Incomplete
MethodDescriptorType: Incomplete
NOT_CLASS_TYPES: Incomplete
WrapperDescriptorType: Incomplete
object_class_dict: Incomplete
ClassMethodDescriptorType: Incomplete
COMPARISON_OPERATORS: Incomplete
ALLOWED_DESCRIPTOR_ACCESS: Incomplete

def safe_getattr(obj, name, default=...): ...

class SignatureParam(NamedTuple):
    name: Incomplete
    has_default: Incomplete
    default: Incomplete
    default_string: Incomplete
    has_annotation: Incomplete
    annotation: Incomplete
    annotation_string: Incomplete
    kind_name: Incomplete

def shorten_repr(func): ...
def create_access(inference_state, obj): ...
def load_module(inference_state, dotted_name, sys_path): ...

class AccessPath:
    accesses: Incomplete
    def __init__(self, accesses) -> None: ...

def create_access_path(inference_state, obj) -> AccessPath: ...
def get_api_type(obj): ...

class DirectObjectAccess:
    def __init__(self, inference_state, obj) -> None: ...
    def py__bool__(self): ...
    def py__file__(self) -> Path | None: ...
    def py__doc__(self): ...
    def py__name__(self): ...
    def py__mro__accesses(self): ...
    def py__getitem__all_values(self): ...
    def py__simple_getitem__(self, index, *, safe: bool = True): ...
    def py__iter__list(self): ...
    def py__class__(self): ...
    def py__bases__(self): ...
    def py__path__(self): ...
    def get_repr(self): ...
    def is_class(self): ...
    def is_function(self): ...
    def is_module(self): ...
    def is_instance(self): ...
    def ismethoddescriptor(self): ...
    def get_qualified_names(self): ...
    def dir(self): ...
    def has_iter(self): ...
    def is_allowed_getattr(self, name, safe: bool = True) -> Tuple[bool, bool, AccessPath | None]: ...
    def getattr_paths(self, name, default=...): ...
    def get_safe_value(self): ...
    def get_api_type(self): ...
    def get_array_type(self): ...
    def get_key_paths(self): ...
    def get_access_path_tuples(self): ...
    def execute_operation(self, other_access_handle, operator): ...
    def get_annotation_name_and_args(self):
        """
        Returns Tuple[Optional[str], Tuple[AccessPath, ...]]
        """
    def needs_type_completions(self): ...
    def get_signature_params(self): ...
    def get_return_annotation(self) -> AccessPath | None: ...
    def negate(self): ...
    def get_dir_infos(self):
        """
        Used to return a couple of infos that are needed when accessing the sub
        objects of an objects
        """
