from . import Image as Image, ImageFile as ImageFile
from _typeshed import Incomplete

DDS_MAGIC: int
DDSD_CAPS: int
DDSD_HEIGHT: int
DDSD_WIDTH: int
DDSD_PITCH: int
DDSD_PIXELFORMAT: int
DDSD_MIPMAPCOUNT: int
DDSD_LINEARSIZE: int
DDSD_DEPTH: int
DDSCAPS_COMPLEX: int
DDSCAPS_TEXTURE: int
DDSCAPS_MIPMAP: int
DDSCAPS2_CUBEMAP: int
DDSCAPS2_CUBEMAP_POSITIVEX: int
DDSCAPS2_CUBEMAP_NEGATIVEX: int
DDSCAPS2_CUBEMAP_POSITIVEY: int
DDSCAPS2_CUBEMAP_NEGATIVEY: int
DDSCAPS2_CUBEMAP_POSITIVEZ: int
DDSCAPS2_CUBEMAP_NEGATIVEZ: int
DDSCAPS2_VOLUME: int
DDPF_ALPHAPIXELS: int
DDPF_ALPHA: int
DDPF_FOURCC: int
DDPF_PALETTEINDEXED8: int
DDPF_RGB: int
DDPF_LUMINANCE: int
DDS_FOURCC = DDPF_FOURCC
DDS_RGB = DDPF_RGB
DDS_RGBA: Incomplete
DDS_LUMINANCE = DDPF_LUMINANCE
DDS_LUMINANCEA: Incomplete
DDS_ALPHA = DDPF_ALPHA
DDS_PAL8 = DDPF_PALETTEINDEXED8
DDS_HEADER_FLAGS_TEXTURE: Incomplete
DDS_HEADER_FLAGS_MIPMAP = DDSD_MIPMAPCOUNT
DDS_HEADER_FLAGS_VOLUME = DDSD_DEPTH
DDS_HEADER_FLAGS_PITCH = DDSD_PITCH
DDS_HEADER_FLAGS_LINEARSIZE = DDSD_LINEARSIZE
DDS_HEIGHT = DDSD_HEIGHT
DDS_WIDTH = DDSD_WIDTH
DDS_SURFACE_FLAGS_TEXTURE = DDSCAPS_TEXTURE
DDS_SURFACE_FLAGS_MIPMAP: Incomplete
DDS_SURFACE_FLAGS_CUBEMAP = DDSCAPS_COMPLEX
DDS_CUBEMAP_POSITIVEX: Incomplete
DDS_CUBEMAP_NEGATIVEX: Incomplete
DDS_CUBEMAP_POSITIVEY: Incomplete
DDS_CUBEMAP_NEGATIVEY: Incomplete
DDS_CUBEMAP_POSITIVEZ: Incomplete
DDS_CUBEMAP_NEGATIVEZ: Incomplete
DXT1_FOURCC: int
DXT3_FOURCC: int
DXT5_FOURCC: int
DXGI_FORMAT_R8G8B8A8_TYPELESS: int
DXGI_FORMAT_R8G8B8A8_UNORM: int
DXGI_FORMAT_R8G8B8A8_UNORM_SRGB: int
DXGI_FORMAT_BC5_TYPELESS: int
DXGI_FORMAT_BC5_UNORM: int
DXGI_FORMAT_BC5_SNORM: int
DXGI_FORMAT_BC6H_UF16: int
DXGI_FORMAT_BC6H_SF16: int
DXGI_FORMAT_BC7_TYPELESS: int
DXGI_FORMAT_BC7_UNORM: int
DXGI_FORMAT_BC7_UNORM_SRGB: int

class DdsImageFile(ImageFile.ImageFile):
    format: str
    format_description: str
    def load_seek(self, pos) -> None: ...
