from . import Image as Image
from _typeshed import Incomplete

def grab(bbox: Incomplete | None = None, include_layered_windows: bool = False, all_screens: bool = False, xdisplay: Incomplete | None = None): ...
def grabclipboard(): ...
