from . import Image as Image, TiffImagePlugin as TiffImagePlugin
from _typeshed import Incomplete

class MicImageFile(TiffImagePlugin.TiffImageFile):
    format: str
    format_description: str
    fp: Incomplete
    frame: Incomplete
    def seek(self, frame) -> None: ...
    def tell(self): ...
    def close(self) -> None: ...
    def __exit__(self, *args) -> None: ...
