import wandb
from .bbox_utils import get_boxes as get_boxes, get_ground_truth_bbox_annotations as get_ground_truth_bbox_annotations
from typing import Any
from ultralytics.engine.results import Results as Results
from ultralytics.models.yolo.pose import PosePredictor as PosePredictor

def annotate_keypoint_results(result: Results, visualize_skeleton: bool): ...
def annotate_keypoint_batch(image_path: str, keypoints: Any, visualize_skeleton: bool): ...
def plot_pose_predictions(result: Results, model_name: str, visualize_skeleton: bool, table: wandb.Table | None = None): ...
def plot_pose_validation_results(dataloader, class_label_map, model_name: str, predictor: PosePredictor, visualize_skeleton: bool, table: wandb.Table, max_validation_batches: int, epoch: int | None = None) -> wandb.Table: ...
