import numpy as np
from collections.abc import Sequence
from jax._src.lib import xla_client as xc

def get_num_ways_dim_sharded(hlo_sharding: xc.HloSharding) -> tuple[Sequence[int], int]: ...
def is_op_sharding_replicated(op: xc.OpSharding | xc.HloSharding) -> bool: ...
def are_op_shardings_equal(op1: xc.OpSharding | xc.HloSharding, op2: xc.OpSharding | xc.HloSharding) -> bool: ...
def op_sharding_to_numpy_indices(hlo_sharding: xc.HloSharding, shape: Sequence[int], num_devices: int) -> np.ndarray: ...
def op_sharding_to_indices(op_sharding: xc.HloSharding, shape: Sequence[int], num_devices: int) -> tuple[tuple[slice, ...], ...]: ...
