from _typeshed import Incomplete

def validate_op_names(model, op_names, logger): ...
def validate_op_types(model, op_types, logger): ...
def validate_op_types_op_names(data): ...

class CompressorSchema:
    data_schema: Incomplete
    compressor_schema: Incomplete
    def __init__(self, data_schema, model, logger) -> None: ...
    def validate(self, data) -> None: ...

def validate_exclude_sparsity(data): ...
def validate_exclude_quant_types_quant_bits(data): ...

class PrunerSchema(CompressorSchema): ...
class QuantizerSchema(CompressorSchema): ...
