import types
import typing

def check_pkcs7_padding(data: bytes) -> bool: ...
def check_ansix923_padding(data: bytes) -> bool: ...

class ObjectIdentifier:
    def __init__(self, val: str) -> None: ...
    @property
    def dotted_string(self) -> str: ...
T = typing.TypeVar('T')

class FixedPool(typing.Generic[T]):
    def __init__(self, create: typing.Callable[[], T]) -> None: ...
    def acquire(self) -> PoolAcquisition[T]: ...

class PoolAcquisition(typing.Generic[T]):
    def __enter__(self) -> T: ...
    def __exit__(self, exc_type: typing.Type[BaseException] | None, exc_value: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
