from ..extern.jaraco.text import yield_lines as yield_lines
from ..extern.packaging.requirements import Requirement as Requirement

def write_requirements(cmd, basename, filename) -> None: ...
def write_setup_requirements(cmd, basename, filename) -> None: ...
