from _typeshed import Incomplete
from sympy.polys.densearith import dmp_abs as dmp_abs, dmp_add as dmp_add, dmp_add_ground as dmp_add_ground, dmp_add_mul as dmp_add_mul, dmp_add_term as dmp_add_term, dmp_div as dmp_div, dmp_expand as dmp_expand, dmp_exquo as dmp_exquo, dmp_exquo_ground as dmp_exquo_ground, dmp_ff_div as dmp_ff_div, dmp_l1_norm as dmp_l1_norm, dmp_l2_norm_squared as dmp_l2_norm_squared, dmp_max_norm as dmp_max_norm, dmp_mul as dmp_mul, dmp_mul_ground as dmp_mul_ground, dmp_mul_term as dmp_mul_term, dmp_neg as dmp_neg, dmp_pdiv as dmp_pdiv, dmp_pexquo as dmp_pexquo, dmp_pow as dmp_pow, dmp_pquo as dmp_pquo, dmp_prem as dmp_prem, dmp_quo as dmp_quo, dmp_quo_ground as dmp_quo_ground, dmp_rem as dmp_rem, dmp_rr_div as dmp_rr_div, dmp_sqr as dmp_sqr, dmp_sub as dmp_sub, dmp_sub_ground as dmp_sub_ground, dmp_sub_mul as dmp_sub_mul, dmp_sub_term as dmp_sub_term, dup_abs as dup_abs, dup_add as dup_add, dup_add_ground as dup_add_ground, dup_add_mul as dup_add_mul, dup_add_term as dup_add_term, dup_div as dup_div, dup_expand as dup_expand, dup_exquo as dup_exquo, dup_exquo_ground as dup_exquo_ground, dup_ff_div as dup_ff_div, dup_l1_norm as dup_l1_norm, dup_l2_norm_squared as dup_l2_norm_squared, dup_lshift as dup_lshift, dup_max_norm as dup_max_norm, dup_mul as dup_mul, dup_mul_ground as dup_mul_ground, dup_mul_term as dup_mul_term, dup_neg as dup_neg, dup_pdiv as dup_pdiv, dup_pexquo as dup_pexquo, dup_pow as dup_pow, dup_pquo as dup_pquo, dup_prem as dup_prem, dup_quo as dup_quo, dup_quo_ground as dup_quo_ground, dup_rem as dup_rem, dup_rr_div as dup_rr_div, dup_rshift as dup_rshift, dup_sqr as dup_sqr, dup_sub as dup_sub, dup_sub_ground as dup_sub_ground, dup_sub_mul as dup_sub_mul, dup_sub_term as dup_sub_term
from sympy.polys.densebasic import dmp_LC as dmp_LC, dmp_TC as dmp_TC, dmp_degree as dmp_degree, dmp_degree_in as dmp_degree_in, dmp_ground_LC as dmp_ground_LC, dmp_ground_TC as dmp_ground_TC, dmp_to_dict as dmp_to_dict, dup_LC as dup_LC, dup_TC as dup_TC, dup_degree as dup_degree
from sympy.polys.densetools import dmp_clear_denoms as dmp_clear_denoms, dmp_compose as dmp_compose, dmp_diff as dmp_diff, dmp_diff_eval_in as dmp_diff_eval_in, dmp_diff_in as dmp_diff_in, dmp_eval as dmp_eval, dmp_eval_in as dmp_eval_in, dmp_eval_tail as dmp_eval_tail, dmp_ground_content as dmp_ground_content, dmp_ground_extract as dmp_ground_extract, dmp_ground_monic as dmp_ground_monic, dmp_ground_primitive as dmp_ground_primitive, dmp_ground_trunc as dmp_ground_trunc, dmp_integrate as dmp_integrate, dmp_integrate_in as dmp_integrate_in, dmp_lift as dmp_lift, dmp_trunc as dmp_trunc, dup_clear_denoms as dup_clear_denoms, dup_compose as dup_compose, dup_content as dup_content, dup_decompose as dup_decompose, dup_diff as dup_diff, dup_eval as dup_eval, dup_extract as dup_extract, dup_integrate as dup_integrate, dup_mirror as dup_mirror, dup_monic as dup_monic, dup_primitive as dup_primitive, dup_real_imag as dup_real_imag, dup_revert as dup_revert, dup_scale as dup_scale, dup_shift as dup_shift, dup_sign_variations as dup_sign_variations, dup_transform as dup_transform, dup_trunc as dup_trunc
from sympy.polys.euclidtools import dmp_cancel as dmp_cancel, dmp_content as dmp_content, dmp_discriminant as dmp_discriminant, dmp_euclidean_prs as dmp_euclidean_prs, dmp_ff_lcm as dmp_ff_lcm, dmp_ff_prs_gcd as dmp_ff_prs_gcd, dmp_gcd as dmp_gcd, dmp_gcdex as dmp_gcdex, dmp_half_gcdex as dmp_half_gcdex, dmp_inner_gcd as dmp_inner_gcd, dmp_inner_subresultants as dmp_inner_subresultants, dmp_invert as dmp_invert, dmp_lcm as dmp_lcm, dmp_primitive as dmp_primitive, dmp_primitive_prs as dmp_primitive_prs, dmp_prs_resultant as dmp_prs_resultant, dmp_qq_collins_resultant as dmp_qq_collins_resultant, dmp_qq_heu_gcd as dmp_qq_heu_gcd, dmp_resultant as dmp_resultant, dmp_rr_lcm as dmp_rr_lcm, dmp_rr_prs_gcd as dmp_rr_prs_gcd, dmp_subresultants as dmp_subresultants, dmp_zz_collins_resultant as dmp_zz_collins_resultant, dmp_zz_heu_gcd as dmp_zz_heu_gcd, dmp_zz_modular_resultant as dmp_zz_modular_resultant, dup_cancel as dup_cancel, dup_discriminant as dup_discriminant, dup_euclidean_prs as dup_euclidean_prs, dup_ff_lcm as dup_ff_lcm, dup_ff_prs_gcd as dup_ff_prs_gcd, dup_gcd as dup_gcd, dup_gcdex as dup_gcdex, dup_half_gcdex as dup_half_gcdex, dup_inner_gcd as dup_inner_gcd, dup_inner_subresultants as dup_inner_subresultants, dup_invert as dup_invert, dup_lcm as dup_lcm, dup_primitive_prs as dup_primitive_prs, dup_prs_resultant as dup_prs_resultant, dup_qq_heu_gcd as dup_qq_heu_gcd, dup_resultant as dup_resultant, dup_rr_lcm as dup_rr_lcm, dup_rr_prs_gcd as dup_rr_prs_gcd, dup_subresultants as dup_subresultants, dup_zz_heu_gcd as dup_zz_heu_gcd
from sympy.polys.factortools import dmp_ext_factor as dmp_ext_factor, dmp_factor_list as dmp_factor_list, dmp_factor_list_include as dmp_factor_list_include, dmp_gf_factor as dmp_gf_factor, dmp_irreducible_p as dmp_irreducible_p, dmp_qq_i_factor as dmp_qq_i_factor, dmp_trial_division as dmp_trial_division, dmp_zz_diophantine as dmp_zz_diophantine, dmp_zz_factor as dmp_zz_factor, dmp_zz_i_factor as dmp_zz_i_factor, dmp_zz_mignotte_bound as dmp_zz_mignotte_bound, dmp_zz_wang as dmp_zz_wang, dmp_zz_wang_hensel_lifting as dmp_zz_wang_hensel_lifting, dmp_zz_wang_lead_coeffs as dmp_zz_wang_lead_coeffs, dmp_zz_wang_non_divisors as dmp_zz_wang_non_divisors, dup_cyclotomic_p as dup_cyclotomic_p, dup_ext_factor as dup_ext_factor, dup_factor_list as dup_factor_list, dup_factor_list_include as dup_factor_list_include, dup_gf_factor as dup_gf_factor, dup_irreducible_p as dup_irreducible_p, dup_qq_i_factor as dup_qq_i_factor, dup_trial_division as dup_trial_division, dup_zz_cyclotomic_factor as dup_zz_cyclotomic_factor, dup_zz_cyclotomic_poly as dup_zz_cyclotomic_poly, dup_zz_diophantine as dup_zz_diophantine, dup_zz_factor as dup_zz_factor, dup_zz_factor_sqf as dup_zz_factor_sqf, dup_zz_hensel_lift as dup_zz_hensel_lift, dup_zz_hensel_step as dup_zz_hensel_step, dup_zz_i_factor as dup_zz_i_factor, dup_zz_irreducible_p as dup_zz_irreducible_p, dup_zz_mignotte_bound as dup_zz_mignotte_bound, dup_zz_zassenhaus as dup_zz_zassenhaus
from sympy.polys.galoistools import gf_LC as gf_LC, gf_Qmatrix as gf_Qmatrix, gf_TC as gf_TC, gf_add as gf_add, gf_add_ground as gf_add_ground, gf_add_mul as gf_add_mul, gf_berlekamp as gf_berlekamp, gf_cofactors as gf_cofactors, gf_compose as gf_compose, gf_compose_mod as gf_compose_mod, gf_ddf_shoup as gf_ddf_shoup, gf_ddf_zassenhaus as gf_ddf_zassenhaus, gf_degree as gf_degree, gf_diff as gf_diff, gf_div as gf_div, gf_edf_shoup as gf_edf_shoup, gf_edf_zassenhaus as gf_edf_zassenhaus, gf_eval as gf_eval, gf_expand as gf_expand, gf_exquo as gf_exquo, gf_factor as gf_factor, gf_factor_sqf as gf_factor_sqf, gf_from_dict as gf_from_dict, gf_from_int_poly as gf_from_int_poly, gf_gcd as gf_gcd, gf_gcdex as gf_gcdex, gf_irred_p_ben_or as gf_irred_p_ben_or, gf_irred_p_rabin as gf_irred_p_rabin, gf_irreducible as gf_irreducible, gf_irreducible_p as gf_irreducible_p, gf_lcm as gf_lcm, gf_lshift as gf_lshift, gf_monic as gf_monic, gf_mul as gf_mul, gf_mul_ground as gf_mul_ground, gf_multi_eval as gf_multi_eval, gf_neg as gf_neg, gf_pow as gf_pow, gf_pow_mod as gf_pow_mod, gf_quo as gf_quo, gf_quo_ground as gf_quo_ground, gf_random as gf_random, gf_rem as gf_rem, gf_rshift as gf_rshift, gf_shoup as gf_shoup, gf_sqf_p as gf_sqf_p, gf_sqf_part as gf_sqf_part, gf_sqr as gf_sqr, gf_strip as gf_strip, gf_sub as gf_sub, gf_sub_ground as gf_sub_ground, gf_sub_mul as gf_sub_mul, gf_to_dict as gf_to_dict, gf_to_int_poly as gf_to_int_poly, gf_trace_map as gf_trace_map, gf_zassenhaus as gf_zassenhaus
from sympy.polys.rootisolation import dup_count_complex_roots as dup_count_complex_roots, dup_count_real_roots as dup_count_real_roots, dup_inner_isolate_negative_roots as dup_inner_isolate_negative_roots, dup_inner_isolate_positive_roots as dup_inner_isolate_positive_roots, dup_inner_isolate_real_roots as dup_inner_isolate_real_roots, dup_inner_refine_real_root as dup_inner_refine_real_root, dup_isolate_all_roots as dup_isolate_all_roots, dup_isolate_all_roots_sqf as dup_isolate_all_roots_sqf, dup_isolate_complex_roots_sqf as dup_isolate_complex_roots_sqf, dup_isolate_real_roots as dup_isolate_real_roots, dup_isolate_real_roots_list as dup_isolate_real_roots_list, dup_isolate_real_roots_sqf as dup_isolate_real_roots_sqf, dup_outer_refine_real_root as dup_outer_refine_real_root, dup_refine_real_root as dup_refine_real_root, dup_root_lower_bound as dup_root_lower_bound, dup_root_upper_bound as dup_root_upper_bound, dup_step_refine_real_root as dup_step_refine_real_root, dup_sturm as dup_sturm
from sympy.polys.sqfreetools import dmp_gf_sqf_list as dmp_gf_sqf_list, dmp_gf_sqf_part as dmp_gf_sqf_part, dmp_gff_list as dmp_gff_list, dmp_sqf_list as dmp_sqf_list, dmp_sqf_list_include as dmp_sqf_list_include, dmp_sqf_norm as dmp_sqf_norm, dmp_sqf_p as dmp_sqf_p, dmp_sqf_part as dmp_sqf_part, dup_gf_sqf_list as dup_gf_sqf_list, dup_gf_sqf_part as dup_gf_sqf_part, dup_gff_list as dup_gff_list, dup_sqf_list as dup_sqf_list, dup_sqf_list_include as dup_sqf_list_include, dup_sqf_norm as dup_sqf_norm, dup_sqf_p as dup_sqf_p, dup_sqf_part as dup_sqf_part
from sympy.utilities import public as public

class IPolys:
    symbols: Incomplete
    ngens: Incomplete
    domain: Incomplete
    order: Incomplete
    gens: Incomplete
    def drop(self, gen) -> None: ...
    def clone(self, symbols: Incomplete | None = None, domain: Incomplete | None = None, order: Incomplete | None = None) -> None: ...
    def to_ground(self) -> None: ...
    def ground_new(self, element) -> None: ...
    def domain_new(self, element) -> None: ...
    def from_dict(self, d) -> None: ...
    def wrap(self, element): ...
    def to_dense(self, element): ...
    def from_dense(self, element): ...
    def dup_add_term(self, f, c, i): ...
    def dmp_add_term(self, f, c, i): ...
    def dup_sub_term(self, f, c, i): ...
    def dmp_sub_term(self, f, c, i): ...
    def dup_mul_term(self, f, c, i): ...
    def dmp_mul_term(self, f, c, i): ...
    def dup_add_ground(self, f, c): ...
    def dmp_add_ground(self, f, c): ...
    def dup_sub_ground(self, f, c): ...
    def dmp_sub_ground(self, f, c): ...
    def dup_mul_ground(self, f, c): ...
    def dmp_mul_ground(self, f, c): ...
    def dup_quo_ground(self, f, c): ...
    def dmp_quo_ground(self, f, c): ...
    def dup_exquo_ground(self, f, c): ...
    def dmp_exquo_ground(self, f, c): ...
    def dup_lshift(self, f, n): ...
    def dup_rshift(self, f, n): ...
    def dup_abs(self, f): ...
    def dmp_abs(self, f): ...
    def dup_neg(self, f): ...
    def dmp_neg(self, f): ...
    def dup_add(self, f, g): ...
    def dmp_add(self, f, g): ...
    def dup_sub(self, f, g): ...
    def dmp_sub(self, f, g): ...
    def dup_add_mul(self, f, g, h): ...
    def dmp_add_mul(self, f, g, h): ...
    def dup_sub_mul(self, f, g, h): ...
    def dmp_sub_mul(self, f, g, h): ...
    def dup_mul(self, f, g): ...
    def dmp_mul(self, f, g): ...
    def dup_sqr(self, f): ...
    def dmp_sqr(self, f): ...
    def dup_pow(self, f, n): ...
    def dmp_pow(self, f, n): ...
    def dup_pdiv(self, f, g): ...
    def dup_prem(self, f, g): ...
    def dup_pquo(self, f, g): ...
    def dup_pexquo(self, f, g): ...
    def dmp_pdiv(self, f, g): ...
    def dmp_prem(self, f, g): ...
    def dmp_pquo(self, f, g): ...
    def dmp_pexquo(self, f, g): ...
    def dup_rr_div(self, f, g): ...
    def dmp_rr_div(self, f, g): ...
    def dup_ff_div(self, f, g): ...
    def dmp_ff_div(self, f, g): ...
    def dup_div(self, f, g): ...
    def dup_rem(self, f, g): ...
    def dup_quo(self, f, g): ...
    def dup_exquo(self, f, g): ...
    def dmp_div(self, f, g): ...
    def dmp_rem(self, f, g): ...
    def dmp_quo(self, f, g): ...
    def dmp_exquo(self, f, g): ...
    def dup_max_norm(self, f): ...
    def dmp_max_norm(self, f): ...
    def dup_l1_norm(self, f): ...
    def dmp_l1_norm(self, f): ...
    def dup_l2_norm_squared(self, f): ...
    def dmp_l2_norm_squared(self, f): ...
    def dup_expand(self, polys): ...
    def dmp_expand(self, polys): ...
    def dup_LC(self, f): ...
    def dmp_LC(self, f): ...
    def dup_TC(self, f): ...
    def dmp_TC(self, f): ...
    def dmp_ground_LC(self, f): ...
    def dmp_ground_TC(self, f): ...
    def dup_degree(self, f): ...
    def dmp_degree(self, f): ...
    def dmp_degree_in(self, f, j): ...
    def dup_integrate(self, f, m): ...
    def dmp_integrate(self, f, m): ...
    def dup_diff(self, f, m): ...
    def dmp_diff(self, f, m): ...
    def dmp_diff_in(self, f, m, j): ...
    def dmp_integrate_in(self, f, m, j): ...
    def dup_eval(self, f, a): ...
    def dmp_eval(self, f, a): ...
    def dmp_eval_in(self, f, a, j): ...
    def dmp_diff_eval_in(self, f, m, a, j): ...
    def dmp_eval_tail(self, f, A): ...
    def dup_trunc(self, f, p): ...
    def dmp_trunc(self, f, g): ...
    def dmp_ground_trunc(self, f, p): ...
    def dup_monic(self, f): ...
    def dmp_ground_monic(self, f): ...
    def dup_extract(self, f, g): ...
    def dmp_ground_extract(self, f, g): ...
    def dup_real_imag(self, f): ...
    def dup_mirror(self, f): ...
    def dup_scale(self, f, a): ...
    def dup_shift(self, f, a): ...
    def dup_transform(self, f, p, q): ...
    def dup_compose(self, f, g): ...
    def dmp_compose(self, f, g): ...
    def dup_decompose(self, f): ...
    def dmp_lift(self, f): ...
    def dup_sign_variations(self, f): ...
    def dup_clear_denoms(self, f, convert: bool = False): ...
    def dmp_clear_denoms(self, f, convert: bool = False): ...
    def dup_revert(self, f, n): ...
    def dup_half_gcdex(self, f, g): ...
    def dmp_half_gcdex(self, f, g): ...
    def dup_gcdex(self, f, g): ...
    def dmp_gcdex(self, f, g): ...
    def dup_invert(self, f, g): ...
    def dmp_invert(self, f, g): ...
    def dup_euclidean_prs(self, f, g): ...
    def dmp_euclidean_prs(self, f, g): ...
    def dup_primitive_prs(self, f, g): ...
    def dmp_primitive_prs(self, f, g): ...
    def dup_inner_subresultants(self, f, g): ...
    def dmp_inner_subresultants(self, f, g): ...
    def dup_subresultants(self, f, g): ...
    def dmp_subresultants(self, f, g): ...
    def dup_prs_resultant(self, f, g): ...
    def dmp_prs_resultant(self, f, g): ...
    def dmp_zz_modular_resultant(self, f, g, p): ...
    def dmp_zz_collins_resultant(self, f, g): ...
    def dmp_qq_collins_resultant(self, f, g): ...
    def dup_resultant(self, f, g): ...
    def dmp_resultant(self, f, g): ...
    def dup_discriminant(self, f): ...
    def dmp_discriminant(self, f): ...
    def dup_rr_prs_gcd(self, f, g): ...
    def dup_ff_prs_gcd(self, f, g): ...
    def dmp_rr_prs_gcd(self, f, g): ...
    def dmp_ff_prs_gcd(self, f, g): ...
    def dup_zz_heu_gcd(self, f, g): ...
    def dmp_zz_heu_gcd(self, f, g): ...
    def dup_qq_heu_gcd(self, f, g): ...
    def dmp_qq_heu_gcd(self, f, g): ...
    def dup_inner_gcd(self, f, g): ...
    def dmp_inner_gcd(self, f, g): ...
    def dup_gcd(self, f, g): ...
    def dmp_gcd(self, f, g): ...
    def dup_rr_lcm(self, f, g): ...
    def dup_ff_lcm(self, f, g): ...
    def dup_lcm(self, f, g): ...
    def dmp_rr_lcm(self, f, g): ...
    def dmp_ff_lcm(self, f, g): ...
    def dmp_lcm(self, f, g): ...
    def dup_content(self, f): ...
    def dup_primitive(self, f): ...
    def dmp_content(self, f): ...
    def dmp_primitive(self, f): ...
    def dmp_ground_content(self, f): ...
    def dmp_ground_primitive(self, f): ...
    def dup_cancel(self, f, g, include: bool = True): ...
    def dmp_cancel(self, f, g, include: bool = True): ...
    def dup_trial_division(self, f, factors): ...
    def dmp_trial_division(self, f, factors): ...
    def dup_zz_mignotte_bound(self, f): ...
    def dmp_zz_mignotte_bound(self, f): ...
    def dup_zz_hensel_step(self, m, f, g, h, s, t): ...
    def dup_zz_hensel_lift(self, p, f, f_list, l): ...
    def dup_zz_zassenhaus(self, f): ...
    def dup_zz_irreducible_p(self, f): ...
    def dup_cyclotomic_p(self, f, irreducible: bool = False): ...
    def dup_zz_cyclotomic_poly(self, n): ...
    def dup_zz_cyclotomic_factor(self, f): ...
    def dmp_zz_wang_non_divisors(self, E, cs, ct): ...
    def dmp_zz_wang_lead_coeffs(self, f, T, cs, E, H, A): ...
    def dup_zz_diophantine(self, F, m, p): ...
    def dmp_zz_diophantine(self, F, c, A, d, p): ...
    def dmp_zz_wang_hensel_lifting(self, f, H, LC, A, p): ...
    def dmp_zz_wang(self, f, mod: Incomplete | None = None, seed: Incomplete | None = None): ...
    def dup_zz_factor_sqf(self, f): ...
    def dup_zz_factor(self, f): ...
    def dmp_zz_factor(self, f): ...
    def dup_qq_i_factor(self, f): ...
    def dmp_qq_i_factor(self, f): ...
    def dup_zz_i_factor(self, f): ...
    def dmp_zz_i_factor(self, f): ...
    def dup_ext_factor(self, f): ...
    def dmp_ext_factor(self, f): ...
    def dup_gf_factor(self, f): ...
    def dmp_gf_factor(self, f): ...
    def dup_factor_list(self, f): ...
    def dup_factor_list_include(self, f): ...
    def dmp_factor_list(self, f): ...
    def dmp_factor_list_include(self, f): ...
    def dup_irreducible_p(self, f): ...
    def dmp_irreducible_p(self, f): ...
    def dup_sturm(self, f): ...
    def dup_sqf_p(self, f): ...
    def dmp_sqf_p(self, f): ...
    def dup_sqf_norm(self, f): ...
    def dmp_sqf_norm(self, f): ...
    def dup_gf_sqf_part(self, f): ...
    def dmp_gf_sqf_part(self, f): ...
    def dup_sqf_part(self, f): ...
    def dmp_sqf_part(self, f): ...
    def dup_gf_sqf_list(self, f, all: bool = False): ...
    def dmp_gf_sqf_list(self, f, all: bool = False): ...
    def dup_sqf_list(self, f, all: bool = False): ...
    def dup_sqf_list_include(self, f, all: bool = False): ...
    def dmp_sqf_list(self, f, all: bool = False): ...
    def dmp_sqf_list_include(self, f, all: bool = False): ...
    def dup_gff_list(self, f): ...
    def dmp_gff_list(self, f): ...
    def dup_root_upper_bound(self, f): ...
    def dup_root_lower_bound(self, f): ...
    def dup_step_refine_real_root(self, f, M, fast: bool = False): ...
    def dup_inner_refine_real_root(self, f, M, eps: Incomplete | None = None, steps: Incomplete | None = None, disjoint: Incomplete | None = None, fast: bool = False, mobius: bool = False): ...
    def dup_outer_refine_real_root(self, f, s, t, eps: Incomplete | None = None, steps: Incomplete | None = None, disjoint: Incomplete | None = None, fast: bool = False): ...
    def dup_refine_real_root(self, f, s, t, eps: Incomplete | None = None, steps: Incomplete | None = None, disjoint: Incomplete | None = None, fast: bool = False): ...
    def dup_inner_isolate_real_roots(self, f, eps: Incomplete | None = None, fast: bool = False): ...
    def dup_inner_isolate_positive_roots(self, f, eps: Incomplete | None = None, inf: Incomplete | None = None, sup: Incomplete | None = None, fast: bool = False, mobius: bool = False): ...
    def dup_inner_isolate_negative_roots(self, f, inf: Incomplete | None = None, sup: Incomplete | None = None, eps: Incomplete | None = None, fast: bool = False, mobius: bool = False): ...
    def dup_isolate_real_roots_sqf(self, f, eps: Incomplete | None = None, inf: Incomplete | None = None, sup: Incomplete | None = None, fast: bool = False, blackbox: bool = False): ...
    def dup_isolate_real_roots(self, f, eps: Incomplete | None = None, inf: Incomplete | None = None, sup: Incomplete | None = None, basis: bool = False, fast: bool = False): ...
    def dup_isolate_real_roots_list(self, polys, eps: Incomplete | None = None, inf: Incomplete | None = None, sup: Incomplete | None = None, strict: bool = False, basis: bool = False, fast: bool = False): ...
    def dup_count_real_roots(self, f, inf: Incomplete | None = None, sup: Incomplete | None = None): ...
    def dup_count_complex_roots(self, f, inf: Incomplete | None = None, sup: Incomplete | None = None, exclude: Incomplete | None = None): ...
    def dup_isolate_complex_roots_sqf(self, f, eps: Incomplete | None = None, inf: Incomplete | None = None, sup: Incomplete | None = None, blackbox: bool = False): ...
    def dup_isolate_all_roots_sqf(self, f, eps: Incomplete | None = None, inf: Incomplete | None = None, sup: Incomplete | None = None, fast: bool = False, blackbox: bool = False): ...
    def dup_isolate_all_roots(self, f, eps: Incomplete | None = None, inf: Incomplete | None = None, sup: Incomplete | None = None, fast: bool = False): ...
    def fateman_poly_F_1(self): ...
    def fateman_poly_F_2(self): ...
    def fateman_poly_F_3(self): ...
    def to_gf_dense(self, element): ...
    def from_gf_dense(self, element): ...
    def gf_degree(self, f): ...
    def gf_LC(self, f): ...
    def gf_TC(self, f): ...
    def gf_strip(self, f): ...
    def gf_trunc(self, f): ...
    def gf_normal(self, f): ...
    def gf_from_dict(self, f): ...
    def gf_to_dict(self, f, symmetric: bool = True): ...
    def gf_from_int_poly(self, f): ...
    def gf_to_int_poly(self, f, symmetric: bool = True): ...
    def gf_neg(self, f): ...
    def gf_add_ground(self, f, a): ...
    def gf_sub_ground(self, f, a): ...
    def gf_mul_ground(self, f, a): ...
    def gf_quo_ground(self, f, a): ...
    def gf_add(self, f, g): ...
    def gf_sub(self, f, g): ...
    def gf_mul(self, f, g): ...
    def gf_sqr(self, f): ...
    def gf_add_mul(self, f, g, h): ...
    def gf_sub_mul(self, f, g, h): ...
    def gf_expand(self, F): ...
    def gf_div(self, f, g): ...
    def gf_rem(self, f, g): ...
    def gf_quo(self, f, g): ...
    def gf_exquo(self, f, g): ...
    def gf_lshift(self, f, n): ...
    def gf_rshift(self, f, n): ...
    def gf_pow(self, f, n): ...
    def gf_pow_mod(self, f, n, g): ...
    def gf_cofactors(self, f, g): ...
    def gf_gcd(self, f, g): ...
    def gf_lcm(self, f, g): ...
    def gf_gcdex(self, f, g): ...
    def gf_monic(self, f): ...
    def gf_diff(self, f): ...
    def gf_eval(self, f, a): ...
    def gf_multi_eval(self, f, A): ...
    def gf_compose(self, f, g): ...
    def gf_compose_mod(self, g, h, f): ...
    def gf_trace_map(self, a, b, c, n, f): ...
    def gf_random(self, n): ...
    def gf_irreducible(self, n): ...
    def gf_irred_p_ben_or(self, f): ...
    def gf_irred_p_rabin(self, f): ...
    def gf_irreducible_p(self, f): ...
    def gf_sqf_p(self, f): ...
    def gf_sqf_part(self, f): ...
    def gf_sqf_list(self, f, all: bool = False): ...
    def gf_Qmatrix(self, f): ...
    def gf_berlekamp(self, f): ...
    def gf_ddf_zassenhaus(self, f): ...
    def gf_edf_zassenhaus(self, f, n): ...
    def gf_ddf_shoup(self, f): ...
    def gf_edf_shoup(self, f, n): ...
    def gf_zassenhaus(self, f): ...
    def gf_shoup(self, f): ...
    def gf_factor_sqf(self, f, method: Incomplete | None = None): ...
    def gf_factor(self, f): ...
