from _typeshed import Incomplete
from sympy.core import Symbol as Symbol
from sympy.core.evalf import N as N
from sympy.core.numbers import I as I, Rational as Rational
from sympy.functions import sqrt as sqrt
from sympy.polys.polytools import Poly as Poly
from sympy.utilities import public as public

x: Incomplete

class PolyQuintic:
    """Special functions for solvable quintics"""
    zeta1: Incomplete
    zeta2: Incomplete
    zeta3: Incomplete
    zeta4: Incomplete
    def __init__(self, poly) -> None: ...
    @property
    def f20(self): ...
    @property
    def b(self): ...
    @property
    def o(self): ...
    @property
    def a(self): ...
    @property
    def c(self): ...
    @property
    def F(self): ...
    def l0(self, theta): ...
    def T(self, theta, d): ...
    def order(self, theta, d): ...
    def uv(self, theta, d): ...
    @property
    def zeta(self): ...
