from _typeshed import Incomplete

class TsaDescriptive:
    """collection of descriptive statistical methods for time series

    """
    data: Incomplete
    label: Incomplete
    name: Incomplete
    def __init__(self, data, label: Incomplete | None = None, name: str = '') -> None: ...
    def filter(self, num, den): ...
    def detrend(self, order: int = 1): ...
    mod: Incomplete
    res: Incomplete
    def fit(self, order=(1, 0, 1), **kwds): ...
    def acf(self, nlags: int = 40): ...
    def pacf(self, nlags: int = 40): ...
    def periodogram(self): ...
    def plot4(self, fig: Incomplete | None = None, nobs: int = 100, nacf: int = 20, nfreq: int = 100): ...
