from tensorboard.plugins import base_plugin as base_plugin

class ProfileRedirectPluginLoader(base_plugin.TBLoader):
    """Load the redirect notice iff the dynamic plugin is unavailable."""
    def load(self, context): ...

class _ProfileRedirectPlugin(base_plugin.TBPlugin):
    """Redirect notice pointing users to the new dynamic profile plugin."""
    plugin_name: str
    def get_plugin_apps(self): ...
    def is_active(self): ...
    def frontend_metadata(self): ...
