from _typeshed import Incomplete
from transformers import DonutFeatureExtractor as DonutFeatureExtractor, DonutProcessor as DonutProcessor, DonutSwinConfig as DonutSwinConfig, DonutSwinModel as DonutSwinModel, MBartConfig as MBartConfig, MBartForCausalLM as MBartForCausalLM, VisionEncoderDecoderModel as VisionEncoderDecoderModel, XLMRobertaTokenizerFast as XLMRobertaTokenizerFast

def get_configs(model): ...
def rename_key(name): ...
def convert_state_dict(orig_state_dict, model): ...
def convert_donut_checkpoint(model_name, pytorch_dump_folder_path: Incomplete | None = None, push_to_hub: bool = False) -> None: ...
