from _typeshed import Incomplete
from ctypes import Structure, Union
from numba import literal_unroll as literal_unroll
from numba.core import errors as errors, types as types, utils as utils
from numba.core.extending import intrinsic as intrinsic, overload as overload, overload_method as overload_method, register_jitable as register_jitable
from numba.core.unsafe.bytes import grab_byte as grab_byte, grab_uint64_t as grab_uint64_t
from numba.cpython.randomimpl import const_int as const_int, get_next_int as get_next_int, get_next_int32 as get_next_int32, get_state_ptr as get_state_ptr
from typing import NamedTuple

def ol_defer_hash(obj, hash_func): ...
def hash_overload(obj): ...
def process_return(val): ...
def int_hash(val): ...
def float_hash(val): ...
def complex_hash(val): ...
def tuple_hash(val): ...

class FNV(Structure): ...
class SIPHASH(Structure): ...
class DJBX33A(Structure): ...
class EXPAT(Structure): ...
class _Py_HashSecret_t(Union): ...

class _hashsecret_entry(NamedTuple):
    symbol: Incomplete
    value: Incomplete

msg: str

def unicode_hash(val): ...
