from _typeshed import Incomplete
from databricks_cli.sdk import SecretService as SecretService

class SecretApi:
    client: Incomplete
    def __init__(self, api_client) -> None: ...
    def create_scope(self, scope, initial_manage_principal, scope_backend_type, backend_azure_keyvault): ...
    def delete_scope(self, scope): ...
    def list_scopes(self): ...
    def put_secret(self, scope, key, string_value, bytes_value): ...
    def delete_secret(self, scope, key): ...
    def list_secrets(self, scope): ...
    def put_acl(self, scope, principal, permission): ...
    def delete_acl(self, scope, principal): ...
    def list_acls(self, scope): ...
    def get_acl(self, scope, principal): ...
