from transformers import M2M100Config as M2M100Config, M2M100ForConditionalGeneration as M2M100ForConditionalGeneration

def remove_ignore_keys_(state_dict) -> None: ...
def make_linear_from_emb(emb): ...
def convert_fairseq_m2m100_checkpoint_from_disk(checkpoint_path): ...
