from . import __version__ as __version__, api as api
from _typeshed import Incomplete

def parse_args(parse_this: Incomplete | None = None): ...
def build_parser(): ...
def main(args: Incomplete | None = None) -> None: ...
