import typing
from _typeshed import Incomplete
from cryptography import x509
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives._serialization import PBES as PBES
from cryptography.hazmat.primitives.asymmetric.types import PrivateKeyTypes

__all__ = ['PBES', 'PKCS12PrivateKeyTypes', 'PKCS12Certificate', 'PKCS12KeyAndCertificates', 'load_key_and_certificates', 'load_pkcs12', 'serialize_key_and_certificates']

PKCS12PrivateKeyTypes: Incomplete

class PKCS12Certificate:
    def __init__(self, cert: x509.Certificate, friendly_name: bytes | None) -> None: ...
    @property
    def friendly_name(self) -> bytes | None: ...
    @property
    def certificate(self) -> x509.Certificate: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class PKCS12KeyAndCertificates:
    def __init__(self, key: PrivateKeyTypes | None, cert: PKCS12Certificate | None, additional_certs: typing.List[PKCS12Certificate]) -> None: ...
    @property
    def key(self) -> PrivateKeyTypes | None: ...
    @property
    def cert(self) -> PKCS12Certificate | None: ...
    @property
    def additional_certs(self) -> typing.List[PKCS12Certificate]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

def load_key_and_certificates(data: bytes, password: bytes | None, backend: typing.Any = None) -> typing.Tuple[PrivateKeyTypes | None, x509.Certificate | None, typing.List[x509.Certificate]]: ...
def load_pkcs12(data: bytes, password: bytes | None, backend: typing.Any = None) -> PKCS12KeyAndCertificates: ...
def serialize_key_and_certificates(name: bytes | None, key: PKCS12PrivateKeyTypes | None, cert: x509.Certificate | None, cas: typing.Iterable[_PKCS12CATypes] | None, encryption_algorithm: serialization.KeySerializationEncryption) -> bytes: ...
