from _typeshed import Incomplete

def pre_build_hook(build_ext, ext) -> None: ...
def basiclu_pre_build_hook(build_clib, build_info) -> None: ...
def configuration(parent_package: str = '', top_path: Incomplete | None = None): ...
