from transformers import PLBartConfig as PLBartConfig, PLBartForConditionalGeneration as PLBartForConditionalGeneration, PLBartForSequenceClassification as PLBartForSequenceClassification

def remove_ignore_keys_(state_dict) -> None: ...
def make_linear_from_emb(emb): ...
def convert_fairseq_plbart_checkpoint_from_disk(checkpoint_path, hf_config_path: str = 'uclanlp/plbart-base', finetuned: bool = False, classification: bool = False): ...
