from . import encode_base64 as encode_base64, url_quote as url_quote
from .request_handlers import get_length as get_length
from .response_handlers import return_response_headers as return_response_headers
from _typeshed import Incomplete
from collections.abc import Generator
from io import IOBase

def upload_data_chunks(service: Incomplete | None = None, uploader_class: Incomplete | None = None, total_size: Incomplete | None = None, chunk_size: Incomplete | None = None, max_concurrency: Incomplete | None = None, stream: Incomplete | None = None, validate_content: Incomplete | None = None, progress_hook: Incomplete | None = None, **kwargs): ...
def upload_substream_blocks(service: Incomplete | None = None, uploader_class: Incomplete | None = None, total_size: Incomplete | None = None, chunk_size: Incomplete | None = None, max_concurrency: Incomplete | None = None, stream: Incomplete | None = None, progress_hook: Incomplete | None = None, **kwargs): ...

class _ChunkUploader:
    service: Incomplete
    total_size: Incomplete
    chunk_size: Incomplete
    stream: Incomplete
    parallel: Incomplete
    stream_lock: Incomplete
    progress_total: int
    progress_lock: Incomplete
    progress_hook: Incomplete
    encryptor: Incomplete
    padder: Incomplete
    response_headers: Incomplete
    etag: Incomplete
    last_modified: Incomplete
    request_options: Incomplete
    def __init__(self, service, total_size, chunk_size, stream, parallel, encryptor: Incomplete | None = None, padder: Incomplete | None = None, progress_hook: Incomplete | None = None, **kwargs) -> None: ...
    def get_chunk_streams(self) -> Generator[Incomplete, None, None]: ...
    def process_chunk(self, chunk_data): ...
    def get_substream_blocks(self) -> Generator[Incomplete, None, None]: ...
    def process_substream_block(self, block_data): ...
    def set_response_properties(self, resp) -> None: ...

class BlockBlobChunkUploader(_ChunkUploader):
    current_length: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...

class PageBlobChunkUploader(_ChunkUploader): ...

class AppendBlobChunkUploader(_ChunkUploader):
    current_length: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...

class DataLakeFileChunkUploader(_ChunkUploader): ...
class FileChunkUploader(_ChunkUploader): ...

class SubStream(IOBase):
    def __init__(self, wrapped_stream, stream_begin_index, length, lockObj) -> None: ...
    def __len__(self) -> int: ...
    def close(self) -> None: ...
    def fileno(self): ...
    def flush(self) -> None: ...
    def read(self, size: Incomplete | None = None): ...
    def readable(self): ...
    def readinto(self, b) -> None: ...
    def seek(self, offset, whence: int = 0): ...
    def seekable(self): ...
    def tell(self): ...
    def write(self) -> None: ...
    def writelines(self) -> None: ...
    def writeable(self): ...

class IterStreamer:
    """
    File-like streaming iterator.
    """
    generator: Incomplete
    iterator: Incomplete
    leftover: bytes
    encoding: Incomplete
    def __init__(self, generator, encoding: str = 'UTF-8') -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def seekable(self): ...
    def __next__(self): ...
    def tell(self, *args, **kwargs) -> None: ...
    def seek(self, *args, **kwargs) -> None: ...
    def read(self, size): ...
