from _typeshed import Incomplete
from collections.abc import Generator
from mlflow.entities import FileInfo as FileInfo
from mlflow.store.artifact.artifact_repo import ArtifactRepository as ArtifactRepository

class _SftpPool:
    def __init__(self, connections) -> None: ...
    def get_sfp_connection(self) -> Generator[Incomplete, None, Incomplete]: ...

class SFTPArtifactRepository(ArtifactRepository):
    """Stores artifacts as files in a remote directory, via sftp."""
    uri: Incomplete
    config: Incomplete
    path: Incomplete
    pool: Incomplete
    def __init__(self, artifact_uri) -> None: ...
    def log_artifact(self, local_file, artifact_path: Incomplete | None = None) -> None: ...
    def log_artifacts(self, local_dir, artifact_path: Incomplete | None = None) -> None: ...
    def list_artifacts(self, path: Incomplete | None = None): ...
    def delete_artifacts(self, artifact_path: Incomplete | None = None) -> None: ...
