import abc
from ..lib.mailbox import Mailbox as Mailbox, MailboxHandle as MailboxHandle
from .interface import InterfaceBase as InterfaceBase
from .message_future import MessageFuture as MessageFuture
from .router import MessageRouter as MessageRouter
from _typeshed import Incomplete
from multiprocessing.process import BaseProcess
from typing import Any
from wandb.proto import wandb_internal_pb2 as pb
from wandb.util import json_dumps_safer as json_dumps_safer, json_friendly as json_friendly

logger: Incomplete

class InterfaceShared(InterfaceBase, metaclass=abc.ABCMeta):
    process: BaseProcess | None
    def __init__(self, process: BaseProcess | None = None, process_check: bool = True, mailbox: Any | None = None) -> None: ...
    @property
    def transport_failed(self) -> bool: ...
    @property
    def transport_success_timestamp(self) -> float: ...
    def communicate_login(self, api_key: str | None = None, timeout: int | None = 15) -> pb.LoginResponse: ...
    def publish_defer(self, state: int = 0) -> None: ...
    def publish_footer(self) -> None: ...
    def publish_final(self) -> None: ...
    def publish_login(self, api_key: str | None = None) -> None: ...
    def publish_stats(self, stats_dict: dict) -> None: ...
    def join(self) -> None: ...
