from _typeshed import Incomplete

sig_types: Incomplete

def get_type(info, arg): ...
def make_signature(filename): ...
def get_sig_name(line): ...
def sigs_from_dir(directory, outfile, manual_wrappers: Incomplete | None = None, exclusions: Incomplete | None = None) -> None: ...

lapack_manual_wrappers: str
blas_exclusions: Incomplete
lapack_exclusions: Incomplete
