import abc
import enum
from _typeshed import Incomplete
from torch import Tensor as Tensor, nn as nn
from torch._jit_internal import Future as Future
from torch.distributed.nn import RemoteModule as RemoteModule
from torch.testing._internal.common_distributed import skip_if_lt_x_gpu as skip_if_lt_x_gpu
from torch.testing._internal.common_utils import TemporaryFileName as TemporaryFileName
from torch.testing._internal.distributed.rpc.rpc_agent_test_fixture import RpcAgentTestFixture as RpcAgentTestFixture
from typing import Tuple

def remote_device(module_rref): ...
def remote_module_attributes(remote_module): ...
def remote_forward(remote_module, args): ...
def remote_forward_async(remote_module, args): ...
def get_remote_training_arg(module_rref): ...

class ModuleCreationMode(enum.Enum):
    MODULE_CTOR_WITH_INTERFACE: str
    MODULE_CTOR: str

class MyModuleInterface:
    def forward(self, tensor: Tensor, number: int, word: str = 'default') -> Tuple[str, int, Tensor]: ...

class RemoteMyModuleInterface:
    def forward(self, tensor: Tensor, number: int, word: str = 'default') -> Tuple[str, int, Tensor]: ...
    def forward_async(self, tensor: Tensor, number: int, word: str = 'default') -> Future[Tuple[str, int, Tensor]]: ...

class MyModule(nn.Module):
    param1: Incomplete
    def __init__(self, first_arg, first_kwarg: int = -1) -> None: ...
    def forward(self, tensor: Tensor, number: int, word: str = 'default') -> Tuple[str, int, Tensor]: ...

class BadModule:
    def __init__(self, first_arg, first_kwarg: int = -1) -> None: ...

def create_scripted_module(first_arg, first_kwarg: int = -1): ...

class CommonRemoteModuleTest(RpcAgentTestFixture, metaclass=abc.ABCMeta):
    @property
    def world_size(self): ...

class RemoteModuleTest(CommonRemoteModuleTest, metaclass=abc.ABCMeta):
    def test_bad_module(self) -> None: ...
    def test_forward_async(self) -> None: ...
    def test_forward_async_script(self): ...
    def test_forward_sync(self) -> None: ...
    def test_forward_sync_script(self): ...
    def test_forward_with_kwargs(self) -> None: ...
    def test_remote_parameters(self) -> None: ...
    def test_get_module_rref(self) -> None: ...
    def test_train_eval(self) -> None: ...
    def test_unsupported_methods(self) -> None: ...
    def test_send_remote_module_with_a_new_attribute_not_pickled_over_the_wire(self) -> None: ...
    def test_remote_module_py_pickle_not_supported(self) -> None: ...
    def test_remote_module_py_pickle_not_supported_script(self) -> None: ...

class ThreeWorkersRemoteModuleTest(CommonRemoteModuleTest, metaclass=abc.ABCMeta):
    @property
    def world_size(self): ...
    def test_send_remote_module_over_the_wire(self) -> None: ...
    def test_send_remote_module_over_the_wire_script_not_supported(self) -> None: ...
    def test_create_remote_module_from_module_rref(self) -> None: ...

class CudaRemoteModuleTest(CommonRemoteModuleTest, metaclass=abc.ABCMeta):
    def test_valid_device(self) -> None: ...
    def test_invalid_devices(self) -> None: ...
    def test_input_moved_to_cuda_device(self) -> None: ...
    def test_input_moved_to_cuda_device_script(self): ...
