from tensorflow.python.distribute.coordinator.cluster_coordinator import ClusterCoordinator as ClusterCoordinator
from tensorflow.python.distribute.coordinator.values import RemoteValue as RemoteValue
