from _typeshed import Incomplete
from horovod.spark.lightning import TorchModel
from pyspark.ml.param import TypeConverters as TypeConverters
from synapse.ml.dl.PredictionParams import VisionPredictionParams

class DeepVisionModel(TorchModel, VisionPredictionParams):
    transform_fn: Incomplete
    def __init__(self, history: Incomplete | None = None, model: Incomplete | None = None, input_shapes: Incomplete | None = None, optimizer: Incomplete | None = None, run_id: Incomplete | None = None, _metadata: Incomplete | None = None, loss: Incomplete | None = None, loss_constructors: Incomplete | None = None, transform_fn: Incomplete | None = None, label_col: str = 'label', image_col: str = 'image', prediction_col: str = 'prediction') -> None: ...
    def setTransformFn(self, value): ...
    def getTransformFn(self): ...
    def setTransformationFn(self, value): ...
    def getTransformationFn(self): ...
    def get_prediction_fn(self): ...
    def getOptimizer(self) -> None: ...
