import pytorch_lightning as pl
from _typeshed import Incomplete

class LitDeepVisionModel(pl.LightningModule):
    backbone: Incomplete
    additional_layers_to_train: Incomplete
    num_classes: Incomplete
    input_shape: Incomplete
    optimizer_name: Incomplete
    loss_name: Incomplete
    label_col: Incomplete
    image_col: Incomplete
    dropout_aux: Incomplete
    def __init__(self, backbone, additional_layers_to_train, num_classes, input_shape, optimizer_name, loss_name, label_col, image_col, dropout_aux: float = 0.7) -> None: ...
    def forward(self, x): ...
    def configure_optimizers(self): ...
    def training_step(self, batch, batch_idx): ...
    def validation_step(self, batch, batch_idx) -> None: ...
    def validation_epoch_end(self, outputs) -> None: ...
    def test_step(self, batch, batch_idx): ...
