from .core import CatBoost as CatBoost, CatBoostError as CatBoostError
from _typeshed import Incomplete

FeatureExplanation: Incomplete

def to_polynom(model): ...
def to_polynom_string(model): ...
def explain_features(model): ...
def calc_features_strength(model): ...
def plot_pdp(arg, size_per_plot=(5, 5), plots_per_row: Incomplete | None = None): ...
def plot_features_strength(model, height_per_feature: float = 0.5, width_per_plot: int = 5, plots_per_row: Incomplete | None = None): ...
