from torchgen.model import BackendIndex as BackendIndex, DispatchKey as DispatchKey, NativeFunction as NativeFunction, NativeFunctionsGroup as NativeFunctionsGroup, NativeFunctionsViewGroup as NativeFunctionsViewGroup
from torchgen.utils import S as S, T as T, context as context
from typing import Callable, Dict, Iterator, TypeVar

F = TypeVar('F', NativeFunction, NativeFunctionsGroup, NativeFunctionsViewGroup, NativeFunction | NativeFunctionsGroup, NativeFunction | NativeFunctionsViewGroup)
F2 = TypeVar('F2', NativeFunction, NativeFunctionsGroup, NativeFunction | None, bool, str)

def native_function_manager(g: NativeFunctionsGroup | NativeFunctionsViewGroup | NativeFunction) -> Iterator[None]: ...
def with_native_function(func: Callable[[F], T]) -> Callable[[F], T]: ...
def with_native_function_and(func: Callable[[F, F2], T]) -> Callable[[F, F2], T]: ...
def method_with_native_function(func: Callable[[S, F], T]) -> Callable[[S, F], T]: ...
def with_native_function_and_index(func: Callable[[F, BackendIndex], T]) -> Callable[[F, BackendIndex], T]: ...
def with_native_function_and_indices(func: Callable[[F, Dict[DispatchKey, BackendIndex]], T]) -> Callable[[F, Dict[DispatchKey, BackendIndex]], T]: ...
