from typing import ContextManager, Generator

class CommandContextMixIn:
    def __init__(self) -> None: ...
    def main_context(self) -> Generator[None, None, None]: ...
    def enter_context(self, context_provider: ContextManager[_T]) -> _T: ...
