from _typeshed import Incomplete
from pip._internal.utils.compat import WINDOWS as WINDOWS
from pip._internal.utils.logging import get_indentation as get_indentation
from typing import Generator, IO

logger: Incomplete

class SpinnerInterface:
    def spin(self) -> None: ...
    def finish(self, final_status: str) -> None: ...

class InteractiveSpinner(SpinnerInterface):
    def __init__(self, message: str, file: IO[str] | None = None, spin_chars: str = '-\\|/', min_update_interval_seconds: float = 0.125) -> None: ...
    def spin(self) -> None: ...
    def finish(self, final_status: str) -> None: ...

class NonInteractiveSpinner(SpinnerInterface):
    def __init__(self, message: str, min_update_interval_seconds: float = 60.0) -> None: ...
    def spin(self) -> None: ...
    def finish(self, final_status: str) -> None: ...

class RateLimiter:
    def __init__(self, min_update_interval_seconds: float) -> None: ...
    def ready(self) -> bool: ...
    def reset(self) -> None: ...

def open_spinner(message: str) -> Generator[SpinnerInterface, None, None]: ...

HIDE_CURSOR: str
SHOW_CURSOR: str

def hidden_cursor(file: IO[str]) -> Generator[None, None, None]: ...
