from . import log as log
from .adal_error import AdalError as AdalError
from .constants import Misc as Misc, TokenResponseFields as TokenResponseFields

class CacheDriver:
    def __init__(self, call_context, authority, resource, client_id, cache, refresh_function) -> None: ...
    def find(self, query): ...
    def remove(self, entry) -> None: ...
    def add(self, entry) -> None: ...
