from . import log as log, util as util
from .adal_error import AdalError as AdalError
from .constants import IdTokenFields as IdTokenFields, OAuth2 as OAuth2, TokenResponseFields as TokenResponseFields
from _typeshed import Incomplete

TOKEN_RESPONSE_MAP: Incomplete

def map_fields(in_obj, map_to): ...

class OAuth2Client:
    def __init__(self, call_context, authority) -> None: ...
    def get_token(self, oauth_parameters): ...
    def get_user_code_info(self, oauth_parameters): ...
    def get_token_with_polling(self, oauth_parameters, refresh_internal, expires_in): ...
    def cancel_polling_request(self) -> None: ...
