from .constants import AdalIdParameters as AdalIdParameters

def is_http_success(status_code): ...
def add_default_request_headers(self, options) -> None: ...
def create_request_options(self, *options): ...
def log_return_correlation_id(log, operation_message, response) -> None: ...
def copy_url(url_source): ...
def base64_urlsafe_decode(b64string): ...
