from _typeshed import Incomplete

HEX_COLOR_RE: Incomplete
HTML4: str
CSS2: str
CSS21: str
CSS3: str
SUPPORTED_SPECIFICATIONS: Incomplete
SPECIFICATION_ERROR_TEMPLATE: Incomplete
HTML4_NAMES_TO_HEX: Incomplete
CSS2_NAMES_TO_HEX = HTML4_NAMES_TO_HEX
CSS21_NAMES_TO_HEX: Incomplete
CSS3_NAMES_TO_HEX: Incomplete
HTML4_HEX_TO_NAMES: Incomplete
CSS2_HEX_TO_NAMES = HTML4_HEX_TO_NAMES
CSS21_HEX_TO_NAMES: Incomplete
CSS3_HEX_TO_NAMES: Incomplete
