from _typeshed import Incomplete
from transformers import PegasusConfig as PegasusConfig, PegasusForConditionalGeneration as PegasusForConditionalGeneration, PegasusTokenizer as PegasusTokenizer
from transformers.models.pegasus.configuration_pegasus import DEFAULTS as DEFAULTS, task_specific_params as task_specific_params
from typing import Dict

PATTERNS: Incomplete

def rename_state_dict_key(k): ...
def convert_pegasus(tf_weights: dict, cfg_updates: dict) -> PegasusForConditionalGeneration: ...
def get_tf_weights_as_numpy(path: str = './ckpt/aeslc/model.ckpt-32000') -> Dict: ...
def convert_pegasus_ckpt_to_pytorch(ckpt_path: str, save_dir: str): ...
