import dataclasses
import sympy
import torch
from _typeshed import Incomplete

log: Incomplete

@dataclasses.dataclass(frozen=True)
class ValueRanges:
    lower: sympy.Expr | sympy.Number | int | float | bool
    upper: sympy.Expr | sympy.Number | int | float | bool
    def __contains__(self, x) -> bool: ...
    @classmethod
    def wrap(cls, arg): ...
    @classmethod
    def increasing_map(cls, x, fn):
        """map lower and upper bound with fn"""
    @classmethod
    def decreasing_map(cls, x, fn):
        """map lower bound to upper bound and upper bound to lower bound"""
    @classmethod
    def monotone_map(cls, x, fn):
        """check the max and min of computed upper and lower bound for the output"""
    @classmethod
    def convex_min_zero_map(cls, x, fn):
        """the max is at one of the ends"""
    @classmethod
    def coordinatewise_increasing_map(cls, x, y, fn):
        """map upper and lower bounds accessing corresponding values of inputs"""
    @classmethod
    def coordinatewise_monotone_map(cls, x, y, fn):
        """compute the product of all lower and upper bounds and take min and max"""
    def __init__(self, lower, upper) -> None: ...

class ValueRangeAnalysis:
    name: str
    def __init__(self) -> None: ...
    @staticmethod
    def bool_handler(*args, **kwargs): ...
    @staticmethod
    def default_handler(*args, **kwargs): ...
    def load(self, name: str, index: sympy.Expr): ...
    def store(self, name, index, value, mode: Incomplete | None = None) -> None: ...
    def reduction(self, name, dtype, src_dtype, reduction_type, index, value): ...
    def index_expr(self, index, dtype): ...
    @staticmethod
    def to_dtype(x, dtype: torch.dtype): ...
    @staticmethod
    def constant(value, dtype): ...
    @staticmethod
    def reciprocal(x): ...
    @staticmethod
    def square(x): ...
    @staticmethod
    def abs(x): ...
    @staticmethod
    def neg(x): ...
    @staticmethod
    def truediv(a, b): ...
    @staticmethod
    def div(a, b): ...
    @staticmethod
    def add(a, b): ...
    @staticmethod
    def mul(a, b): ...
    @staticmethod
    def sub(a, b): ...
    @staticmethod
    def exp(x): ...
    @staticmethod
    def log(x): ...
    @staticmethod
    def sqrt(x): ...
    @staticmethod
    def pow(a, b): ...
    @staticmethod
    def minimum(a, b): ...
    @staticmethod
    def maximum(a, b): ...
    @staticmethod
    def where(a, b, c): ...
    @staticmethod
    def floor(x): ...
    @staticmethod
    def ceil(x): ...
    @staticmethod
    def floor_ceil(x, fn_int): ...
    def __getattr__(self, name): ...
