from _typeshed import Incomplete
from torch.testing._internal.distributed.rpc.rpc_agent_test_fixture import RpcAgentTestFixture as RpcAgentTestFixture

retryable_message_types: Incomplete
default_messages_to_delay: Incomplete

class FaultyRpcAgentTestFixture(RpcAgentTestFixture):
    messages_to_fail: Incomplete
    messages_to_delay: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def rpc_backend(self): ...
    @property
    def rpc_backend_options(self): ...
    def setup_fault_injection(self, faulty_messages, messages_to_delay) -> None: ...
    def get_shutdown_error_regex(self): ...
    def get_timeout_error_regex(self): ...
