from torch.testing._internal.common_distributed import tp_transports as tp_transports
from torch.testing._internal.distributed.rpc.rpc_agent_test_fixture import RpcAgentTestFixture as RpcAgentTestFixture

class TensorPipeRpcAgentTestFixture(RpcAgentTestFixture):
    @property
    def rpc_backend(self): ...
    @property
    def rpc_backend_options(self): ...
    def get_shutdown_error_regex(self): ...
    def get_timeout_error_regex(self): ...
