import wandb
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Protocol, Tuple
from wandb.apis.reports import Report as Report
from wandb.proto import wandb_settings_pb2 as wandb_settings_pb2
from wandb.sdk.interface.interface import file_policy_to_enum as file_policy_to_enum
from wandb.sdk.interface.interface_queue import InterfaceQueue as InterfaceQueue
from wandb.sdk.internal import context as context
from wandb.sdk.internal.sender import SendManager as SendManager
from wandb.sdk.internal.settings_static import SettingsStatic as SettingsStatic
from wandb.util import cast_dictlike_to_dict as cast_dictlike_to_dict, coalesce as coalesce

class ImporterRun(Protocol):
    def run_id(self) -> str: ...
    def entity(self) -> str: ...
    def project(self) -> str: ...
    def config(self) -> Dict[str, Any]: ...
    def summary(self) -> Dict[str, float]: ...
    def metrics(self) -> Iterable[Dict[str, float]]:
        """Metrics for the run.

        We expect metrics in this shape:

        [
            {'metric1': 1, 'metric2': 1, '_step': 0},
            {'metric1': 2, 'metric2': 4, '_step': 1},
            {'metric1': 3, 'metric2': 9, '_step': 2},
            ...
        ]

        You can also submit metrics in this shape:
        [
            {'metric1': 1, '_step': 0},
            {'metric2': 1, '_step': 0},
            {'metric1': 2, '_step': 1},
            {'metric2': 4, '_step': 1},
            ...
        ]
        """
    def run_group(self) -> str | None: ...
    def job_type(self) -> str | None: ...
    def display_name(self) -> str: ...
    def notes(self) -> str | None: ...
    def tags(self) -> List[str] | None: ...
    def artifacts(self) -> Iterable[wandb.Artifact] | None: ...
    def used_artifacts(self) -> Iterable[wandb.Artifact] | None: ...
    def os_version(self) -> str | None: ...
    def python_version(self) -> str | None: ...
    def cuda_version(self) -> str | None: ...
    def program(self) -> str | None: ...
    def host(self) -> str | None: ...
    def username(self) -> str | None: ...
    def executable(self) -> str | None: ...
    def gpus_used(self) -> str | None: ...
    def cpus_used(self) -> int | None: ...
    def memory_used(self) -> int | None: ...
    def runtime(self) -> int | None: ...
    def start_time(self) -> int | None: ...
    def code_path(self) -> str | None: ...
    def cli_version(self) -> str | None: ...
    def files(self) -> Iterable[Tuple[str, str]] | None: ...
    def logs(self) -> Iterable[str] | None: ...

class Importer(Protocol):
    def collect_runs(self, *args, **kwargs) -> Iterable[ImporterRun]: ...
    def collect_reports(self, *args, **kwargs) -> Iterable[Report]: ...
    def import_run(self, run: ImporterRun) -> None: ...
    def import_report(self, report: Report) -> None: ...

@dataclass
class RecordMaker:
    run: ImporterRun
    interface: InterfaceQueue = ...
    @property
    def run_dir(self) -> str: ...
    def __init__(self, run, interface) -> None: ...

def send_run_with_send_manager(run: ImporterRun, overrides: Dict[str, Any] | None = None, settings_override: SettingsStatic | None = None) -> None: ...
