from collections import OrderedDict
from typing import Any

class CaseFoldedOrderedDict(OrderedDict):
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def get(self, key: str, default: Any | None = None) -> Any: ...
    def pop(self, key: str, default: Any | None = None) -> Any: ...

def parse(value: str) -> CaseFoldedOrderedDict: ...
