from ..ddl.impl import DefaultImpl as DefaultImpl
from ..util import exc as exc
from ..util.sqla_compat import constraint_name_defined as constraint_name_defined, constraint_name_string as constraint_name_string
from _typeshed import Incomplete
from sqlalchemy import Column, Index, Table
from sqlalchemy.engine import Dialect as Dialect
from sqlalchemy.sql.elements import ColumnClause as ColumnClause, quoted_name as quoted_name
from sqlalchemy.sql.functions import Function as Function
from sqlalchemy.sql.schema import Constraint as Constraint
from sqlalchemy.sql.type_api import TypeEngine as TypeEngine
from typing import Any, Dict, Literal

class BatchOperationsImpl:
    operations: Incomplete
    table_name: Incomplete
    schema: Incomplete
    recreate: Incomplete
    copy_from: Incomplete
    table_args: Incomplete
    table_kwargs: Incomplete
    reflect_args: Incomplete
    reflect_kwargs: Incomplete
    naming_convention: Incomplete
    partial_reordering: Incomplete
    batch: Incomplete
    def __init__(self, operations, table_name, schema, recreate, copy_from, table_args, table_kwargs, reflect_args, reflect_kwargs, naming_convention, partial_reordering) -> None: ...
    @property
    def dialect(self) -> Dialect: ...
    @property
    def impl(self) -> DefaultImpl: ...
    def flush(self) -> None: ...
    def alter_column(self, *arg, **kw) -> None: ...
    def add_column(self, *arg, **kw) -> None: ...
    def drop_column(self, *arg, **kw) -> None: ...
    def add_constraint(self, const: Constraint) -> None: ...
    def drop_constraint(self, const: Constraint) -> None: ...
    def rename_table(self, *arg, **kw) -> None: ...
    def create_index(self, idx: Index, **kw: Any) -> None: ...
    def drop_index(self, idx: Index, **kw: Any) -> None: ...
    def create_table_comment(self, table) -> None: ...
    def drop_table_comment(self, table) -> None: ...
    def create_table(self, table) -> None: ...
    def drop_table(self, table) -> None: ...
    def create_column_comment(self, column) -> None: ...

class ApplyBatchImpl:
    impl: Incomplete
    table: Incomplete
    table_args: Incomplete
    table_kwargs: Incomplete
    temp_table_name: Incomplete
    new_table: Incomplete
    partial_reordering: Incomplete
    add_col_ordering: Incomplete
    column_transfers: Incomplete
    existing_ordering: Incomplete
    reflected: Incomplete
    def __init__(self, impl: DefaultImpl, table: Table, table_args: tuple, table_kwargs: Dict[str, Any], reflected: bool, partial_reordering: tuple = ()) -> None: ...
    def alter_column(self, table_name: str, column_name: str, nullable: bool | None = None, server_default: Function[Any] | str | bool | None = False, name: str | None = None, type_: TypeEngine | None = None, autoincrement: bool | Literal['auto'] | None = None, comment: str | Literal[False] = False, **kw) -> None: ...
    def add_column(self, table_name: str, column: Column[Any], insert_before: str | None = None, insert_after: str | None = None, **kw) -> None: ...
    def drop_column(self, table_name: str, column: ColumnClause[Any] | Column[Any], **kw) -> None: ...
    def create_column_comment(self, column) -> None:
        '''the batch table creation function will issue create_column_comment
        on the real "impl" as part of the create table process.

        That is, the Column object will have the comment on it already,
        so when it is received by add_column() it will be a normal part of
        the CREATE TABLE and doesn\'t need an extra step here.

        '''
    def create_table_comment(self, table) -> None:
        '''the batch table creation function will issue create_table_comment
        on the real "impl" as part of the create table process.

        '''
    def drop_table_comment(self, table) -> None:
        '''the batch table creation function will issue drop_table_comment
        on the real "impl" as part of the create table process.

        '''
    def add_constraint(self, const: Constraint) -> None: ...
    def drop_constraint(self, const: Constraint) -> None: ...
    def create_index(self, idx: Index) -> None: ...
    def drop_index(self, idx: Index) -> None: ...
    def rename_table(self, *arg, **kw) -> None: ...
