from .. import util as util
from ..runtime.migration import MigrationContext as MigrationContext
from ..util import sqla_compat as sqla_compat
from _typeshed import Incomplete
from sqlalchemy.sql.elements import ColumnElement as ColumnElement, TextClause as TextClause
from sqlalchemy.sql.schema import CheckConstraint as CheckConstraint, Column, ForeignKey as ForeignKey, ForeignKeyConstraint as ForeignKeyConstraint, Index, MetaData as MetaData, PrimaryKeyConstraint as PrimaryKeyConstraint, Table as Table, UniqueConstraint as UniqueConstraint
from sqlalchemy.sql.type_api import TypeEngine as TypeEngine
from typing import Any, List, Sequence

class SchemaObjects:
    migration_context: Incomplete
    def __init__(self, migration_context: MigrationContext | None = None) -> None: ...
    def primary_key_constraint(self, name: sqla_compat._ConstraintNameDefined | None, table_name: str, cols: Sequence[str], schema: str | None = None, **dialect_kw) -> PrimaryKeyConstraint: ...
    def foreign_key_constraint(self, name: sqla_compat._ConstraintNameDefined | None, source: str, referent: str, local_cols: List[str], remote_cols: List[str], onupdate: str | None = None, ondelete: str | None = None, deferrable: bool | None = None, source_schema: str | None = None, referent_schema: str | None = None, initially: str | None = None, match: str | None = None, **dialect_kw) -> ForeignKeyConstraint: ...
    def unique_constraint(self, name: sqla_compat._ConstraintNameDefined | None, source: str, local_cols: Sequence[str], schema: str | None = None, **kw) -> UniqueConstraint: ...
    def check_constraint(self, name: sqla_compat._ConstraintNameDefined | None, source: str, condition: str | TextClause | ColumnElement[Any], schema: str | None = None, **kw) -> CheckConstraint: ...
    def generic_constraint(self, name: sqla_compat._ConstraintNameDefined | None, table_name: str, type_: str | None, schema: str | None = None, **kw) -> Any: ...
    def metadata(self) -> MetaData: ...
    def table(self, name: str, *columns, **kw) -> Table: ...
    def column(self, name: str, type_: TypeEngine, **kw) -> Column: ...
    def index(self, name: str | None, tablename: str | None, columns: Sequence[str | TextClause | ColumnElement[Any]], schema: str | None = None, **kw) -> Index: ...
