from . import ops as ops
from ..util.sqla_compat import sqla_2 as sqla_2
from .base import Operations as Operations
from sqlalchemy.sql.schema import Table as Table

def alter_column(operations: Operations, operation: ops.AlterColumnOp) -> None: ...
def drop_table(operations: Operations, operation: ops.DropTableOp) -> None: ...
def drop_column(operations: Operations, operation: ops.DropColumnOp) -> None: ...
def create_index(operations: Operations, operation: ops.CreateIndexOp) -> None: ...
def drop_index(operations: Operations, operation: ops.DropIndexOp) -> None: ...
def create_table(operations: Operations, operation: ops.CreateTableOp) -> Table: ...
def rename_table(operations: Operations, operation: ops.RenameTableOp) -> None: ...
def create_table_comment(operations: Operations, operation: ops.CreateTableCommentOp) -> None: ...
def drop_table_comment(operations: Operations, operation: ops.DropTableCommentOp) -> None: ...
def add_column(operations: Operations, operation: ops.AddColumnOp) -> None: ...
def create_constraint(operations: Operations, operation: ops.AddConstraintOp) -> None: ...
def drop_constraint(operations: Operations, operation: ops.DropConstraintOp) -> None: ...
def bulk_insert(operations: Operations, operation: ops.BulkInsertOp) -> None: ...
def execute_sql(operations: Operations, operation: ops.ExecuteSQLOp) -> None: ...
