from _typeshed import Incomplete
from typing import Callable

REGEX_SEPARATORS: Incomplete
REGEX_NON_ASCII: Incomplete

def encode(uni: str) -> str: ...
def decode(ascii: str) -> str: ...
def map_domain(string: str, fn: Callable[[str], str]) -> str: ...
def to_unicode(obj: str) -> str: ...
def to_ascii(obj: str) -> str: ...
