import sentry_sdk
from _typeshed import Incomplete
from sentry_sdk._compat import iteritems as iteritems, text_type as text_type
from sentry_sdk._types import TYPE_CHECKING as TYPE_CHECKING
from sentry_sdk.hub import Hub as Hub
from sentry_sdk.utils import AnnotatedValue as AnnotatedValue
from typing import Any, Dict

SENSITIVE_ENV_KEYS: Incomplete
SENSITIVE_HEADERS: Incomplete

def request_body_within_bounds(client: sentry_sdk.Client | None, content_length: int) -> bool: ...

class RequestExtractor:
    request: Incomplete
    def __init__(self, request: Any) -> None: ...
    def extract_into_event(self, event: Dict[str, Any]) -> None: ...
    def content_length(self) -> int: ...
    def cookies(self) -> Dict[str, Any]: ...
    def raw_data(self) -> str | bytes | None: ...
    def form(self) -> Dict[str, Any] | None: ...
    def parsed_body(self) -> Dict[str, Any] | None: ...
    def is_json(self) -> bool: ...
    def json(self) -> Any | None: ...
    def files(self) -> Dict[str, Any] | None: ...
    def size_of_file(self, file: Any) -> int: ...
    def env(self) -> Dict[str, Any]: ...
