from sentry_sdk._compat import iteritems as iteritems
from sentry_sdk._types import EventProcessor as EventProcessor, TYPE_CHECKING as TYPE_CHECKING
from sentry_sdk.api import continue_trace as continue_trace
from sentry_sdk.consts import OP as OP
from sentry_sdk.hub import Hub as Hub
from sentry_sdk.integrations import DidNotEnable as DidNotEnable, Integration as Integration
from sentry_sdk.integrations._wsgi_common import RequestExtractor as RequestExtractor
from sentry_sdk.integrations.logging import ignore_logger as ignore_logger
from sentry_sdk.tracing import TRANSACTION_SOURCE_COMPONENT as TRANSACTION_SOURCE_COMPONENT, TRANSACTION_SOURCE_ROUTE as TRANSACTION_SOURCE_ROUTE
from sentry_sdk.utils import CONTEXTVARS_ERROR_MESSAGE as CONTEXTVARS_ERROR_MESSAGE, HAS_REAL_CONTEXTVARS as HAS_REAL_CONTEXTVARS, capture_internal_exceptions as capture_internal_exceptions, event_from_exception as event_from_exception, transaction_from_function as transaction_from_function
from typing import Any, Dict

class TornadoIntegration(Integration):
    identifier: str
    @staticmethod
    def setup_once() -> None: ...

class TornadoRequestExtractor(RequestExtractor):
    def content_length(self) -> int: ...
    def cookies(self) -> Dict[str, str]: ...
    def raw_data(self) -> bytes: ...
    def form(self) -> Dict[str, Any]: ...
    def is_json(self) -> bool: ...
    def files(self) -> Dict[str, Any]: ...
    def size_of_file(self, file: Any) -> int: ...
