from absl.flags import *
from _typeshed import Incomplete

class _FlagValuesWrapper:
    """Wrapper class for absl.flags.FLAGS.

    The difference is that tf.compat.v1.flags.FLAGS implicitly parses
    flags with sys.argv when accessing the FLAGS values before it's
    explicitly parsed, while absl.flags.FLAGS raises an exception.
    """
    def __init__(self, flags_object) -> None: ...
    def __getattribute__(self, name): ...
    def __getattr__(self, name): ...
    def __setattr__(self, name, value): ...
    def __delattr__(self, name): ...
    def __dir__(self): ...
    def __getitem__(self, name): ...
    def __setitem__(self, name, flag) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __call__(self, *args, **kwargs): ...

DEFINE_string: Incomplete
DEFINE_boolean: Incomplete
DEFINE_bool = DEFINE_boolean
DEFINE_float: Incomplete
DEFINE_integer: Incomplete
FLAGS: Incomplete
