from _typeshed import Incomplete
from databricks_cli.sdk import InstancePoolService as InstancePoolService

class InstancePoolsApi:
    client: Incomplete
    def __init__(self, api_client) -> None: ...
    def create_instance_pool(self, json): ...
    def edit_instance_pool(self, json): ...
    def delete_instance_pool(self, instance_pool_id): ...
    def get_instance_pool(self, instance_pool_id): ...
    def list_instance_pools(self): ...
