def temp_result(client): ...
def test_basic(temp_result) -> None: ...
def test_results_iterator(temp_result) -> None:
    """
    A Result.results should be an iterator.
    """
def test_result_details(temp_result) -> None: ...
def test_properties(temp_result) -> None:
    """
    A result should have a number of properties.
    """
def test_pod_attributes(temp_result) -> None: ...
def test_invalid_app_id() -> None: ...
def test_unsuccessful(client) -> None:
    """
    A result for an unsuccessful query should be False and
    have empty info.
    """
def test_from_env(monkeypatch) -> None: ...

class TestDocument:
    def test_missing_attr(self) -> None: ...

class TestAssumption:
    def test_text(self) -> None: ...
