from .base import Candidate as Candidate, Requirement as Requirement
from _typeshed import Incomplete
from pip._vendor.resolvelib.reporters import BaseReporter as BaseReporter
from typing import Any

logger: Incomplete

class PipReporter(BaseReporter):
    reject_count_by_package: Incomplete
    def __init__(self) -> None: ...
    def rejecting_candidate(self, criterion: Any, candidate: Candidate) -> None: ...

class PipDebuggingReporter(BaseReporter):
    """A reporter that does an info log for every event it sees."""
    def starting(self) -> None: ...
    def starting_round(self, index: int) -> None: ...
    def ending_round(self, index: int, state: Any) -> None: ...
    def ending(self, state: Any) -> None: ...
    def adding_requirement(self, requirement: Requirement, parent: Candidate) -> None: ...
    def rejecting_candidate(self, criterion: Any, candidate: Candidate) -> None: ...
    def pinning(self, candidate: Candidate) -> None: ...
