from .base import Candidate as Candidate, CandidateLookup as CandidateLookup, Requirement as Requirement, format_name as format_name
from _typeshed import Incomplete
from pip._internal.req.constructors import install_req_drop_extras as install_req_drop_extras
from pip._internal.req.req_install import InstallRequirement as InstallRequirement
from pip._vendor.packaging.specifiers import SpecifierSet as SpecifierSet
from pip._vendor.packaging.utils import NormalizedName as NormalizedName, canonicalize_name as canonicalize_name

class ExplicitRequirement(Requirement):
    candidate: Incomplete
    def __init__(self, candidate: Candidate) -> None: ...
    @property
    def project_name(self) -> NormalizedName: ...
    @property
    def name(self) -> str: ...
    def format_for_error(self) -> str: ...
    def get_candidate_lookup(self) -> CandidateLookup: ...
    def is_satisfied_by(self, candidate: Candidate) -> bool: ...

class SpecifierRequirement(Requirement):
    def __init__(self, ireq: InstallRequirement) -> None: ...
    @property
    def project_name(self) -> NormalizedName: ...
    @property
    def name(self) -> str: ...
    def format_for_error(self) -> str: ...
    def get_candidate_lookup(self) -> CandidateLookup: ...
    def is_satisfied_by(self, candidate: Candidate) -> bool: ...

class SpecifierWithoutExtrasRequirement(SpecifierRequirement):
    """
    Requirement backed by an install requirement on a base package.
    Trims extras from its install requirement if there are any.
    """
    def __init__(self, ireq: InstallRequirement) -> None: ...

class RequiresPythonRequirement(Requirement):
    """A requirement representing Requires-Python metadata."""
    specifier: Incomplete
    def __init__(self, specifier: SpecifierSet, match: Candidate) -> None: ...
    @property
    def project_name(self) -> NormalizedName: ...
    @property
    def name(self) -> str: ...
    def format_for_error(self) -> str: ...
    def get_candidate_lookup(self) -> CandidateLookup: ...
    def is_satisfied_by(self, candidate: Candidate) -> bool: ...

class UnsatisfiableRequirement(Requirement):
    """A requirement that cannot be satisfied."""
    def __init__(self, name: NormalizedName) -> None: ...
    @property
    def project_name(self) -> NormalizedName: ...
    @property
    def name(self) -> str: ...
    def format_for_error(self) -> str: ...
    def get_candidate_lookup(self) -> CandidateLookup: ...
    def is_satisfied_by(self, candidate: Candidate) -> bool: ...
