from Cython.TestUtils import CythonTest as CythonTest

class TestCodeWriter(CythonTest):
    def t(self, codestr) -> None: ...
    def test_print(self) -> None: ...
    def test_if(self) -> None: ...
    def test_ifelifelse(self) -> None: ...
    def test_def(self) -> None: ...
    def test_cdef(self) -> None: ...
    def test_longness_and_signedness(self) -> None: ...
    def test_signed_short(self) -> None: ...
    def test_typed_args(self) -> None: ...
    def test_cdef_var(self) -> None: ...
    def test_for_loop(self) -> None: ...
    def test_while_loop(self) -> None: ...
    def test_inplace_assignment(self) -> None: ...
    def test_cascaded_assignment(self) -> None: ...
    def test_attribute(self) -> None: ...
    def test_return_none(self) -> None: ...
