import unittest
from ..TestUtils import write_file as write_file, write_newer_file as write_newer_file
from _typeshed import Incomplete

class TestTestUtils(unittest.TestCase):
    temp_dir: Incomplete
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_write_file_text(self) -> None: ...
    def test_write_file_dedent(self) -> None: ...
    def test_write_file_bytes(self) -> None: ...
    def test_write_newer_file(self) -> None: ...
    def test_write_newer_file_same(self) -> None: ...
    def test_write_newer_file_fresh(self) -> None: ...
    def test_parse_pattern(self) -> None: ...
