from Cython.Compiler import Main as Main, Options as Options, Symtab as Symtab, Visitor as Visitor
from Cython.Compiler.ParseTreeTransforms import InterpretCompilerDirectives as InterpretCompilerDirectives, NormalizeTree as NormalizeTree
from Cython.TestUtils import TransformTest as TransformTest
from _typeshed import Incomplete

TOOLS_DIR: Incomplete

class DeclarationsFinder(Visitor.VisitorTransform):
    directives: Incomplete
    visit_Node: Incomplete
    def visit_CompilerDirectivesNode(self, node): ...

class TestJediTyper(TransformTest):
    def test_typing_global_int_loop(self) -> None: ...
    def test_typing_function_int_loop(self) -> None: ...
    def test_conflicting_types_in_function(self) -> None: ...
    def test_typing_global_list(self) -> None: ...
    def test_typing_function_list(self) -> None: ...
    def test_typing_global_dict(self) -> None: ...
    def test_typing_function_dict(self) -> None: ...
    def test_typing_global_set(self) -> None: ...
    def test_typing_function_set(self) -> None: ...

class TestTypeInjection(TestJediTyper):
    """
    Subtype of TestJediTyper that additionally tests type injection and compilation.
    """
    declarations_finder: Incomplete
    pipeline: Incomplete
    def setUp(self) -> None: ...
