import pathlib
from _typeshed import Incomplete
from typing import Sequence

def is_windows() -> bool: ...
def copy_file(src_files: str | Sequence[str], dst_dir: pathlib.Path, dst_filename: Incomplete | None = None, runfiles: Incomplete | None = None) -> None: ...
def platform_tag(cpu: str) -> str: ...
def build_wheel(sources_path: str, output_path: str, package_name: str) -> None:
    """Builds a wheel in `output_path` using the source tree in `sources_path`."""
def build_editable(sources_path: str, output_path: str, package_name: str) -> None: ...
