from . import Markup as Markup
from typing import Any

def escape(s: Any) -> Markup: ...
def escape_silent(s: Any | None) -> Markup: ...
def soft_str(s: Any) -> str: ...
def soft_unicode(s: Any) -> str: ...
