import grpc
from _typeshed import Incomplete
from grpc._typing import DoneCallbackType as DoneCallbackType
from typing import Dict, NamedTuple

class RpcMethodHandler(NamedTuple('_RpcMethodHandler', [('request_streaming', Incomplete), ('response_streaming', Incomplete), ('request_deserializer', Incomplete), ('response_serializer', Incomplete), ('unary_unary', Incomplete), ('unary_stream', Incomplete), ('stream_unary', Incomplete), ('stream_stream', Incomplete)]), grpc.RpcMethodHandler): ...

class DictionaryGenericHandler(grpc.ServiceRpcHandler):
    def __init__(self, service: str, method_handlers: Dict[str, grpc.RpcMethodHandler]) -> None: ...
    def service_name(self) -> str: ...
    def service(self, handler_call_details: grpc.HandlerCallDetails) -> grpc.RpcMethodHandler | None: ...

class _ChannelReadyFuture(grpc.Future):
    def __init__(self, channel: grpc.Channel) -> None: ...
    def cancel(self) -> bool: ...
    def cancelled(self) -> bool: ...
    def running(self) -> bool: ...
    def done(self) -> bool: ...
    def result(self, timeout: float | None = None) -> None: ...
    def exception(self, timeout: float | None = None) -> None: ...
    def traceback(self, timeout: float | None = None) -> None: ...
    def add_done_callback(self, fn: DoneCallbackType): ...
    def start(self) -> None: ...
    def __del__(self) -> None: ...

def channel_ready_future(channel: grpc.Channel) -> _ChannelReadyFuture: ...
