from _typeshed import Incomplete
from transformers import ReformerConfig as ReformerConfig, ReformerModelWithLMHead as ReformerModelWithLMHead
from transformers.utils import logging as logging

def set_param(torch_layer, weight, bias: Incomplete | None = None) -> None: ...
def set_layer_weights_in_torch_lsh(weights, torch_layer, hidden_size) -> None: ...
def set_layer_weights_in_torch_local(weights, torch_layer, hidden_size) -> None: ...
def set_block_weights_in_torch(weights, torch_block, hidden_size) -> None: ...
def set_model_weights_in_torch(weights, torch_model, hidden_size) -> None: ...
def convert_trax_checkpoint_to_pytorch(trax_model_pkl_path, config_file, pytorch_dump_path) -> None: ...
