from _typeshed import Incomplete

float_dict: Incomplete
integer_dict: Incomplete

def generate_feeds(sess, symbolic_dims: dict | None = None): ...
def run_model(model_path, num_iters: int = 1, debug: Incomplete | None = None, profile: Incomplete | None = None, symbolic_dims: Incomplete | None = None, feeds: Incomplete | None = None, override_initializers: bool = True): ...
def main(): ...
