from _typeshed import Incomplete
from transformers import AutoTokenizer as AutoTokenizer, CLIPImageProcessor as CLIPImageProcessor, GitConfig as GitConfig, GitForCausalLM as GitForCausalLM, GitProcessor as GitProcessor, GitVisionConfig as GitVisionConfig, VideoMAEImageProcessor as VideoMAEImageProcessor
from transformers.utils import logging as logging

logger: Incomplete

def get_git_config(model_name): ...
def create_rename_keys(config, prefix: str = ''): ...
def rename_key(dct, old, new) -> None: ...
def read_in_q_k_v(state_dict, config, prefix: str = '') -> None: ...
def prepare_img(model_name): ...
def prepare_video(): ...
def convert_git_checkpoint(model_name, pytorch_dump_folder_path, push_to_hub: bool = False) -> None:
    """
    Copy/paste/tweak model's weights to our GIT structure.
    """
