from _typeshed import Incomplete

class NoDeviceFoundError(Exception): ...

class U2FError(Exception):
    OK: int
    OTHER_ERROR: int
    BAD_REQUEST: int
    CONFIGURATION_UNSUPPORTED: int
    DEVICE_INELIGIBLE: int
    TIMEOUT: int
    code: Incomplete
    cause: Incomplete
    def __init__(self, code, cause: Incomplete | None = None) -> None: ...

class HidError(Exception):
    """Errors in the hid usb transport protocol."""
class InvalidPacketError(HidError): ...
class HardwareError(Exception):
    """Errors in the security key hardware that are transport independent."""
class InvalidRequestError(HardwareError): ...

class ApduError(HardwareError):
    sw1: Incomplete
    sw2: Incomplete
    def __init__(self, sw1, sw2) -> None: ...

class TUPRequiredError(HardwareError): ...
class InvalidKeyHandleError(HardwareError): ...
class UnsupportedVersionException(Exception): ...
class InvalidCommandError(Exception): ...
class InvalidResponseError(Exception): ...
class InvalidModelError(Exception): ...
class OsHidError(Exception): ...
class PluginError(Exception): ...
