import types
from _typeshed import Incomplete

class _XNNPACKEnabled:
    def __get__(self, obj, objtype): ...
    def __set__(self, obj, val) -> None: ...

class XNNPACKEngine(types.ModuleType):
    m: Incomplete
    def __init__(self, m, name) -> None: ...
    def __getattr__(self, attr): ...
    enabled: Incomplete
