from .. import AsyncLibraryNotFoundError as AsyncLibraryNotFoundError, current_async_library as current_async_library, current_async_library_cvar as current_async_library_cvar, thread_local as thread_local

def test_basics_cvar() -> None: ...
def test_basics_tlocal() -> None: ...
def test_asyncio() -> None: ...
def test_curio() -> None: ...
