import torch
from _typeshed import Incomplete
from torch import Tensor as Tensor
from typing import Callable, Dict, List, Tuple

decomposition_table: Incomplete
decomposition_table_for_jvp: Dict[torch._ops.OpOverload, Callable]
register_decomposition: Incomplete
aten: Incomplete

def maybe_register_decomposition(op): ...
def register_decomposition_for_jvp(fn): ...
def trace(self) -> Tensor: ...
def log_sigmoid_forward(self) -> Tuple[Tensor, Tensor]: ...
def recompute_mean_var(input: Tensor, rstd: Tensor, inner_dim_indices: List[int], keepdim: bool): ...
def native_layer_norm_backward(grad_out: Tensor, input: Tensor, normalized_shape: List[int], mean: Tensor, rstd: Tensor, weight: Tensor | None, bias: Tensor | None, output_mask: List[bool]) -> Tuple[Tensor | None, Tensor | None, Tensor | None]: ...
def prod(x: List[int]): ...
def native_batch_norm_backward(grad_out: Tensor, input: Tensor, weight: Tensor | None, running_mean: Tensor | None, running_var: Tensor | None, save_mean: Tensor | None, save_invstd: Tensor | None, train: bool, eps: float, output_mask: List[bool]) -> Tuple[Tensor, Tensor | None, Tensor | None]: ...
