from _typeshed import Incomplete
from databricks_cli.sdk import JobsService as JobsService

class JobsApi:
    client: Incomplete
    def __init__(self, api_client) -> None: ...
    def create_job(self, json, headers: Incomplete | None = None, version: Incomplete | None = None): ...
    def list_jobs(self, job_type: Incomplete | None = None, expand_tasks: Incomplete | None = None, offset: Incomplete | None = None, limit: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None, name: Incomplete | None = None): ...
    def delete_job(self, job_id, headers: Incomplete | None = None, version: Incomplete | None = None): ...
    def get_job(self, job_id, headers: Incomplete | None = None, version: Incomplete | None = None): ...
    def reset_job(self, json, headers: Incomplete | None = None, version: Incomplete | None = None): ...
    def run_now(self, job_id, jar_params, notebook_params, python_params, spark_submit_params, python_named_params: Incomplete | None = None, idempotency_token: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None): ...
