from .. import variables as variables
from ..exc import unimplemented as unimplemented
from ..guards import GuardBuilder as GuardBuilder
from ..source import AttrSource as AttrSource, ODictGetItemSource as ODictGetItemSource, RandomValueSource as RandomValueSource
from ..utils import is_namedtuple_cls as is_namedtuple_cls, namedtuple_fields as namedtuple_fields
from .base import MutableLocal as MutableLocal, VariableTracker as VariableTracker
from .misc import NullContextVariable as NullContextVariable
from _typeshed import Incomplete
from typing import Dict, List

class UserDefinedVariable(VariableTracker): ...

class UserDefinedClassVariable(UserDefinedVariable):
    value: Incomplete
    def __init__(self, value, **kwargs) -> None: ...
    def as_python_constant(self): ...
    def python_type(self): ...
    def var_getattr(self, tx, name: str) -> VariableTracker: ...
    def call_method(self, tx, name, args: List[VariableTracker], kwargs: Dict[str, VariableTracker]) -> VariableTracker: ...
    def call_function(self, tx, args: List[VariableTracker], kwargs: Dict[str, VariableTracker]) -> VariableTracker: ...
    def const_getattr(self, tx, name): ...

class UserDefinedObjectVariable(UserDefinedVariable):
    """
    Mostly objects of defined type.  Catch-all for something where we only know the type.
    """
    value: Incomplete
    value_type: Incomplete
    def __init__(self, value, value_type: Incomplete | None = None, **kwargs) -> None: ...
    def python_type(self): ...
    def call_method(self, tx, name, args: List[VariableTracker], kwargs: Dict[str, VariableTracker]) -> VariableTracker: ...
    def is_supported_random(self): ...
    def call_function(self, tx, args: List[VariableTracker], kwargs: Dict[str, VariableTracker]) -> VariableTracker: ...
    def var_getattr(self, tx, name): ...
    def call_hasattr(self, tx, name: str) -> VariableTracker: ...
    def odict_getitem(self, tx, key): ...
