from _typeshed import Incomplete
from logging import Logger
from torch.nn import Module as Module
from typing import Dict, List

class CompressorSchema:
    data_schema: Incomplete
    compressor_schema: Incomplete
    def __init__(self, data_schema: List[Dict], model: Module, logger: Logger) -> None: ...
    def validate(self, data) -> None: ...

def validate_op_names(model, op_names, logger): ...
def validate_op_types(model, op_types, logger): ...
def validate_op_types_op_names(data): ...
