from _typeshed import Incomplete
from torch.nn import Module
from torch.optim import Optimizer
from torch.optim.lr_scheduler import _LRScheduler
from typing import Callable, Dict, List, Type

__all__ = ['OptimizerConstructHelper', 'LRSchedulerConstructHelper']

class ConstructHelper:
    callable_obj: Incomplete
    args: Incomplete
    kwargs: Incomplete
    def __init__(self, callable_obj: Callable, *args, **kwargs) -> None: ...
    def call(self): ...

class OptimizerConstructHelper(ConstructHelper):
    def __init__(self, model: Module, optimizer_class: Type[Optimizer], *args, **kwargs) -> None: ...
    def params2names(self, model: Module, params: List) -> List[Dict]: ...
    def names2params(self, wrapped_model: Module, origin2wrapped_name_map: Dict | None, params: List[Dict]) -> List[Dict]: ...
    def call(self, wrapped_model: Module, origin2wrapped_name_map: Dict | None) -> Optimizer: ...
    @staticmethod
    def from_trace(model: Module, optimizer_trace: Optimizer): ...

class LRSchedulerConstructHelper(ConstructHelper):
    def __init__(self, lr_scheduler_class: Type[_LRScheduler], *args, **kwargs) -> None: ...
    def call(self, optimizer: Optimizer) -> _LRScheduler: ...
    @staticmethod
    def from_trace(lr_scheduler_trace: _LRScheduler): ...
