from fluent import asyncsender as asyncsender, handler as handler

class FluentHandler(handler.FluentHandler):
    """
    Asynchronous Logging Handler for fluent.
    """
    def getSenderClass(self): ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
