import msgpack
from _typeshed import Incomplete

def setup(tag, **kwargs) -> None: ...
def get_global_sender(): ...
def close() -> None: ...

class EventTime(msgpack.ExtType):
    def __new__(cls, timestamp): ...

class FluentSender:
    tag: Incomplete
    host: Incomplete
    port: Incomplete
    bufmax: Incomplete
    timeout: Incomplete
    verbose: Incomplete
    buffer_overflow_handler: Incomplete
    nanosecond_precision: Incomplete
    msgpack_kwargs: Incomplete
    socket: Incomplete
    pendings: Incomplete
    lock: Incomplete
    def __init__(self, tag, host: str = 'localhost', port: int = 24224, bufmax=..., timeout: float = 3.0, verbose: bool = False, buffer_overflow_handler: Incomplete | None = None, nanosecond_precision: bool = False, msgpack_kwargs: Incomplete | None = None, **kwargs) -> None:
        """
        :param kwargs: This kwargs argument is not used in __init__. This will be removed in the next major version.
        """
    def emit(self, label, data): ...
    def emit_with_time(self, label, timestamp, data): ...
    @property
    def last_error(self): ...
    @last_error.setter
    def last_error(self, err) -> None: ...
    def clear_last_error(self, _thread_id: Incomplete | None = None) -> None: ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, typ: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
