from . import context as context, sample as sample, tb_watcher as tb_watcher
from ..interface.interface_queue import InterfaceQueue as InterfaceQueue
from ..lib import handler_util as handler_util, proto_util as proto_util, tracelog as tracelog, wburls as wburls
from .settings_static import SettingsStatic as SettingsStatic
from .system.system_monitor import SystemMonitor as SystemMonitor
from _typeshed import Incomplete
from queue import Queue
from threading import Event
from typing import Any, Dict
from wandb.proto.wandb_internal_pb2 import HistoryRecord as HistoryRecord, InternalMessages as InternalMessages, MetricRecord as MetricRecord, MetricSummary as MetricSummary, Record as Record, Result as Result, RunRecord as RunRecord, SampledHistoryItem as SampledHistoryItem, SummaryItem as SummaryItem, SummaryRecord as SummaryRecord, SummaryRecordRequest as SummaryRecordRequest, SystemMetricSample as SystemMetricSample, SystemMetricsBuffer as SystemMetricsBuffer

SummaryDict = Dict[str, Any]
logger: Incomplete

class HandleManager:
    def __init__(self, settings: SettingsStatic, record_q: Queue[Record], result_q: Queue[Result], stopped: Event, writer_q: Queue[Record], interface: InterfaceQueue, context_keeper: context.ContextKeeper) -> None: ...
    def __len__(self) -> int: ...
    def handle(self, record: Record) -> None: ...
    def handle_request(self, record: Record) -> None: ...
    def debounce(self) -> None: ...
    def handle_request_cancel(self, record: Record) -> None: ...
    def handle_request_defer(self, record: Record) -> None: ...
    def handle_request_login(self, record: Record) -> None: ...
    def handle_run(self, record: Record) -> None: ...
    def handle_stats(self, record: Record) -> None: ...
    def handle_config(self, record: Record) -> None: ...
    def handle_output(self, record: Record) -> None: ...
    def handle_output_raw(self, record: Record) -> None: ...
    def handle_files(self, record: Record) -> None: ...
    def handle_link_artifact(self, record: Record) -> None: ...
    def handle_use_artifact(self, record: Record) -> None: ...
    def handle_artifact(self, record: Record) -> None: ...
    def handle_alert(self, record: Record) -> None: ...
    def handle_history(self, record: Record) -> None: ...
    def handle_request_sender_mark_report(self, record: Record) -> None: ...
    def handle_request_status_report(self, record: Record) -> None: ...
    def handle_request_partial_history(self, record: Record) -> None: ...
    def handle_summary(self, record: Record) -> None: ...
    def handle_exit(self, record: Record) -> None: ...
    def handle_final(self, record: Record) -> None: ...
    def handle_preempting(self, record: Record) -> None: ...
    def handle_header(self, record: Record) -> None: ...
    def handle_footer(self, record: Record) -> None: ...
    def handle_request_check_version(self, record: Record) -> None: ...
    def handle_request_attach(self, record: Record) -> None: ...
    def handle_request_log_artifact(self, record: Record) -> None: ...
    def handle_telemetry(self, record: Record) -> None: ...
    def handle_request_run_start(self, record: Record) -> None: ...
    def handle_request_resume(self, record: Record) -> None: ...
    def handle_request_pause(self, record: Record) -> None: ...
    def handle_request_poll_exit(self, record: Record) -> None: ...
    def handle_request_stop_status(self, record: Record) -> None: ...
    def handle_request_network_status(self, record: Record) -> None: ...
    def handle_request_internal_messages(self, record: Record) -> None: ...
    def handle_request_status(self, record: Record) -> None: ...
    def handle_request_get_summary(self, record: Record) -> None: ...
    def handle_request_get_system_metrics(self, record: Record) -> None: ...
    def handle_tbrecord(self, record: Record) -> None: ...
    def handle_metric(self, record: Record) -> None:
        """Handle MetricRecord.

        Walkthrough of the life of a MetricRecord:

        Metric defined:
        - run.define_metric() parses arguments create wandb_metric.Metric
        - build MetricRecord publish to interface
        - handler (this function) keeps list of metrics published:
          - self._metric_defines: Fully defined metrics
          - self._metric_globs: metrics that have a wildcard
        - dispatch writer and sender thread
          - writer: records are saved to persistent store
          - sender: fully defined metrics get mapped into metadata for UI

        History logged:
        - handle_history
        - check if metric matches _metric_defines
        - if not, check if metric matches _metric_globs
        - if _metric globs match, generate defined metric and call _handle_metric

        Args:
            record (Record): Metric record to process
        """
    def handle_request_sampled_history(self, record: Record) -> None: ...
    def handle_request_server_info(self, record: Record) -> None: ...
    def handle_request_keepalive(self, record: Record) -> None:
        """Handle a keepalive request.

        Keepalive is a noop, we just want to verify transport is alive.
        """
    def handle_request_run_status(self, record: Record) -> None: ...
    def handle_request_shutdown(self, record: Record) -> None: ...
    def handle_request_job_info(self, record: Record) -> None: ...
    def finish(self) -> None: ...
    def __next__(self) -> Record: ...
    next = __next__
