from . import context as context, datastore as datastore, flow_control as flow_control
from ..interface.interface_queue import InterfaceQueue as InterfaceQueue
from ..lib import proto_util as proto_util, telemetry as telemetry, tracelog as tracelog
from .settings_static import SettingsStatic as SettingsStatic
from _typeshed import Incomplete
from queue import Queue
from wandb.proto import wandb_internal_pb2 as pb

logger: Incomplete

class WriteManager:
    def __init__(self, settings: SettingsStatic, record_q: Queue[pb.Record], result_q: Queue[pb.Result], sender_q: Queue[pb.Record], interface: InterfaceQueue, context_keeper: context.ContextKeeper) -> None: ...
    def open(self) -> None: ...
    def write(self, record: pb.Record) -> None: ...
    def write_request(self, record: pb.Record) -> None: ...
    def write_request_run_status(self, record: pb.Record) -> None: ...
    def write_request_status_report(self, record: pb.Record) -> None: ...
    def write_request_cancel(self, record: pb.Record) -> None: ...
    def finish(self) -> None: ...
    def debounce(self) -> None: ...
