import abc
from _typeshed import Incomplete

class Reporter(abc.ABC, metaclass=abc.ABCMeta):
    def __init__(self, *args, **kwargs) -> None: ...
    @abc.abstractmethod
    def report(self): ...
    @abc.abstractmethod
    def write(self, row_name: str, precision: float, recall: float, f1: float, support: int): ...

class DictReporter(Reporter):
    report_dict: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def report(self): ...
    def write(self, row_name: str, precision: float, recall: float, f1: float, support: int): ...
    def write_blank(self) -> None: ...

class StringReporter(Reporter):
    buffer: Incomplete
    row_fmt: Incomplete
    width: Incomplete
    digits: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def report(self): ...
    def write(self, row_name: str, precision: float, recall: float, f1: float, support: int): ...
    def write_header(self): ...
    def write_blank(self) -> None: ...
