from nni.nas.execution.common import AbstractExecutionEngine, DefaultListener, Model
from typing import Iterable

__all__ = ['init_execution_engine', 'get_execution_engine', 'get_and_register_default_listener', 'list_models', 'submit_models', 'wait_models', 'query_available_resources', 'set_execution_engine', 'is_stopped_exec', 'budget_exhausted']

def init_execution_engine(config, port, url_prefix) -> AbstractExecutionEngine: ...
def set_execution_engine(engine: AbstractExecutionEngine) -> None: ...
def get_execution_engine() -> AbstractExecutionEngine: ...
def get_and_register_default_listener(engine: AbstractExecutionEngine) -> DefaultListener: ...
def submit_models(*models: Model) -> None: ...
def list_models(*models: Model) -> Iterable[Model]: ...
def wait_models(*models: Model) -> None: ...
def query_available_resources() -> int: ...
def is_stopped_exec(model: Model) -> bool: ...
def budget_exhausted() -> bool: ...
