from jax import lax as lax
from jax._src.numpy.util import promote_args_inexact as promote_args_inexact
from jax._src.typing import Array as Array, ArrayLike as ArrayLike
from jax.scipy.special import gammaincc as gammaincc, gammaln as gammaln, xlogy as xlogy

def logpmf(k: ArrayLike, mu: ArrayLike, loc: ArrayLike = 0) -> Array: ...
def pmf(k: ArrayLike, mu: ArrayLike, loc: ArrayLike = 0) -> Array: ...
def cdf(k: ArrayLike, mu: ArrayLike, loc: ArrayLike = 0) -> Array: ...
