from transformers import CLIPSegConfig as CLIPSegConfig, CLIPSegForImageSegmentation as CLIPSegForImageSegmentation, CLIPSegProcessor as CLIPSegProcessor, CLIPSegTextConfig as CLIPSegTextConfig, CLIPSegVisionConfig as CLIPSegVisionConfig, CLIPTokenizer as CLIPTokenizer, ViTFeatureExtractor as ViTFeatureExtractor

def get_clipseg_config(model_name): ...
def rename_key(name): ...
def convert_state_dict(orig_state_dict, config): ...
def prepare_img(): ...
def convert_clipseg_checkpoint(model_name, checkpoint_path, pytorch_dump_folder_path, push_to_hub) -> None: ...
