from _typeshed import Incomplete

DEBUG_PRINT: bool
MAX_TENSOR: int
MAX_TENSOR_DIM: int
MAX_TENSOR_SIZE: Incomplete
DEBUG_TENSOR: bool
DEVICE: str
DTYPE: Incomplete
GRAPH_FACTOR: int

class WrongResultException(Exception): ...

def get_broadcast_compatible_shape(tensor_shape): ...
def random_topology_test(seed, *inp_tensor_list): ...
def prepareInputTensorsToRandomTopoTest(seed, max_tensor_num, max_tensor_dim, max_tensor_size, debug_tensor, device, dtype): ...
def reproString(current_seed, args): ...
def runDefaultTestWithSeed(seed): ...
def runTest(seed, args) -> None: ...
def parse_args(): ...
