from _typeshed import Incomplete
from matplotlib.axes import Axes as Axes
from matplotlib.figure import Figure as Figure
from pandas import DataFrame as DataFrame, Index as Index, Series as Series
from pandas.core.dtypes.missing import notna as notna
from pandas.io.formats.printing import pprint_thing as pprint_thing
from pandas.plotting._matplotlib.style import get_standard_colors as get_standard_colors
from pandas.plotting._matplotlib.tools import create_subplots as create_subplots, do_adjust_figure as do_adjust_figure, maybe_adjust_figure as maybe_adjust_figure, set_ticks_props as set_ticks_props

def scatter_matrix(frame: DataFrame, alpha: float = 0.5, figsize: Incomplete | None = None, ax: Incomplete | None = None, grid: bool = False, diagonal: str = 'hist', marker: str = '.', density_kwds: Incomplete | None = None, hist_kwds: Incomplete | None = None, range_padding: float = 0.05, **kwds): ...
def radviz(frame: DataFrame, class_column, ax: Axes | None = None, color: Incomplete | None = None, colormap: Incomplete | None = None, **kwds) -> Axes: ...
def andrews_curves(frame: DataFrame, class_column, ax: Axes | None = None, samples: int = 200, color: Incomplete | None = None, colormap: Incomplete | None = None, **kwds) -> Axes: ...
def bootstrap_plot(series: Series, fig: Figure | None = None, size: int = 50, samples: int = 500, **kwds) -> Figure: ...
def parallel_coordinates(frame: DataFrame, class_column, cols: Incomplete | None = None, ax: Axes | None = None, color: Incomplete | None = None, use_columns: bool = False, xticks: Incomplete | None = None, colormap: Incomplete | None = None, axvlines: bool = True, axvlines_kwds: Incomplete | None = None, sort_labels: bool = False, **kwds) -> Axes: ...
def lag_plot(series: Series, lag: int = 1, ax: Axes | None = None, **kwds) -> Axes: ...
def autocorrelation_plot(series: Series, ax: Axes | None = None, **kwds) -> Axes: ...
def unpack_single_str_list(keys): ...
