from _typeshed import Incomplete

class Recoverable:
    recovered_max_param_id: int
    recovered_trial_params: Incomplete
    def __init__(self) -> None: ...
    def load_checkpoint(self) -> None: ...
    def save_checkpoint(self) -> None: ...
    def get_checkpoint_path(self) -> str | None: ...
    def recover_parameter_id(self, data) -> int: ...
    def is_created_in_previous_exp(self, param_id: int) -> bool: ...
    def get_previous_param(self, param_id: int) -> dict: ...
