from .constants import DataLossWarning as DataLossWarning
from _typeshed import Incomplete

baseChar: str
ideographic: str
combiningCharacter: str
digit: str
extender: str
letter: Incomplete
name: Incomplete
nameFirst: Incomplete
reChar: Incomplete
reCharRange: Incomplete

def charStringToList(chars): ...
def normaliseCharList(charList): ...

max_unicode: Incomplete

def missingRanges(charList): ...
def listToRegexpStr(charList): ...
def hexToInt(hex_str): ...
def escapeRegexp(string): ...

nonXmlNameBMPRegexp: Incomplete
nonXmlNameFirstBMPRegexp: Incomplete
nonPubidCharRegexp: Incomplete

class InfosetFilter:
    replacementRegexp: Incomplete
    dropXmlnsLocalName: Incomplete
    dropXmlnsAttrNs: Incomplete
    preventDoubleDashComments: Incomplete
    preventDashAtCommentEnd: Incomplete
    replaceFormFeedCharacters: Incomplete
    preventSingleQuotePubid: Incomplete
    replaceCache: Incomplete
    def __init__(self, dropXmlnsLocalName: bool = False, dropXmlnsAttrNs: bool = False, preventDoubleDashComments: bool = False, preventDashAtCommentEnd: bool = False, replaceFormFeedCharacters: bool = True, preventSingleQuotePubid: bool = False) -> None: ...
    def coerceAttribute(self, name, namespace: Incomplete | None = None): ...
    def coerceElement(self, name): ...
    def coerceComment(self, data): ...
    def coerceCharacters(self, data): ...
    def coercePubid(self, data): ...
    def toXmlName(self, name): ...
    def getReplacementCharacter(self, char): ...
    def fromXmlName(self, name): ...
    def escapeChar(self, char): ...
    def unescapeChar(self, charcode): ...
