from ._inputstream import HTMLInputStream as HTMLInputStream
from ._trie import Trie as Trie
from .constants import EOF as EOF, asciiLetters as asciiLetters, asciiUpper2Lower as asciiUpper2Lower, digits as digits, entities as entities, hexDigits as hexDigits, replacementCharacters as replacementCharacters, spaceCharacters as spaceCharacters, tagTokenTypes as tagTokenTypes, tokenTypes as tokenTypes
from _typeshed import Incomplete
from collections import OrderedDict

entitiesTrie: Incomplete
attributeMap = dict
attributeMap = OrderedDict

class HTMLTokenizer:
    """ This class takes care of tokenizing HTML.

    * self.currentToken
      Holds the token that is currently being processed.

    * self.state
      Holds a reference to the method to be invoked... XXX

    * self.stream
      Points to HTMLInputStream object.
    """
    stream: Incomplete
    parser: Incomplete
    escapeFlag: bool
    lastFourChars: Incomplete
    state: Incomplete
    escape: bool
    currentToken: Incomplete
    def __init__(self, stream, parser: Incomplete | None = None, **kwargs) -> None: ...
    tokenQueue: Incomplete
    def __iter__(self):
        """ This is where the magic happens.

        We do our usually processing through the states and when we have a token
        to return we yield the token which pauses processing until the next token
        is requested.
        """
    def consumeNumberEntity(self, isHex):
        '''This function returns either U+FFFD or the character based on the
        decimal or hexadecimal representation. It also discards ";" if present.
        If not present self.tokenQueue.append({"type": tokenTypes["ParseError"]}) is invoked.
        '''
    def consumeEntity(self, allowedChar: Incomplete | None = None, fromAttribute: bool = False) -> None: ...
    def processEntityInAttribute(self, allowedChar) -> None:
        '''This method replaces the need for "entityInAttributeValueState".
        '''
    def emitCurrentToken(self) -> None:
        '''This method is a generic handler for emitting the tags. It also sets
        the state to "data" because that\'s what\'s needed after a token has been
        emitted.
        '''
    def dataState(self): ...
    def entityDataState(self): ...
    def rcdataState(self): ...
    def characterReferenceInRcdata(self): ...
    def rawtextState(self): ...
    def scriptDataState(self): ...
    def plaintextState(self): ...
    def tagOpenState(self): ...
    def closeTagOpenState(self): ...
    def tagNameState(self): ...
    temporaryBuffer: str
    def rcdataLessThanSignState(self): ...
    def rcdataEndTagOpenState(self): ...
    def rcdataEndTagNameState(self): ...
    def rawtextLessThanSignState(self): ...
    def rawtextEndTagOpenState(self): ...
    def rawtextEndTagNameState(self): ...
    def scriptDataLessThanSignState(self): ...
    def scriptDataEndTagOpenState(self): ...
    def scriptDataEndTagNameState(self): ...
    def scriptDataEscapeStartState(self): ...
    def scriptDataEscapeStartDashState(self): ...
    def scriptDataEscapedState(self): ...
    def scriptDataEscapedDashState(self): ...
    def scriptDataEscapedDashDashState(self): ...
    def scriptDataEscapedLessThanSignState(self): ...
    def scriptDataEscapedEndTagOpenState(self): ...
    def scriptDataEscapedEndTagNameState(self): ...
    def scriptDataDoubleEscapeStartState(self): ...
    def scriptDataDoubleEscapedState(self): ...
    def scriptDataDoubleEscapedDashState(self): ...
    def scriptDataDoubleEscapedDashDashState(self): ...
    def scriptDataDoubleEscapedLessThanSignState(self): ...
    def scriptDataDoubleEscapeEndState(self): ...
    def beforeAttributeNameState(self): ...
    def attributeNameState(self): ...
    def afterAttributeNameState(self): ...
    def beforeAttributeValueState(self): ...
    def attributeValueDoubleQuotedState(self): ...
    def attributeValueSingleQuotedState(self): ...
    def attributeValueUnQuotedState(self): ...
    def afterAttributeValueState(self): ...
    def selfClosingStartTagState(self): ...
    def bogusCommentState(self): ...
    def markupDeclarationOpenState(self): ...
    def commentStartState(self): ...
    def commentStartDashState(self): ...
    def commentState(self): ...
    def commentEndDashState(self): ...
    def commentEndState(self): ...
    def commentEndBangState(self): ...
    def doctypeState(self): ...
    def beforeDoctypeNameState(self): ...
    def doctypeNameState(self): ...
    def afterDoctypeNameState(self): ...
    def afterDoctypePublicKeywordState(self): ...
    def beforeDoctypePublicIdentifierState(self): ...
    def doctypePublicIdentifierDoubleQuotedState(self): ...
    def doctypePublicIdentifierSingleQuotedState(self): ...
    def afterDoctypePublicIdentifierState(self): ...
    def betweenDoctypePublicAndSystemIdentifiersState(self): ...
    def afterDoctypeSystemKeywordState(self): ...
    def beforeDoctypeSystemIdentifierState(self): ...
    def doctypeSystemIdentifierDoubleQuotedState(self): ...
    def doctypeSystemIdentifierSingleQuotedState(self): ...
    def afterDoctypeSystemIdentifierState(self): ...
    def bogusDoctypeState(self): ...
    def cdataSectionState(self): ...
