from _typeshed import Incomplete

def enum(**enums): ...

ENV_DETECTED: Incomplete

def is_cloud_env(detected): ...

class EnvironmentDetector:
    checks: Incomplete
    def __init__(self) -> None: ...
    def detect(self): ...
