from ._auth_record import AuthenticationRecord as AuthenticationRecord
from ._constants import AzureAuthorityHosts as AzureAuthorityHosts, KnownAuthorities as KnownAuthorities
from ._credentials import AuthorizationCodeCredential as AuthorizationCodeCredential, AzureCliCredential as AzureCliCredential, AzureDeveloperCliCredential as AzureDeveloperCliCredential, AzurePowerShellCredential as AzurePowerShellCredential, CertificateCredential as CertificateCredential, ChainedTokenCredential as ChainedTokenCredential, ClientAssertionCredential as ClientAssertionCredential, ClientSecretCredential as ClientSecretCredential, DefaultAzureCredential as DefaultAzureCredential, DeviceCodeCredential as DeviceCodeCredential, EnvironmentCredential as EnvironmentCredential, InteractiveBrowserCredential as InteractiveBrowserCredential, ManagedIdentityCredential as ManagedIdentityCredential, OnBehalfOfCredential as OnBehalfOfCredential, SharedTokenCacheCredential as SharedTokenCacheCredential, UsernamePasswordCredential as UsernamePasswordCredential, VisualStudioCodeCredential as VisualStudioCodeCredential, WorkloadIdentityCredential as WorkloadIdentityCredential
from ._exceptions import AuthenticationRequiredError as AuthenticationRequiredError, CredentialUnavailableError as CredentialUnavailableError
from ._persistent_cache import TokenCachePersistenceOptions as TokenCachePersistenceOptions
from ._version import VERSION

__all__ = ['AuthenticationRecord', 'AuthenticationRequiredError', 'AuthorizationCodeCredential', 'AzureAuthorityHosts', 'AzureCliCredential', 'AzureDeveloperCliCredential', 'AzurePowerShellCredential', 'CertificateCredential', 'ChainedTokenCredential', 'ClientAssertionCredential', 'ClientSecretCredential', 'CredentialUnavailableError', 'DefaultAzureCredential', 'DeviceCodeCredential', 'EnvironmentCredential', 'InteractiveBrowserCredential', 'KnownAuthorities', 'OnBehalfOfCredential', 'ManagedIdentityCredential', 'SharedTokenCacheCredential', 'TokenCachePersistenceOptions', 'UsernamePasswordCredential', 'VisualStudioCodeCredential', 'WorkloadIdentityCredential']

__version__ = VERSION
