import threading
from .common import DTDForbidden as DTDForbidden, EntitiesForbidden as EntitiesForbidden, NotSupportedError as NotSupportedError
from _typeshed import Incomplete
from lxml import etree as _etree

LXML3: Incomplete
__origin__: str
tostring: Incomplete

class RestrictedElement(_etree.ElementBase):
    """A restricted Element class that filters out instances of some classes"""
    blacklist: Incomplete
    def __iter__(self): ...
    def iterchildren(self, tag: Incomplete | None = None, reversed: bool = False): ...
    def iter(self, tag: Incomplete | None = None, *tags): ...
    def iterdescendants(self, tag: Incomplete | None = None, *tags): ...
    def itersiblings(self, tag: Incomplete | None = None, preceding: bool = False): ...
    def getchildren(self): ...
    def getiterator(self, tag: Incomplete | None = None): ...

class GlobalParserTLS(threading.local):
    """Thread local context for custom parser instances"""
    parser_config: Incomplete
    element_class = RestrictedElement
    def createDefaultParser(self): ...
    def setDefaultParser(self, parser) -> None: ...
    def getDefaultParser(self): ...

getDefaultParser: Incomplete

def check_docinfo(elementtree, forbid_dtd: bool = False, forbid_entities: bool = True) -> None:
    """Check docinfo of an element tree for DTD and entity declarations

    The check for entity declarations needs lxml 3 or newer. lxml 2.x does
    not support dtd.iterentities().
    """
def parse(source, parser: Incomplete | None = None, base_url: Incomplete | None = None, forbid_dtd: bool = False, forbid_entities: bool = True): ...
def fromstring(text, parser: Incomplete | None = None, base_url: Incomplete | None = None, forbid_dtd: bool = False, forbid_entities: bool = True): ...
XML = fromstring

def iterparse(*args, **kwargs) -> None: ...
