from _typeshed import Incomplete
from openai import api_requestor as api_requestor, util as util
from openai.api_resources.abstract import APIResource as APIResource

class Audio(APIResource):
    OBJECT_NAME: str
    @classmethod
    def transcribe(cls, model, file, api_key: Incomplete | None = None, api_base: Incomplete | None = None, api_type: Incomplete | None = None, api_version: Incomplete | None = None, organization: Incomplete | None = None, **params): ...
    @classmethod
    def translate(cls, model, file, api_key: Incomplete | None = None, api_base: Incomplete | None = None, api_type: Incomplete | None = None, api_version: Incomplete | None = None, organization: Incomplete | None = None, **params): ...
    @classmethod
    def transcribe_raw(cls, model, file, filename, api_key: Incomplete | None = None, api_base: Incomplete | None = None, api_type: Incomplete | None = None, api_version: Incomplete | None = None, organization: Incomplete | None = None, **params): ...
    @classmethod
    def translate_raw(cls, model, file, filename, api_key: Incomplete | None = None, api_base: Incomplete | None = None, api_type: Incomplete | None = None, api_version: Incomplete | None = None, organization: Incomplete | None = None, **params): ...
    @classmethod
    async def atranscribe(cls, model, file, api_key: Incomplete | None = None, api_base: Incomplete | None = None, api_type: Incomplete | None = None, api_version: Incomplete | None = None, organization: Incomplete | None = None, **params): ...
    @classmethod
    async def atranslate(cls, model, file, api_key: Incomplete | None = None, api_base: Incomplete | None = None, api_type: Incomplete | None = None, api_version: Incomplete | None = None, organization: Incomplete | None = None, **params): ...
    @classmethod
    async def atranscribe_raw(cls, model, file, filename, api_key: Incomplete | None = None, api_base: Incomplete | None = None, api_type: Incomplete | None = None, api_version: Incomplete | None = None, organization: Incomplete | None = None, **params): ...
    @classmethod
    async def atranslate_raw(cls, model, file, filename, api_key: Incomplete | None = None, api_base: Incomplete | None = None, api_type: Incomplete | None = None, api_version: Incomplete | None = None, organization: Incomplete | None = None, **params): ...
