from transformers import Speech2TextConfig as Speech2TextConfig, Speech2TextForConditionalGeneration as Speech2TextForConditionalGeneration

def remove_ignore_keys_(state_dict) -> None: ...
def rename_keys(s_dict) -> None: ...
def make_linear_from_emb(emb): ...
def convert_fairseq_s2t_checkpoint_to_tfms(checkpoint_path, pytorch_dump_folder_path) -> None: ...
