from _typeshed import Incomplete
from jedi import debug as debug
from jedi.inference.helpers import is_string as is_string

CODES: Incomplete

class Error:
    path: Incomplete
    name: Incomplete
    message: Incomplete
    def __init__(self, name, module_path, start_pos, message: Incomplete | None = None) -> None: ...
    @property
    def line(self): ...
    @property
    def column(self): ...
    @property
    def code(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class Warning(Error): ...

def add(node_context, error_name, node, message: Incomplete | None = None, typ=..., payload: Incomplete | None = None): ...
def add_attribute_error(name_context, lookup_value, name) -> None: ...
