from _typeshed import Incomplete

class JobsService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def create_job(self, name: Incomplete | None = None, existing_cluster_id: Incomplete | None = None, new_cluster: Incomplete | None = None, libraries: Incomplete | None = None, email_notifications: Incomplete | None = None, timeout_seconds: Incomplete | None = None, max_retries: Incomplete | None = None, min_retry_interval_millis: Incomplete | None = None, retry_on_timeout: Incomplete | None = None, schedule: Incomplete | None = None, notebook_task: Incomplete | None = None, spark_jar_task: Incomplete | None = None, spark_python_task: Incomplete | None = None, spark_submit_task: Incomplete | None = None, max_concurrent_runs: Incomplete | None = None, tasks: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None, git_source: Incomplete | None = None, job_clusters: Incomplete | None = None, tags: Incomplete | None = None, format: Incomplete | None = None, dbt_task: Incomplete | None = None, access_control_list: Incomplete | None = None, pipeline_task: Incomplete | None = None, python_wheel_task: Incomplete | None = None, sql_task: Incomplete | None = None, webhook_notifications: Incomplete | None = None, continuous: Incomplete | None = None): ...
    def submit_run(self, run_name: Incomplete | None = None, existing_cluster_id: Incomplete | None = None, new_cluster: Incomplete | None = None, libraries: Incomplete | None = None, notebook_task: Incomplete | None = None, spark_jar_task: Incomplete | None = None, spark_python_task: Incomplete | None = None, spark_submit_task: Incomplete | None = None, timeout_seconds: Incomplete | None = None, tasks: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None, idempotency_token: Incomplete | None = None, job_clusters: Incomplete | None = None, git_source: Incomplete | None = None, dbt_task: Incomplete | None = None, access_control_list: Incomplete | None = None, pipeline_task: Incomplete | None = None, python_wheel_task: Incomplete | None = None, sql_task: Incomplete | None = None, webhook_notifications: Incomplete | None = None): ...
    def reset_job(self, job_id, new_settings, headers: Incomplete | None = None, version: Incomplete | None = None): ...
    def update_job(self, job_id, new_settings: Incomplete | None = None, fields_to_remove: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None): ...
    def delete_job(self, job_id, headers: Incomplete | None = None, version: Incomplete | None = None): ...
    def get_job(self, job_id, headers: Incomplete | None = None, version: Incomplete | None = None, include_trigger_history: Incomplete | None = None): ...
    def list_jobs(self, job_type: Incomplete | None = None, expand_tasks: Incomplete | None = None, limit: Incomplete | None = None, offset: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None, name: Incomplete | None = None): ...
    def run_now(self, job_id: Incomplete | None = None, jar_params: Incomplete | None = None, notebook_params: Incomplete | None = None, python_params: Incomplete | None = None, spark_submit_params: Incomplete | None = None, python_named_params: Incomplete | None = None, idempotency_token: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None, dbt_commands: Incomplete | None = None, pipeline_params: Incomplete | None = None): ...
    def repair(self, run_id, latest_repair_id: Incomplete | None = None, rerun_tasks: Incomplete | None = None, jar_params: Incomplete | None = None, notebook_params: Incomplete | None = None, python_params: Incomplete | None = None, spark_submit_params: Incomplete | None = None, python_named_params: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None, dbt_commands: Incomplete | None = None, pipeline_params: Incomplete | None = None, rerun_all_failed_tasks: Incomplete | None = None, rerun_dependent_tasks: Incomplete | None = None): ...
    def list_runs(self, job_id: Incomplete | None = None, active_only: Incomplete | None = None, completed_only: Incomplete | None = None, offset: Incomplete | None = None, limit: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None, run_type: Incomplete | None = None, expand_tasks: Incomplete | None = None, start_time_from: Incomplete | None = None, start_time_to: Incomplete | None = None, page_token: Incomplete | None = None): ...
    def get_run(self, run_id: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None, include_history: Incomplete | None = None): ...
    def delete_run(self, run_id: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None): ...
    def cancel_run(self, run_id, headers: Incomplete | None = None, version: Incomplete | None = None): ...
    def cancel_all_runs(self, job_id: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None, all_queued_runs: Incomplete | None = None): ...
    def get_run_output(self, run_id, headers: Incomplete | None = None, version: Incomplete | None = None): ...
    def export_run(self, run_id, views_to_export: Incomplete | None = None, headers: Incomplete | None = None, version: Incomplete | None = None): ...

class ClusterService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def list_clusters(self, headers: Incomplete | None = None): ...
    def create_cluster(self, num_workers: Incomplete | None = None, autoscale: Incomplete | None = None, cluster_name: Incomplete | None = None, spark_version: Incomplete | None = None, spark_conf: Incomplete | None = None, aws_attributes: Incomplete | None = None, node_type_id: Incomplete | None = None, driver_node_type_id: Incomplete | None = None, ssh_public_keys: Incomplete | None = None, custom_tags: Incomplete | None = None, cluster_log_conf: Incomplete | None = None, spark_env_vars: Incomplete | None = None, autotermination_minutes: Incomplete | None = None, enable_elastic_disk: Incomplete | None = None, cluster_source: Incomplete | None = None, instance_pool_id: Incomplete | None = None, headers: Incomplete | None = None, azure_attributes: Incomplete | None = None, gcp_attributes: Incomplete | None = None, policy_id: Incomplete | None = None, enable_local_disk_encryption: Incomplete | None = None, driver_instance_pool_id: Incomplete | None = None, apply_policy_default_values: Incomplete | None = None): ...
    def start_cluster(self, cluster_id, headers: Incomplete | None = None): ...
    def list_spark_versions(self, headers: Incomplete | None = None): ...
    def delete_cluster(self, cluster_id, headers: Incomplete | None = None): ...
    def permanent_delete_cluster(self, cluster_id, headers: Incomplete | None = None): ...
    def restart_cluster(self, cluster_id, headers: Incomplete | None = None): ...
    def resize_cluster(self, cluster_id, num_workers: Incomplete | None = None, autoscale: Incomplete | None = None, headers: Incomplete | None = None): ...
    def edit_cluster(self, cluster_id, num_workers: Incomplete | None = None, autoscale: Incomplete | None = None, cluster_name: Incomplete | None = None, spark_version: Incomplete | None = None, spark_conf: Incomplete | None = None, aws_attributes: Incomplete | None = None, node_type_id: Incomplete | None = None, driver_node_type_id: Incomplete | None = None, ssh_public_keys: Incomplete | None = None, custom_tags: Incomplete | None = None, cluster_log_conf: Incomplete | None = None, spark_env_vars: Incomplete | None = None, autotermination_minutes: Incomplete | None = None, enable_elastic_disk: Incomplete | None = None, cluster_source: Incomplete | None = None, instance_pool_id: Incomplete | None = None, headers: Incomplete | None = None, azure_attributes: Incomplete | None = None, gcp_attributes: Incomplete | None = None, policy_id: Incomplete | None = None, enable_local_disk_encryption: Incomplete | None = None, driver_instance_pool_id: Incomplete | None = None, apply_policy_default_values: Incomplete | None = None): ...
    def get_cluster(self, cluster_id, headers: Incomplete | None = None): ...
    def pin_cluster(self, cluster_id, headers: Incomplete | None = None): ...
    def unpin_cluster(self, cluster_id, headers: Incomplete | None = None): ...
    def list_node_types(self, headers: Incomplete | None = None): ...
    def list_available_zones(self, headers: Incomplete | None = None): ...
    def get_events(self, cluster_id, start_time: Incomplete | None = None, end_time: Incomplete | None = None, order: Incomplete | None = None, event_types: Incomplete | None = None, offset: Incomplete | None = None, limit: Incomplete | None = None, headers: Incomplete | None = None): ...

class PolicyService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def get_policy(self, policy_id: Incomplete | None = None, headers: Incomplete | None = None): ...
    def list_policies(self, headers: Incomplete | None = None): ...
    def create_policy(self, policy_name: Incomplete | None = None, definition: Incomplete | None = None, headers: Incomplete | None = None, name: Incomplete | None = None): ...
    def edit_policy(self, policy_id, policy_name: Incomplete | None = None, definition: Incomplete | None = None, headers: Incomplete | None = None, name: Incomplete | None = None): ...
    def delete_policy(self, policy_id, headers: Incomplete | None = None): ...

class ManagedLibraryService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def cluster_status(self, cluster_id, headers: Incomplete | None = None): ...
    def all_cluster_statuses(self, headers: Incomplete | None = None): ...
    def install_libraries(self, cluster_id, libraries: Incomplete | None = None, headers: Incomplete | None = None): ...
    def uninstall_libraries(self, cluster_id, libraries: Incomplete | None = None, headers: Incomplete | None = None): ...

class DbfsService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def read(self, path, offset: Incomplete | None = None, length: Incomplete | None = None, headers: Incomplete | None = None): ...
    def get_status(self, path, headers: Incomplete | None = None): ...
    def list(self, path, headers: Incomplete | None = None): ...
    def put(self, path, contents: Incomplete | None = None, overwrite: Incomplete | None = None, headers: Incomplete | None = None, src_path: Incomplete | None = None): ...
    def mkdirs(self, path, headers: Incomplete | None = None): ...
    def move(self, source_path, destination_path, headers: Incomplete | None = None): ...
    def delete(self, path, recursive: Incomplete | None = None, headers: Incomplete | None = None): ...
    def create(self, path, overwrite: Incomplete | None = None, headers: Incomplete | None = None): ...
    def add_block(self, handle, data, headers: Incomplete | None = None): ...
    def close(self, handle, headers: Incomplete | None = None): ...

class WorkspaceService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def mkdirs(self, path, headers: Incomplete | None = None): ...
    def list(self, path, headers: Incomplete | None = None): ...
    def import_workspace(self, path, format: Incomplete | None = None, language: Incomplete | None = None, content: Incomplete | None = None, overwrite: Incomplete | None = None, headers: Incomplete | None = None): ...
    def export_workspace(self, path, format: Incomplete | None = None, direct_download: Incomplete | None = None, headers: Incomplete | None = None): ...
    def delete(self, path, recursive: Incomplete | None = None, headers: Incomplete | None = None): ...
    def get_status(self, path, headers: Incomplete | None = None): ...

class SecretService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def create_scope(self, scope, initial_manage_principal: Incomplete | None = None, scope_backend_type: Incomplete | None = None, backend_azure_keyvault: Incomplete | None = None, headers: Incomplete | None = None): ...
    def delete_scope(self, scope, headers: Incomplete | None = None): ...
    def list_scopes(self, headers: Incomplete | None = None): ...
    def put_secret(self, scope, key, string_value: Incomplete | None = None, bytes_value: Incomplete | None = None, headers: Incomplete | None = None): ...
    def delete_secret(self, scope, key, headers: Incomplete | None = None): ...
    def list_secrets(self, scope, headers: Incomplete | None = None): ...
    def put_acl(self, scope, principal, permission, headers: Incomplete | None = None): ...
    def delete_acl(self, scope, principal, headers: Incomplete | None = None): ...
    def list_acls(self, scope, headers: Incomplete | None = None): ...
    def get_acl(self, scope, principal, headers: Incomplete | None = None): ...

class GroupsService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def create_group(self, group_name, headers: Incomplete | None = None): ...
    def add_to_group(self, parent_name, user_name: Incomplete | None = None, group_name: Incomplete | None = None, headers: Incomplete | None = None): ...
    def remove_from_group(self, parent_name, user_name: Incomplete | None = None, group_name: Incomplete | None = None, headers: Incomplete | None = None): ...
    def get_groups(self, headers: Incomplete | None = None): ...
    def get_group_members(self, group_name, headers: Incomplete | None = None): ...
    def remove_group(self, group_name, headers: Incomplete | None = None): ...
    def get_groups_for_principal(self, user_name: Incomplete | None = None, group_name: Incomplete | None = None, headers: Incomplete | None = None): ...

class TokenService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def create_token(self, lifetime_seconds: Incomplete | None = None, comment: Incomplete | None = None, headers: Incomplete | None = None): ...
    def list_tokens(self, headers: Incomplete | None = None): ...
    def revoke_token(self, token_id, headers: Incomplete | None = None): ...

class InstancePoolService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def create_instance_pool(self, instance_pool_name: Incomplete | None = None, min_idle_instances: Incomplete | None = None, max_capacity: Incomplete | None = None, aws_attributes: Incomplete | None = None, node_type_id: Incomplete | None = None, custom_tags: Incomplete | None = None, idle_instance_autotermination_minutes: Incomplete | None = None, enable_elastic_disk: Incomplete | None = None, disk_spec: Incomplete | None = None, preloaded_spark_versions: Incomplete | None = None, headers: Incomplete | None = None, preloaded_docker_images: Incomplete | None = None, azure_attributes: Incomplete | None = None, gcp_attributes: Incomplete | None = None): ...
    def delete_instance_pool(self, instance_pool_id: Incomplete | None = None, headers: Incomplete | None = None): ...
    def edit_instance_pool(self, instance_pool_id, instance_pool_name: Incomplete | None = None, min_idle_instances: Incomplete | None = None, max_capacity: Incomplete | None = None, aws_attributes: Incomplete | None = None, node_type_id: Incomplete | None = None, custom_tags: Incomplete | None = None, idle_instance_autotermination_minutes: Incomplete | None = None, enable_elastic_disk: Incomplete | None = None, disk_spec: Incomplete | None = None, preloaded_spark_versions: Incomplete | None = None, headers: Incomplete | None = None, preloaded_docker_images: Incomplete | None = None, azure_attributes: Incomplete | None = None, gcp_attributes: Incomplete | None = None): ...
    def get_instance_pool(self, instance_pool_id: Incomplete | None = None, headers: Incomplete | None = None): ...
    def list_instance_pools(self, headers: Incomplete | None = None): ...

class DeltaPipelinesService:
    client: Incomplete
    def __init__(self, client) -> None: ...
    def create(self, id: Incomplete | None = None, name: Incomplete | None = None, storage: Incomplete | None = None, configuration: Incomplete | None = None, clusters: Incomplete | None = None, libraries: Incomplete | None = None, trigger: Incomplete | None = None, filters: Incomplete | None = None, target: Incomplete | None = None, continuous: Incomplete | None = None, development: Incomplete | None = None, allow_duplicate_names: Incomplete | None = None, headers: Incomplete | None = None): ...
    def deploy(self, pipeline_id: Incomplete | None = None, id: Incomplete | None = None, name: Incomplete | None = None, storage: Incomplete | None = None, configuration: Incomplete | None = None, clusters: Incomplete | None = None, libraries: Incomplete | None = None, trigger: Incomplete | None = None, filters: Incomplete | None = None, target: Incomplete | None = None, continuous: Incomplete | None = None, development: Incomplete | None = None, allow_duplicate_names: Incomplete | None = None, headers: Incomplete | None = None): ...
    def delete(self, pipeline_id: Incomplete | None = None, headers: Incomplete | None = None): ...
    def get(self, pipeline_id: Incomplete | None = None, headers: Incomplete | None = None): ...
    def list(self, pagination: Incomplete | None = None, headers: Incomplete | None = None): ...
    def reset(self, pipeline_id: Incomplete | None = None, headers: Incomplete | None = None): ...
    def run(self, pipeline_id: Incomplete | None = None, headers: Incomplete | None = None): ...
    def start_update(self, pipeline_id: Incomplete | None = None, full_refresh: Incomplete | None = None, headers: Incomplete | None = None): ...
    def stop(self, pipeline_id: Incomplete | None = None, headers: Incomplete | None = None): ...

class ReposService:
    __git_providers__: Incomplete
    __aws_code_commit_regexp__: Incomplete
    client: Incomplete
    def __init__(self, client) -> None: ...
    @staticmethod
    def detect_repo_provider(url): ...
    def list_repos(self, path_prefix: Incomplete | None = None, next_page_token: Incomplete | None = None, headers: Incomplete | None = None): ...
    def get_repo(self, id, headers: Incomplete | None = None): ...
    def update_repo(self, id, branch: Incomplete | None = None, tag: Incomplete | None = None, headers: Incomplete | None = None): ...
    def create_repo(self, url, provider, path: Incomplete | None = None, headers: Incomplete | None = None): ...
    def delete_repo(self, id, headers: Incomplete | None = None): ...
