from .. import _dtypes
from ...wandb_run import Run as LocalRun
from ..base_types.media import Media as Media
from _typeshed import Incomplete
from typing import Any, Dict, Sequence
from wandb.sdk.artifacts.artifact import Artifact as Artifact

class Classes(Media):
    def __init__(self, class_set: Sequence[dict]) -> None:
        '''Classes is holds class metadata intended to be used in concert with other objects when visualizing artifacts.

        Args:
            class_set (list): list of dicts in the form of {"id":int|str, "name":str}
        '''
    @classmethod
    def from_json(cls, json_obj: dict, source_artifact: Artifact | None) -> Classes: ...
    def to_json(self, run_or_artifact: LocalRun | Artifact | None) -> dict: ...
    def get_type(self) -> _ClassesIdType: ...
    def __ne__(self, other: object) -> bool: ...
    def __eq__(self, other: object) -> bool: ...

class _ClassesIdType(_dtypes.Type):
    name: str
    legacy_names: Incomplete
    types: Incomplete
    wb_classes_obj_ref: Incomplete
    def __init__(self, classes_obj: Classes | None = None, valid_ids: _dtypes.UnionType | None = None) -> None: ...
    def assign(self, py_obj: Any | None = None) -> _dtypes.Type: ...
    def assign_type(self, wb_type: _dtypes.Type) -> _dtypes.Type: ...
    @classmethod
    def from_obj(cls, py_obj: Any | None = None) -> _dtypes.Type: ...
    def to_json(self, artifact: Artifact | None = None) -> Dict[str, Any]: ...
    @classmethod
    def from_json(cls, json_dict: Dict[str, Any], artifact: Artifact | None = None) -> _dtypes.Type: ...
