from _typeshed import Incomplete
from fontTools.varLib.models import VariationModel as VariationModel, normalizeValue as normalizeValue, piecewiseLinearMap as piecewiseLinearMap

def Location(loc): ...

class VariableScalar:
    """A scalar with different values at different points in the designspace."""
    values: Incomplete
    axes: Incomplete
    def __init__(self, location_value={}) -> None: ...
    @property
    def does_vary(self): ...
    @property
    def axes_dict(self): ...
    def fix_location(self, location): ...
    def add_value(self, location, value) -> None: ...
    def fix_all_locations(self) -> None: ...
    @property
    def default(self): ...
    def value_at_location(self, location, model_cache: Incomplete | None = None, avar: Incomplete | None = None): ...
    def model(self, model_cache: Incomplete | None = None, avar: Incomplete | None = None): ...
    def get_deltas_and_supports(self, model_cache: Incomplete | None = None, avar: Incomplete | None = None): ...
    def add_to_variation_store(self, store_builder, model_cache: Incomplete | None = None, avar: Incomplete | None = None): ...
