from mypy.options import Options as Options

class Errors:
    num_errors: int
    num_warnings: int
    def __init__(self, options: Options) -> None: ...
    def error(self, msg: str, path: str, line: int) -> None: ...
    def note(self, msg: str, path: str, line: int) -> None: ...
    def warning(self, msg: str, path: str, line: int) -> None: ...
    def new_messages(self) -> list[str]: ...
    def flush_errors(self) -> None: ...
