from _typeshed import Incomplete
from mypyc.ir.rtypes import RArray as RArray, RInstance as RInstance, RPrimitive as RPrimitive, RStruct as RStruct, RTuple as RTuple, RType as RType, RTypeVisitor as RTypeVisitor, RUnion as RUnion, RVoid as RVoid, is_bit_rprimitive as is_bit_rprimitive, is_bool_rprimitive as is_bool_rprimitive, is_int_rprimitive as is_int_rprimitive, is_short_int_rprimitive as is_short_int_rprimitive
from mypyc.subtype import is_subtype as is_subtype

def is_runtime_subtype(left: RType, right: RType) -> bool: ...

class RTSubtypeVisitor(RTypeVisitor[bool]):
    """Is left a runtime subtype of right?

    A few special cases such as right being 'object' are handled in
    is_runtime_subtype and don't need to be covered here.
    """
    right: Incomplete
    def __init__(self, right: RType) -> None: ...
    def visit_rinstance(self, left: RInstance) -> bool: ...
    def visit_runion(self, left: RUnion) -> bool: ...
    def visit_rprimitive(self, left: RPrimitive) -> bool: ...
    def visit_rtuple(self, left: RTuple) -> bool: ...
    def visit_rstruct(self, left: RStruct) -> bool: ...
    def visit_rarray(self, left: RArray) -> bool: ...
    def visit_rvoid(self, left: RVoid) -> bool: ...
