from _typeshed import Incomplete
from mypyc.ir.func_ir import FUNC_STATICMETHOD as FUNC_STATICMETHOD, FuncIR as FuncIR
from mypyc.ir.ops import Assign as Assign, AssignMulti as AssignMulti, BaseAssign as BaseAssign, BasicBlock as BasicBlock, Box as Box, Branch as Branch, Call as Call, CallC as CallC, Cast as Cast, ComparisonOp as ComparisonOp, ControlOp as ControlOp, DecRef as DecRef, Extend as Extend, FloatComparisonOp as FloatComparisonOp, FloatNeg as FloatNeg, FloatOp as FloatOp, GetAttr as GetAttr, GetElementPtr as GetElementPtr, Goto as Goto, IncRef as IncRef, InitStatic as InitStatic, IntOp as IntOp, Integer as Integer, KeepAlive as KeepAlive, LoadAddress as LoadAddress, LoadErrorValue as LoadErrorValue, LoadGlobal as LoadGlobal, LoadLiteral as LoadLiteral, LoadMem as LoadMem, LoadStatic as LoadStatic, MethodCall as MethodCall, Op as Op, OpVisitor as OpVisitor, RaiseStandardError as RaiseStandardError, Register as Register, Return as Return, SetAttr as SetAttr, SetMem as SetMem, Truncate as Truncate, TupleGet as TupleGet, TupleSet as TupleSet, Unborrow as Unborrow, Unbox as Unbox, Unreachable as Unreachable, Value as Value
from mypyc.ir.pprint import format_func as format_func
from mypyc.ir.rtypes import RArray as RArray, RInstance as RInstance, RPrimitive as RPrimitive, RType as RType, RUnion as RUnion, bytes_rprimitive as bytes_rprimitive, dict_rprimitive as dict_rprimitive, int_rprimitive as int_rprimitive, is_float_rprimitive as is_float_rprimitive, is_object_rprimitive as is_object_rprimitive, list_rprimitive as list_rprimitive, range_rprimitive as range_rprimitive, set_rprimitive as set_rprimitive, str_rprimitive as str_rprimitive, tuple_rprimitive as tuple_rprimitive

class FnError:
    source: Incomplete
    desc: Incomplete
    def __init__(self, source: Op | BasicBlock, desc: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...

def check_func_ir(fn: FuncIR) -> list[FnError]:
    """Applies validations to a given function ir and returns a list of errors found."""

class IrCheckException(Exception): ...

def assert_func_ir_valid(fn: FuncIR) -> None: ...
def check_op_sources_valid(fn: FuncIR) -> list[FnError]: ...

disjoint_types: Incomplete

def can_coerce_to(src: RType, dest: RType) -> bool:
    """Check if src can be assigned to dest_rtype.

    Currently okay to have false positives.
    """

class OpChecker(OpVisitor[None]):
    parent_fn: Incomplete
    errors: Incomplete
    def __init__(self, parent_fn: FuncIR) -> None: ...
    def fail(self, source: Op, desc: str) -> None: ...
    def check_control_op_targets(self, op: ControlOp) -> None: ...
    def check_type_coercion(self, op: Op, src: RType, dest: RType) -> None: ...
    def check_compatibility(self, op: Op, t: RType, s: RType) -> None: ...
    def expect_float(self, op: Op, v: Value) -> None: ...
    def expect_non_float(self, op: Op, v: Value) -> None: ...
    def visit_goto(self, op: Goto) -> None: ...
    def visit_branch(self, op: Branch) -> None: ...
    def visit_return(self, op: Return) -> None: ...
    def visit_unreachable(self, op: Unreachable) -> None: ...
    def visit_assign(self, op: Assign) -> None: ...
    def visit_assign_multi(self, op: AssignMulti) -> None: ...
    def visit_load_error_value(self, op: LoadErrorValue) -> None: ...
    def check_tuple_items_valid_literals(self, op: LoadLiteral, t: tuple[object, ...]) -> None: ...
    def check_frozenset_items_valid_literals(self, op: LoadLiteral, s: frozenset[object]) -> None: ...
    def visit_load_literal(self, op: LoadLiteral) -> None: ...
    def visit_get_attr(self, op: GetAttr) -> None: ...
    def visit_set_attr(self, op: SetAttr) -> None: ...
    def visit_load_static(self, op: LoadStatic) -> None: ...
    def visit_init_static(self, op: InitStatic) -> None: ...
    def visit_tuple_get(self, op: TupleGet) -> None: ...
    def visit_tuple_set(self, op: TupleSet) -> None: ...
    def visit_inc_ref(self, op: IncRef) -> None: ...
    def visit_dec_ref(self, op: DecRef) -> None: ...
    def visit_call(self, op: Call) -> None: ...
    def visit_method_call(self, op: MethodCall) -> None: ...
    def visit_cast(self, op: Cast) -> None: ...
    def visit_box(self, op: Box) -> None: ...
    def visit_unbox(self, op: Unbox) -> None: ...
    def visit_raise_standard_error(self, op: RaiseStandardError) -> None: ...
    def visit_call_c(self, op: CallC) -> None: ...
    def visit_truncate(self, op: Truncate) -> None: ...
    def visit_extend(self, op: Extend) -> None: ...
    def visit_load_global(self, op: LoadGlobal) -> None: ...
    def visit_int_op(self, op: IntOp) -> None: ...
    def visit_comparison_op(self, op: ComparisonOp) -> None: ...
    def visit_float_op(self, op: FloatOp) -> None: ...
    def visit_float_neg(self, op: FloatNeg) -> None: ...
    def visit_float_comparison_op(self, op: FloatComparisonOp) -> None: ...
    def visit_load_mem(self, op: LoadMem) -> None: ...
    def visit_set_mem(self, op: SetMem) -> None: ...
    def visit_get_element_ptr(self, op: GetElementPtr) -> None: ...
    def visit_load_address(self, op: LoadAddress) -> None: ...
    def visit_keep_alive(self, op: KeepAlive) -> None: ...
    def visit_unborrow(self, op: Unborrow) -> None: ...
