from _typeshed import Incomplete
from typing import Literal as Literal

__all__ = ['asunicode', 'asstr', 'asbytes', 'Literal', 'lmap', 'lzip', 'lrange', 'lfilter', 'with_metaclass']

asunicode: Incomplete

def asbytes(s): ...
def asstr(s): ...
def lrange(*args, **kwargs): ...
def lzip(*args, **kwargs): ...
def lmap(*args, **kwargs): ...
def lfilter(*args, **kwargs): ...
def with_metaclass(meta, *bases):
    """Create a base class with a metaclass."""
