from jax._src import clusters as clusters, xla_bridge as xla_bridge
from jax._src.cloud_tpu_init import running_in_cloud_tpu_vm as running_in_cloud_tpu_vm

def get_metadata(key): ...

class TpuCluster(clusters.ClusterEnv):
    @classmethod
    def is_env_present(cls) -> bool: ...
    @classmethod
    def get_coordinator_address(cls) -> str: ...
    @classmethod
    def get_process_count(cls) -> int: ...
    @classmethod
    def get_process_id(cls) -> int: ...
    @classmethod
    def get_local_process_id(cls) -> int | None: ...
