import abc
from torch import Tensor as Tensor
from torch.distributed.rpc import rpc_async as rpc_async
from torch.testing import FileCheck as FileCheck
from torch.testing._internal.dist_utils import dist_init as dist_init, worker_name as worker_name
from torch.testing._internal.distributed.rpc.rpc_agent_test_fixture import RpcAgentTestFixture as RpcAgentTestFixture

def local_add(t1, t2): ...
def remote_add(t1, t2, dst: str): ...
def fork_add(t1, t2, dst: str): ...

class JitDistAutogradTest(RpcAgentTestFixture, metaclass=abc.ABCMeta):
    def test_get_gradients(self): ...
    def test_dist_backward(self) -> None: ...
    def test_jit_fork_within_context(self) -> None: ...
    def test_restore_context_after_swtich_to_jit_thread(self): ...
