def build_intlist(data): ...
def build_tensorlist(data): ...
def build_doublelist(data): ...
def build_boollist(data): ...
def build_tensor_from_id(data): ...
def restore_type_tag(value, type_str): ...
