from _typeshed import Incomplete

class EnabledProxy:
    """Stores whether the JIT is enabled or not.

    This is just a wrapper for a bool, so that we get reference semantics
    """
    enabled: Incomplete
    def __init__(self) -> None: ...
    def parse_env(self, name, default, true_message, false_message): ...
    def __bool__(self) -> bool: ...

def disable() -> None: ...
def enable() -> None: ...
