from .A import A as A
from .Abbr import Abbr as Abbr
from .Acronym import Acronym as Acronym
from .Address import Address as Address
from .Area import Area as Area
from .Article import Article as Article
from .Aside import Aside as Aside
from .Audio import Audio as Audio
from .B import B as B
from .Base import Base as Base
from .Basefont import Basefont as Basefont
from .Bdi import Bdi as Bdi
from .Bdo import Bdo as Bdo
from .Big import Big as Big
from .Blink import Blink as Blink
from .Blockquote import Blockquote as Blockquote
from .Br import Br as Br
from .Button import Button as Button
from .Canvas import Canvas as Canvas
from .Caption import Caption as Caption
from .Center import Center as Center
from .Cite import Cite as Cite
from .Code import Code as Code
from .Col import Col as Col
from .Colgroup import Colgroup as Colgroup
from .Content import Content as Content
from .Data import Data as Data
from .Datalist import Datalist as Datalist
from .Dd import Dd as Dd
from .Del import Del as Del
from .Details import Details as Details
from .Dfn import Dfn as Dfn
from .Dialog import Dialog as Dialog
from .Div import Div as Div
from .Dl import Dl as Dl
from .Dt import Dt as Dt
from .Em import Em as Em
from .Embed import Embed as Embed
from .Fieldset import Fieldset as Fieldset
from .Figcaption import Figcaption as Figcaption
from .Figure import Figure as Figure
from .Font import Font as Font
from .Footer import Footer as Footer
from .Form import Form as Form
from .Frame import Frame as Frame
from .Frameset import Frameset as Frameset
from .H1 import H1 as H1
from .H2 import H2 as H2
from .H3 import H3 as H3
from .H4 import H4 as H4
from .H5 import H5 as H5
from .H6 import H6 as H6
from .Header import Header as Header
from .Hgroup import Hgroup as Hgroup
from .Hr import Hr as Hr
from .I import I as I
from .Iframe import Iframe as Iframe
from .Img import Img as Img
from .Ins import Ins as Ins
from .Kbd import Kbd as Kbd
from .Keygen import Keygen as Keygen
from .Label import Label as Label
from .Legend import Legend as Legend
from .Li import Li as Li
from .Link import Link as Link
from .Main import Main as Main
from .MapEl import MapEl as MapEl
from .Mark import Mark as Mark
from .Marquee import Marquee as Marquee
from .Meta import Meta as Meta
from .Meter import Meter as Meter
from .Nav import Nav as Nav
from .Nobr import Nobr as Nobr
from .Noscript import Noscript as Noscript
from .ObjectEl import ObjectEl as ObjectEl
from .Ol import Ol as Ol
from .Optgroup import Optgroup as Optgroup
from .Option import Option as Option
from .Output import Output as Output
from .P import P as P
from .Param import Param as Param
from .Picture import Picture as Picture
from .Plaintext import Plaintext as Plaintext
from .Pre import Pre as Pre
from .Progress import Progress as Progress
from .Q import Q as Q
from .Rb import Rb as Rb
from .Rp import Rp as Rp
from .Rt import Rt as Rt
from .Rtc import Rtc as Rtc
from .Ruby import Ruby as Ruby
from .S import S as S
from .Samp import Samp as Samp
from .Script import Script as Script
from .Section import Section as Section
from .Select import Select as Select
from .Shadow import Shadow as Shadow
from .Slot import Slot as Slot
from .Small import Small as Small
from .Source import Source as Source
from .Spacer import Spacer as Spacer
from .Span import Span as Span
from .Strike import Strike as Strike
from .Strong import Strong as Strong
from .Sub import Sub as Sub
from .Summary import Summary as Summary
from .Sup import Sup as Sup
from .Table import Table as Table
from .Tbody import Tbody as Tbody
from .Td import Td as Td
from .Template import Template as Template
from .Textarea import Textarea as Textarea
from .Tfoot import Tfoot as Tfoot
from .Th import Th as Th
from .Thead import Thead as Thead
from .Time import Time as Time
from .Title import Title as Title
from .Tr import Tr as Tr
from .Track import Track as Track
from .U import U as U
from .Ul import Ul as Ul
from .Var import Var as Var
from .Video import Video as Video
from .Wbr import Wbr as Wbr
from .Xmp import Xmp as Xmp

__all__ = ['A', 'Abbr', 'Acronym', 'Address', 'Area', 'Article', 'Aside', 'Audio', 'B', 'Base', 'Basefont', 'Bdi', 'Bdo', 'Big', 'Blink', 'Blockquote', 'Br', 'Button', 'Canvas', 'Caption', 'Center', 'Cite', 'Code', 'Col', 'Colgroup', 'Content', 'Data', 'Datalist', 'Dd', 'Del', 'Details', 'Dfn', 'Dialog', 'Div', 'Dl', 'Dt', 'Em', 'Embed', 'Fieldset', 'Figcaption', 'Figure', 'Font', 'Footer', 'Form', 'Frame', 'Frameset', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'Header', 'Hgroup', 'Hr', 'I', 'Iframe', 'Img', 'Ins', 'Kbd', 'Keygen', 'Label', 'Legend', 'Li', 'Link', 'Main', 'MapEl', 'Mark', 'Marquee', 'Meta', 'Meter', 'Nav', 'Nobr', 'Noscript', 'ObjectEl', 'Ol', 'Optgroup', 'Option', 'Output', 'P', 'Param', 'Picture', 'Plaintext', 'Pre', 'Progress', 'Q', 'Rb', 'Rp', 'Rt', 'Rtc', 'Ruby', 'S', 'Samp', 'Script', 'Section', 'Select', 'Shadow', 'Slot', 'Small', 'Source', 'Spacer', 'Span', 'Strike', 'Strong', 'Sub', 'Summary', 'Sup', 'Table', 'Tbody', 'Td', 'Template', 'Textarea', 'Tfoot', 'Th', 'Thead', 'Time', 'Title', 'Tr', 'Track', 'U', 'Ul', 'Var', 'Video', 'Wbr', 'Xmp']
