from _typeshed import Incomplete
from absl.testing import parameterized
from tensorflow.python.eager import backprop as backprop, context as context
from tensorflow.python.framework import config as config, constant_op as constant_op, dtypes as dtypes, errors_impl as errors_impl, test_util as test_util
from tensorflow.python.ops import array_ops as array_ops, gen_image_ops as gen_image_ops, gradient_checker_v2 as gradient_checker_v2, image_ops as image_ops, math_ops as math_ops
from tensorflow.python.platform import test as test

class ResizeNearestNeighborOpTestBase(test.TestCase):
    TYPES: Incomplete
    def testShapeIsCorrectAfterOp(self) -> None: ...
    def testGradFromResizeToLargerInBothDims(self): ...
    def testGradFromResizeToSmallerInBothDims(self): ...
    def testCompareGpuVsCpu(self): ...

class ResizeBilinearOpTestBase(test.TestCase, parameterized.TestCase):
    def testGradients(self, batch_size, channel_count) -> None: ...
    def testTypes(self) -> None: ...
    def testGradOnUnsupportedType(self, use_tape) -> None: ...
    def testCompareGpuVsCpu(self, batch_size, channel_count) -> None: ...
    def testCompareGpuVsCpuFloat64(self) -> None: ...

class ResizeBicubicOpTestBase(test.TestCase, parameterized.TestCase):
    """Tests resize bicubic ops."""
    def testShapeIsCorrectAfterOp(self) -> None: ...
    def testGradFromResizeToLargerInBothDims(self): ...
    def testGradFromResizeToSmallerInBothDims(self): ...
    def testGradOnUnsupportedType(self, use_tape) -> None: ...

class ScaleAndTranslateOpTestBase(test.TestCase):
    """Tests scale and translate op."""
    def testGrads(self): ...
    def testIdentityGrads(self) -> None:
        """Tests that Gradients for 1.0 scale should be ones for some kernels."""

class CropAndResizeOpTestBase(test.TestCase):
    def testShapeIsCorrectAfterOp(self) -> None: ...
    def testGradRandomBoxes(self):
        """Test that the gradient is correct for randomly generated boxes.

    The mapping is piecewise differentiable with respect to the box coordinates.
    The points where the function is not differentiable are those which are
    mapped to image pixels, i.e., the normalized y coordinates in
    np.linspace(0, 1, image_height) and normalized x coordinates in
    np.linspace(0, 1, image_width). Make sure that the box coordinates are
    sufficiently far away from those rectangular grid centers that are points of
    discontinuity, so that the finite difference Jacobian is close to the
    computed one.
    """

class RGBToHSVOpTestBase(test.TestCase):
    TYPES: Incomplete
    def testShapeIsCorrectAfterOp(self) -> None: ...
    def testRGBToHSVGradSimpleCase(self): ...
    def testRGBToHSVGradRandomCase(self): ...
    def testRGBToHSVGradSpecialCaseRGreatest(self): ...
