import unittest
from _typeshed import Incomplete

class StrSubclass(str):
    def __getitem__(self, index): ...

class BytesSubclass(bytes):
    def __getitem__(self, index): ...

class RegexTests(unittest.TestCase):
    PATTERN_CLASS: str
    FLAGS_WITH_COMPILED_PAT: str
    INVALID_GROUP_REF: str
    MISSING_GT: str
    BAD_GROUP_NAME: str
    MISSING_GROUP_NAME: str
    MISSING_LT: str
    UNKNOWN_GROUP_I: str
    UNKNOWN_GROUP: str
    BAD_ESCAPE: str
    BAD_OCTAL_ESCAPE: str
    BAD_SET: str
    STR_PAT_ON_BYTES: str
    BYTES_PAT_ON_STR: str
    STR_PAT_BYTES_TEMPL: str
    BYTES_PAT_STR_TEMPL: str
    BYTES_PAT_UNI_FLAG: str
    MIXED_FLAGS: str
    MISSING_RPAREN: str
    TRAILING_CHARS: str
    BAD_CHAR_RANGE: str
    NOTHING_TO_REPEAT: str
    MULTIPLE_REPEAT: str
    OPEN_GROUP: str
    DUPLICATE_GROUP: str
    CANT_TURN_OFF: str
    UNDEF_CHAR_NAME: str
    def assertTypedEqual(self, actual, expect, msg: Incomplete | None = None) -> None: ...
    def test_weakref(self) -> None: ...
    def test_search_star_plus(self) -> None: ...
    def bump_num(self, matchobj): ...
    def test_basic_regex_sub(self): ...
    def test_bug_449964(self) -> None: ...
    def test_bug_449000(self) -> None: ...
    def test_bug_1661(self): ...
    def test_bug_3629(self) -> None: ...
    def test_sub_template_numeric_escape(self): ...
    def test_qualified_re_sub(self) -> None: ...
    def test_bug_114660(self) -> None: ...
    def test_bug_462270(self) -> None: ...
    def test_bug_14462(self) -> None: ...
    def test_symbolic_refs(self): ...
    def test_re_subn(self) -> None: ...
    def test_re_split(self) -> None: ...
    def test_qualified_re_split(self) -> None: ...
    def test_re_findall(self) -> None: ...
    def test_bug_117612(self) -> None: ...
    def test_re_match(self) -> None: ...
    def test_re_groupref_exists(self) -> None: ...
    def test_re_groupref(self) -> None: ...
    def test_groupdict(self) -> None: ...
    def test_expand(self) -> None: ...
    def test_repeat_minmax(self) -> None: ...
    def test_getattr(self) -> None: ...
    def test_special_escapes(self) -> None: ...
    def test_bigcharset(self) -> None: ...
    def test_anyall(self) -> None: ...
    def test_non_consuming(self) -> None: ...
    def test_ignore_case(self) -> None: ...
    def test_case_folding(self) -> None: ...
    def test_category(self) -> None: ...
    def test_not_literal(self) -> None: ...
    def test_search_coverage(self) -> None: ...
    def test_re_escape(self) -> None: ...
    def test_re_escape_byte(self) -> None: ...
    def test_constants(self) -> None: ...
    def test_flags(self) -> None: ...
    def test_sre_character_literals(self): ...
    def test_sre_character_class_literals(self): ...
    def test_bug_113254(self) -> None: ...
    def test_bug_527371(self) -> None: ...
    def test_bug_545855(self): ...
    def test_bug_418626(self) -> None: ...
    def test_bug_612074(self) -> None: ...
    def test_stack_overflow(self) -> None: ...
    def test_scanner(self): ...
    def test_bug_448951(self) -> None: ...
    def test_bug_725106(self) -> None: ...
    def test_bug_725149(self) -> None: ...
    def test_bug_764548(self) -> None: ...
    def test_finditer(self) -> None: ...
    def test_bug_926075(self) -> None: ...
    def test_bug_931848(self) -> None: ...
    def test_bug_581080(self): ...
    def test_bug_817234(self): ...
    def test_empty_array(self) -> None: ...
    def test_inline_flags(self) -> None: ...
    def test_dollar_matches_twice(self) -> None: ...
    def test_bytes_str_mixing(self): ...
    def test_ascii_and_unicode_flag(self): ...
    def test_subscripting_match(self) -> None: ...
    def test_new_named_groups(self) -> None: ...
    def test_properties(self) -> None: ...
    def test_word_class(self) -> None: ...
    def test_search_anchor(self) -> None: ...
    def test_search_reverse(self) -> None: ...
    def test_atomic(self) -> None: ...
    def test_possessive(self) -> None: ...
    def test_zerowidth(self) -> None: ...
    def test_scoped_and_inline_flags(self): ...
    def test_repeated_repeats(self) -> None: ...
    def test_lookbehind(self) -> None: ...
    def test_unmatched_in_sub(self) -> None: ...
    def test_bug_10328(self): ...
    def test_overlapped(self) -> None: ...
    def test_splititer(self) -> None: ...
    def test_grapheme(self) -> None: ...
    def test_word_boundary(self) -> None: ...
    def test_line_boundary(self) -> None: ...
    def test_branch_reset(self) -> None: ...
    def test_set(self) -> None: ...
    def test_various(self) -> None: ...
    def test_replacement(self): ...
    def test_common_prefix(self) -> None: ...
    def test_captures(self) -> None: ...
    def test_guards(self) -> None: ...
    def test_turkic(self) -> None: ...
    def test_named_lists(self) -> None: ...
    def test_fuzzy(self) -> None: ...
    def test_recursive(self) -> None: ...
    def test_copy(self) -> None: ...
    def test_format(self) -> None: ...
    def test_fullmatch(self) -> None: ...
    def test_issue_18468(self) -> None: ...
    def test_partial(self) -> None: ...
    def test_hg_bugs(self): ...
    def test_fuzzy_ext(self) -> None: ...
    def test_subscripted_captures(self) -> None: ...
    def test_more_zerowidth(self) -> None: ...

def test_main() -> None: ...
