import hypothesis.strategies as st
import pydantic.types
from _typeshed import Incomplete
from pydantic.utils import lenient_issubclass as lenient_issubclass
from typing import Callable, Dict

def is_valid_email(s: str) -> bool: ...
def add_luhn_digit(card_number: str) -> str: ...

card_patterns: Incomplete
RESOLVERS: Dict[type, Callable[[type], st.SearchStrategy]]

def resolves(typ: type | pydantic.types.ConstrainedNumberMeta) -> Callable[[Callable[..., st.SearchStrategy]], Callable[..., st.SearchStrategy]]: ...
def resolve_json(cls): ...
def resolve_conbytes(cls): ...
def resolve_condecimal(cls): ...
def resolve_confloat(cls): ...
def resolve_conint(cls): ...
def resolve_condate(cls): ...
def resolve_constr(cls): ...
