from .core import Array as Array, RETURN_BYTES as RETURN_BYTES
from .core.format import Format as Format
from .core.imopen import imopen as imopen
from .typing import ArrayLike as ArrayLike, ImageResource as ImageResource
from _typeshed import Incomplete
from typing import Dict, List, Literal, overload

MEMTEST_DEFAULT_MIM: str
MEMTEST_DEFAULT_MVOL: str

def to_nbytes(arg: float = None, default: Incomplete | None = None) -> float: ...
def help(name: Incomplete | None = None) -> None: ...
def decypher_format_arg(format_name: str | None) -> Dict[str, str]: ...
def get_reader(uri: ImageResource, format: Format = None, mode: str = '?', **kwargs) -> Format.Reader: ...
def get_writer(uri: ImageResource, format: Format = None, mode: str = '?', **kwargs) -> Format.Writer: ...
def imread(uri: ImageResource, format: Format = None, **kwargs) -> Array: ...
@overload
def imwrite(uri: Literal['<bytes>'], im: ArrayLike, format: Format = None, **kwargs) -> bytes: ...
@overload
def imwrite(uri: ImageResource, im: ArrayLike, format: Format = None, **kwargs) -> None: ...
def mimread(uri: ImageResource, format: Format = None, memtest=..., **kwargs) -> List[Array]: ...
@overload
def mimwrite(uri: Literal['<bytes>'], ims: List[ArrayLike], format: Format = None, **kwargs) -> bytes: ...
@overload
def mimwrite(uri: ImageResource, ims: List[ArrayLike], format: Format = None, **kwargs) -> None: ...
def volread(uri: ImageResource, format: Format = None, **kwargs) -> Array: ...
@overload
def volwrite(uri: Literal['<bytes>'], im: ArrayLike, format: Format = None, **kwargs) -> bytes: ...
@overload
def volwrite(uri: ImageResource, im: ArrayLike, format: Format = None, **kwargs) -> None: ...
def mvolread(uri: ImageResource, format: Format = None, memtest: float = ..., **kwargs) -> List[Array]: ...
@overload
def mvolwrite(uri: Literal['<bytes>'], ims: List[ArrayLike], format: Format = None, **kwargs) -> bytes: ...
@overload
def mvolwrite(uri: ImageResource, ims: List[ArrayLike], format: Format = None, **kwargs) -> None: ...
read = get_reader
save = get_writer
imsave = imwrite
mimsave = mimwrite
volsave = volwrite
mvolsave = mvolwrite
