from _typeshed import Incomplete

DESCRIPTOR: Incomplete
DataType: Incomplete
DatasetType: Incomplete
Status: Incomplete
SortOrder: Incomplete
AggregationType: Incomplete
DATA_TYPE_UNSET: int
DATA_TYPE_STRING: int
DATA_TYPE_BOOL: int
DATA_TYPE_FLOAT64: int
DATASET_UNKNOWN: int
DATASET_TRAINING: int
DATASET_VALIDATION: int
STATUS_UNKNOWN: int
STATUS_SUCCESS: int
STATUS_FAILURE: int
STATUS_RUNNING: int
ORDER_UNSPECIFIED: int
ORDER_ASC: int
ORDER_DESC: int
AGGREGATION_UNSET: int
AGGREGATION_AVG: int
AGGREGATION_MEDIAN: int
AGGREGATION_MIN: int
AGGREGATION_MAX: int
Experiment: Incomplete
HParamInfo: Incomplete
Interval: Incomplete
MetricName: Incomplete
MetricInfo: Incomplete
SessionGroup: Incomplete
MetricValue: Incomplete
Session: Incomplete
GetExperimentRequest: Incomplete
ListSessionGroupsRequest: Incomplete
ColParams: Incomplete
ListSessionGroupsResponse: Incomplete
ListMetricEvalsRequest: Incomplete
