from wandb import env as env, trigger as trigger
from wandb.errors import Error as Error
from wandb.sdk.lib.exit_hooks import ExitHooks as ExitHooks
from wandb.sdk.lib.import_hooks import unregister_all_post_import_hooks as unregister_all_post_import_hooks
from wandb.sdk.service import service as service
from wandb.sdk.service.service_base import ServiceInterface as ServiceInterface
from wandb.sdk.wandb_settings import Settings as Settings

class ManagerConnectionError(Error):
    """Raised when service process is not running."""
class ManagerConnectionRefusedError(ManagerConnectionError):
    """Raised when service process is not running."""

class _ManagerToken:
    def __init__(self, token: str) -> None: ...
    @classmethod
    def from_environment(cls) -> _ManagerToken | None: ...
    @classmethod
    def from_params(cls, transport: str, host: str, port: int) -> _ManagerToken: ...
    def set_environment(self) -> None: ...
    def reset_environment(self) -> None: ...
    @property
    def token(self) -> str: ...
    @property
    def pid(self) -> int: ...
    @property
    def transport(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...

class _Manager:
    def __init__(self, settings: Settings) -> None: ...
