from _typeshed import Incomplete
from numba import typeof as typeof
from numba.core import serialize as serialize, types as types
from numba.np.numpy_support import ufunc_find_matching_loop as ufunc_find_matching_loop
from numba.np.ufunc.sigparse import parse_signature as parse_signature
from numba.np.ufunc.ufuncbuilder import GUFuncBuilder as GUFuncBuilder

class GUFunc(serialize.ReduceMixin):
    """
    Dynamic generalized universal function (GUFunc)
    intended to act like a normal Numpy gufunc, but capable
    of call-time (just-in-time) compilation of fast loops
    specialized to inputs.
    """
    ufunc: Incomplete
    gufunc_builder: Incomplete
    def __init__(self, py_func, signature, identity: Incomplete | None = None, cache: Incomplete | None = None, is_dynamic: bool = False, targetoptions={}, writable_args=()) -> None: ...
    def add(self, fty) -> None: ...
    def build_ufunc(self): ...
    def disable_compile(self) -> None:
        """
        Disable the compilation of new signatures at call time.
        """
    @property
    def is_dynamic(self): ...
    @property
    def nin(self): ...
    @property
    def nout(self): ...
    @property
    def nargs(self): ...
    @property
    def ntypes(self): ...
    @property
    def types(self): ...
    @property
    def identity(self): ...
    @property
    def signature(self): ...
    @property
    def accumulate(self): ...
    @property
    def at(self): ...
    @property
    def outer(self): ...
    @property
    def reduce(self): ...
    @property
    def reduceat(self): ...
    def __call__(self, *args, **kwargs): ...
