from _typeshed import Incomplete
from pyasn1.type import univ
from pyasn1_modules import rfc5280 as rfc5280, rfc5652 as rfc5652

MAX: Incomplete
ContentType = rfc5652.ContentType
IssuerAndSerialNumber = rfc5652.IssuerAndSerialNumber
SubjectKeyIdentifier = rfc5652.SubjectKeyIdentifier
PolicyInformation = rfc5280.PolicyInformation
GeneralNames = rfc5280.GeneralNames
CertificateSerialNumber = rfc5280.CertificateSerialNumber
id_aa_signingCertificate: Incomplete

class Hash(univ.OctetString): ...
class IssuerSerial(univ.Sequence): ...
class ESSCertID(univ.Sequence): ...
class SigningCertificate(univ.Sequence): ...

id_aa_mlExpandHistory: Incomplete
ub_ml_expansion_history: Incomplete

class EntityIdentifier(univ.Choice): ...
class MLReceiptPolicy(univ.Choice): ...
class MLData(univ.Sequence): ...
class MLExpansionHistory(univ.SequenceOf): ...

id_aa_securityLabel: Incomplete
ub_privacy_mark_length: Incomplete
ub_security_categories: Incomplete
ub_integer_options: Incomplete

class ESSPrivacyMark(univ.Choice): ...
class SecurityClassification(univ.Integer): ...
class SecurityPolicyIdentifier(univ.ObjectIdentifier): ...
class SecurityCategory(univ.Sequence): ...
class SecurityCategories(univ.SetOf): ...
class ESSSecurityLabel(univ.Set): ...

id_aa_equivalentLabels: Incomplete

class EquivalentLabels(univ.SequenceOf): ...

id_aa_contentIdentifier: Incomplete

class ContentIdentifier(univ.OctetString): ...

id_aa_contentReference: Incomplete

class ContentReference(univ.Sequence): ...

id_aa_msgSigDigest: Incomplete

class MsgSigDigest(univ.OctetString): ...

id_aa_contentHint: Incomplete

class ContentHints(univ.Sequence): ...
class AllOrFirstTier(univ.Integer): ...
class ReceiptsFrom(univ.Choice): ...

id_aa_receiptRequest: Incomplete
ub_receiptsTo: Incomplete

class ReceiptRequest(univ.Sequence): ...
class ESSVersion(univ.Integer): ...

id_ct_receipt: Incomplete

class Receipt(univ.Sequence): ...
