from _typeshed import Incomplete
from pyasn1.type import univ
from pyasn1_modules import rfc5280 as rfc5280

id_pe_ipAddrBlocks: Incomplete

class IPAddress(univ.BitString): ...
class IPAddressRange(univ.Sequence): ...
class IPAddressOrRange(univ.Choice): ...
class IPAddressChoice(univ.Choice): ...
class IPAddressFamily(univ.Sequence): ...
class IPAddrBlocks(univ.SequenceOf): ...

id_pe_autonomousSysIds: Incomplete

class ASId(univ.Integer): ...
class ASRange(univ.Sequence): ...
class ASIdOrRange(univ.Choice): ...
class ASIdentifierChoice(univ.Choice): ...
class ASIdentifiers(univ.Sequence): ...
