from _typeshed import Incomplete
from pyasn1.type import univ
from pyasn1_modules import rfc4210 as rfc4210, rfc5280 as rfc5280, rfc5652 as rfc5652

Extensions = rfc5280.Extensions
AlgorithmIdentifier = rfc5280.AlgorithmIdentifier
GeneralName = rfc5280.GeneralName
ContentInfo = rfc5652.ContentInfo
PKIFreeText = rfc4210.PKIFreeText
id_ct_TSTInfo: Incomplete

class Accuracy(univ.Sequence): ...
class MessageImprint(univ.Sequence): ...
class PKIFailureInfo(univ.BitString): ...
class PKIStatus(univ.Integer): ...
class PKIStatusInfo(univ.Sequence): ...
class TSAPolicyId(univ.ObjectIdentifier): ...
class TSTInfo(univ.Sequence): ...
class TimeStampReq(univ.Sequence): ...
class TimeStampToken(ContentInfo): ...
class TimeStampResp(univ.Sequence): ...
