from _typeshed import Incomplete
from pyasn1.type import univ
from pyasn1_modules import rfc5280 as rfc5280, rfc6170 as rfc6170

MAX: Incomplete

class HashAlgAndValue(univ.Sequence): ...
class LogotypeDetails(univ.Sequence): ...
class LogotypeAudioInfo(univ.Sequence): ...
class LogotypeAudio(univ.Sequence): ...
class LogotypeImageType(univ.Integer): ...
class LogotypeImageResolution(univ.Choice): ...
class LogotypeImageInfo(univ.Sequence): ...
class LogotypeImage(univ.Sequence): ...
class LogotypeData(univ.Sequence): ...
class LogotypeReference(univ.Sequence): ...
class LogotypeInfo(univ.Choice): ...

id_logo_background: Incomplete
id_logo_loyalty: Incomplete
id_logo_certImage: Incomplete

class OtherLogotypeInfo(univ.Sequence): ...

id_pe_logotype: Incomplete

class LogotypeExtn(univ.Sequence): ...
