from _typeshed import Incomplete
from pyasn1.type import univ
from pyasn1_modules import rfc3280 as rfc3280

MAX: Incomplete

class ObjectDigestInfo(univ.Sequence): ...
class IssuerSerial(univ.Sequence): ...
class TargetCert(univ.Sequence): ...
class Target(univ.Choice): ...
class Targets(univ.SequenceOf): ...
class ProxyInfo(univ.SequenceOf): ...

id_at_role: Incomplete
id_pe_aaControls: Incomplete
id_ce_targetInformation: Incomplete
id_pe_ac_auditIdentity: Incomplete

class ClassList(univ.BitString): ...
class SecurityCategory(univ.Sequence): ...
class Clearance(univ.Sequence): ...
class AttCertVersion(univ.Integer): ...

id_aca: Incomplete
id_at_clearance: Incomplete

class AttrSpec(univ.SequenceOf): ...
class AAControls(univ.Sequence): ...
class AttCertValidityPeriod(univ.Sequence): ...

id_aca_authenticationInfo: Incomplete

class V2Form(univ.Sequence): ...
class AttCertIssuer(univ.Choice): ...
class Holder(univ.Sequence): ...
class AttributeCertificateInfo(univ.Sequence): ...
class AttributeCertificate(univ.Sequence): ...

id_mod: Incomplete
id_mod_attribute_cert: Incomplete
id_aca_accessIdentity: Incomplete

class RoleSyntax(univ.Sequence): ...

id_aca_chargingIdentity: Incomplete

class ACClearAttrs(univ.Sequence): ...

id_aca_group: Incomplete
id_pe_ac_proxying: Incomplete

class SvceAuthInfo(univ.Sequence): ...
class IetfAttrSyntax(univ.Sequence): ...

id_aca_encAttrs: Incomplete
