from _typeshed import Incomplete
from pyasn1.type import char as char, univ, useful as useful
from pyasn1_modules import rfc5280 as rfc5280, rfc5652 as rfc5652

MAX: Incomplete

class HardwareSerialEntry(univ.Choice): ...
class HardwareModules(univ.Sequence): ...
class CommunityIdentifier(univ.Choice): ...
class PreferredPackageIdentifier(univ.Sequence): ...
class PreferredOrLegacyPackageIdentifier(univ.Choice): ...
class CurrentFWConfig(univ.Sequence): ...
class PreferredOrLegacyStalePackageIdentifier(univ.Choice): ...
class FirmwarePackageLoadErrorCode(univ.Enumerated): ...
class VendorLoadErrorCode(univ.Integer): ...

id_aa_wrappedFirmwareKey: Incomplete

class WrappedFirmwareKey(rfc5652.EnvelopedData): ...

id_aa_firmwarePackageInfo: Incomplete

class FirmwarePackageInfo(univ.Sequence): ...

id_aa_communityIdentifiers: Incomplete

class CommunityIdentifiers(univ.SequenceOf): ...

id_aa_implCompressAlgs: Incomplete

class ImplementedCompressAlgorithms(univ.SequenceOf): ...

id_aa_implCryptoAlgs: Incomplete

class ImplementedCryptoAlgorithms(univ.SequenceOf): ...

id_aa_decryptKeyID: Incomplete

class DecryptKeyIdentifier(univ.OctetString): ...

id_aa_targetHardwareIDs: Incomplete

class TargetHardwareIdentifiers(univ.SequenceOf): ...

id_aa_firmwarePackageID: Incomplete

class FirmwarePackageIdentifier(univ.Sequence): ...

id_aa_fwPkgMessageDigest: Incomplete

class FirmwarePackageMessageDigest(univ.Sequence): ...
class FWErrorVersion(univ.Integer): ...

id_ct_firmwareLoadError: Incomplete

class FirmwarePackageLoadError(univ.Sequence): ...
class FWReceiptVersion(univ.Integer): ...

id_ct_firmwareLoadReceipt: Incomplete

class FirmwarePackageLoadReceipt(univ.Sequence): ...

id_ct_firmwarePackage: Incomplete

class FirmwarePkgData(univ.OctetString): ...

id_on_hardwareModuleName: Incomplete

class HardwareModuleName(univ.Sequence): ...
