from _typeshed import Incomplete
from pyasn1.type import char, univ, useful

MAX: Incomplete
ub_e163_4_sub_address_length: Incomplete
ub_e163_4_number_length: Incomplete
unformatted_postal_address: Incomplete

class TerminalType(univ.Integer): ...
class Extension(univ.Sequence): ...
class Extensions(univ.SequenceOf): ...

physical_delivery_personal_name: Incomplete
ub_unformatted_address_length: Incomplete
ub_pds_parameter_length: Incomplete
ub_pds_physical_address_lines: Incomplete

class UnformattedPostalAddress(univ.Set): ...

ub_organization_name: Incomplete

class X520OrganizationName(univ.Choice): ...

ub_x121_address_length: Incomplete
pds_name: Incomplete
id_pkix: Incomplete
id_kp: Incomplete
ub_postal_code_length: Incomplete

class PostalCode(univ.Choice): ...

ub_generation_qualifier_length: Incomplete
unique_postal_name: Incomplete

class DomainComponent(char.IA5String): ...

ub_domain_defined_attribute_value_length: Incomplete
ub_match: Incomplete
id_at: Incomplete

class AttributeType(univ.ObjectIdentifier): ...

id_at_organizationalUnitName: Incomplete
terminal_type: Incomplete

class PDSParameter(univ.Set): ...
class PhysicalDeliveryPersonalName(PDSParameter): ...

ub_surname_length: Incomplete
id_ad: Incomplete
ub_domain_defined_attribute_type_length: Incomplete

class TeletexDomainDefinedAttribute(univ.Sequence): ...

ub_domain_defined_attributes: Incomplete

class TeletexDomainDefinedAttributes(univ.SequenceOf): ...

extended_network_address: Incomplete
ub_locality_name: Incomplete

class X520LocalityName(univ.Choice): ...

teletex_organization_name: Incomplete
ub_given_name_length: Incomplete
ub_initials_length: Incomplete

class PersonalName(univ.Set): ...

ub_organizational_unit_name_length: Incomplete

class OrganizationalUnitName(char.PrintableString): ...

id_at_generationQualifier: Incomplete

class Version(univ.Integer): ...
class CertificateSerialNumber(univ.Integer): ...

algorithmIdentifierMap: Incomplete

class AlgorithmIdentifier(univ.Sequence):
    componentType: Incomplete

class Time(univ.Choice): ...
class AttributeValue(univ.Any): ...

certificateAttributesMap: Incomplete

class AttributeTypeAndValue(univ.Sequence):
    componentType: Incomplete

class RelativeDistinguishedName(univ.SetOf): ...
class RDNSequence(univ.SequenceOf): ...
class Name(univ.Choice): ...
class TBSCertList(univ.Sequence): ...
class CertificateList(univ.Sequence): ...
class PhysicalDeliveryOfficeName(PDSParameter): ...

ub_extension_attributes: Incomplete
certificateExtensionsMap: Incomplete
oraddressExtensionAttributeMap: Incomplete

class ExtensionAttribute(univ.Sequence):
    componentType: Incomplete

id_qt: Incomplete
id_qt_cps: Incomplete
id_at_stateOrProvinceName: Incomplete
id_at_title: Incomplete
id_at_serialNumber: Incomplete

class X520dnQualifier(char.PrintableString): ...
class PosteRestanteAddress(PDSParameter): ...

poste_restante_address: Incomplete

class UniqueIdentifier(univ.BitString): ...
class Validity(univ.Sequence): ...
class SubjectPublicKeyInfo(univ.Sequence): ...
class TBSCertificate(univ.Sequence): ...

physical_delivery_office_name: Incomplete
ub_name: Incomplete

class X520name(univ.Choice): ...

id_at_dnQualifier: Incomplete
ub_serial_number: Incomplete
ub_pseudonym: Incomplete
pkcs_9: Incomplete

class X121Address(char.NumericString): ...
class NetworkAddress(X121Address): ...

ub_integer_options: Incomplete
id_at_commonName: Incomplete
ub_organization_name_length: Incomplete
id_ad_ocsp: Incomplete
ub_country_name_numeric_length: Incomplete
ub_country_name_alpha_length: Incomplete

class PhysicalDeliveryCountryName(univ.Choice): ...

id_emailAddress: Incomplete
common_name: Incomplete

class X520Pseudonym(univ.Choice): ...

ub_domain_name_length: Incomplete

class AdministrationDomainName(univ.Choice): ...
class PresentationAddress(univ.Sequence): ...
class ExtendedNetworkAddress(univ.Choice): ...
class TeletexOrganizationName(char.TeletexString): ...

ub_terminal_id_length: Incomplete

class TerminalIdentifier(char.PrintableString): ...

id_ad_caIssuers: Incomplete
id_at_countryName: Incomplete

class StreetAddress(PDSParameter): ...

postal_code: Incomplete
id_at_givenName: Incomplete
ub_title: Incomplete

class ExtensionAttributes(univ.SetOf): ...

ub_emailaddress_length: Incomplete
id_ad_caRepository: Incomplete

class ExtensionORAddressComponents(PDSParameter): ...

ub_organizational_unit_name: Incomplete

class X520OrganizationalUnitName(univ.Choice): ...
class LocalPostalAttributes(PDSParameter): ...

teletex_organizational_unit_names: Incomplete

class X520Title(univ.Choice): ...

id_at_localityName: Incomplete
id_at_initials: Incomplete
ub_state_name: Incomplete

class X520StateOrProvinceName(univ.Choice): ...

physical_delivery_organization_name: Incomplete
id_at_surname: Incomplete

class X520countryName(char.PrintableString): ...

physical_delivery_office_number: Incomplete
id_qt_unotice: Incomplete

class X520SerialNumber(char.PrintableString): ...

class Attribute(univ.Sequence):
    componentType: Incomplete

ub_common_name: Incomplete
id_pe: Incomplete

class ExtensionPhysicalDeliveryAddressComponents(PDSParameter): ...
class EmailAddress(char.IA5String): ...

id_at_organizationName: Incomplete
post_office_box_address: Incomplete

class BuiltInDomainDefinedAttribute(univ.Sequence): ...
class BuiltInDomainDefinedAttributes(univ.SequenceOf): ...

id_at_pseudonym: Incomplete
id_domainComponent: Incomplete

class X520CommonName(univ.Choice): ...

extension_OR_address_components: Incomplete
ub_organizational_units: Incomplete
teletex_personal_name: Incomplete
ub_numeric_user_id_length: Incomplete
ub_common_name_length: Incomplete

class TeletexCommonName(char.TeletexString): ...
class PhysicalDeliveryOrganizationName(PDSParameter): ...

extension_physical_delivery_address_components: Incomplete

class NumericUserIdentifier(char.NumericString): ...
class CountryName(univ.Choice): ...
class OrganizationName(char.PrintableString): ...
class OrganizationalUnitNames(univ.SequenceOf): ...
class PrivateDomainName(univ.Choice): ...
class BuiltInStandardAttributes(univ.Sequence): ...
class ORAddress(univ.Sequence): ...
class DistinguishedName(RDNSequence): ...

id_ad_timeStamping: Incomplete

class PhysicalDeliveryOfficeNumber(PDSParameter): ...

teletex_domain_defined_attributes: Incomplete

class UniquePostalName(PDSParameter): ...

physical_delivery_country_name: Incomplete
ub_pds_name_length: Incomplete

class PDSName(char.PrintableString): ...
class TeletexPersonalName(univ.Set): ...

street_address: Incomplete

class PostOfficeBoxAddress(PDSParameter): ...

local_postal_attributes: Incomplete

class DirectoryString(univ.Choice): ...

teletex_common_name: Incomplete

class CommonName(char.PrintableString): ...
class Certificate(univ.Sequence): ...
class TeletexOrganizationalUnitName(char.TeletexString): ...

id_at_name: Incomplete

class TeletexOrganizationalUnitNames(univ.SequenceOf): ...

id_ce: Incomplete
id_ce_issuerAltName: Incomplete

class SkipCerts(univ.Integer): ...
class CRLReason(univ.Enumerated): ...
class PrivateKeyUsagePeriod(univ.Sequence): ...

anotherNameMap: Incomplete

class AnotherName(univ.Sequence):
    componentType: Incomplete

class EDIPartyName(univ.Sequence): ...
class GeneralName(univ.Choice): ...
class BaseDistance(univ.Integer): ...
class GeneralSubtree(univ.Sequence): ...
class GeneralNames(univ.SequenceOf): ...
class DistributionPointName(univ.Choice): ...
class ReasonFlags(univ.BitString): ...
class IssuingDistributionPoint(univ.Sequence): ...

id_ce_certificatePolicies: Incomplete
id_kp_emailProtection: Incomplete

class AccessDescription(univ.Sequence): ...
class IssuerAltName(GeneralNames): ...

id_ce_cRLDistributionPoints: Incomplete
holdInstruction: Incomplete
id_holdinstruction_callissuer: Incomplete
id_ce_subjectDirectoryAttributes: Incomplete
id_ce_issuingDistributionPoint: Incomplete

class DistributionPoint(univ.Sequence): ...
class CRLDistributionPoints(univ.SequenceOf): ...
class GeneralSubtrees(univ.SequenceOf): ...
class NameConstraints(univ.Sequence): ...
class SubjectDirectoryAttributes(univ.SequenceOf): ...

id_kp_OCSPSigning: Incomplete
id_kp_timeStamping: Incomplete

class DisplayText(univ.Choice): ...
class NoticeReference(univ.Sequence): ...
class UserNotice(univ.Sequence): ...
class PolicyQualifierId(univ.ObjectIdentifier): ...

policyQualifierInfoMap: Incomplete

class PolicyQualifierInfo(univ.Sequence):
    componentType: Incomplete

class CertPolicyId(univ.ObjectIdentifier): ...
class PolicyInformation(univ.Sequence): ...
class CertificatePolicies(univ.SequenceOf): ...
class SubjectAltName(GeneralNames): ...

id_ce_basicConstraints: Incomplete
id_ce_authorityKeyIdentifier: Incomplete
id_kp_codeSigning: Incomplete

class BasicConstraints(univ.Sequence): ...

id_ce_certificateIssuer: Incomplete

class PolicyMappings(univ.SequenceOf): ...
class InhibitAnyPolicy(SkipCerts): ...

anyPolicy: Incomplete

class CRLNumber(univ.Integer): ...
class BaseCRLNumber(CRLNumber): ...

id_ce_nameConstraints: Incomplete
id_kp_serverAuth: Incomplete
id_ce_freshestCRL: Incomplete
id_ce_cRLReasons: Incomplete
id_ce_extKeyUsage: Incomplete

class KeyIdentifier(univ.OctetString): ...
class AuthorityKeyIdentifier(univ.Sequence): ...
class FreshestCRL(CRLDistributionPoints): ...

id_ce_policyConstraints: Incomplete
id_pe_authorityInfoAccess: Incomplete

class AuthorityInfoAccessSyntax(univ.SequenceOf): ...

id_holdinstruction_none: Incomplete

class CPSuri(char.IA5String): ...

id_pe_subjectInfoAccess: Incomplete

class SubjectKeyIdentifier(KeyIdentifier): ...

id_ce_subjectAltName: Incomplete

class KeyPurposeId(univ.ObjectIdentifier): ...
class ExtKeyUsageSyntax(univ.SequenceOf): ...
class HoldInstructionCode(univ.ObjectIdentifier): ...

id_ce_deltaCRLIndicator: Incomplete
id_ce_keyUsage: Incomplete
id_ce_holdInstructionCode: Incomplete

class SubjectInfoAccessSyntax(univ.SequenceOf): ...
class InvalidityDate(useful.GeneralizedTime): ...
class KeyUsage(univ.BitString): ...

id_ce_invalidityDate: Incomplete
id_ce_policyMappings: Incomplete
anyExtendedKeyUsage: Incomplete
id_ce_privateKeyUsagePeriod: Incomplete
id_ce_cRLNumber: Incomplete

class CertificateIssuer(GeneralNames): ...

id_holdinstruction_reject: Incomplete

class PolicyConstraints(univ.Sequence): ...

id_kp_clientAuth: Incomplete
id_ce_subjectKeyIdentifier: Incomplete
id_ce_inhibitAnyPolicy: Incomplete
