from _typeshed import Incomplete
from pyasn1.type import univ
from pyasn1_modules import rfc4211 as rfc4211, rfc5280 as rfc5280, rfc5652 as rfc5652

MAX: Incomplete
cmcControlAttributesMap: Incomplete

class ChangeSubjectName(univ.Sequence): ...
class AttributeValue(univ.Any): ...
class CMCStatus(univ.Integer): ...
class PendInfo(univ.Sequence): ...

bodyIdMax: Incomplete

class BodyPartID(univ.Integer): ...
class BodyPartPath(univ.SequenceOf): ...
class BodyPartReference(univ.Choice): ...
class CMCFailInfo(univ.Integer): ...
class CMCStatusInfoV2(univ.Sequence): ...
class GetCRL(univ.Sequence): ...

id_pkix: Incomplete
id_cmc: Incomplete
id_cmc_batchResponses: Incomplete
id_cmc_popLinkWitness: Incomplete

class PopLinkWitnessV2(univ.Sequence): ...

id_cmc_popLinkWitnessV2: Incomplete
id_cmc_identityProofV2: Incomplete
id_cmc_revokeRequest: Incomplete
id_cmc_recipientNonce: Incomplete

class ControlsProcessed(univ.Sequence): ...
class CertificationRequest(univ.Sequence): ...
class TaggedCertificationRequest(univ.Sequence): ...
class TaggedRequest(univ.Choice): ...

id_cmc_popLinkRandom: Incomplete
id_cmc_statusInfo: Incomplete
id_cmc_trustedAnchors: Incomplete
id_cmc_transactionId: Incomplete
id_cmc_encryptedPOP: Incomplete

class PublishTrustAnchors(univ.Sequence): ...
class RevokeRequest(univ.Sequence): ...

id_cmc_senderNonce: Incomplete
id_cmc_authData: Incomplete

class TaggedContentInfo(univ.Sequence): ...
class IdentifyProofV2(univ.Sequence): ...
class CMCPublicationInfo(univ.Sequence): ...

id_kp_cmcCA: Incomplete
id_cmc_confirmCertAcceptance: Incomplete
id_cmc_raIdentityWitness: Incomplete
id_ExtensionReq: Incomplete
id_cct: Incomplete
id_cct_PKIData: Incomplete
id_kp_cmcRA: Incomplete

class CMCStatusInfo(univ.Sequence): ...
class DecryptedPOP(univ.Sequence): ...

id_cmc_addExtensions: Incomplete
id_cmc_modCertTemplate: Incomplete

class TaggedAttribute(univ.Sequence): ...
class OtherMsg(univ.Sequence): ...
class PKIData(univ.Sequence): ...
class BodyPartList(univ.SequenceOf): ...

id_cmc_responseBody: Incomplete

class AuthPublish(BodyPartID): ...
class CMCUnsignedData(univ.Sequence): ...
class CMCCertId(rfc5652.IssuerAndSerialNumber): ...
class PKIResponse(univ.Sequence): ...
class ResponseBody(PKIResponse): ...

id_cmc_statusInfoV2: Incomplete
id_cmc_lraPOPWitness: Incomplete

class ModCertTemplate(univ.Sequence): ...

id_cmc_regInfo: Incomplete
id_cmc_identityProof: Incomplete

class ExtensionReq(univ.SequenceOf): ...

id_kp_cmcArchive: Incomplete
id_cmc_publishCert: Incomplete
id_cmc_dataReturn: Incomplete

class LraPopWitness(univ.Sequence): ...

id_aa: Incomplete
id_aa_cmc_unsignedData: Incomplete
id_cmc_getCert: Incomplete
id_cmc_batchRequests: Incomplete
id_cmc_decryptedPOP: Incomplete
id_cmc_responseInfo: Incomplete
id_cmc_changeSubjectName: Incomplete

class GetCert(univ.Sequence): ...

id_cmc_identification: Incomplete
id_cmc_queryPending: Incomplete

class AddExtensions(univ.Sequence): ...
class EncryptedPOP(univ.Sequence): ...

id_cmc_getCRL: Incomplete
id_cct_PKIResponse: Incomplete
id_cmc_controlProcessed: Incomplete

class NoSignatureValue(univ.OctetString): ...

id_ad_cmc: Incomplete
id_alg_noSignature: Incomplete
