from _typeshed import Incomplete
from pyasn1.type import univ

id_mmhs_CDT: Incomplete

class AlgorithmID_ShortForm(univ.Integer): ...
class ContentType_ShortForm(univ.Integer): ...
class CompressedContentInfo(univ.Sequence): ...
class CompressionAlgorithmIdentifier(univ.Choice): ...
class CompressedData(univ.Sequence): ...
