from pathlib import Path
from typing import List, MutableMapping

Env = MutableMapping | None
CONFIG_PATHS: str
SWEEP_PARAM_PATH: str
SHOW_RUN: str
DEBUG: str
SILENT: str
QUIET: str
INITED: str
DIR: str
DESCRIPTION: str
NAME: str
NOTEBOOK_NAME: str
NOTES: str
USERNAME: str
USER_EMAIL: str
PROJECT: str
ENTITY: str
BASE_URL: str
APP_URL: str
PROGRAM: str
ARGS: str
MODE: str
START_METHOD: str
RESUME: str
RUN_ID: str
RUN_STORAGE_ID: str
RUN_GROUP: str
RUN_DIR: str
SWEEP_ID: str
HTTP_TIMEOUT: str
FILE_PUSHER_TIMEOUT: str
API_KEY: str
JOB_TYPE: str
DISABLE_CODE: str
DISABLE_GIT: str
GIT_ROOT: str
SAVE_CODE: str
TAGS: str
IGNORE: str
ERROR_REPORTING: str
DOCKER: str
AGENT_REPORT_INTERVAL: str
AGENT_KILL_DELAY: str
AGENT_DISABLE_FLAPPING: str
AGENT_MAX_INITIAL_FAILURES: str
CRASH_NOSYNC_TIME: str
MAGIC: str
HOST: str
ANONYMOUS: str
JUPYTER: str
CONFIG_DIR: str
DATA_DIR: str
ARTIFACT_DIR: str
ARTIFACT_FETCH_FILE_URL_BATCH_SIZE: str
CACHE_DIR: str
DISABLE_SSL: str
SERVICE: str
SENTRY_DSN: str
INIT_TIMEOUT: str
GIT_COMMIT: str
GIT_REMOTE_URL: str
USE_V1_ARTIFACTS: str

def immutable_keys() -> List[str]:
    """These are env keys that shouldn't change within a single process.

    We use this to maintain certain values between multiple calls to wandb.init within a single process.
    """
def is_debug(default: str | None = None, env: Env | None = None) -> bool: ...
def error_reporting_enabled() -> bool: ...
def ssl_disabled() -> bool: ...
def get_error_reporting(default: bool | str = True, env: Env | None = None) -> bool | str: ...
def get_run(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_args(default: List[str] | None = None, env: Env | None = None) -> List[str] | None: ...
def get_docker(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_http_timeout(default: int = 20, env: Env | None = None) -> int: ...
def get_file_pusher_timeout(default: int | None = None, env: Env | None = None) -> int | None: ...
def get_ignore(default: List[str] | None = None, env: Env | None = None) -> List[str] | None: ...
def get_project(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_username(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_user_email(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_entity(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_base_url(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_app_url(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_show_run(default: str | None = None, env: Env | None = None) -> bool: ...
def get_description(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_tags(default: str = '', env: Env | None = None) -> List[str]: ...
def get_dir(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_config_paths(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_agent_report_interval(default: str | None = None, env: Env | None = None) -> int | None: ...
def get_agent_kill_delay(default: str | None = None, env: Env | None = None) -> int | None: ...
def get_crash_nosync_time(default: str | None = None, env: Env | None = None) -> int | None: ...
def get_magic(default: str | None = None, env: Env | None = None) -> str | None: ...
def get_data_dir(env: Env | None = None) -> str: ...
def get_artifact_dir(env: Env | None = None) -> str: ...
def get_artifact_fetch_file_url_batch_size(env: Env | None = None) -> int: ...
def get_cache_dir(env: Env | None = None) -> Path: ...
def get_use_v1_artifacts(env: Env | None = None) -> bool: ...
def get_agent_max_initial_failures(default: int | None = None, env: Env | None = None) -> int | None: ...
def set_entity(value: str, env: Env | None = None) -> None: ...
def set_project(value: str, env: Env | None = None) -> None: ...
def should_save_code() -> bool: ...
def disable_git(env: Env | None = None) -> bool: ...
