from typing import Any, Callable

def reset() -> None: ...
def register(event: str, func: Callable): ...
def call(event_str: str, *args: Any, **kwargs: Any): ...
def unregister(event: str, func: Callable): ...
