from typing import Any, Dict, Tuple
from wandb.data_types import Table as Table
from wandb.errors import Error as Error

class Visualize:
    def __init__(self, id: str, data: Table) -> None: ...
    def get_config_value(self, key: str) -> Dict[str, Any]: ...
    @staticmethod
    def get_config_key(key: str) -> Tuple[str, str, str]: ...
    @property
    def value(self) -> Table: ...

class CustomChart:
    def __init__(self, id: str, data: Table, fields: Dict[str, Any], string_fields: Dict[str, Any]) -> None: ...
    def get_config_value(self, panel_type: str, query: Dict[str, Any]) -> Dict[str, Any]: ...
    @staticmethod
    def get_config_key(key: str) -> Tuple[str, str, str]: ...
    @staticmethod
    def user_query(table_key: str) -> Dict[str, Any]: ...
    @property
    def table(self) -> Table: ...
    @property
    def fields(self) -> Dict[str, Any]: ...
    @property
    def string_fields(self) -> Dict[str, Any]: ...

def custom_chart(vega_spec_name: str, data_table: Table, fields: Dict[str, Any], string_fields: Dict[str, Any] | None = None) -> CustomChart: ...
def visualize(id: str, value: Table) -> Visualize: ...
