from _typeshed import Incomplete
from typing import Callable, List
from wandb import env as env
from wandb.apis import InternalApi as InternalApi
from wandb.sdk import wandb_sweep as wandb_sweep
from wandb.sdk.launch.sweeps.utils import handle_sweep_config_violations as handle_sweep_config_violations, sweep_config_err_text_from_jsonschema_violations as sweep_config_err_text_from_jsonschema_violations
from wandb.util import get_module as get_module

sweeps: Incomplete
SWEEP_INITIAL_RUN_STATE: Incomplete

class ControllerError(Exception):
    """Base class for sweep errors."""

class _WandbController:
    """Sweep controller class.

    Internal datastructures on the sweep object to coordinate local controller with
    cloud controller.

    Data structures:
        controller: {
            schedule: [
                { id: SCHEDULE_ID
                  data: {param1: val1, param2: val2}},
            ]
            earlystop: [RUN_ID, ...]
        scheduler:
            scheduled: [
                { id: SCHEDULE_ID
                  runid: RUN_ID},
            ]

    `controller` is only updated by the client
    `scheduler` is only updated by the cloud backend

    Protocols:
        Scheduling a run:
        - client controller adds a schedule entry on the controller.schedule list
        - cloud backend notices the new entry and creates a run with the parameters
        - cloud backend adds a scheduled entry on the scheduler.scheduled list
        - client controller notices that the run has been scheduled and removes it from
          controller.schedule list

    Current implementation details:
        - Runs are only schedule if there are no other runs scheduled.

    """
    def __init__(self, sweep_id_or_config: Incomplete | None = None, entity: Incomplete | None = None, project: Incomplete | None = None) -> None: ...
    def configure_search(self, search: str | Callable[[dict | sweeps.SweepConfig, List[sweeps.SweepRun]], sweeps.SweepRun | None]): ...
    def configure_stopping(self, stopping: str | Callable[[dict | sweeps.SweepConfig, List[sweeps.SweepRun]], List[sweeps.SweepRun]], **kwargs): ...
    def configure_metric(self, metric, goal: Incomplete | None = None) -> None: ...
    def configure_program(self, program) -> None: ...
    def configure_name(self, name) -> None: ...
    def configure_description(self, description) -> None: ...
    def configure_parameter(self, name, values: Incomplete | None = None, value: Incomplete | None = None, distribution: Incomplete | None = None, min: Incomplete | None = None, max: Incomplete | None = None, mu: Incomplete | None = None, sigma: Incomplete | None = None, q: Incomplete | None = None, a: Incomplete | None = None, b: Incomplete | None = None) -> None: ...
    def configure_controller(self, type) -> None:
        """Configure controller to local if type == 'local'."""
    def configure(self, sweep_dict_or_config) -> None: ...
    @property
    def sweep_config(self) -> dict | sweeps.SweepConfig: ...
    @property
    def sweep_id(self) -> str: ...
    def create(self, from_dict: bool = False) -> str: ...
    def run(self, verbose: bool = False, print_status: bool = True, print_actions: bool = False, print_debug: bool = False) -> None: ...
    def step(self) -> None: ...
    def done(self) -> bool: ...
    def search(self) -> sweeps.SweepRun | None: ...
    def stopping(self) -> List[sweeps.SweepRun]: ...
    def schedule(self, run: sweeps.SweepRun | None) -> None: ...
    def stop_runs(self, runs: List[sweeps.SweepRun]) -> None: ...
    def print_status(self) -> None: ...
    def print_actions(self) -> None: ...
    def print_debug(self) -> None: ...
    def print_space(self) -> None: ...
    def print_summary(self) -> None: ...
