from _typeshed import Incomplete

class NumbaArrayPrinter:
    val: Incomplete
    def __init__(self, val) -> None: ...
    def to_string(self): ...

class NumbaComplexPrinter:
    val: Incomplete
    def __init__(self, val) -> None: ...
    def to_string(self): ...

class NumbaTuplePrinter:
    val: Incomplete
    def __init__(self, val) -> None: ...
    def to_string(self): ...

class NumbaUniTuplePrinter:
    val: Incomplete
    def __init__(self, val) -> None: ...
    def to_string(self): ...

class NumbaUnicodeTypePrinter:
    val: Incomplete
    def __init__(self, val) -> None: ...
    def to_string(self): ...
