from numba import gdb as gdb, gdb_breakpoint as gdb_breakpoint, gdb_init as gdb_init
from numba.core import cgutils as cgutils, config as config, errors as errors, types as types, utils as utils
from numba.core.extending import intrinsic as intrinsic, overload as overload

def hook_gdb(*args): ...
def hook_gdb_init(*args): ...
def init_gdb_codegen(cgctx, builder, signature, args, const_args, do_break: bool = False) -> None: ...
def gen_gdb_impl(const_args, do_break): ...
def hook_gdb_breakpoint():
    """
    Adds the Numba break point into the source
    """
def gen_bp_impl(): ...
