from torch.jit._serialization import validate_map_location as validate_map_location

class LiteScriptModule:
    def __init__(self, cpp_module) -> None: ...
    def __call__(self, *input): ...
    def find_method(self, method_name): ...
    def forward(self, *input): ...
    def run_method(self, method_name, *input): ...
