from transformers import AutoFeatureExtractor as AutoFeatureExtractor, SwinConfig as SwinConfig, SwinForImageClassification as SwinForImageClassification

def get_swin_config(swin_name): ...
def rename_key(name): ...
def convert_state_dict(orig_state_dict, model): ...
def convert_swin_checkpoint(swin_name, pytorch_dump_folder_path) -> None: ...
