from _typeshed import Incomplete
from dataclasses import dataclass
from enum import IntEnum
from wandb.sdk.launch.errors import LaunchError as LaunchError

PREFIX_HTTPS: str
PREFIX_SSH: str
SUFFIX_GIT: str
GIT_COMMIT_REGEX: Incomplete

class ReferenceType(IntEnum):
    BRANCH: int
    COMMIT: int

@dataclass
class GitHubReference:
    username: str | None = ...
    password: str | None = ...
    host: str | None = ...
    organization: str | None = ...
    repo: str | None = ...
    view: str | None = ...
    path: str | None = ...
    default_branch: str | None = ...
    ref: str | None = ...
    ref_type: ReferenceType | None = ...
    commit_hash: str | None = ...
    directory: str | None = ...
    file: str | None = ...
    def update_ref(self, ref: str | None) -> None: ...
    @property
    def url_host(self) -> str: ...
    @property
    def url_organization(self) -> str: ...
    @property
    def url_repo(self) -> str: ...
    @property
    def repo_ssh(self) -> str: ...
    @property
    def url(self) -> str: ...
    @staticmethod
    def parse(uri: str) -> GitHubReference | None:
        """Attempt to parse a string as a GitHub URL."""
    def fetch(self, dst_dir: str) -> None:
        """Fetch the repo into dst_dir and refine githubref based on what we learn."""
    def __init__(self, username, password, host, organization, repo, view, path, default_branch, ref, ref_type, commit_hash, directory, file) -> None: ...
