from _typeshed import Incomplete
from dataclasses import dataclass
from enum import IntEnum

PREFIX_HTTP: str
PREFIX_HTTPS: str

class ReferenceType(IntEnum):
    RUN: int
    JOB: int

RESERVED_NON_ENTITIES: Incomplete
RESERVED_NON_PROJECTS: Incomplete
RESERVED_JOB_PATHS: Incomplete

@dataclass
class WandbReference:
    host: str | None = ...
    entity: str | None = ...
    project: str | None = ...
    path: str | None = ...
    ref_type: ReferenceType | None = ...
    run_id: str | None = ...
    job_name: str | None = ...
    job_alias: str = ...
    def is_bare(self) -> bool: ...
    def is_job(self) -> bool: ...
    def is_run(self) -> bool: ...
    def is_job_or_run(self) -> bool: ...
    def job_reference(self) -> str: ...
    def job_reference_scoped(self) -> str: ...
    def url_host(self) -> str: ...
    def url_entity(self) -> str: ...
    def url_project(self) -> str: ...
    @staticmethod
    def parse(uri: str) -> WandbReference | None:
        """Attempt to parse a string as a W&B URL."""
    @staticmethod
    def is_uri_job_or_run(uri: str) -> bool: ...
    def __init__(self, host, entity, project, path, ref_type, run_id, job_name, job_alias) -> None: ...
