from .errors import LaTeXParsingError as LaTeXParsingError
from _typeshed import Incomplete
from sympy.external import import_module as import_module
from sympy.physics.quantum.state import Bra as Bra, Ket as Ket
from sympy.printing.str import StrPrinter as StrPrinter

LaTeXParser: Incomplete
LaTeXLexer: Incomplete
MathErrorListener: Incomplete
ErrorListener: Incomplete

class MathErrorListener(ErrorListener.ErrorListener):
    src: Incomplete
    def __init__(self, src) -> None: ...
    def syntaxError(self, recog, symbol, line, col, msg, e) -> None: ...

def parse_latex(sympy): ...
def convert_relation(rel): ...
def convert_expr(expr): ...
def convert_add(add): ...
def convert_mp(mp): ...
def convert_unary(unary): ...
def convert_postfix_list(arr, i: int = 0): ...
def do_subs(expr, at): ...
def convert_postfix(postfix): ...
def convert_exp(exp): ...
def convert_comp(comp): ...
def convert_atom(atom): ...
def rule2text(ctx): ...
def convert_frac(frac): ...
def convert_binom(binom): ...
def convert_floor(floor): ...
def convert_ceil(ceil): ...
def convert_func(func): ...
def convert_func_arg(arg): ...
def handle_integral(func): ...
def handle_sum_or_prod(func, name): ...
def handle_limit(func): ...
def get_differential_var(d): ...
def get_differential_var_str(text): ...
