from _typeshed import Incomplete

PY2: Incomplete
string_types: Incomplete

def register_post_import_hook(hook, name) -> None: ...
def discover_post_import_hooks(group) -> None: ...
def notify_module_loaded(module) -> None: ...

class _ImportHookLoader:
    def load_module(self, fullname): ...

class _ImportHookChainedLoader:
    loader: Incomplete
    load_module: Incomplete
    create_module: Incomplete
    exec_module: Incomplete
    def __init__(self, loader) -> None: ...

class ImportHookFinder:
    in_progress: Incomplete
    def __init__(self) -> None: ...
    def find_module(self, fullname, path: Incomplete | None = None): ...
    def find_spec(self, fullname, path: Incomplete | None = None, target: Incomplete | None = None): ...

def when_imported(name): ...
