from _typeshed import Incomplete

class DrawTree:
    x: float
    y: Incomplete
    tree: Incomplete
    children: Incomplete
    parent: Incomplete
    thread: Incomplete
    mod: int
    ancestor: Incomplete
    change: int
    number: Incomplete
    def __init__(self, tree, parent: Incomplete | None = None, depth: int = 0, number: int = 1) -> None: ...
    def left(self): ...
    def right(self): ...
    def lbrother(self): ...
    def get_lmost_sibling(self): ...
    lmost_sibling: Incomplete
    def max_extents(self): ...

def buchheim(tree): ...
def third_walk(tree, n) -> None: ...
def first_walk(v, distance: float = 1.0): ...
def apportion(v, default_ancestor, distance): ...
def move_subtree(wl, wr, shift) -> None: ...
def execute_shifts(v) -> None: ...
def ancestor(vil, v, default_ancestor): ...
def second_walk(v, m: int = 0, depth: int = 0, min: Incomplete | None = None): ...

class Tree:
    label: Incomplete
    node_id: Incomplete
    children: Incomplete
    def __init__(self, label: str = '', node_id: int = -1, *children) -> None: ...
