from _typeshed import Incomplete

__all__ = ['Popen']

class Popen:
    method: str
    returncode: Incomplete
    finalizer: Incomplete
    def __init__(self, process_obj) -> None: ...
    def duplicate_for_child(self, fd): ...
    def poll(self, flag=...): ...
    def wait(self, timeout: Incomplete | None = None): ...
    def terminate(self) -> None: ...
    def kill(self) -> None: ...
    def close(self) -> None: ...
