import plotly.graph_objs as go
from ._core import make_figure as make_figure
from ._doc import make_docstring as make_docstring
from _typeshed import Incomplete

def scatter(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, color: Incomplete | None = None, symbol: Incomplete | None = None, size: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, text: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, error_x: Incomplete | None = None, error_x_minus: Incomplete | None = None, error_y: Incomplete | None = None, error_y_minus: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, orientation: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, opacity: Incomplete | None = None, size_max: Incomplete | None = None, marginal_x: Incomplete | None = None, marginal_y: Incomplete | None = None, trendline: Incomplete | None = None, trendline_options: Incomplete | None = None, trendline_color_override: Incomplete | None = None, trendline_scope: str = 'trace', log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, render_mode: str = 'auto', title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a scatter plot, each row of `data_frame` is represented by a symbol
    mark in 2D space.
    """
def density_contour(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, z: Incomplete | None = None, color: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, orientation: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, marginal_x: Incomplete | None = None, marginal_y: Incomplete | None = None, trendline: Incomplete | None = None, trendline_options: Incomplete | None = None, trendline_color_override: Incomplete | None = None, trendline_scope: str = 'trace', log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, histfunc: Incomplete | None = None, histnorm: Incomplete | None = None, nbinsx: Incomplete | None = None, nbinsy: Incomplete | None = None, text_auto: bool = False, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a density contour plot, rows of `data_frame` are grouped together
    into contour marks to visualize the 2D distribution of an aggregate
    function `histfunc` (e.g. the count or sum) of the value `z`.
    """
def density_heatmap(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, z: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, orientation: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, marginal_x: Incomplete | None = None, marginal_y: Incomplete | None = None, opacity: Incomplete | None = None, log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, histfunc: Incomplete | None = None, histnorm: Incomplete | None = None, nbinsx: Incomplete | None = None, nbinsy: Incomplete | None = None, text_auto: bool = False, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a density heatmap, rows of `data_frame` are grouped together into
    colored rectangular tiles to visualize the 2D distribution of an
    aggregate function `histfunc` (e.g. the count or sum) of the value `z`.
    """
def line(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, line_group: Incomplete | None = None, color: Incomplete | None = None, line_dash: Incomplete | None = None, symbol: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, text: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, error_x: Incomplete | None = None, error_x_minus: Incomplete | None = None, error_y: Incomplete | None = None, error_y_minus: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, orientation: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, line_dash_sequence: Incomplete | None = None, line_dash_map: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, markers: bool = False, log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, line_shape: Incomplete | None = None, render_mode: str = 'auto', title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a 2D line plot, each row of `data_frame` is represented as vertex of
    a polyline mark in 2D space.
    """
def area(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, line_group: Incomplete | None = None, color: Incomplete | None = None, pattern_shape: Incomplete | None = None, symbol: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, text: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, pattern_shape_sequence: Incomplete | None = None, pattern_shape_map: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, markers: bool = False, orientation: Incomplete | None = None, groupnorm: Incomplete | None = None, log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, line_shape: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a stacked area plot, each row of `data_frame` is represented as
    vertex of a polyline mark in 2D space. The area between successive
    polylines is filled.
    """
def bar(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, color: Incomplete | None = None, pattern_shape: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, text: Incomplete | None = None, base: Incomplete | None = None, error_x: Incomplete | None = None, error_x_minus: Incomplete | None = None, error_y: Incomplete | None = None, error_y_minus: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, pattern_shape_sequence: Incomplete | None = None, pattern_shape_map: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, opacity: Incomplete | None = None, orientation: Incomplete | None = None, barmode: str = 'relative', log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, text_auto: bool = False, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a bar plot, each row of `data_frame` is represented as a rectangular
    mark.
    """
def timeline(data_frame: Incomplete | None = None, x_start: Incomplete | None = None, x_end: Incomplete | None = None, y: Incomplete | None = None, color: Incomplete | None = None, pattern_shape: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, text: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, pattern_shape_sequence: Incomplete | None = None, pattern_shape_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, opacity: Incomplete | None = None, range_x: Incomplete | None = None, range_y: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a timeline plot, each row of `data_frame` is represented as a rectangular
    mark on an x axis of type `date`, spanning from `x_start` to `x_end`.
    """
def histogram(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, color: Incomplete | None = None, pattern_shape: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, pattern_shape_sequence: Incomplete | None = None, pattern_shape_map: Incomplete | None = None, marginal: Incomplete | None = None, opacity: Incomplete | None = None, orientation: Incomplete | None = None, barmode: str = 'relative', barnorm: Incomplete | None = None, histnorm: Incomplete | None = None, log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, histfunc: Incomplete | None = None, cumulative: Incomplete | None = None, nbins: Incomplete | None = None, text_auto: bool = False, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a histogram, rows of `data_frame` are grouped together into a
    rectangular mark to visualize the 1D distribution of an aggregate
    function `histfunc` (e.g. the count or sum) of the value `y` (or `x` if
    `orientation` is `'h'`).
    """
def ecdf(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, color: Incomplete | None = None, text: Incomplete | None = None, line_dash: Incomplete | None = None, symbol: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, markers: bool = False, lines: bool = True, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, line_dash_sequence: Incomplete | None = None, line_dash_map: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, marginal: Incomplete | None = None, opacity: Incomplete | None = None, orientation: Incomplete | None = None, ecdfnorm: str = 'probability', ecdfmode: str = 'standard', render_mode: str = 'auto', log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a Empirical Cumulative Distribution Function (ECDF) plot, rows of `data_frame`
    are sorted by the value `x` (or `y` if `orientation` is `'h'`) and their cumulative
    count (or the cumulative sum of `y` if supplied and `orientation` is `h`) is drawn
    as a line.
    """
def violin(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, color: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, orientation: Incomplete | None = None, violinmode: Incomplete | None = None, log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, points: Incomplete | None = None, box: bool = False, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a violin plot, rows of `data_frame` are grouped together into a
    curved mark to visualize their distribution.
    """
def box(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, color: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, orientation: Incomplete | None = None, boxmode: Incomplete | None = None, log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, points: Incomplete | None = None, notched: bool = False, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    '''
    In a box plot, rows of `data_frame` are grouped together into a
    box-and-whisker mark to visualize their distribution.

    Each box spans from quartile 1 (Q1) to quartile 3 (Q3). The second
    quartile (Q2) is marked by a line inside the box. By default, the
    whiskers correspond to the box\' edges +/- 1.5 times the interquartile
    range (IQR: Q3-Q1), see "points" for other options.
    '''
def strip(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, color: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, orientation: Incomplete | None = None, stripmode: Incomplete | None = None, log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a strip plot each row of `data_frame` is represented as a jittered
    mark within categories.
    """
def scatter_3d(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, z: Incomplete | None = None, color: Incomplete | None = None, symbol: Incomplete | None = None, size: Incomplete | None = None, text: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, error_x: Incomplete | None = None, error_x_minus: Incomplete | None = None, error_y: Incomplete | None = None, error_y_minus: Incomplete | None = None, error_z: Incomplete | None = None, error_z_minus: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, size_max: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, opacity: Incomplete | None = None, log_x: bool = False, log_y: bool = False, log_z: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, range_z: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a 3D scatter plot, each row of `data_frame` is represented by a
    symbol mark in 3D space.
    """
def line_3d(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, z: Incomplete | None = None, color: Incomplete | None = None, line_dash: Incomplete | None = None, text: Incomplete | None = None, line_group: Incomplete | None = None, symbol: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, error_x: Incomplete | None = None, error_x_minus: Incomplete | None = None, error_y: Incomplete | None = None, error_y_minus: Incomplete | None = None, error_z: Incomplete | None = None, error_z_minus: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, line_dash_sequence: Incomplete | None = None, line_dash_map: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, markers: bool = False, log_x: bool = False, log_y: bool = False, log_z: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, range_z: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a 3D line plot, each row of `data_frame` is represented as vertex of
    a polyline mark in 3D space.
    """
def scatter_ternary(data_frame: Incomplete | None = None, a: Incomplete | None = None, b: Incomplete | None = None, c: Incomplete | None = None, color: Incomplete | None = None, symbol: Incomplete | None = None, size: Incomplete | None = None, text: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, opacity: Incomplete | None = None, size_max: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a ternary scatter plot, each row of `data_frame` is represented by a
    symbol mark in ternary coordinates.
    """
def line_ternary(data_frame: Incomplete | None = None, a: Incomplete | None = None, b: Incomplete | None = None, c: Incomplete | None = None, color: Incomplete | None = None, line_dash: Incomplete | None = None, line_group: Incomplete | None = None, symbol: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, text: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, line_dash_sequence: Incomplete | None = None, line_dash_map: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, markers: bool = False, line_shape: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a ternary line plot, each row of `data_frame` is represented as
    vertex of a polyline mark in ternary coordinates.
    """
def scatter_polar(data_frame: Incomplete | None = None, r: Incomplete | None = None, theta: Incomplete | None = None, color: Incomplete | None = None, symbol: Incomplete | None = None, size: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, text: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, opacity: Incomplete | None = None, direction: str = 'clockwise', start_angle: int = 90, size_max: Incomplete | None = None, range_r: Incomplete | None = None, range_theta: Incomplete | None = None, log_r: bool = False, render_mode: str = 'auto', title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a polar scatter plot, each row of `data_frame` is represented by a
    symbol mark in polar coordinates.
    """
def line_polar(data_frame: Incomplete | None = None, r: Incomplete | None = None, theta: Incomplete | None = None, color: Incomplete | None = None, line_dash: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, line_group: Incomplete | None = None, text: Incomplete | None = None, symbol: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, line_dash_sequence: Incomplete | None = None, line_dash_map: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, markers: bool = False, direction: str = 'clockwise', start_angle: int = 90, line_close: bool = False, line_shape: Incomplete | None = None, render_mode: str = 'auto', range_r: Incomplete | None = None, range_theta: Incomplete | None = None, log_r: bool = False, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a polar line plot, each row of `data_frame` is represented as vertex
    of a polyline mark in polar coordinates.
    """
def bar_polar(data_frame: Incomplete | None = None, r: Incomplete | None = None, theta: Incomplete | None = None, color: Incomplete | None = None, pattern_shape: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, base: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, pattern_shape_sequence: Incomplete | None = None, pattern_shape_map: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, barnorm: Incomplete | None = None, barmode: str = 'relative', direction: str = 'clockwise', start_angle: int = 90, range_r: Incomplete | None = None, range_theta: Incomplete | None = None, log_r: bool = False, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a polar bar plot, each row of `data_frame` is represented as a wedge
    mark in polar coordinates.
    """
def choropleth(data_frame: Incomplete | None = None, lat: Incomplete | None = None, lon: Incomplete | None = None, locations: Incomplete | None = None, locationmode: Incomplete | None = None, geojson: Incomplete | None = None, featureidkey: Incomplete | None = None, color: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, projection: Incomplete | None = None, scope: Incomplete | None = None, center: Incomplete | None = None, fitbounds: Incomplete | None = None, basemap_visible: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a choropleth map, each row of `data_frame` is represented by a
    colored region mark on a map.
    """
def scatter_geo(data_frame: Incomplete | None = None, lat: Incomplete | None = None, lon: Incomplete | None = None, locations: Incomplete | None = None, locationmode: Incomplete | None = None, geojson: Incomplete | None = None, featureidkey: Incomplete | None = None, color: Incomplete | None = None, text: Incomplete | None = None, symbol: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, size: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, opacity: Incomplete | None = None, size_max: Incomplete | None = None, projection: Incomplete | None = None, scope: Incomplete | None = None, center: Incomplete | None = None, fitbounds: Incomplete | None = None, basemap_visible: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a geographic scatter plot, each row of `data_frame` is represented
    by a symbol mark on a map.
    """
def line_geo(data_frame: Incomplete | None = None, lat: Incomplete | None = None, lon: Incomplete | None = None, locations: Incomplete | None = None, locationmode: Incomplete | None = None, geojson: Incomplete | None = None, featureidkey: Incomplete | None = None, color: Incomplete | None = None, line_dash: Incomplete | None = None, text: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, line_group: Incomplete | None = None, symbol: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, line_dash_sequence: Incomplete | None = None, line_dash_map: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, markers: bool = False, projection: Incomplete | None = None, scope: Incomplete | None = None, center: Incomplete | None = None, fitbounds: Incomplete | None = None, basemap_visible: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a geographic line plot, each row of `data_frame` is represented as
    vertex of a polyline mark on a map.
    """
def scatter_mapbox(data_frame: Incomplete | None = None, lat: Incomplete | None = None, lon: Incomplete | None = None, color: Incomplete | None = None, text: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, size: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, opacity: Incomplete | None = None, size_max: Incomplete | None = None, zoom: int = 8, center: Incomplete | None = None, mapbox_style: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a Mapbox scatter plot, each row of `data_frame` is represented by a
    symbol mark on a Mapbox map.
    """
def choropleth_mapbox(data_frame: Incomplete | None = None, geojson: Incomplete | None = None, featureidkey: Incomplete | None = None, locations: Incomplete | None = None, color: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, opacity: Incomplete | None = None, zoom: int = 8, center: Incomplete | None = None, mapbox_style: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a Mapbox choropleth map, each row of `data_frame` is represented by a
    colored region on a Mapbox map.
    """
def density_mapbox(data_frame: Incomplete | None = None, lat: Incomplete | None = None, lon: Incomplete | None = None, z: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, opacity: Incomplete | None = None, zoom: int = 8, center: Incomplete | None = None, mapbox_style: Incomplete | None = None, radius: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a Mapbox density map, each row of `data_frame` contributes to the intensity of
    the color of the region around the corresponding point on the map
    """
def line_mapbox(data_frame: Incomplete | None = None, lat: Incomplete | None = None, lon: Incomplete | None = None, color: Incomplete | None = None, text: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, line_group: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, zoom: int = 8, center: Incomplete | None = None, mapbox_style: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a Mapbox line plot, each row of `data_frame` is represented as
    vertex of a polyline mark on a Mapbox map.
    """
def scatter_matrix(data_frame: Incomplete | None = None, dimensions: Incomplete | None = None, color: Incomplete | None = None, symbol: Incomplete | None = None, size: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, symbol_sequence: Incomplete | None = None, symbol_map: Incomplete | None = None, opacity: Incomplete | None = None, size_max: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a scatter plot matrix (or SPLOM), each row of `data_frame` is
    represented by a multiple symbol marks, one in each cell of a grid of
    2D scatter plots, which plot each pair of `dimensions` against each
    other.
    """
def parallel_coordinates(data_frame: Incomplete | None = None, dimensions: Incomplete | None = None, color: Incomplete | None = None, labels: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a parallel coordinates plot, each row of `data_frame` is represented
    by a polyline mark which traverses a set of parallel axes, one for each
    of the `dimensions`.
    """
def parallel_categories(data_frame: Incomplete | None = None, dimensions: Incomplete | None = None, color: Incomplete | None = None, labels: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None, dimensions_max_cardinality: int = 50) -> go.Figure:
    """
    In a parallel categories (or parallel sets) plot, each row of
    `data_frame` is grouped with other rows that share the same values of
    `dimensions` and then plotted as a polyline mark through a set of
    parallel axes, one for each of the `dimensions`.
    """
def pie(data_frame: Incomplete | None = None, names: Incomplete | None = None, values: Incomplete | None = None, color: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None, opacity: Incomplete | None = None, hole: Incomplete | None = None) -> go.Figure:
    """
    In a pie plot, each row of `data_frame` is represented as a sector of a
    pie.
    """
def sunburst(data_frame: Incomplete | None = None, names: Incomplete | None = None, values: Incomplete | None = None, parents: Incomplete | None = None, path: Incomplete | None = None, ids: Incomplete | None = None, color: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, labels: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None, branchvalues: Incomplete | None = None, maxdepth: Incomplete | None = None) -> go.Figure:
    """
    A sunburst plot represents hierarchial data as sectors laid out over
    several levels of concentric rings.
    """
def treemap(data_frame: Incomplete | None = None, names: Incomplete | None = None, values: Incomplete | None = None, parents: Incomplete | None = None, ids: Incomplete | None = None, path: Incomplete | None = None, color: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, labels: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None, branchvalues: Incomplete | None = None, maxdepth: Incomplete | None = None) -> go.Figure:
    """
    A treemap plot represents hierarchial data as nested rectangular
    sectors.
    """
def icicle(data_frame: Incomplete | None = None, names: Incomplete | None = None, values: Incomplete | None = None, parents: Incomplete | None = None, path: Incomplete | None = None, ids: Incomplete | None = None, color: Incomplete | None = None, color_continuous_scale: Incomplete | None = None, range_color: Incomplete | None = None, color_continuous_midpoint: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, labels: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None, branchvalues: Incomplete | None = None, maxdepth: Incomplete | None = None) -> go.Figure:
    """
    An icicle plot represents hierarchial data with adjoined rectangular
    sectors that all cascade from root down to leaf in one direction.
    """
def funnel(data_frame: Incomplete | None = None, x: Incomplete | None = None, y: Incomplete | None = None, color: Incomplete | None = None, facet_row: Incomplete | None = None, facet_col: Incomplete | None = None, facet_col_wrap: int = 0, facet_row_spacing: Incomplete | None = None, facet_col_spacing: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, text: Incomplete | None = None, animation_frame: Incomplete | None = None, animation_group: Incomplete | None = None, category_orders: Incomplete | None = None, labels: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, opacity: Incomplete | None = None, orientation: Incomplete | None = None, log_x: bool = False, log_y: bool = False, range_x: Incomplete | None = None, range_y: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None) -> go.Figure:
    """
    In a funnel plot, each row of `data_frame` is represented as a
    rectangular sector of a funnel.
    """
def funnel_area(data_frame: Incomplete | None = None, names: Incomplete | None = None, values: Incomplete | None = None, color: Incomplete | None = None, color_discrete_sequence: Incomplete | None = None, color_discrete_map: Incomplete | None = None, hover_name: Incomplete | None = None, hover_data: Incomplete | None = None, custom_data: Incomplete | None = None, labels: Incomplete | None = None, title: Incomplete | None = None, template: Incomplete | None = None, width: Incomplete | None = None, height: Incomplete | None = None, opacity: Incomplete | None = None) -> go.Figure:
    """
    In a funnel area plot, each row of `data_frame` is represented as a
    trapezoidal sector of a funnel.
    """
