from .. import fixtures as fixtures
from ... import ForeignKey as ForeignKey, Integer as Integer, String as String, select as select, testing as testing
from ..assertions import eq_ as eq_
from ..schema import Column as Column, Table as Table
from _typeshed import Incomplete

class CTETest(fixtures.TablesTest):
    __backend__: bool
    __requires__: Incomplete
    run_inserts: str
    run_deletes: str
    @classmethod
    def define_tables(cls, metadata) -> None: ...
    @classmethod
    def insert_data(cls, connection) -> None: ...
    def test_select_nonrecursive_round_trip(self, connection) -> None: ...
    def test_select_recursive_round_trip(self, connection) -> None: ...
    def test_insert_from_select_round_trip(self, connection) -> None: ...
    def test_update_from_round_trip(self, connection) -> None: ...
    def test_delete_from_round_trip(self, connection) -> None: ...
    def test_delete_scalar_subq_round_trip(self, connection) -> None: ...
