import collections.abc
from _typeshed import Incomplete

class OrderPreservingSet(collections.abc.MutableSet):
    """A set based on dict so that it preserves key insertion order."""
    def __init__(self, iterable: Incomplete | None = None) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, value) -> bool: ...
    def __iter__(self): ...
    def add(self, item) -> None: ...
    def discard(self, value) -> None: ...
    def clear(self) -> None: ...
    def __eq__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...
    def __and__(self, other): ...
    def __or__(self, other): ...
    def union(self, other): ...
