import typing
from _typeshed import Incomplete

class BaseLockException(Exception):
    LOCK_FAILED: int
    fh: Incomplete
    def __init__(self, *args: typing.Any, fh: typing.IO | None | int = None, **kwargs: typing.Any) -> None: ...

class LockException(BaseLockException): ...
class AlreadyLocked(LockException): ...
class FileToLarge(LockException): ...
