from .albania import AL as AL, ALB as ALB, Albania as Albania
from .algeria import Algeria as Algeria, DZ as DZ, DZA as DZA
from .american_samoa import AS as AS, ASM as ASM, AmericanSamoa as AmericanSamoa, HolidaysAS as HolidaysAS
from .andorra import AD as AD, AND as AND, Andorra as Andorra
from .angola import AGO as AGO, AO as AO, Angola as Angola
from .argentina import AR as AR, ARG as ARG, Argentina as Argentina
from .armenia import AM as AM, ARM as ARM, Armenia as Armenia
from .aruba import ABW as ABW, AW as AW, Aruba as Aruba
from .australia import AU as AU, AUS as AUS, Australia as Australia
from .austria import AT as AT, AUT as AUT, Austria as Austria
from .azerbaijan import AZ as AZ, AZE as AZE, Azerbaijan as Azerbaijan
from .bahrain import BAH as BAH, BH as BH, Bahrain as Bahrain
from .bangladesh import BD as BD, BGD as BGD, Bangladesh as Bangladesh
from .barbados import BB as BB, BRB as BRB, Barbados as Barbados
from .belarus import BLR as BLR, BY as BY, Belarus as Belarus
from .belgium import BE as BE, BEL as BEL, Belgium as Belgium
from .belize import BLZ as BLZ, BZ as BZ, Belize as Belize
from .bolivia import BO as BO, BOL as BOL, Bolivia as Bolivia
from .bosnia_and_herzegovina import BA as BA, BIH as BIH, BosniaAndHerzegovina as BosniaAndHerzegovina
from .botswana import BW as BW, BWA as BWA, Botswana as Botswana
from .brazil import BR as BR, BRA as BRA, Brazil as Brazil
from .brunei import BN as BN, BRN as BRN, Brunei as Brunei
from .bulgaria import BG as BG, BLG as BLG, Bulgaria as Bulgaria
from .burkina_faso import BF as BF, BFA as BFA, BurkinaFaso as BurkinaFaso
from .burundi import BDI as BDI, BI as BI, Burundi as Burundi
from .cambodia import Cambodia as Cambodia, KH as KH, KHM as KHM
from .cameroon import CM as CM, CMR as CMR, Cameroon as Cameroon
from .canada import CA as CA, CAN as CAN, Canada as Canada
from .chad import Chad as Chad, TCD as TCD, TD as TD
from .chile import CHL as CHL, CL as CL, Chile as Chile
from .china import CHN as CHN, CN as CN, China as China
from .colombia import CO as CO, COL as COL, Colombia as Colombia
from .costa_rica import CR as CR, CRI as CRI, CostaRica as CostaRica
from .croatia import Croatia as Croatia, HR as HR, HRV as HRV
from .cuba import CU as CU, CUB as CUB, Cuba as Cuba
from .curacao import CUW as CUW, CW as CW, Curacao as Curacao
from .cyprus import CY as CY, CYP as CYP, Cyprus as Cyprus
from .czechia import CZ as CZ, CZE as CZE, Czechia as Czechia
from .denmark import DK as DK, DNK as DNK, Denmark as Denmark
from .djibouti import DJ as DJ, DJI as DJI, Djibouti as Djibouti
from .dominican_republic import DO as DO, DOM as DOM, DominicanRepublic as DominicanRepublic
from .ecuador import EC as EC, ECU as ECU, Ecuador as Ecuador
from .egypt import EG as EG, EGY as EGY, Egypt as Egypt
from .el_salvador import ElSalvador as ElSalvador, SLV as SLV, SV as SV
from .estonia import EE as EE, EST as EST, Estonia as Estonia
from .eswatini import Eswatini as Eswatini, SZ as SZ, SZW as SZW, Swaziland as Swaziland
from .ethiopia import ET as ET, ETH as ETH, Ethiopia as Ethiopia
from .finland import FI as FI, FIN as FIN, Finland as Finland
from .france import FR as FR, FRA as FRA, France as France
from .gabon import GA as GA, GAB as GAB, Gabon as Gabon
from .georgia import GE as GE, GEO as GEO, Georgia as Georgia
from .germany import DE as DE, DEU as DEU, Germany as Germany
from .greece import GR as GR, GRC as GRC, Greece as Greece
from .guam import GU as GU, GUM as GUM, Guam as Guam, HolidaysGU as HolidaysGU
from .guatemala import GT as GT, GUA as GUA, Guatemala as Guatemala
from .honduras import HN as HN, HND as HND, Honduras as Honduras
from .hongkong import HK as HK, HKG as HKG, HongKong as HongKong
from .hungary import HU as HU, HUN as HUN, Hungary as Hungary
from .iceland import IS as IS, ISL as ISL, Iceland as Iceland
from .india import IN as IN, IND as IND, India as India
from .indonesia import ID as ID, IDN as IDN, Indonesia as Indonesia
from .iran import IR as IR, IRN as IRN, Iran as Iran
from .ireland import IE as IE, IRL as IRL, Ireland as Ireland
from .isle_of_man import IM as IM, IMN as IMN, IsleOfMan as IsleOfMan
from .israel import IL as IL, ISR as ISR, Israel as Israel
from .italy import IT as IT, ITA as ITA, Italy as Italy
from .jamaica import JAM as JAM, JM as JM, Jamaica as Jamaica
from .japan import JP as JP, JPN as JPN, Japan as Japan
from .kazakhstan import KAZ as KAZ, KZ as KZ, Kazakhstan as Kazakhstan
from .kenya import KE as KE, KEN as KEN, Kenya as Kenya
from .kyrgyzstan import KG as KG, KGZ as KGZ, Kyrgyzstan as Kyrgyzstan
from .laos import LA as LA, LAO as LAO, Laos as Laos
from .latvia import LV as LV, LVA as LVA, Latvia as Latvia
from .lesotho import LS as LS, LSO as LSO, Lesotho as Lesotho
from .liechtenstein import LI as LI, LIE as LIE, Liechtenstein as Liechtenstein
from .lithuania import LT as LT, LTU as LTU, Lithuania as Lithuania
from .luxembourg import LU as LU, LUX as LUX, Luxembourg as Luxembourg
from .madagascar import MDG as MDG, MG as MG, Madagascar as Madagascar
from .malawi import MW as MW, MWI as MWI, Malawi as Malawi
from .malaysia import MY as MY, MYS as MYS, Malaysia as Malaysia
from .maldives import MDV as MDV, MV as MV, Maldives as Maldives
from .malta import MLT as MLT, MT as MT, Malta as Malta
from .marshall_islands import HolidaysMH as HolidaysMH, MH as MH, MHL as MHL, MarshallIslands as MarshallIslands
from .mexico import MEX as MEX, MX as MX, Mexico as Mexico
from .moldova import MD as MD, MDA as MDA, Moldova as Moldova
from .monaco import MC as MC, MCO as MCO, Monaco as Monaco
from .montenegro import ME as ME, MNE as MNE, Montenegro as Montenegro
from .morocco import MA as MA, MOR as MOR, Morocco as Morocco
from .mozambique import MOZ as MOZ, MZ as MZ, Mozambique as Mozambique
from .namibia import NA as NA, NAM as NAM, Namibia as Namibia
from .netherlands import NL as NL, NLD as NLD, Netherlands as Netherlands
from .new_zealand import NZ as NZ, NZL as NZL, NewZealand as NewZealand
from .nicaragua import NI as NI, NIC as NIC, Nicaragua as Nicaragua
from .nigeria import NG as NG, NGA as NGA, Nigeria as Nigeria
from .north_macedonia import MK as MK, MKD as MKD, NorthMacedonia as NorthMacedonia
from .northern_mariana_islands import HolidaysMP as HolidaysMP, MNP as MNP, MP as MP, NorthernMarianaIslands as NorthernMarianaIslands
from .norway import NO as NO, NOR as NOR, Norway as Norway
from .pakistan import PAK as PAK, PK as PK, Pakistan as Pakistan
from .panama import PA as PA, PAN as PAN, Panama as Panama
from .paraguay import PRY as PRY, PY as PY, Paraguay as Paraguay
from .peru import PE as PE, PER as PER, Peru as Peru
from .philippines import PH as PH, PHL as PHL, Philippines as Philippines
from .poland import PL as PL, POL as POL, Poland as Poland
from .portugal import PRT as PRT, PT as PT, Portugal as Portugal
from .puerto_rico import HolidaysPR as HolidaysPR, PR as PR, PRI as PRI, PuertoRico as PuertoRico
from .romania import RO as RO, ROU as ROU, Romania as Romania
from .russia import RU as RU, RUS as RUS, Russia as Russia
from .san_marino import SM as SM, SMR as SMR, SanMarino as SanMarino
from .saudi_arabia import SA as SA, SAU as SAU, SaudiArabia as SaudiArabia
from .serbia import RS as RS, SRB as SRB, Serbia as Serbia
from .singapore import SG as SG, SGP as SGP, Singapore as Singapore
from .slovakia import SK as SK, SVK as SVK, Slovakia as Slovakia
from .slovenia import SI as SI, SVN as SVN, Slovenia as Slovenia
from .south_africa import SouthAfrica as SouthAfrica, ZA as ZA, ZAF as ZAF
from .south_korea import KOR as KOR, KR as KR, Korea as Korea, SouthKorea as SouthKorea
from .spain import ES as ES, ESP as ESP, Spain as Spain
from .sweden import SE as SE, SWE as SWE, Sweden as Sweden
from .switzerland import CH as CH, CHE as CHE, Switzerland as Switzerland
from .taiwan import TW as TW, TWN as TWN, Taiwan as Taiwan
from .tanzania import TZ as TZ, TZA as TZA, Tanzania as Tanzania
from .thailand import TH as TH, THA as THA, Thailand as Thailand
from .tunisia import TN as TN, TUN as TUN, Tunisia as Tunisia
from .turkey import TR as TR, TUR as TUR, Turkey as Turkey
from .ukraine import UA as UA, UKR as UKR, Ukraine as Ukraine
from .united_arab_emirates import AE as AE, ARE as ARE, UnitedArabEmirates as UnitedArabEmirates
from .united_kingdom import GB as GB, GBR as GBR, UK as UK, UnitedKingdom as UnitedKingdom
from .united_states import US as US, USA as USA, UnitedStates as UnitedStates
from .united_states_minor_outlying_islands import HolidaysUM as HolidaysUM, UM as UM, UMI as UMI, UnitedStatesMinorOutlyingIslands as UnitedStatesMinorOutlyingIslands
from .united_states_virgin_islands import HolidaysVI as HolidaysVI, UnitedStatesVirginIslands as UnitedStatesVirginIslands, VI as VI, VIR as VIR
from .uruguay import URY as URY, UY as UY, Uruguay as Uruguay
from .uzbekistan import UZ as UZ, UZB as UZB, Uzbekistan as Uzbekistan
from .vanuatu import VTU as VTU, VU as VU, Vanuatu as Vanuatu
from .vatican_city import VA as VA, VAT as VAT, VaticanCity as VaticanCity
from .venezuela import VE as VE, VEN as VEN, Venezuela as Venezuela
from .vietnam import VN as VN, VNM as VNM, Vietnam as Vietnam
from .zambia import ZM as ZM, ZMB as ZMB, Zambia as Zambia
from .zimbabwe import ZW as ZW, ZWE as ZWE, Zimbabwe as Zimbabwe
