import unittest
from _typeshed import Incomplete
from collections.abc import Generator

def read_cnf(path):
    """
    read a DIMACS cnf formatted file from `path`, and return the clauses
    and number of variables
    """
def evaluate(clauses, sol):
    """
    evaluate the clauses with the solution
    """
def py_itersolve(clauses) -> Generator[Incomplete, None, None]: ...
def process_cnf_file(path): ...

nvars1: Incomplete
clauses1: Incomplete
nvars2: Incomplete
clauses2: Incomplete
nvars3: Incomplete
clauses3: Incomplete
tests: Incomplete

class TestSolve(unittest.TestCase):
    def test_wrong_args(self) -> None: ...
    def test_no_clauses(self) -> None: ...
    def test_cnf1(self) -> None: ...
    def test_iter_clauses(self) -> None: ...
    def test_each_clause_iter(self) -> None: ...
    def test_tuple_caluses(self) -> None: ...
    def test_each_clause_tuples(self) -> None: ...
    def test_gen_clauses(self) -> None: ...
    def test_each_clause_gen(self) -> None: ...
    def test_bad_iter(self) -> None: ...
    def test_cnf2(self) -> None: ...
    def test_cnf3(self) -> None: ...
    def test_cnf3_3vars(self) -> None: ...
    def test_cnf1_prop_limit(self) -> None: ...
    def test_cnf1_vars(self) -> None: ...

class TestIterSolve(unittest.TestCase):
    def test_wrong_args(self) -> None: ...
    def test_no_clauses(self) -> None: ...
    def test_iter_clauses(self) -> None: ...
    def test_each_clause_iter(self) -> None: ...
    def test_tuple_caluses(self) -> None: ...
    def test_each_clause_tuples(self) -> None: ...
    def test_gen_clauses(self) -> None: ...
    def test_each_clause_gen(self) -> None: ...
    def test_bad_iter(self) -> None: ...
    def test_cnf1(self) -> None: ...
    def test_shuffle_clauses(self) -> None: ...
    def test_many_clauses(self) -> None: ...
    def test_cnf2(self) -> None: ...
    def test_cnf3_3vars(self) -> None: ...
    def test_cnf1_prop_limit(self) -> None: ...

def run(verbosity: int = 1, repeat: int = 1): ...
