from _typeshed import Incomplete

class PyTridentTokenLibrary:
    @staticmethod
    def getTridentTokenLibrary(): ...
    @staticmethod
    def get_access_token(resource): ...
    @staticmethod
    def get_mwc_token(workspaceId, artifactId, tokenVersion, workloadType: str = 'SparkCore'): ...
    @staticmethod
    def get_secret_with_token(vault_uri, secret_name, access_token): ...
    @staticmethod
    def get_libraries_to_process(api_url, aad_token, config: Incomplete | None = None): ...
    @staticmethod
    def proxy_to_sparkcore_workload(callingComponentName, apiUrl, apiDescription: str = '', method: str = 'get', content: Incomplete | None = None, extraHeaders: Incomplete | None = None): ...
    @staticmethod
    def get_access_token_from_cache(resource): ...
    @staticmethod
    def is_expired_token(token): ...
    @staticmethod
    def proxy_to_sparkcore_workloadV2(callingComponentName, apiUrl, apiDescription: str = '', method: str = 'get', content: str = '', extraHeaders: Incomplete | None = None): ...
    @staticmethod
    def help(): ...
