from _typeshed import Incomplete

INFINITY: Incomplete
QUOTES: Incomplete
REDIRECTION_PIPE: str
REDIRECTION_OUTPUT: str
REDIRECTION_APPEND: str
REDIRECTION_CHARS: Incomplete
REDIRECTION_TOKENS: Incomplete
COMMENT_CHAR: str
MULTILINE_TERMINATOR: str
LINE_FEED: str
HORIZONTAL_ELLIPSIS: str
DEFAULT_SHORTCUTS: Incomplete
COMMAND_NAME: str
COMMAND_FUNC_PREFIX: str
HELP_FUNC_PREFIX: str
COMPLETER_FUNC_PREFIX: str
CMD_ATTR_HELP_CATEGORY: str
CLASS_ATTR_DEFAULT_HELP_CATEGORY: str
CMD_ATTR_ARGPARSER: str
CMD_ATTR_PRESERVE_QUOTES: str
SUBCMD_ATTR_COMMAND: str
SUBCMD_ATTR_NAME: str
SUBCMD_ATTR_ADD_PARSER_KWARGS: str
PARSER_ATTR_COMMANDSET: str
NS_ATTR_SUBCMD_HANDLER: str
