from .parsing import Statement as Statement

class PostparsingData:
    """Data class containing information passed to postparsing hook methods"""
    stop: bool
    statement: Statement
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class PrecommandData:
    """Data class containing information passed to precommand hook methods"""
    statement: Statement
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class PostcommandData:
    """Data class containing information passed to postcommand hook methods"""
    stop: bool
    statement: Statement
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class CommandFinalizationData:
    """Data class containing information passed to command finalization hook methods"""
    stop: bool
    statement: Statement | None
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
