FileNotFoundError = FileNotFoundError

class FileNotFoundError(IOError): ...
FileExistsError = FileExistsError

class FileExistsError(OSError): ...
PermissionError = PermissionError

class PermissionError(OSError): ...
class DatalakeBadOffsetException(IOError): ...
class DatalakeIncompleteTransferException(IOError): ...
class DatalakeRESTException(IOError): ...
