from ._rest_py3 import HttpRequest as HttpRequest
from typing import Any, AsyncIterable, Dict, IO, Iterable, Mapping, MutableMapping, Sequence, Tuple

binary_type = str
PrimitiveData = str | int | float | bool | None
ParamsType = Mapping[str, PrimitiveData | Sequence[PrimitiveData]]
FileContent = str | bytes | IO[str] | IO[bytes]
FileType = Tuple[str | None, FileContent]
FilesType = Mapping[str, FileType] | Sequence[Tuple[str, FileType]]
ContentTypeBase = str | bytes | Iterable[bytes]
ContentType = str | bytes | Iterable[bytes] | AsyncIterable[bytes]
DataType = bytes | Dict[str, str | int] | None

def set_urlencoded_body(data, has_files): ...
def set_multipart_body(files): ...
def set_xml_body(content): ...
def set_content_body(content: Any) -> Tuple[MutableMapping[str, str], ContentTypeBase | None]: ...
def set_json_body(json: Any) -> Tuple[Dict[str, str], Any]: ...
def lookup_encoding(encoding: str) -> bool: ...
def get_charset_encoding(response) -> str | None: ...
def decode_to_text(encoding: str | None, content: bytes) -> str: ...

class HttpRequestBackcompatMixin:
    def __getattr__(self, attr: str) -> Any: ...
    def __setattr__(self, attr: str, value: Any) -> None: ...
