from .. import util as util
from ..util import sqla_compat as sqla_compat
from .base import AddColumn as AddColumn, ColumnDefault as ColumnDefault, ColumnName as ColumnName, ColumnNullable as ColumnNullable, ColumnType as ColumnType, RenameTable as RenameTable, _ServerDefault, alter_column as alter_column, alter_table as alter_table, format_column_name as format_column_name, format_server_default as format_server_default, format_table_name as format_table_name, format_type as format_type
from .impl import DefaultImpl as DefaultImpl
from _typeshed import Incomplete
from sqlalchemy.dialects.mssql.base import MSDDLCompiler as MSDDLCompiler, MSSQLCompiler as MSSQLCompiler
from sqlalchemy.engine.cursor import CursorResult as CursorResult
from sqlalchemy.schema import Column
from sqlalchemy.sql.base import Executable
from sqlalchemy.sql.elements import ClauseElement
from sqlalchemy.sql.schema import Index as Index, Table as Table
from sqlalchemy.sql.selectable import TableClause as TableClause
from sqlalchemy.sql.type_api import TypeEngine as TypeEngine
from typing import Any, Dict, List, Literal

class MSSQLImpl(DefaultImpl):
    __dialect__: str
    transactional_ddl: bool
    batch_separator: str
    type_synonyms: Incomplete
    identity_attrs_ignore: Incomplete
    def __init__(self, *arg, **kw) -> None: ...
    def emit_begin(self) -> None: ...
    def emit_commit(self) -> None: ...
    def alter_column(self, table_name: str, column_name: str, nullable: bool | None = None, server_default: _ServerDefault | Literal[False] | None = False, name: str | None = None, type_: TypeEngine | None = None, schema: str | None = None, existing_type: TypeEngine | None = None, existing_server_default: _ServerDefault | None = None, existing_nullable: bool | None = None, **kw: Any) -> None: ...
    def create_index(self, index: Index, **kw: Any) -> None: ...
    def bulk_insert(self, table: TableClause | Table, rows: List[dict], **kw: Any) -> None: ...
    def drop_column(self, table_name: str, column: Column[Any], schema: str | None = None, **kw) -> None: ...
    def compare_server_default(self, inspector_column, metadata_column, rendered_metadata_default, rendered_inspector_default): ...
    def adjust_reflected_dialect_options(self, reflected_object: Dict[str, Any], kind: str) -> Dict[str, Any]: ...

class _ExecDropConstraint(Executable, ClauseElement):
    inherit_cache: bool
    tname: Incomplete
    colname: Incomplete
    type_: Incomplete
    schema: Incomplete
    def __init__(self, tname: str, colname: Column[Any] | str, type_: str, schema: str | None) -> None: ...

class _ExecDropFKConstraint(Executable, ClauseElement):
    inherit_cache: bool
    tname: Incomplete
    colname: Incomplete
    schema: Incomplete
    def __init__(self, tname: str, colname: Column[Any], schema: str | None) -> None: ...

def visit_add_column(element: AddColumn, compiler: MSDDLCompiler, **kw) -> str: ...
def mssql_add_column(compiler: MSDDLCompiler, column: Column[Any], **kw) -> str: ...
def visit_column_nullable(element: ColumnNullable, compiler: MSDDLCompiler, **kw) -> str: ...
def visit_column_default(element: ColumnDefault, compiler: MSDDLCompiler, **kw) -> str: ...
def visit_rename_column(element: ColumnName, compiler: MSDDLCompiler, **kw) -> str: ...
def visit_column_type(element: ColumnType, compiler: MSDDLCompiler, **kw) -> str: ...
def visit_rename_table(element: RenameTable, compiler: MSDDLCompiler, **kw) -> str: ...
