from _typeshed import Incomplete
from pyasn1.compat.octets import ensureString as ensureString, null as null, oct2int as oct2int

implementation: Incomplete

def from_bytes(octets, signed: bool = False): ...
def to_bytes(value, signed: bool = False, length: int = 0): ...
def bitLength(number): ...
