import abc
import jax
from _typeshed import Incomplete
from collections.abc import Sequence
from jax._src import core as core
from jax._src.typing import Array as Array

class JAXSparse(abc.ABC, metaclass=abc.ABCMeta):
    """Base class for high-level JAX sparse objects."""
    data: jax.Array
    shape: tuple[int, ...]
    nse: property
    dtype: property
    __hash__: Incomplete
    def __len__(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def ndim(self) -> int: ...
    def __init__(self, args: tuple[Array, ...], *, shape: Sequence[int]) -> None: ...
    @abc.abstractmethod
    def tree_flatten(self): ...
    @classmethod
    @abc.abstractmethod
    def tree_unflatten(cls, aux_data, children): ...
    @abc.abstractmethod
    def transpose(self, axes: Incomplete | None = None): ...
    @property
    def T(self): ...
    def block_until_ready(self): ...
    def sum(self, *args, **kwargs) -> None: ...
    def __neg__(self) -> None: ...
    def __pos__(self) -> None: ...
    def __matmul__(self, other) -> None: ...
    def __rmatmul__(self, other) -> None: ...
    def __mul__(self, other) -> None: ...
    def __rmul__(self, other) -> None: ...
    def __add__(self, other) -> None: ...
    def __radd__(self, other) -> None: ...
    def __sub__(self, other) -> None: ...
    def __rsub__(self, other) -> None: ...
    def __getitem__(self, item) -> None: ...
