import torch
from _typeshed import Incomplete

__all__ = ['BatchNorm2d', 'BatchNorm3d']

class _BatchNorm(torch.nn.modules.batchnorm._BatchNorm):
    def __init__(self, num_features, eps: float = 1e-05, momentum: float = 0.1, device: Incomplete | None = None, dtype: Incomplete | None = None) -> None: ...
    @staticmethod
    def from_float(cls, mod): ...
    @classmethod
    def from_reference(cls, bn, output_scale, output_zero_point): ...

class BatchNorm2d(_BatchNorm):
    """This is the quantized version of :class:`~torch.nn.BatchNorm2d`.
    """
    def __init__(self, num_features, eps: float = 1e-05, momentum: float = 0.1, device: Incomplete | None = None, dtype: Incomplete | None = None) -> None: ...
    def forward(self, input: torch.Tensor) -> torch.Tensor: ...
    @classmethod
    def from_float(cls, mod): ...

class BatchNorm3d(_BatchNorm):
    """This is the quantized version of :class:`~torch.nn.BatchNorm3d`.
    """
    def __init__(self, num_features, eps: float = 1e-05, momentum: float = 0.1, device: Incomplete | None = None, dtype: Incomplete | None = None) -> None: ...
    def forward(self, input: torch.Tensor) -> torch.Tensor: ...
    @classmethod
    def from_float(cls, mod): ...
