from _typeshed import Incomplete
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import list_ops as list_ops, tensor_array_ops as tensor_array_ops

def dynamic_list_append(target, element):
    """Converts a list append call inline."""

class TensorList:
    """Tensor list wrapper API-compatible with Python built-in list."""
    dtype: Incomplete
    shape: Incomplete
    def __init__(self, shape, dtype) -> None: ...
    list_: Incomplete
    def append(self, value) -> None: ...
    def pop(self): ...
    def clear(self) -> None: ...
    def count(self): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
