import abc
import datetime
from optuna.distributions import BaseDistribution as BaseDistribution, CategoricalChoiceType as CategoricalChoiceType
from typing import Any, Dict, Sequence

class BaseTrial(metaclass=abc.ABCMeta):
    """Base class for trials.

    Note that this class is not supposed to be directly accessed by library users.
    """
    @abc.abstractmethod
    def suggest_float(self, name: str, low: float, high: float, *, step: float | None = None, log: bool = False) -> float: ...
    @abc.abstractmethod
    def suggest_uniform(self, name: str, low: float, high: float) -> float: ...
    @abc.abstractmethod
    def suggest_loguniform(self, name: str, low: float, high: float) -> float: ...
    @abc.abstractmethod
    def suggest_discrete_uniform(self, name: str, low: float, high: float, q: float) -> float: ...
    @abc.abstractmethod
    def suggest_int(self, name: str, low: int, high: int, step: int = 1, log: bool = False) -> int: ...
    @abc.abstractmethod
    def suggest_categorical(self, name: str, choices: Sequence[CategoricalChoiceType]) -> CategoricalChoiceType: ...
    @abc.abstractmethod
    def report(self, value: float, step: int) -> None: ...
    @abc.abstractmethod
    def should_prune(self) -> bool: ...
    @abc.abstractmethod
    def set_user_attr(self, key: str, value: Any) -> None: ...
    @abc.abstractmethod
    def set_system_attr(self, key: str, value: Any) -> None: ...
    @property
    @abc.abstractmethod
    def params(self) -> Dict[str, Any]: ...
    @property
    @abc.abstractmethod
    def distributions(self) -> Dict[str, BaseDistribution]: ...
    @property
    @abc.abstractmethod
    def user_attrs(self) -> Dict[str, Any]: ...
    @property
    @abc.abstractmethod
    def system_attrs(self) -> Dict[str, Any]: ...
    @property
    @abc.abstractmethod
    def datetime_start(self) -> datetime.datetime | None: ...
    @property
    def number(self) -> int: ...
