from ..core import Command as Command
from _typeshed import Incomplete

class install_headers(Command):
    description: str
    user_options: Incomplete
    boolean_options: Incomplete
    install_dir: Incomplete
    force: int
    outfiles: Incomplete
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def get_inputs(self): ...
    def get_outputs(self): ...
