from _typeshed import Incomplete
from databricks_cli.sdk import PolicyService as PolicyService

class ClusterPolicyApi:
    client: Incomplete
    def __init__(self, api_client) -> None: ...
    @staticmethod
    def format_policy_for_api(policy): ...
    def create_cluster_policy(self, json): ...
    def edit_cluster_policy(self, json): ...
    def delete_cluster_policy(self, policy_id): ...
    def get_cluster_policy(self, policy_id): ...
    def list_cluster_policies(self): ...
