import typing as t
from .utils import pass_eval_context as pass_eval_context

V = t.TypeVar('V')

def async_variant(normal_func): ...
async def auto_await(value: t.Awaitable['V'] | V) -> V: ...
async def auto_aiter(iterable: t.AsyncIterable[V] | t.Iterable[V]) -> t.AsyncIterator[V]: ...
async def auto_to_list(value: t.AsyncIterable[V] | t.Iterable[V]) -> t.List['V']: ...
