from _typeshed import Incomplete
from databricks_cli.dbfs.exceptions import LocalFileExistsException as LocalFileExistsException
from databricks_cli.sdk import WorkspaceService as WorkspaceService
from databricks_cli.workspace.types import WorkspaceFormat as WorkspaceFormat, WorkspaceLanguage as WorkspaceLanguage

DIRECTORY: str
NOTEBOOK: str
LIBRARY: str
REPO: str

class WorkspaceFileInfo:
    path: Incomplete
    object_type: Incomplete
    language: Incomplete
    object_id: Incomplete
    def __init__(self, path, object_type, object_id, language: Incomplete | None = None, **kwargs) -> None: ...
    def to_row(self, is_long_form, is_absolute, with_object_id: bool = False): ...
    @property
    def is_dir(self): ...
    @property
    def is_notebook(self): ...
    @property
    def is_library(self): ...
    @property
    def basename(self): ...
    @classmethod
    def from_json(cls, deserialized_json): ...

class WorkspaceApi:
    client: Incomplete
    def __init__(self, api_client) -> None: ...
    def get_status(self, workspace_path, headers: Incomplete | None = None): ...
    def list_objects(self, workspace_path, headers: Incomplete | None = None): ...
    def mkdirs(self, workspace_path, headers: Incomplete | None = None) -> None: ...
    def import_workspace(self, source_path, target_path, language, fmt, is_overwrite, headers: Incomplete | None = None) -> None: ...
    def export_workspace(self, source_path, target_path, fmt, is_overwrite, headers: Incomplete | None = None) -> None:
        """
        Faithfully exports the source_path to the target_path. Does not
        attempt to do any munging of the target_path if it is a directory.
        """
    def delete(self, workspace_path, is_recursive, headers: Incomplete | None = None) -> None: ...
    def import_workspace_dir(self, source_path, target_path, overwrite, exclude_hidden_files, headers: Incomplete | None = None) -> None: ...
    def export_workspace_dir(self, source_path, target_path, overwrite, headers: Incomplete | None = None) -> None: ...
