from collections.abc import Generator
from pathlib import Path

def flatten_result(result): ...
def result_lines(result): ...
def make_path(filespec: Path | str, make_absolute: bool = True, check_exists: bool = False) -> Path: ...
def replace_file_with_dir(pathspec): ...
def file_with_template_code(filespec): ...
def rewind_compile_time(hours: int = 1) -> Generator[None, None, None]: ...
