from _typeshed import Incomplete

def tridentml_tracking_store_builder(store_uri, artifact_uri: Incomplete | None = None): ...
def tridentml_artifacts_builder(artifact_uri: Incomplete | None = None): ...
def tridentml_run_context_provider_builder(): ...
def tridentml_model_registry_store_builder(store_uri): ...
def tridentml_request_header_provider_builder(): ...
