from .model.shared_artifact import PBIArtifact as PBIArtifact, ReservedNamesResponse as ReservedNamesResponse
from .synapse_mlflow_utils import get_mlflow_env_config as get_mlflow_env_config, timed as timed
from _typeshed import Incomplete
from typing import List

logger: Incomplete
kusto_logger: Incomplete
ASYNC_CREATE_RETRY_COUNT: int
ASYNC_CREATE_RETRY_INTERVAL: int

def is_artifact_name_in_use(artifact_name: str, artifact_type: str) -> bool: ...
def list_workspace_artifacts() -> List[PBIArtifact]: ...
def create_artifact(name: str, artifact_type: str, discription: str = '') -> PBIArtifact: ...
def get_artifact(artifact_id: str) -> PBIArtifact: ...
def delete_artifact(artifact_id: str): ...
