from _typeshed import Incomplete
from sympy.polys.domains.domainelement import DomainElement as DomainElement
from sympy.polys.polyerrors import CoercionFailed as CoercionFailed
from sympy.polys.polyutils import PicklableWithSlots as PicklableWithSlots
from sympy.utilities import public as public

class ModularInteger(PicklableWithSlots, DomainElement):
    """A class representing a modular integer. """
    mod: Incomplete
    dom: Incomplete
    sym: Incomplete
    def parent(self): ...
    val: Incomplete
    def __init__(self, val) -> None: ...
    def __hash__(self): ...
    def __int__(self) -> int: ...
    def to_int(self): ...
    def __pos__(self): ...
    def __neg__(self): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    def __truediv__(self, other): ...
    def __rtruediv__(self, other): ...
    def __mod__(self, other): ...
    def __rmod__(self, other): ...
    def __pow__(self, exp): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __bool__(self) -> bool: ...
    def invert(self): ...

def ModularIntegerFactory(_mod, _dom, _sym, parent):
    """Create custom class for specific integer modulus."""
