from tensorflow.python._pywrap_mlir import *
from _typeshed import Incomplete
from tensorflow.python import pywrap_tensorflow as pywrap_tensorflow
from tensorflow.python.eager import context as context

def import_graphdef(graphdef, pass_pipeline, show_debug_info, input_names: Incomplete | None = None, input_data_types: Incomplete | None = None, input_data_shapes: Incomplete | None = None, output_names=[]): ...
def import_function(concrete_function, pass_pipeline, show_debug_info): ...
def experimental_convert_saved_model_to_mlir(saved_model_path, exported_names, show_debug_info): ...
def experimental_convert_saved_model_v1_to_mlir_lite(saved_model_path, exported_names, tags, upgrade_legacy, show_debug_info): ...
def experimental_convert_saved_model_v1_to_mlir(saved_model_path, exported_names, tags, lift_variables, upgrade_legacy, show_debug_info): ...
def experimental_run_pass_pipeline(mlir_txt, pass_pipeline, show_debug_info): ...
def experimental_write_bytecode(filename, mlir_txt): ...
