from _typeshed import Incomplete
from flaml.automl.data import pd as pd
from flaml.automl.task.task import MULTICHOICECLASSIFICATION as MULTICHOICECLASSIFICATION, NLG_TASKS as NLG_TASKS, SEQCLASSIFICATION as SEQCLASSIFICATION, SEQREGRESSION as SEQREGRESSION, SUMMARIZATION as SUMMARIZATION, TOKENCLASSIFICATION as TOKENCLASSIFICATION

def todf(X, Y, column_name):
    """
    todf converts Y from any format (list, pandas.Series, numpy array) to a DataFrame before being returned
    """
def tokenize_text(X, Y: Incomplete | None = None, task: Incomplete | None = None, hf_args: Incomplete | None = None, tokenizer: Incomplete | None = None): ...
def tokenize_seq2seq(X, Y, tokenizer, task: Incomplete | None = None, hf_args: Incomplete | None = None): ...
def tokenize_and_align_labels(examples, tokenizer, label_to_id, b_to_i_label, hf_args: Incomplete | None = None, X_sent_key: Incomplete | None = None, Y_sent_key: Incomplete | None = None, return_column_name: bool = False): ...
def tokenize_text_tokclassification(X, Y, tokenizer, hf_args: Incomplete | None = None): ...
def tokenize_onedataframe(X, tokenizer, task: Incomplete | None = None, hf_args: Incomplete | None = None, prefix_str: Incomplete | None = None): ...
def tokenize_row(this_row, tokenizer, prefix: Incomplete | None = None, task: Incomplete | None = None, hf_args: Incomplete | None = None, return_column_name: bool = False): ...
def tokenize_text_multiplechoice(X, tokenizer, hf_args: Incomplete | None = None): ...
def tokenize_swag(this_row, tokenizer, hf_args: Incomplete | None = None, return_column_name: bool = False): ...
def postprocess_prediction_and_true(task, y_pred, tokenizer, hf_args, y_true: Incomplete | None = None, X: Incomplete | None = None): ...
def load_model(checkpoint_path, task, num_labels: Incomplete | None = None): ...
