import click.shell_completion
from ._completion_shared import COMPLETION_SCRIPT_BASH as COMPLETION_SCRIPT_BASH, COMPLETION_SCRIPT_FISH as COMPLETION_SCRIPT_FISH, COMPLETION_SCRIPT_POWER_SHELL as COMPLETION_SCRIPT_POWER_SHELL, COMPLETION_SCRIPT_ZSH as COMPLETION_SCRIPT_ZSH, Shells as Shells
from _typeshed import Incomplete
from typing import Any, Dict, List, Tuple

class BashComplete(click.shell_completion.BashComplete):
    name: Incomplete
    source_template = COMPLETION_SCRIPT_BASH
    def source_vars(self) -> Dict[str, Any]: ...
    def get_completion_args(self) -> Tuple[List[str], str]: ...
    def format_completion(self, item: click.shell_completion.CompletionItem) -> str: ...
    def complete(self) -> str: ...

class ZshComplete(click.shell_completion.ZshComplete):
    name: Incomplete
    source_template = COMPLETION_SCRIPT_ZSH
    def source_vars(self) -> Dict[str, Any]: ...
    def get_completion_args(self) -> Tuple[List[str], str]: ...
    def format_completion(self, item: click.shell_completion.CompletionItem) -> str: ...
    def complete(self) -> str: ...

class FishComplete(click.shell_completion.FishComplete):
    name: Incomplete
    source_template = COMPLETION_SCRIPT_FISH
    def source_vars(self) -> Dict[str, Any]: ...
    def get_completion_args(self) -> Tuple[List[str], str]: ...
    def format_completion(self, item: click.shell_completion.CompletionItem) -> str: ...
    def complete(self) -> str: ...

class PowerShellComplete(click.shell_completion.ShellComplete):
    name: Incomplete
    source_template = COMPLETION_SCRIPT_POWER_SHELL
    def source_vars(self) -> Dict[str, Any]: ...
    def get_completion_args(self) -> Tuple[List[str], str]: ...
    def format_completion(self, item: click.shell_completion.CompletionItem) -> str: ...

def completion_init() -> None: ...
