import click
from ._completion_shared import Shells as Shells, get_completion_script as get_completion_script, install as install
from .models import ParamMeta as ParamMeta
from .params import Option as Option
from .utils import get_params_from_function as get_params_from_function
from typing import Any, Dict, Tuple

def get_completion_inspect_parameters() -> Tuple[ParamMeta, ParamMeta]: ...
def install_callback(ctx: click.Context, param: click.Parameter, value: Any) -> Any: ...
def show_callback(ctx: click.Context, param: click.Parameter, value: Any) -> Any: ...
def completion_init() -> None: ...
def shell_complete(cli: click.BaseCommand, ctx_args: Dict[str, Any], prog_name: str, complete_var: str, instruction: str) -> int: ...
