import click
import click.core
import click.shell_completion
import click.types
from . import rich_utils as rich_utils
from _typeshed import Incomplete
from typer.completion import completion_init as completion_init
from typing import Any, Callable, Dict, List, Sequence, Tuple

MarkupMode: Incomplete

class TyperArgument(click.core.Argument):
    help: Incomplete
    show_default: Incomplete
    show_choices: Incomplete
    show_envvar: Incomplete
    hidden: Incomplete
    rich_help_panel: Incomplete
    def __init__(self, *, param_decls: List[str], type: Any | None = None, required: bool | None = None, default: Any | None = None, callback: Callable[..., Any] | None = None, nargs: int | None = None, metavar: str | None = None, expose_value: bool = True, is_eager: bool = False, envvar: str | List[str] | None = None, shell_complete: Callable[[click.Context, click.Parameter, str], List['click.shell_completion.CompletionItem'] | List[str]] | None = None, autocompletion: Callable[..., Any] | None = None, show_default: bool | str = True, show_choices: bool = True, show_envvar: bool = True, help: str | None = None, hidden: bool = False, rich_help_panel: str | None = None) -> None: ...
    def get_help_record(self, ctx: click.Context) -> Tuple[str, str] | None: ...
    def make_metavar(self) -> str: ...
    def shell_complete(self, ctx: click.Context, incomplete: str) -> List['click.shell_completion.CompletionItem']: ...

class TyperOption(click.core.Option):
    rich_help_panel: Incomplete
    def __init__(self, *, param_decls: List[str], type: click.types.ParamType | Any | None = None, required: bool | None = None, default: Any | None = None, callback: Callable[..., Any] | None = None, nargs: int | None = None, metavar: str | None = None, expose_value: bool = True, is_eager: bool = False, envvar: str | List[str] | None = None, shell_complete: Callable[[click.Context, click.Parameter, str], List['click.shell_completion.CompletionItem'] | List[str]] | None = None, autocompletion: Callable[..., Any] | None = None, show_default: bool | str = False, prompt: bool | str = False, confirmation_prompt: bool | str = False, prompt_required: bool = True, hide_input: bool = False, is_flag: bool | None = None, flag_value: Any | None = None, multiple: bool = False, count: bool = False, allow_from_autoenv: bool = True, help: str | None = None, hidden: bool = False, show_choices: bool = True, show_envvar: bool = False, rich_help_panel: str | None = None) -> None: ...
    def get_help_record(self, ctx: click.Context) -> Tuple[str, str] | None: ...
    def shell_complete(self, ctx: click.Context, incomplete: str) -> List['click.shell_completion.CompletionItem']: ...

class TyperCommand(click.core.Command):
    rich_markup_mode: Incomplete
    rich_help_panel: Incomplete
    def __init__(self, name: str | None, *, context_settings: Dict[str, Any] | None = None, callback: Callable[..., Any] | None = None, params: List[click.Parameter] | None = None, help: str | None = None, epilog: str | None = None, short_help: str | None = None, options_metavar: str | None = '[OPTIONS]', add_help_option: bool = True, no_args_is_help: bool = False, hidden: bool = False, deprecated: bool = False, rich_markup_mode: MarkupMode = None, rich_help_panel: str | None = None) -> None: ...
    def format_options(self, ctx: click.Context, formatter: click.HelpFormatter) -> None: ...
    def main(self, args: Sequence[str] | None = None, prog_name: str | None = None, complete_var: str | None = None, standalone_mode: bool = True, windows_expand_args: bool = True, **extra: Any) -> Any: ...
    def format_help(self, ctx: click.Context, formatter: click.HelpFormatter) -> None: ...

class TyperGroup(click.core.Group):
    rich_markup_mode: Incomplete
    rich_help_panel: Incomplete
    def __init__(self, *, name: str | None = None, commands: Dict[str, click.Command] | Sequence[click.Command] | None = None, rich_markup_mode: MarkupMode = None, rich_help_panel: str | None = None, **attrs: Any) -> None: ...
    def format_options(self, ctx: click.Context, formatter: click.HelpFormatter) -> None: ...
    def main(self, args: Sequence[str] | None = None, prog_name: str | None = None, complete_var: str | None = None, standalone_mode: bool = True, windows_expand_args: bool = True, **extra: Any) -> Any: ...
    def format_help(self, ctx: click.Context, formatter: click.HelpFormatter) -> None: ...
