from ._additive import Additive as Additive
from ._deep import Deep as Deep
from ._exact import Exact as Exact
from ._gpu_tree import GPUTree as GPUTree
from ._linear import Linear as Linear
from ._partition import Partition as Partition
from ._permutation import Permutation as Permutation
from ._sampling import Sampling as Sampling
from ._tree import Tree as Tree
