from _typeshed import Incomplete
from typing import Dict, List, Mapping
from wandb.sdk.artifacts.artifact_manifest_entry import ArtifactManifestEntry as ArtifactManifestEntry
from wandb.sdk.artifacts.storage_policy import StoragePolicy as StoragePolicy
from wandb.sdk.lib.hashutil import HexMD5 as HexMD5

class ArtifactManifest:
    entries: Dict[str, 'ArtifactManifestEntry']
    @classmethod
    def from_manifest_json(cls, manifest_json: Dict) -> ArtifactManifest: ...
    @classmethod
    def version(cls) -> int: ...
    storage_policy: Incomplete
    def __init__(self, storage_policy: StoragePolicy, entries: Mapping[str, 'ArtifactManifestEntry'] | None = None) -> None: ...
    def __len__(self) -> int: ...
    def to_manifest_json(self) -> Dict: ...
    def digest(self) -> HexMD5: ...
    def add_entry(self, entry: ArtifactManifestEntry) -> None: ...
    def remove_entry(self, entry: ArtifactManifestEntry) -> None: ...
    def get_entry_by_path(self, path: str) -> ArtifactManifestEntry | None: ...
    def get_entries_in_directory(self, directory: str) -> List['ArtifactManifestEntry']: ...
