from typing import Dict, Sequence, Type
from wandb.filesync.step_prepare import StepPrepare as StepPrepare
from wandb.sdk.artifacts.artifact import Artifact as Artifact
from wandb.sdk.artifacts.artifact_manifest_entry import ArtifactManifestEntry as ArtifactManifestEntry
from wandb.sdk.internal.progress import ProgressFn as ProgressFn
from wandb.sdk.lib.paths import FilePathStr as FilePathStr, URIStr as URIStr

class StoragePolicy:
    @classmethod
    def lookup_by_name(cls, name: str) -> Type['StoragePolicy']: ...
    @classmethod
    def name(cls) -> str: ...
    @classmethod
    def from_config(cls, config: Dict) -> StoragePolicy: ...
    def config(self) -> Dict: ...
    def load_file(self, artifact: Artifact, manifest_entry: ArtifactManifestEntry) -> FilePathStr: ...
    def store_file_sync(self, artifact_id: str, artifact_manifest_id: str, entry: ArtifactManifestEntry, preparer: StepPrepare, progress_callback: ProgressFn | None = None) -> bool: ...
    async def store_file_async(self, artifact_id: str, artifact_manifest_id: str, entry: ArtifactManifestEntry, preparer: StepPrepare, progress_callback: ProgressFn | None = None) -> bool:
        """Async equivalent to `store_file_sync`."""
    def store_reference(self, artifact: Artifact, path: URIStr | FilePathStr, name: str | None = None, checksum: bool = True, max_objects: int | None = None) -> Sequence['ArtifactManifestEntry']: ...
    def load_reference(self, manifest_entry: ArtifactManifestEntry, local: bool = False) -> FilePathStr | URIStr: ...
