from _typeshed import Incomplete
from stack_data import BlankLineRange as BlankLineRange, BlankLines as BlankLines, FrameInfo as FrameInfo, LINE_GAP as LINE_GAP, Line as Line, Options as Options, RepeatedFrames as RepeatedFrames, Variable as Variable, style_with_executing_node as style_with_executing_node
from stack_data.utils import assert_ as assert_
from types import FrameType, TracebackType
from typing import Iterable

class Formatter:
    pygmented: Incomplete
    show_executing_node: Incomplete
    executing_node_underline: Incomplete
    current_line_indicator: Incomplete
    line_gap_string: Incomplete
    line_number_gap_string: Incomplete
    line_number_format_string: Incomplete
    show_variables: Incomplete
    show_linenos: Incomplete
    use_code_qualname: Incomplete
    strip_leading_indent: Incomplete
    html: Incomplete
    chain: Incomplete
    options: Incomplete
    collapse_repeated_frames: Incomplete
    def __init__(self, *, options: Incomplete | None = None, pygmented: bool = False, show_executing_node: bool = True, pygments_formatter_cls: Incomplete | None = None, pygments_formatter_kwargs: Incomplete | None = None, pygments_style: str = 'monokai', executing_node_modifier: str = 'bg:#005080', executing_node_underline: str = '^', current_line_indicator: str = '-->', line_gap_string: str = '(...)', line_number_gap_string: str = ':', line_number_format_string: str = '{:4} | ', show_variables: bool = False, use_code_qualname: bool = True, show_linenos: bool = True, strip_leading_indent: bool = True, html: bool = False, chain: bool = True, collapse_repeated_frames: bool = True) -> None: ...
    def set_hook(self) -> None: ...
    def print_exception(self, e: Incomplete | None = None, *, file: Incomplete | None = None) -> None: ...
    def print_stack(self, frame_or_tb: Incomplete | None = None, *, file: Incomplete | None = None) -> None: ...
    def print_lines(self, lines, *, file: Incomplete | None = None) -> None: ...
    def format_exception(self, e: Incomplete | None = None) -> Iterable[str]: ...
    def format_stack(self, frame_or_tb: Incomplete | None = None) -> Iterable[str]: ...
    def format_stack_data(self, stack: Iterable[FrameInfo | RepeatedFrames]) -> Iterable[str]: ...
    def format_repeated_frames(self, repeated_frames: RepeatedFrames) -> str: ...
    def format_frame(self, frame: FrameInfo | FrameType | TracebackType) -> Iterable[str]: ...
    def format_frame_header(self, frame_info: FrameInfo) -> str: ...
    def format_line(self, line: Line) -> str: ...
    def format_blank_lines_linenumbers(self, blank_line): ...
    def format_variables(self, frame_info: FrameInfo) -> Iterable[str]: ...
    def format_variable(self, var: Variable) -> str: ...
    def format_variable_value(self, value) -> str: ...
