from .common import device_from_inputs as device_from_inputs, fake_tensor_unsupported as fake_tensor_unsupported
from .registry import register_backend as register_backend
from _typeshed import Incomplete

def default_provider(device_type): ...
def has_onnxruntime(): ...
def onnxrt(gm, example_inputs, *, filename: Incomplete | None = None, provider: Incomplete | None = None): ...
