from _typeshed import Incomplete

__all__ = ['ensure_dir', 'symlink', 'copy', 'symlink', 'copytree', 'safe_delete']

def ensure_dir(path) -> None: ...
def symlink(src, dest) -> None: ...
def copy(src, dest) -> None: ...
def copytree(src, dest) -> None: ...
def safe_delete(dest) -> None: ...

class _Debug:
    src: Incomplete
    dest: Incomplete
    def __init__(self, src, dest) -> None: ...
